### ISSUE TITLE
call back example of the client ?

### ISSUE THREAD

**Issue by jeffpeiyt** [line/armeria#10]
Cool project!

Wonder do you have some simple example on the client onComplete() like callback example for the future<>?

http://line.github.io/armeria/client-http.html

also how is the performance compared with OKHttp?

I was thinking on adding alternative HTTP client to the core of Parallec

**Comment by jeffpeiyt** [comment]
just show the callback here: for the RPC with the service/  Thrift IDL..

wonder what about the call back example for none IDL,  just use as an HTTP client.. ?

**Comment by trustin** [comment]
It doesn't have a callback. You can simply add a listener to the `Future` returned by the `execute()` method. e.g.

```java
Future<SimpleHttpResponse> f = client.execute(req);
f.addListener((Future<SimpleHttpResponse>) f -> { ... });
```

**Comment by trustin** [comment]
Let me close the question since it seems like it's answered.
