### ISSUE TITLE
Add ServerListenerBuilder

### ISSUE THREAD

**Issue by dongjinleekr** [line/armeria#1003]
Until now, `ServerListener` instance should be written by the user one by one. This approach is enough when there are only a few `ServerListener`s, but if lots of `ServerListener`s are required, this approach becomes not only cumbersome but also time-consuming and error-prone. Writing Armeria application that interacts with Zookeeper using Curator is a good example of this (#882) - you have to start and stop some Curator instances when the Server is started or stopping. Even worse, most of those routines are repetitive.

If Armeria supports an easy way to build `ServerListener` instance by composing `Runnable` instances, there are following advantages:

- Easy to write: the listener can be written with only a few lambda syntax.
- Better Readability: it focuses what it does.
- Reusable: we can define reusable capsulations of the repetitive routines.

**Comment by dongjinleekr** [comment]
You can check my implementation in [this commit](https://github.com/dongjinleekr/armeria/commit/8d91dffe767cb3e778ed0dc7e05467781ad55bb8) in [this branch](https://github.com/dongjinleekr/armeria/tree/feature/issue-1003). How are they? 😄

**Comment by trustin** [comment]
Sounds good to me. Could you send a PR so we can review?
