### ISSUE TITLE
Mode.IN_NODE_VALUE in Zookeeper-based service discovery is meaningless

### ISSUE THREAD

**Issue by dongjinleekr** [line/armeria#1005]
I found this problem while I was working on #882.

1. The constructor of `ZooKeeperUpdatingListener` (and underlying `ZooKeeperRegistration`) does not provide a way to specify `Mode` to use; Actually, its value is fixed to `Mode.IN_CHILD_NODES` and there is no way to change it.
2. `ZooKeeperRegistrationTest` also tests the case of `Mode.IN_CHILD_NODES` only.
3. Even if `ZooKeeperUpdatingListener` and `ZooKeeperRegistration` support `Mode` parameter, there is another problem: Zookeeper can't detect whether the server registered in node value is alive; Since it is a value of Persistent Node.

So: `Mode` should be removed and [the documentation](https://github.com/line/armeria/tree/master/site/src/sphinx/advanced-zookeeper.rst) should also be updated, before progressing #882. (In that update, Zookeeper-based service discovery feature is implemented with `CuratorFramework` instance only.)

**Comment by trustin** [comment]
Ah, didn't realize IN_NODE_VALUE stores the values as a permanent node.

It seems to make sense to remove `IN_NODE_VALUE`.

However, if you could come up with a replacement implementation soon, I think we can just replace the current one with yours, instead of dealing with the old implementation. What do you think?

**Comment by trustin** [comment]
It also would be nice if our storage layout is compatible with curator-x-discovery so a user of curator-x-discovery can access our endpoint list.

**Comment by dongjinleekr** [comment]
> However, if you could come up with a replacement implementation soon, I think we can just replace the current one with yours, instead of dealing with the old implementation. What do you think?

Of course, I already succeeded to implement the replacement which supports both of legacy API and curator-x-discovery based API. 😃 It requires only one API modification to the users.

**Comment by dongjinleekr** [comment]
For API modification, I will create another issue which describes the problem and the solution throughly.
