### ISSUE TITLE
Provide alternative way to create ZooKeeperUpdatingListener

### ISSUE THREAD

**Issue by dongjinleekr** [line/armeria#1007]
\* It is a preparation of #882 - it will be implemented on top of this update.

Since Armeria will support Apache Curator integration with #882, we should replace the current implementation of Zookeeper-based Service Discovery with `CuratorFramework` based one. (If not, the legacy `ZookeeperConnector` will conflict with the `CuratorFramework` instance - I experienced it.)

The problem is: Currently, `ZooKeeperUpdatingListener` instance which handles Zookeeper Service Registration only can be created by invoking the constructor directly. So, it is impossible to change the type of the instance.

I propose following solution:

1. Make the `ZooKeeperUpdatingListener` constructor deprecated.
2. Provide another API to create `ServerListener` instance which registers the server to Zookeeper, which also hides the actual type of the instance.

By doing so, we can provide the users a stepping stone to change the API.

To be more specific, a builder class named `ZookeeperRegisterBuilder` can handle the tasks; By adapting Builder pattern, we can add more options in the future.

How do you think?

**Comment by trustin** [comment]
SGTM. Looking forward to your PR.
