### ISSUE TITLE
Lack of armeria essential artifacts in the BOM

### ISSUE THREAD

**Issue by tanakeeeeen** [line/armeria#1008]
Hi
I wanna use the armeria BOM, but it seems to be lack of armeria core artifacts as below.
http://repo1.maven.org/maven2/com/linecorp/armeria/armeria-bom/0.57.0/armeria-bom-0.57.0.pom
armeria
armeria-grpc
armeria-jetty
...etc

Could you add the artifacts as above to BOM?

**Comment by trustin** [comment]
Yes. Will fix before the next release.

**Comment by tanakeeeeen** [comment]
@trustin 
Thanks, I understand.

**Comment by trustin** [comment]
https://github.com/line/gradle-scripts/pull/8 should fix this issue.
