### ISSUE TITLE
Expose netty channel option to end-user

### ISSUE THREAD

**Issue by huydx** [line/armeria#1009]
For some high performance network applications, users may need to tune those options
SO_REUSEADDR for example

**Comment by imasahiro** [comment]
We may want to introduce server/client netty option like lettuce's [NettyCustomizer](https://github.com/lettuce-io/lettuce-core/blob/9b7b318c134ed7ae7993f9d1030b38f4653dd24a/src/main/java/com/lambdaworks/redis/resource/NettyCustomizer.java)?

**Comment by trustin** [comment]
I guess that will increase the future difficulty of shading Netty. It'd be fine if choose not to shade Netty, though :-)

**Comment by imasahiro** [comment]
Realized that we already exposing API that customize socket options at `ClientFactoryBuilder` but didn't expose at `ServerBuilder`. How about just exposing `ChannelOption` instead of adding general netty customizer?

**Comment by rkapsi** [comment]
+1 I'm very interested in this feature and happy to PR it

**Comment by trustin** [comment]
We must decide we should shade Netty or not first. If we do, we must hide the references to the Netty classes from our public API. Otherwise, we can expose Netty classes in our public API. How we should tackle this issue changes vastly depending on this. Let me create a poll.

**Comment by trustin** [comment]
Created a poll - https://github.com/line/armeria/issues/1168
