### ISSUE TITLE
HttpStatusBasedRetryStrategy should allow retrying on exceptions rather than just HTTP status

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1013]
Currently, `HttpStatusBasedRetryStrategy` ignores exceptions in the result. It is common to have exceptions like `ClosedSessionException`, which should be retried since they can be random socket closures, so it seems like a bad default to ignore the exceptions. Should we have it default to retrying on exception?

**Comment by minwoox** [comment]
Sorry for the late response.
As you said, it will be better retrying when those exceptions happen by default. I will make a PR for that. Thank you~!!

**Comment by trustin** [comment]
I think it highly depends on how and when such an exception has been raised. That being said, we have some questions like:

- Should we retry on any `Exception` types or on just a few specific types?
- Should we retry when the HEADERS frame of the response has been received but connection has failed (or exception has been raised) before the last frame is received?
- Should we retry when an error occurred while preparing or sending a request?

I think this highly depends on what HTTP API we are calling. e.g. for GET, we will want to retry aggressively while we may not (or may depending on implementation?) for non-idempotent methods.

**Comment by anuraaga** [comment]
I agree that it shouldn't be all-encompassing, and questionable to default, but it is probably useful to add knobs on the builder we already have to make it simple to treat exception as failure. Otherwise, the only option is forking lots of logic like this

https://github.com/curioswitch/curiostack/blob/master/common/google-cloud/armeria-cloud-storage/src/main/java/org/curioswitch/curiostack/gcloud/storage/ErrorRetryStrategy.java

**Comment by trustin** [comment]
Agreed. How about this:

- Provide a builder like `RetryStrategyBuilder` which provides various knobs, `HttpStatus` and `Exception` most notably.
  - Do some composition, like composing `HttpStatusBasedRetryStrategy` and `ExceptionBasedRetryStrategy`?
- Change `RetryStrategy.on*Status()` to default to 'retry on any exceptions thrown before content preview is done.'

**Comment by trustin** [comment]
Closed by #1056. Thanks @anuraaga and @minwoox for suggestion and fix.
