### ISSUE TITLE
H2 with Linkerd

### ISSUE THREAD

**Issue by daveconde** [line/armeria#1014]
I am trying to get retrofit to proxy via Linkerd using h2c. I need to be able to override the authority header as mentioned [here](https://linkerd.io/getting-started/k8s/) while still keeping the URL pointing at the linkerd host and port. How do I set this using the armeria client?

Thanks

**Comment by trustin** [comment]
You can override the headers sent by an Armeria HTTP client as explained here: https://line.github.io/armeria/client-custom-http-headers.html

You could override the ':authority' header using one of the 3 ways explained? Please let me know if it does not work so we can fix it.

I'm also curious about what you think about the current way of overriding headers. Can we do better in terms of simplicity and user-friendliness? Any suggestions for better API?

**Comment by trustin** [comment]
More specifically, you could use 'ArmeriaRetrofitBuilder.withClientOptions()' to set the ClientOption.HTTP_HEADERS option:

withClientOptions((uri, builder) -> builder.setHttpHeader(HttpHeaderNames.AUTHORITY, "..."))

**Comment by daveconde** [comment]
I attempted the below with a decorator but it seems the authority is being set from the URL instead of the header override.

`retrofit = new ArmeriaRetrofitBuilder()
                    .baseUrl("h2c://" + host)
                    .addConverterFactory(JacksonConverterFactory.create())
                    .withClientOptions((url, optionsBuilder) -> {
                        optionsBuilder.decorator(HttpRequest.class, HttpResponse.class, (delegate, ctx, req) -> {
                            req.headers().set(AUTHORITY, adStoreApiHost + "." + namespace);
                            return delegate.execute(ctx, req);
                        });
                        return optionsBuilder;
                    })
                    .build();`

I also attempted the below but then got an exception around authority being blacklisted.

` optionsBuilder.httpHeader(HEADER_NAME, value);`

Is there another method you would recommend?

Thanks for the help :)

**Comment by trustin** [comment]
I guess :authority header cannot be overridden in current implementation but it's an unnecessary restriction we enforced. Let me whitelist :authority in the next release, which should be out this week.

Thanks!

**Comment by daveconde** [comment]
As a workaround I have configured linkerd to look for another header but as far as I can see any extra headers are removed before the call goes over the wire.

**Comment by trustin** [comment]
That's weird. Could you share your construction code so I can reproduce?

**Comment by daveconde** [comment]
After lots of debugging I got to the bottom of the issue. The headers were actually being removed on the initial protocol upgrade call. Unfortunately linkerd doesn't support protocol upgrade. Setting useHttp2Preface(true) on the client got me passed that. I then configured linkerd to look for a new dedicated header for routing requests as documented [here](https://github.com/linkerd/linkerd/blob/master/linkerd/docs/protocol-h2.md#http2-header-token-identifier).

Finally I hit an issue where headers were being delivered over multiple windows and causing a NPE. Once fixed using [this](https://github.com/line/armeria/pull/1016) requests seem to flow as expected :)

**Comment by trustin** [comment]
Thanks a lot for taking your time to fix the problem! I left a question at #1016.

**Comment by trustin** [comment]
@daveconde Could you please try the latest master and let us know if the problem is gone? Thanks!

**Comment by trustin** [comment]
Sent #1110 for defaulting to HTTP/2 preface upgrade
