### ISSUE TITLE
Support Cookie header injection by annotated HTTP service

### ISSUE THREAD

**Issue by hyangtack** [line/armeria#1026]
We may automatically decode `Cookie` header as a Java object like `io.netty.handler.codec.http.cookie.Cookie`.

**Comment by trustin** [comment]
We probably should also look into other implementations such as `AsyncHttpClient` and fork the best one.

**Comment by hyangtack** [comment]
What if we add `Cookies` interface which extends `Set<Cookie>` like below?
```
public interface Cookies extends Set<Cookie> {
}
```

So we can decode `Cookie` header when a user specify `Cookies` on his or her parameter of an annotated service method.
