### ISSUE TITLE
Zombie gRPC connections

### ISSUE THREAD

**Issue by tobias-** [line/armeria#1028]
When using constructs of the type:
```
rpc StreamClientCancels2(SimpleRequest) returns (stream SimpleResponse);
```
there is no way to know if the client has disconnected. OnCancelHandler is not called, nor is there any exception thrown when sending more data. It will just silently discard all data sent.

I've added a test case (CC0 on my changes, claim ownership if you want)
https://github.com/tobias-/armeria/tree/zombie_connections

**Comment by tobias-** [comment]
It seems that https://github.com/line/armeria/blame/master/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L208 silently ignores the result from `res.write()`. 
IMHO it should be throwing an Exception when res.write returns false (which according to the javadoc indicates that the stream has already been closed).

@anuraaga Could you confirm/deny that this isn't intended?

**Comment by anuraaga** [comment]
Thanks for debugging this - I had thought for some reason `AbortedStreamException` would be thrown but it looks like checking for `false` is required.

@trustin What do you think of changing write to return `void` and throw when it's closed? I notice reactor seems to behave like that.
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/FluxSink.html#next-T-

**Comment by trustin** [comment]
+1 for throwing an exception. Could add tryWrite() that returns boolean instead.
