### ISSUE TITLE
Can't specify NodeValueCodec when creating ZooKeeperUpdatingListener instance

### ISSUE THREAD

**Issue by dongjinleekr** [line/armeria#1035]
I found this problem while working on #882 and #1005.

As of now, there is a parity problem in the service discovery feature; Although `ZookeeperEndpointGroup` provides a way to specify `NodeValueCodec` with `ZooKeeperEndpointGroup(String, String, int, NodeValueCodec)`, the counterpart is missing in `ZooKeeperUpdatingListener`.

We should provide a way to specify `NodeValueCodec`, which determines how the node value would be stored.

**Comment by dongjinleekr** [comment]
@trustin @anuraaga @imasahiro This problem can be solved with #1007 at once. You can check the implementation [here](https://github.com/dongjinleekr/armeria/commit/e646b4c23ec2219c51495b574d98ee24dffb9206).

**Comment by trustin** [comment]
Sounds good to me. Please send a PR. :-)
