### ISSUE TITLE
Version of bundled Thrift binary

### ISSUE THREAD

**Issue by dittos** [line/armeria#104]
I found that the Thrift binary included in the repo is not a vanilla version:

```
$ ./src/build/thrift.osx-x86_64 -version
Thrift version 0.9.1-LINE
```

Is there any difference in the generated code? I know these binaries are only used for generating test code, but was just curious :blush: 

Added: Linux binary is not a customized version, but from 0.9.2.

```
$ ./thrift.linux-x86_64 -version
Thrift version 0.9.2
```

**Comment by trustin** [comment]
@dittos I think the generated code has no differences as far as I know. I guess 0.9.1-LINE includes some patches that actually makes it pretty much same with 0.9.2. But please feel free to let us know if you find any differences. Also, please consider opening a PR that updates the OSX binary to 0.9.2. (I do not use OSX ;-))

**Comment by trustin** [comment]
We've just updated our OSX Thrift compiler binary to vanilla 0.9.3. Linux and Windows versions stay at 0.9.2 but I think it doesn't matter.

**Comment by trustin** [comment]
Thanks again @anuraaga for taking initiative and fixing this long-standing issue (although it was a side-effect of trying to fix other issue ;-))
