### ISSUE TITLE
Possible race in HTTP/2 flow control handling

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1040]
I am writing a cloud storage client based on armeria where it is common for the client to send multiple, e.g. 1MB requests across the same HTTP/2 connection at the same time. I encountered issues though where with simultaneous requests, some would complete while others just hang forever. With Logging client enabled, the requests are all shown but only zero to one responses when 2-4 requests are sent at the same time (haven't tried with more that 4). The response never completes, future never completes, and further business logic cannot be run. Eventually the backend usually closes the socket. Note that the business logic will not attempt to send another request on the connection until it gets a response for the precious one, so during the stuck state there are no additional bytes being added, until it timesout, tries the next chunk, and gets stuck again. Also, there are occasional cases where both succeed and processing can go normally (very rare with 4 writres a bit more common with just 2).

Switching to H1 makes the writes completely reliable (just changed the url from https to h1). I suspect that flow control is an issue and it's possible that a bug prevents throttled frames from ever being sent. I guess we'd need to start by adding detailed logging of flow control of a connection (allowed bytes, pending bytes, etc).

**Comment by trustin** [comment]
Were the recent fixes relevant to this issue?

**Comment by anuraaga** [comment]
Actually, I forgot that this is just a normal `HttpClient` and not gRPC so probably not. Anyways will try again with new armeria to confirm

**Comment by anuraaga** [comment]
I tried with http2 again and it seems to be working fine. Perhaps it was a backend issue or Netty version upgrade helped, not sure but seems to be working.

**Comment by trustin** [comment]
Great to hear that. Not sure what the problem really was though. :-/
