### ISSUE TITLE
Exception should be thrown when the port collides.

### ISSUE THREAD

**Issue by kishida** [line/armeria#1042]
The code does not throw any `Exception`, not put any logs.
```
Server server1 = new ServerBuilder()
        .port(8080, SessionProtocol.HTTP)
        .service("/", (ctx, req) -> HttpResponse.of(HttpStatus.OK,
                MediaType.PLAIN_TEXT_UTF_8, "Hello!"))
        .build();
server1.start();
Server server2 = new ServerBuilder()
        .port(8080, SessionProtocol.HTTP)
        .service("/", (ctx, req) -> HttpResponse.of(HttpStatus.OK,
                MediaType.PLAIN_TEXT_UTF_8, "Great!!"))
        .build();
server2.start();
```
It will make hard to find a mistake especially when starting to use Armeria.

**Comment by trustin** [comment]
You should not ignore the `CompletableFuture` returned by the `start()` method.

**Comment by trustin** [comment]
Obviously, the first example [here](https://line.github.io/armeria/server-basics.html) does not call `join()` on the returned future. Let me send a PR for this.

**Comment by trustin** [comment]
Closing, since we updated our documentation at #1068. Thanks for feed back, @kishida!
