### ISSUE TITLE
ServerBuilder.port() raises an exception when H1/H1C/H2/H2C is specified

### ISSUE THREAD

**Issue by trustin** [line/armeria#1050]
From Slack:

> yashinovsky: I have a question about Armeria and HTTP2. I tried passing H2 in the ServerBuilder set port, but it throws an exception since it only accepts HTTP or HTTPS
> trustin: You can just specify HTTPS then it will support both H1 and H2. (and HTTP for both H1C and H2C) There's no way currently to disable only HTTP/1 or HTTP/2. Do you need to do that?

It seems like some users are confused about this behavior. For disambiguation, we could replace `port()` with `http()` and `https()`, with some deprecation phase. What do you think?

**Comment by minwoox** [comment]
I thought about adding the explanation which SessionProtocol can be accepted, but having `httpPort()` and `httpsPort()` is much better.
