### ISSUE TITLE
service register to zookeeper with hostname, does IP supported

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#1061]
while I integrate my service with armeria-zookeeper, it registered with the hostname of the service deployed. but our servers were routed by ip other than hostname. 

so I want to know is there any options to make the service bind with the IP of the server other than hostname to zookeeper.

**Comment by trustin** [comment]
You can specify an `Endpoint` explicitly when instantiating `ZooKeeperUpdatingListener`:

```java
ServerBuilder sb = ...;
sb.serverListener(new ZooKeeperUpdatingListener(
    zkConnStr, zNodePath, sessTimeout, Endpoint.of("192.168.0.100", 8080)));
```

Is this what you are looking for?

**Comment by trustin** [comment]
Or, do you want `ZooKeeperUpdatingListener` to determine the IP address of the machine automatically? What would be the desired behavior if there are more than one network interface in the machine?

**Comment by eonezhang** [comment]
I let have a try, and post the result here later. @trustin thanks for your suggestion.
