### ISSUE TITLE
Default "RequestConverterFunction" for Java beans

### ISSUE THREAD

**Issue by LiYing2010** [line/armeria#1066]
Currently, there are only 3 default implements for `RequestConverterFunction`:
(1)`ByteArrayRequestConverterFunction`
(2)`StringRequestConverterFunction`
(3)`JacksonRequestConverterFunction`

If I want to parse request parameters from `path mapping result`, `query string`, `request headers`, and wrap all these parameters into a Java Bean, I have to implement my own `RequestConverterFunction` class.
It is possible, but a little in-convenience.

It will be helpful if `Armeria` can provide a new default implement for `RequestConverterFunction` which can handle all these boilerplate code for us.

The basic idea is:
(1)user only need to declare a request bean, e.g.
```
public class MyRequestBean {
  @Param("userName")    <== this param should retrieve from path variable or query string
  private String userName;

  @Param("age")
  private int age;

  @Header("x-user-permission")    <== this param should retrieve from HTTP Request Header
  private String permission;
}
```

(2)and the new `RequestConverterFunction` implement should parse request parameters from `path mapping result`, `query string`, `request headers` etc, and set them into the bean instance

I think this new feature will make `request conversion` pattern much more usable.

**Comment by trustin** [comment]
Sounds like a good idea. Please feel free to send us a PR if you are interested. I'm curious how you would inject the parameters into the member fields or the setter method invocations. Do you know any light-weight bean property injection library we can use as a shaded dependency?

**Comment by LiYing2010** [comment]
Hi, I created a PR for this:  https://github.com/line/armeria/pull/1096
Could anyone review it?

**Comment by trustin** [comment]
Thank you! We will review it soon. :+1:
