### ISSUE TITLE
How to get ThreadLocal variables for Async Thrift Service.

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#1067]
here is my requirements,
1. Extract rpc context info from HttpRequest by Decorator and set it to the ThreadLocal.
```
AsciiString name = AsciiString.of("actor");
String actor = req.headers().get(name);
if (actor == null) {
    return HttpResponse.of(HttpStatus.UNAUTHORIZED);
}
ContextImpl c = new ContextImpl();
c.setActorId(actor);
Context.set(c);
try {
    return delegate().serve(ctx, req);
} finally {
    Context.remove();
}
```

2. In my Thrift service, try to get info from context, but the context is null.
```
Context ctx = Context.current();
resultHandler.onComplete("Hello " + name);
```
here `ctx=null`

I know the async call was excuted on another thread, but in my case, the legacy code was heavily depend on ThreadLocal variables, is there any solution for this OR any workaround. @trustin  what's your suggestions.

**Comment by trustin** [comment]
There are various ways to handle this.

1.

You can put your context into Armeria's context:

```java
private static final AttributeKey<Context> ATTR_CTX = AttributeKey.valueOf(...);

ServiceRequestContext armeriaCtx = ...; // given as a parameter of your decorator.
armeriaCtx.attr(ATTR_CTX).set(c); // set your ContextImpl here.

// Later in your async callback:
ServiceRequestContext armeriaCtx = RequestContext.current();
Context c = armeriaCtx.attr(ATTR_CTX).get()
```

2.

You can use `onEnter` and `onExit` callbacks:

```java
ServiceRequestContext armeriaCtx = ...; // given as a parameter of your decorator.
armeriaCtx.onEnter(() -> { Context.set(c); });
armeriaCtx.onExit(() -> { Context.remove(); });

// Later in your callback:
Context c = Context.current();
```

**Comment by eonezhang** [comment]
@trustin both way work fine for me. and I have extra question for option 1, it seems no cleanup for the `context` object, does it introduce memory leak, is it necessary to remove my `context` object from the `armeriaCtx` like below:
```
armeriaCtx.attr(ATTR_CTX).remove();
```
and if it is true, I want to know where should I put this code fragment.

**Comment by trustin** [comment]
When a request is complete, `ServiceRequestContext` will usually be garbage-collected. You don't have to remove your attribute unless you need to clean up your resources manually, e.g. files and database connections
