### ISSUE TITLE
Support WebSocket

### ISSUE THREAD

**Issue by trustin** [line/armeria#1076]
https://en.wikipedia.org/wiki/WebSocket

**Comment by Adanz** [comment]
great!

**Comment by alex-lx** [comment]
Gently ask any progress here? We‘re planing to start a websocket based project using the wonderful armeria server...

**Comment by trustin** [comment]
Hi! There's no progress yet. I think it will take place after 1.0. We always look for volunteers, so please let us know if you have an idea. :bowing_man:

**Comment by minwoox** [comment]
I also need to add documentation and support WebSocket extensions as follow-ups.
