### ISSUE TITLE
EndpointGroup design issues

### ISSUE THREAD

**Issue by trustin** [line/armeria#1084]
It seems like some users have the following concerns with the current `EndpointGroup` and `EndpointGroupRegistry` API:

- Using a 'string' as a way to specify a target endpoint group makes it hard to build a clear dependency between an `EndpointGroup` and a `Client`.
- There's no clear unified contract for the life cycle of an `EndpointGroup`, which complicates the user application shutdown process.

**Comment by anuraaga** [comment]
While digging into endpoint groups, I came to a feeling that `EndpointGroup` should be tied to `ClientFactory` instead of a static registry. The main reason for this is `HttpHealthCheckedEndpointGroup` is tied to a `ClientFactory` - it doesn't seem to make sense for this to be accessible from different factories through the static registry and is hard for me to reason about. Also, using custom `ClientFactory` is somewhat advanced - I think these users would generally expect registering endpoints to their custom, awesome `ClientFactory`. Normal usage could still use a static method to register to the default `ClientFactory`.

**Comment by trustin** [comment]
One advantage of keeping `EndpointGroup`s in a `ClientFactory` is that they can be closed automatically when their `ClientFactory` is closed.

**Comment by anuraaga** [comment]
In https://github.com/openzipkin/zipkin/issues/2699 I found that even after configuring a http health checked endpoint group with our customized client factory, I was still missing the fact that `DnsEndpointGroup` should be using that factory's event loop group, not common pools, to keep everything together. So not just `HttpHealthCheckedEndpointGroup`, but also `DnsEndpointGroup` and any other type of endpoint group that uses armeria / netty inside it will be easier to set up in a consistent way if a client factory is involved in initialization.

**Comment by trustin** [comment]
@anuraaga wrote:

Realized this idea was proposed in the issue already but didn't think enough until now - I'm not sure this is all that much better since it means creating the client before registering the endpoint group.

```java
HttpClient client = HttpClient.of("https://group:foobar/");
HealthCheckedEndpointGroup foobar = HealthCheckedEndpointGroup.builder(...)
  .options(client.options())
  .build();
EndpointGroupRegistry.register("foobar", foobar, ROUND_ROBIN);
```
Creating an `HttpClient` that references a group that doesn't exist yet seems quite awkward. There's a bit less code but semantically this doesn't seem quite right to me.

Though as mentioned in the issue, it seems hard to solve in a great way so maybe this is still the best we can do.

(Copied from https://github.com/line/armeria/pull/2019#pullrequestreview-278938806)

**Comment by trustin** [comment]
I had a chance to think about this issue lately and realized that it is not possible to tie an `EndpointGroupRegistry` into a `ClientFactory` because a user might want to use a different `ClientFactory` for `EndpointGroup`s. For example, a user may want to use separate set of event loops for health checks or DNS queries.

However, it would be still nice if `EndpointGroup`s are closed automatically when their `ClientFactory`s are closed. Perhaps we could provide an abstract `EndpointGroup` class so that all `EndpointGroup` implementations that extent it automatically registers themselves to their `ClientFactory`?

> Using a 'string' as a way to specify a target endpoint group makes it hard to build a clear dependency between an `EndpointGroup` and a `Client`.

We current have `Clients.newClient()`, `Clients.builder()` and `WebClient.builder()` that accept a host `Endpoint`. Similarly, perhaps we could let a user specify an `EndpointGroup` and `EndpointSelectionStrategy`?

**Comment by trustin** [comment]
> Similarly, perhaps we could let a user specify an `EndpointGroup` and `EndpointSelectionStrategy`?

How about integrating `EndpointSelectionStrategy` into `EndpointGroup`, e.g.

```java
Endpoint endpoint =
    HealthCheckedEndpointGroup.builder(...)
                              .strategy(...)
                              .build();

MyStub stub = Clients.newClient("gproto+http", endpoint, MyStub.class);
```

...? No need to overload more methods in `Clients` and things look cleaner.

**Comment by trustin** [comment]
If there's no objection, I'll give it a shot next week after #2177 is merged. /cc @monorisk

**Comment by anuraaga** [comment]
SGTM

**Comment by minwoox** [comment]
:+1:

**Comment by trustin** [comment]
> There's no clear unified contract for the life cycle of an `EndpointGroup`, which complicates the user application shutdown process.

Thinking of allowing an `EndpointGroup` implementation to add a listener to a `ClientFactory` so that it can close itself when the `ClientFactory` is closed. What do you think?
