### ISSUE TITLE
Generalize endpoint decoding from DNS records

### ISSUE THREAD

**Issue by trustin** [line/armeria#1088]
We currently provide `DnsServiceEndpointGroup` that decodes the SRV records compatible with k8s. In some case, a user may want to:

- Use a different format for SRV records or
- Use other record type than SRV, such as TXT to decode the endpoint information

We could generalize `DnsServiceEndpointGroup` so we support such use cases.

**Comment by anuraaga** [comment]
To clarify, `SRV` records have a standard format, it's not related to `k8s`. I just looked at this spec - https://en.wikipedia.org/wiki/SRV_record

**Comment by trustin** [comment]
As @anuraaga said, SRV record has a standard format and we can't change that, i.e. there's no point of allowing customization.

It would be useful to build an `Endpoint` from a TXT record, but #1148 doesn't fix that yet.

**Comment by trustin** [comment]
#1148 now has `DnsTextEndpointGroup`.
