### ISSUE TITLE
how to get remote address when using thrift based on http

### ISSUE THREAD

**Issue by chenjianfei2017** [line/armeria#1095]
As title shows, I am using thrift server based on http, something like: "sb.service("/report", THttpService.of(new MyHelloIml(), ThriftSerializationFormats.JSON)",  MyHelloIml is a class defined by thrift, the question is how should I do to get remote address in this situation? It looks like that Armeria does not provide interface to solve this problem.

**Comment by trustin** [comment]
You can get the RequestContext object from your service implementation:

    ServiceRequestContext ctx = RequestContext.current();
    InetSocketAddress.raddr = ctx.remotrAddr();

Let me know if it works for you.

**Comment by chenjianfei2017** [comment]
Your comments solved my problem perfectly! My appreciation to you for your generous help is beyond my words.

**Comment by chenjianfei2017** [comment]
hi, I have another problem. What should I do to get real client address since nginx is used as a revise proxy? I found some API: proxiedAddresses().sourceAddress(). I tried like this: RequestContext.current().proxiedAddresses().sourceAddress(), but it got errors. How should I do to get client address correctly?

**Comment by trustin** [comment]
You can configure NGINX to set a header like `X-Forwarded-For`, and then you can get the header from `RequestContext.request()`. You can downcast it to `HttpRequest`:

```java
HttpRequest req = RequestContext.current().request();
req.headers().get(HttpHeaderNames.of("x-forwarded-for"))
```

Please consult NGINX documentation about setting the `X-Forwarded-For` header.

**Comment by trustin** [comment]
https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

**Comment by chenjianfei2017** [comment]
I see. I got correct address now! Thanks very much.
May I give a suggestion? Perhaps we can supply more documentation and examples since armeria is so powerful.
Best wishes.

**Comment by trustin** [comment]
Sure. That'd deserve a dedicated issue.
