### ISSUE TITLE
Can Armeria work with Linkerd

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#1109]
I'm curious about how can I combine armeria with linkerd.
I saw linkerd support [grpc](https://linkerd.io/config/1.3.6/linkerd/index.html#grpc-default) and [thrift](https://linkerd.io/config/1.3.6/linkerd/index.html#thrift-protocol) routes.

**Comment by trustin** [comment]
There was once a bug report about the interoperability with Linkerd at #1014 which has been resolved. That being said, Armeria should now have no problem with Linkerd, but I didn't try to run Linkerd by myself yet.

@daveconde, does Armeria work fine with Linkerd now? How was your experience so far?
