### ISSUE TITLE
Please update protobuf-jackson to newest version

### ISSUE THREAD

**Issue by Necropaw** [line/armeria#1128]
### Expected behavior
Runs with Java 10

### Current behavior
Because of using net.bytebuddy:1.7.0 in protobuf-jackson:0.11 the upstream error happens: raphw/byte-buddy#351

[protobuf-jackson](https://github.com/curioswitch/curiostack/releases/tag/protobuf-jackson-0.2.0) released a new version for support for Java 10 because of this.

**Comment by trustin** [comment]
Thanks for reporting, @Necropaw
