### ISSUE TITLE
ServiceWithPathMappings is hard to decorate

### ISSUE THREAD

**Issue by trustin** [line/armeria#1137]
Let's say we created a `GrpcService`:

```java
GrpcService service = new GrpcServiceBuilder()...build();
ServerBuilder sb = new ServerBuilder();
// This works.
sb.service(service);
// This does not work because it's not a `ServiceWithPathMappings` anymore.
sb.service(service.decorate(...));
```

To fix this issue, we need to remove the type constraint of `ServerBuilder.service(ServiceWithPathMappings)` and do runtime validation only.

What do you think?
/cc @anuraaga

**Comment by anuraaga** [comment]
I think this is why we added the `decorator` version of the method to `ServerBuilder` - is it too confusing? I feel like it's enough

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java#L729

**Comment by trustin** [comment]
Ah, yeah. Completely forgot about that one. Let me close this issue. :+1:
