### ISSUE TITLE
Make Endpoint coherent again

### ISSUE THREAD

**Issue by dongjinleekr** [line/armeria#1140]
I found this problem while working at #1007, #1035 & #882. And it also related to #1084 possibly.

Currently, `Endpoint` class represents various concepts; host or group endpoint, along with weight. As @trustin left:

> Remove weight and make Endpoint a pure endpoint representation. We could specify an additional attributes such as weight/priority when adding an Endpoint to an EndpointGroup.

We can improve the current design by separating attributes (e.g., weight) and splitting host/group endpoint.

**Comment by dongjinleekr** [comment]
![endpoint-design](https://user-images.githubusercontent.com/2375128/38539077-8dae39e2-3cd1-11e8-887e-634575eaf740.png)

How about this design?

**Comment by trustin** [comment]
I'm not sure I like the idea of complicating the endpoint idea. It's too soon to tell what the best way to model an endpoint is until we have more load-balancing algorithms. Maybe it's just OK as it is? 'weight' is a fairly common concept which is understood by most load-balancing algorithm.

**Comment by trustin** [comment]
@line/cdtf What do you think?
