### ISSUE TITLE
Difficult to request from an absolute URL with HttpClient

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1143]
Currently, `HttpClient`'s various `get`, `execute`, etc methods can only be used with a URL path. There are cases that a user has an absolute URL (such as from a `Location` header) and I think this can only be used by parsing the URL into authority + path and creating a client for the authority. It would also be nice to allow something like `HttpClient.DEFAULT.get("https://github.com/foo/bar/gaz")` as a drop-in replacement for simple usage of Apache or JDK.

**Comment by trustin** [comment]
Agreed. A user doesn't really need to specify authority or scheme when creating an `HttpClient`. May require a fair bit of refactoring.

**Comment by adriancole** [comment]
I would love something like this, but also settle for a http client function of endpoint

**Comment by ikhoon** [comment]
I’d like to handle this issue. 😉
