### ISSUE TITLE
Can we use armeria in a NIO/NAIO (not AIO) way?

### ISSUE THREAD

**Issue by rogerbosman** [line/armeria#1169]
So first of I'm sorry if something here is unclear or wrong, I'm still wrapping my head around this whole NIO vs AIO subject, and the terms being used inconsistently doesn't help.

My understanding so far is that we can utilize libraries like Netty to do "true" NIO/NAIO, meaning that we can execute multiple request on the same thread, thus not needing a thread pool (using something like epoll). This means an app implementing this can be "truly" reactive with just one thread per core, instead of a thread-per-request.

I'm trying to verify this is faster, but would like to keep using Retrofit (or something similar) as simplicity comes before true speed in this use case. 

However, reading on armeria's website, they state that "Asynchronous connection pool ensures your application never blocks even on pool exhaustion." Does this mean armeria is using AIO over this "true" NIO/NAIO that Netty offers? Or am I misunderstanding something? And if I'm not misunderstanding, is there any way to use this NIO/NAIO?

Thanks a lot

**Comment by anuraaga** [comment]
> Does this mean armeria is using AIO over this "true" NIO/NAIO that Netty offers?

To clarify, by AIO, here, do you mean delegating I/O tasks to a thread pool while NIO is executing all I/O on an event loop? If so, then armeria is completely NIO with optional support for delegating to a threadpool for business logic (usually a Thrift synchronous service). Even DNS is non-blocking, which is quite rare from what I've seen.

> "Asynchronous connection pool ensures your application never blocks even on pool exhaustion."

For HTTP/2 it is possible to serve everything on one connection, but not for HTTP/1, or when having multiple load balanced endpoints, etc. This just means that a calling thread will not block when initiating a new connection, and there might be 1000s of new connections. But there are only 2*num CPU threads serving all those connections using epoll for I/O events as in "true" NIO.

Admittedly, it's very common to talk about connection pools like a JDBC pool where each connection is served by a dedicated thread, which might cause the confusion - perhaps we can rephrase to remove the word pool to make it clearer?

**Comment by rogerbosman** [comment]
Thanks for the reply!

To summarise my question, I understand the benefits that the thread-per-core model given by event-driven has over the thread-per-connection, and that using a library that is async but internally blocking (i.e. using its own, internal thead-per-request threadpool) somewhat mitigates this effect as there are still many threads (but hidden inside this library). 

As far as I understand from your answer, this is not wat armeria is doing. Instead, it handles multiple connections on a set (cpu*2) amount of threads, like Netty does. Therefore, implementing armeria has the same effect as implementing Netty directly (in this aspect).

Am I correct? If so, thanks for the effort and I will start experimenting. If not, can you explain where I'm wrong? Thanks!

**Comment by anuraaga** [comment]
That sounds correct - armeria's connection handling is a fairly thin wrapper around Netty so uses the same threading model of having only a few threads serving many connections. This is true for pretty much all armeria related code (including retrofit which you mentioned) with only some unavoidable exceptions for supported business logic like implementing a synchronous Thrift service, since that by nature requires supporting blocking within the business logic itself.

**Comment by rogerbosman** [comment]
Thanks for the quick and helpful reactions! Question answered :)

**Comment by trustin** [comment]
Thank you for answering, @anuraaga !
