### ISSUE TITLE
Refactor annotated HTTP service 

### ISSUE THREAD

**Issue by hyangtack** [line/armeria#1175]
The first goal is to extract a common code from `AnnotatedHttpServiceMethod` and `BeanRequestConverterFunction` to support `@Param`, `@Header` and `@Default` annotations in a same way.

It might be to support `@RequestObject` annotation for a bean so that a bean is able to hold another bean. I'm not sure yet if this feature is good or not.

**Comment by hyangtack** [comment]
@LiYing2010 
Let me work on this issue. If you have any idea, please let me know.

**Comment by LiYing2010** [comment]
great job~~
