### ISSUE TITLE
How armeria service been tested

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#1183]
is there anyone can share some best practice to test armeria service components, with mockito or anything else?

**Comment by eonezhang** [comment]
I have service depends on TService, so I want to mock the TService while unit test. I don't find a good way to mock the TSerivce(thrift service), I'd like to hear the experience from  you.

**Comment by imasahiro** [comment]
I think it depends on what kind of feature you want to test. In our case, we sometimes mocks `MyService.Iface` or  `MyService.AsyncIface` like [this](https://github.com/line/armeria/blob/75ec237f5e61e56bfe3076a5e4d025bc96ad5f14/thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java#L73)

**Comment by trustin** [comment]
If you don't mind integrated testing, you can try [`ServerRule`](https://line.github.io/armeria/apidocs/index.html?com/linecorp/armeria/testing/server/ServerRule.html):

```java
public class MyJunitTest {
    @ClassRule
    public static final ServerRule server = new ServerRule() {
        @Override
        protected void configure(ServerBuilder sb) {
            sb.service("/someService", ...);
        }
    };

    @Test
    public void someTest() throws Exception {
        String uri = server.httpUri("/someService");
        // .. Send a request to the URI ..
    }
}
```

**Comment by trustin** [comment]
You'll have to mock `YourServiceClassGeneratedByThriftCompiler.AsyncIface` or `*.Iface`.

**Comment by eonezhang** [comment]
@trustin thanks for your response, I found it's difficult to mock `AsyncIface`, do you have any good idea.

**Comment by trustin** [comment]
With Mockito, it would be like this, assuming `iface` is the mock and it has a method called `foo(String, AsyncMethodCallback<Void>)`:

```java
doAnswer(invocation -> {
    final AsyncMethodCallback<Void> callback = invocation.getArgument(1);
    callback.onComplete(null);
    return null;
}).when(iface).foo(any(), any());

// .. Send some request here ..

verify(iface).foo(eq("someValue"), any());
```

**Comment by eonezhang** [comment]
@trustin great thanks and appreciate for you response.
here is my workable sample for test async interface of thrift. for some people need it.
```
    @Test
    public void createAnalysisTask() throws TException {
        AnalysisService.AsyncIface iface = mock(AnalysisService.AsyncIface.class);
        doAnswer(invocation -> {
            final AsyncMethodCallback<AnalysisDTO> callback = invocation.getArgument(1);
            AnalysisDTO dto = mock(AnalysisDTO.class);
            when(dto.getAppId()).thenReturn(1L);
            callback.onComplete(dto);
            return null;
        }).when(iface).createAnalysisTask(any(), any());

        iface.createAnalysisTask(new AnalysisDTO(), new AsyncMethodCallback<AnalysisDTO>() {
            @Override
            public void onComplete(AnalysisDTO response) {
                assertEquals("", 1L, response.getAppId());
            }

            @Override
            public void onError(Exception exception) {

            }
        });

        verify(iface).createAnalysisTask(any(), any());
    }
```

**Comment by trustin** [comment]
@eonezhang Thanks a lot for sharing your solution. Let me close this question, then.
