### ISSUE TITLE
HttpClientBuilder() should accept strings without serialization format

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1200]
Currently, there are two versions of `HttpClientBuilder()`, one that takes a `String` and one that takes `URI`. The latter automatically prepends `none+` to the `URI` but the former will just reject URL strings without a serialization format. It's surprising for these two similar methods to have different accepted input - I think it's better of the `String` version also automatically adds `none+` when no format is specified. `HttpClient.of` already does this, so this is also confusing distinction between the builder and static factories.

**Comment by imasahiro** [comment]
Both `HttpClient.of(String)` and `HttpClient.of(URI)` finally use same `HttpClientBuilder` constructor (`HttpClientBuilder(URI)`). So `HttpClient.of(String)` accepts string without serialization format, right?

https://github.com/line/armeria/blob/54e124d73178609b4f0af6d833ea562a1ce15bd9/core/src/main/java/com/linecorp/armeria/client/HttpClientBuilder.java#L47-L49

https://github.com/line/armeria/blob/54e124d73178609b4f0af6d833ea562a1ce15bd9/core/src/main/java/com/linecorp/armeria/client/HttpClientBuilder.java#L57-L59

**Comment by anuraaga** [comment]
Oops - I thought the issue also affected `HttpClient.of`, sorry for not checking. I would expect `HttpClientBuilder` to have identical behavior as the static methods so changed issue for that.

**Comment by anuraaga** [comment]
Actually looking at your snippet, I see what you're saying. Hmm, let me find the exception I saw.

**Comment by anuraaga** [comment]
```
Caused by: java.lang.IllegalArgumentException: URI with unknown scheme: http://169.254.169.254/
	at com.linecorp.armeria.client.AbstractClientFactory.validateScheme(AbstractClientFactory.java:74)
	at com.linecorp.armeria.client.DefaultClientFactory.newClient(DefaultClientFactory.java:117)
	at com.linecorp.armeria.client.ClientBuilder.build(ClientBuilder.java:88)
```

**Comment by imasahiro** [comment]
Just checked current `(Http)?ClientBuilder` behavior.

```java
// Pass
new HttpClientBuilder("http://localhost");
// IllegalArgumentException: scheme : none+http 
new HttpClientBuilder("none+http://localhost");
// Pass
new HttpClientBuilder(URI.create("http://localhost"));
// IllegalArgumentException: scheme : none+http 
new HttpClientBuilder(URI.create("none+http://localhost"));
```

```java
// Pass
new ClientBuilder("none+http://localhost").build(HttpClient.class);
// IllegalArgumentException: URI with unknown scheme
new ClientBuilder("http://localhost").build(HttpClient.class);
// Pass
new ClientBuilder(URI.create("none+http://localhost")).build(HttpClient.class);
// IllegalArgumentException: URI with unknown scheme
new ClientBuilder(URI.create("http://localhost")).build(HttpClient.class);
```

**Comment by anuraaga** [comment]
Oops! Got the classes mixed up in my head :( I went from `HttpClient` to `ClientBuilder` instead of `HttpClientBuilder`. I guess `ClientBuilder` requiring format but not `HttpClientBuilder` makes sense.

**Comment by anuraaga** [comment]
I'll go ahead and close this issue since the behavior seems reasonable, though possibly too easy to get mixed up.

**Comment by trustin** [comment]
Not directly related but perhaps we could tolerate the case where the scheme starts with `none+`?
