### ISSUE TITLE
ArmeriaRetrofitBuilder & HTTP2 - Max Number of Streams

### ISSUE THREAD

**Issue by DrMattFaulkner** [line/armeria#1206]
Hi,

I'm using the ArmeriaRetrofitBuilder to wrap an HTTP2 REST API call asynchronous:

```
Retrofit retrofit = new ArmeriaRetrofitBuilder()
        .baseUrl(url)
        .addConverterFactory(JacksonConverterFactory.create(mapper))
        .addCallAdapterFactory(Java8CallAdapterFactory.create())
        .build();

SomeService service = retrofit.create(SomeService.class);
Call<String> sayHello = server.sayHello();
sayHello.enqueue(this);

```

But I am getting this error:

`io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint.`

Am I using something wrong?
If not, how do I set the max number of active streams?

Thanks

**Comment by trustin** [comment]
Does the problem occur when you send just one request? If not, how many concurrent requests do you send? 

The default maximum number of active streams in Armeria (and Netty) is `Integer.MAX_VALUE` which is effectively infinite (https://http2.github.io/http2-spec/#iana-settings), so I think you should never see that exception unless your server is configured to limit the number of active streams.

**Comment by DrMattFaulkner** [comment]
The server side is configured for a max concurrent streams of 128. 

It doesn't occur with a single request. I'm trying to perform a load test ( ~ 1 million calls ) as fast as I can.

**Comment by trustin** [comment]
I believe it's a defect in Armeria client implementation which does not respect the max number of active streams.

**Comment by trustin** [comment]
What would be the desired behavior when a connection reaches at its max active streams? Creating a new connection?

**Comment by trustin** [comment]
Related section in the RFC: https://http2.github.io/http2-spec/#rfc.section.5.1.2

**Comment by DrMattFaulkner** [comment]
FYI I used https://nghttp2.org/documentation/h2load-howto.html with the same configuration and all was good.

**Comment by trustin** [comment]
> Shouldn't the number of streams should be a MIN ( server advised, client configured ) ?

Correct. The problem is that Armeria currently does not respect the server-provided value.

> If a new connection is opened, there should also be a configurable limit of number of connections. Otherwise we'd back at the same problem.

Isn't MAX_CONCURRENT_STREAMS applied on per-connection basis and thus we can open as many streams as we want as long as we open new connections? Please correct me if I'm wrong.

> What causes a new stream to open?

In HTTP/2, each request is a 'stream', i.e. active streams == the requests in progress

> FYI I used https://nghttp2.org/documentation/h2load-howto.html with the same configuration and all was good.

and the server is NGINX, right?

**Comment by DrMattFaulkner** [comment]
> Isn't MAX_CONCURRENT_STREAMS applied on per-connection basis and thus we can open as many streams as we want as long as we open new connections? Please correct me if I'm wrong.

That sounds right to me.

> In HTTP/2, each request is a 'stream', i.e. active streams == the requests in progress

I think this was your question, but what should happen if your number of requests exceeds the max active streams? 

> and the server is NGINX, right?

Actually no. I'm using a jetty http2 server. Although I don't think this makes much difference in this example.


Should there should be a setHttp2StreamLimit method to set a client side limit?

**Comment by trustin** [comment]
> I think this was your question, but what should happen if your number of requests exceeds the max active streams?

I think it's fine to just make a new connection as long as the server accepts it.

> Should there be a setHttp2StreamLimit method to set a client side limit?

Yes, but it's unimplemented at the moment. I think you can work around this issue by decorating the `HttpClient` you specified with `ConcurrencyLimitingHttpClient`:

```java
Retrofit retrofit = new ArmeriaRetrofitBuilder()
    .withClientOptions((uri, optionsBuilder) -> {
        return optionsBuilder.decorator(
                HttpRequest.class, HttpResponse.class, 
                ConcurrencyLimitingHttpClient.newDecorator(...));
    }).build();
```

I must admit this is not ideal at all: 1) It should work without this workaround and 2) the way of decorating is too verbose. Let me try to find some time to sort this out.

**Comment by trustin** [comment]
- Provide a way for a user to specify `MAX_CONCURRENT_STREAMS` setting on the server side.
- Make client respect the `MAX_CONCURRENT_STREAMS` setting, i.e. modify `DefaultKeyedChannelPool` so it does not acquire a channel which reached at the maximum number of concurrent streams.
- Add more variants of `decorator()` methods to `AbstractClientOptionsBuilder`:
  - `httpDecorator()` and `rpcDecorator()` which are shortcut to `decorator(HttpRequest.class, HttpResponse, ...)` and `decorator(RpcRequest.class, RpcResponse.class, ...)`
- Consider allowing a user pass an Armeria `HttpClient` to `ArmeriaRetrofitBuilder` so that a user can do this:

  ```java
  HttpClient hc = new HttpClientBuilder(baseUrl)
          .decorator(ConcurrencyLimitingHttpClient.newDecorator(...))
          .build();
  Retrofit retrofit = new ArmeriaRetrofitBuilder(hc)...build();
  ```

**Comment by DrMattFaulkner** [comment]
I would like to have a way of bounding the number of connections a client makes too. I don't know what should happen in the case of hitting the max stream AND max connections. Maybe just block the client?

**Comment by trustin** [comment]
#1481 fixes this issue by making Armeria client respect `MAX_CONCURRENT_STREAMS`. We do not limit the number of connections yet though.
