### ISSUE TITLE
HTTP header/parameter-based path mapping

### ISSUE THREAD

**Issue by hyangtack** [line/armeria#1207]
Spring framework provides HTTP header/parameter-based path mapping like below:

```
@GetMapping(value = "/hello", params = {"name"})
public String method(@RequestParam("name") String name) { ... }
```

I think that it's not a high priority issue, but we need to figure out how to support this kind of usage.

**Comment by hyangtack** [comment]
Seems that the following changes can make this possible:
- Add `headers(HttpHeaders)` and `parameters(Iterable<String>)` to `RouteBuilder`.
  - `DefaultRoute` will use them for routing.
- Reuse the existing annotations in order to specify HTTP header and parameter on an annotated method, e.g. `@Header("x-custom-header")` and `@Param("name")`. It would make sense in terms of consistency with other annotations such as `@Consumes` and `@Produces`.

@minwoox As I know, you've recently worked on this part. Please let me know if this approach is not suitable. ;-)

**Comment by minwoox** [comment]
Yeah, Using `RouteBuilder` is the only way to implement that. :-)

> Add headers(HttpHeaders) and parameters(Iterable<String>) to RouteBuilder

Couldn't figure out why we need `headers(HttpHeaders)`, would you tell me why?

**Comment by trustin** [comment]
Probably just enough to route based on the existence of headers/parameters, not by their values?

**Comment by hyangtack** [comment]
> Couldn't figure out why we need headers(HttpHeaders), would you tell me why?

Ah, yes. `headers(Iterable<String>)` is enough. It's my mistake. :-)

**Comment by hyangtack** [comment]
https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestMapping.html#params--

They provide simple expressions such as:
- `myParam=myValue`
- `myParam!=myValue`
- `myParam`
- `!myParam`

and special handling for media type wildcards(*):
- `headers = "content-type=text/*"`

I think we don't need to support the latter one because I think it's part of media type negotiation which is already supported by `@Consumes` and `@Produces`. But the former feature seems to be worth to have. What do you think? @minwoox @trustin @ikhoon

**Comment by trustin** [comment]
+1. Should we introduce another annotation?

**Comment by hyangtack** [comment]
> +1. Should we introduce another annotation?

Yes, it seems that. But I have no idea yet. 😆 The followings are what I'm thinking now:
- `@MatchesHeader`/`@NonMatchesHeader`
- `@MatchesParam`/`@NonMatchesParam`

e.g.
- `@MatchesHeader(name = "My-Header")` : if there's a `My-Header` header
- `@MatchesHeader(name = "My-Header", value = "my-value")` : if there's a `My-Header` header with `my-value` value
- `@NonMatchesHeader(name = "My-Header")` : if there's no `My-Header` header
- `@NonMatchesHeader(name = "My-Header", value = "my-value")` : if there's no `My-Header` header, or if it exists but its value is not `my-value`.

We may make all annotations above repeatable so that a user can make more complex condition with annotations.

And, I realized that we cannot cover POST form data because we are deciding a route using `RequestHeaders` only. I think this kind of limitation is reasonable for now.

**Comment by trustin** [comment]
How about using a single value? i.e.

- `@MatchesHeader("my-header")` if there's a `my-header` header.
- `@MatchesHeader("my-header: my-value")` if there's a `my-header` header with `my-value` value

**Comment by trustin** [comment]
But.. maybe we need to make this consistent with `@AdditionalHeader`, which has `name` and `values`.. (or we can change `AdditionalHeader`.)
