### ISSUE TITLE
False warning about path param auto-injection

### ISSUE THREAD

**Issue by LiYing2010** [line/armeria#1213]
The following code checks if all the path mapping parameters are consumed by function parameters:
https://github.com/line/armeria/blob/0296b6cb71945cf0871ac957e896fe95b8c64151/core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java#L574-L580

if not, it will output a warning log.

But we added a new feature: [`Injecting value of parameters and HTTP headers into a Java object`](https://line.github.io/armeria/server-annotated-service.html#injecting-value-of-parameters-and-http-headers-into-a-java-object), which can inject parameters into a Java Bean, and function can consume this Java Bean.

So, in this case, the check logic mentioned above will raise a false warning.
Actually, these false warnings happened in my project.

Solution:
this check logic should check more deeply, not only the function parameters, but also the the Java Beans which used in function parameters.

**Comment by LiYing2010** [comment]
I think I can fix this problem.
But I must wait PR https://github.com/line/armeria/pull/1191 merged, to avoid source code conflict

**Comment by LiYing2010** [comment]
Thanks.
Should I close this issue? or wait your PR merged, and make a proper check logic for path param and Java Bean?

**Comment by hyangtack** [comment]
Actually I believe that it may be overkill to check all beans in order to suppress this warning log. Besides, there may be another request converter which consumes a path variable without using `@Param` annotation. It means that we cannot check exactly whether all path variables are consumed or not. What do you think?

**Comment by trustin** [comment]
I think we can close this issue now that we suppress warning for the cases that can trigger false warnings. Or, is this still an issue, @LiYing2010 ?

**Comment by LiYing2010** [comment]
@trustin  san:
sorry for the late response.
I will check the latest version

**Comment by LiYing2010** [comment]
@trustin :
I have tested with the latest version `0.99.2`
the false warnings were gone.

I am closing this issue
