### ISSUE TITLE
DynamicEndpointGroup should only notify when endpoints changed

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1216]
Currently, `DynamicEndpointGroup` notifies listeners anytime when `setEndpoints` is called. This happens even if the endpoints didn't change, which doesn't seem very useful. I think a couple options would be

1) (preferred) `DynamicEndpointGroup` doesn't call `notifyListeners` when endpoints didn't change (by using `Object.equals` to compare the old and new ones)
2) `DynamicEndpointGroup` notifies listeners of both new and old endpoints so they can make the decision of whether to execute business logic even if nothing changed.

What do you think?

**Comment by trustin** [comment]
+1 I'm also curious if `DynamicEndpointGroup` should normalize the ordering of endpoints.

**Comment by anuraaga** [comment]
Yeah seems reasonable - sent a PR
