### ISSUE TITLE
Consider changing the http tracing code to use Brave's HttpTracing helper

### ISSUE THREAD

**Issue by adriancole** [line/armeria#1223]
Currently, the tagging policy of Armeria is framework-specific. This is not a problem in "pure armeria" applications per-se, but on the other hand, it doesn't leverage the abstraction work in Brave with regards to span lifecycle and data policy.

Most notably, using the `brave-instrumentation-http` library allow users to plugin standard sampling and tagging policy types. This is particularly helpful when sending data to strict systems such as Amazon X-Ray or Google Stackdriver, as you can ensure the data they need to read makes it.

https://github.com/openzipkin/brave/tree/master/instrumentation/http

Moreover, we have a standard test which verifies some edge cases, and we'd get more coverage for free this way. Here's something similar, for example, how vertx-web is written and tested:

https://github.com/openzipkin/brave/blob/master/instrumentation/vertx-web/src/main/java/brave/vertx/web/TracingRoutingContextHandler.java#L58
https://github.com/openzipkin/brave/blob/master/instrumentation/vertx-web/src/test/java/brave/vertx/web/ITVertxWebTracing.java

I could help a bit with this, but definitely would be awesome if someone else would be interested in doing it.

**Comment by anuraaga** [comment]
I remember looking at that code and avoided it for some reason - can't remember what that reason was though, it might not have been a good one.

**Comment by adriancole** [comment]
PS I'm polishing our self-tracing now and noticed this again.. it would be really useful to have the http pattern in the endpoints. For example, I can guess the root span was a "get /zipkin/traces" endpoint but others might not.

<img width="1024" alt="Screen Shot 2019-04-22 at 9 49 24 AM" src="https://user-images.githubusercontent.com/64215/56480429-f9f6a700-64f4-11e9-84af-a2439bd2d289.png">

here's another related change which might help https://github.com/reactor/reactor-netty/pull/622

**Comment by adriancole** [comment]
one impact of not doing this is it discourages switching because sampling policy is lost. For example, the HttpTracing module includes a server and client sampler object used to mute paths (ex static assets) from being traced, or to avoid originating traces from ad-hoc client use. In zipkin, for example, our self-tracing is going to overrun with low value assets until we add an after-the-fact handler to drop traces related to that. It would be nicer to have a means before-the-fact (normal sampling)
