### ISSUE TITLE
Default flow control window in Http2Settings?

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1241]
I was looking through upstream gRPC code and noticed they always set a default initial flow control window size in their `Http2Settings`

https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L58

Do you think armeria should set a default too? From what I can tell, the default is 64K, which seems pretty small and might affect connection warmup performance.

https://http2.github.io/http2-spec/#SETTINGS

```
SETTINGS_INITIAL_WINDOW_SIZE (0x4):
Indicates the sender's initial window size (in octets) for stream-level flow control. The initial value is 216-1 (65,535) octets.
```

It might be good to also allow configuring max streams. I wonder if max frame size should also be configurable, 16K seems a little small

```
ETTINGS_MAX_FRAME_SIZE (0x5):
Indicates the size of the largest frame payload that the sender is willing to receive, in octets.

The initial value is 214 (16,384) octets. 
```

For reference, gRPC's settings initialization.

https://github.com/grpc/grpc-java/blob/60a0b0c471d720b0546ee3a5b4fa4283635dfbcf/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L216

**Comment by trustin** [comment]
Sounds like a good suggestion.

**Comment by trustin** [comment]
Related: #1206
