### ISSUE TITLE
GRPC exception status code to HTTP status code could be improved

### ISSUE THREAD

**Issue by demongaorui** [line/armeria#1252]
Currently, Armeria-GRPC is mapping GRPC exception response status code very generally, for example:   For status ALREADY_EXISTS(GRPC status code: 6) to Http status 500.

While the upstream [GRPC gateway](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/third_party/googleapis/google/rpc/code.proto) is mapping  ALREADY_EXISTS(GRPC status code: 6) to [Http status 409(Conflict)](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/third_party/googleapis/google/rpc/code.proto#L96), which is makes more sense for making status code meaning more specific and clear.

Do you think it will be good to improve GPRC status code and HTTP status mapping in Armeria-GRPC? 

@trustin @anuraaga

**Comment by trustin** [comment]
Sounds like a good suggestion. What do you think, @anuraaga?

@demongaorui Please let us know if you interested in sending a PR :-)

**Comment by anuraaga** [comment]
To clarify, you are referring to unframed requests, right? For normal gRPC, the status code is always 200.

Changing the way to map errors to codes in unframed seems fine, though mapping `ABORTED` and `ALREADY_EXISTS` to the same code also seems very weird to me, but matching the behavior for unframed requests is a good change.

**Comment by demongaorui** [comment]
@anuraaga Yes, you are right, I mean unframed requests.  And, mapping `ABORTED ` and `ALREADY_EXISTS ` both to `HTTP Mapping: 409 Conflict` indeed is weird. 

@trustin I'd like to prepare a PR to improve Armeria-GRPC unframed requests mapping and also raise up a discussion issue in the upstream repository for mapping rules at the same time. Let's see whether they have particular reasons for the weird mapping.

**Comment by demongaorui** [comment]
@anuraaga   I've checked Http status codes trying to find a better matching for `ABORTED` and/or `ALREADY_EXISTS` instead of `409 Conflict`, which don't find ideal candidates. Any ideas?

**Comment by trustin** [comment]
Missed @demongaorui's last comment:

> I've checked Http status codes trying to find a better matching for `ABORTED` and/or `ALREADY_EXISTS` instead of `409 Conflict`, while don't find ideal candidates. Any ideas?

@anuraaga, thoughts?

**Comment by anuraaga** [comment]
I would personally pick either Service Unavailable or Internal Error since I can't see how Aborted should map to a client error. As far as Armeria goes, though, we should just reproduce upstream behavior and have a unit test to catch if upstream feels the same (they may not). Since we reproduce the behavior ok, there's nothing else to do here :)
