### ISSUE TITLE
ServerBuilder.tls should cause server to only start with HTTPS?

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1279]
I was confused recently when I used `ServerBuilder.tls(ctx)` and it started with both HTTP and HTTPS. I was expecting behavior similar to when calling `ServerBuilder.https(0)` in that when TLS is requested, it is the only one enabled. Does anyone else feel the same confusion?

**Comment by trustin** [comment]
That's a good question. Yes, I agree it may be confusing and sometimes could be a security concern. +1 for defaulting to HTTPS only when `.tls()` was invoked without any `http/https/port()`. Thoughts? @minwoox @hyangtack

**Comment by hyangtack** [comment]
@trustin @anuraaga +1
