### ISSUE TITLE
How do you enable exception logging?

### ISSUE THREAD

**Issue by chaschev** [line/armeria#1294]
Created my server like below. Everything works fine, except that I don't see stack traces when there are exceptions in gRPC handlers. I see other messages and was able to enable access log, however I don't see stack traces. As much as I want those errors to never occur again, for now it is not an option. Thanks!

```kotlin
val grpc = GrpcServiceBuilder()
      .supportedSerializationFormats(GrpcSerializationFormats.values())
      .addService(RpcAuthService())
      .addService(RpcUserTableService())
      .addService(RpcTableService())
      .build()

    logger.info { "[$sub] grpc path mappings: ${grpc.pathMappings()}" }

    server = ServerBuilder()
      .port(core.grpcPort, SessionProtocol.HTTP)
      .service(
        grpc,
        corsBuilder.newDecorator()
      )
      .accessLogWriter(AccessLogWriters.common())
      .serviceLoggerPrefix("pfx")
      .build()
```

**Comment by chaschev** [comment]
That worked, though I am not sure I can see the stacktrace

**Comment by trustin** [comment]
It does log stack trace: https://github.com/line/armeria/blob/armeria-0.67.2/core/src/main/java/com/linecorp/armeria/internal/logging/LoggingDecorators.java#L58-L75

Please let us know if anything doesn't work as intended.

**Comment by chaschev** [comment]
That turned out to be a bug in my logging library. It didn't recognise exception in the list of logging method arguments. Thanks!

**Comment by trustin** [comment]
Thanks for getting back to us with an update. :smile:
