### ISSUE TITLE
HttpClient should reject authority that doesn't match client URL?

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1343]
Currently, it's possible to send a request with a different authority than the client stub was created with

```java
HttpClient client = HttpClient.of("https://github.com/");
HttpRequest req = HttpRequest.of(HttpMethod.GET, "/");
req.authority("bitbucket.org");
client.execute(req);
```

This will send a request to `github.com` with authority `bitbucket.org`. This isn't terrible but I found with `0.69.0`, the authority is actually used in TLS negotiation. It's extremely likely that when using TLS, such a mismatch of URL and authority will fail with cryptic TLS handshake errors.

I'm not sure if it's better to do anything about this, as it is conceivable that a server/client is set up that such an abuse of authority works. But it was pretty surprising and hard to debug when running into it as a bug. For reference, I ran into it with a proxy service, which is probably where it is most likely to crop up.

```java
(ctx, req) -> {
  req.headers().path("/proxied");
  // Wish there was an easier way of knowing I need to do this too
  // req.authority("");  Without this, the request will fail to do TLS handshake.
  // TLS handshake failures usually happen deep in JDK or netty and are very hard to
  // troubleshoot :(
  return client.execute(req);
}
```

/cc @gavinreaney

**Comment by anuraaga** [comment]
Yeah I'm not sure how common either behavior is (for that example I'm a bit surprised internal hosts would have the external cert provisioned to them) so not sure what the default would be but an option would be nice.

**Comment by anuraaga** [comment]
Think this was fixed by https://github.com/line/armeria/pull/1961

**Comment by trustin** [comment]
Thanks, @anuraaga
