### ISSUE TITLE
Implement HTTP/2 graceful shutdown

### ISSUE THREAD

**Issue by trustin** [line/armeria#1346]
According to https://httpwg.org/specs/rfc7540.html#GOAWAY

> A client that is unable to retry requests loses all requests that are in flight when the server closes the connection. This is especially true for intermediaries that might not be serving clients using HTTP/2. A server that is attempting to gracefully shut down a connection SHOULD send an initial GOAWAY frame with the last stream identifier set to 2^31-1 and a NO_ERROR code. This signals to the client that a shutdown is imminent and that initiating further requests is prohibited. After allowing time for any in-flight stream creation (at least one round-trip time), the server can send another GOAWAY frame with an updated last stream identifier. This ensures that a connection can be cleanly shut down without losing requests.

**Comment by anuraaga** [comment]
Just wondering, was this fixed by #1392?

**Comment by ikhoon** [comment]
Fixed by #3715
