### ISSUE TITLE
How can I use JPA repository methods in Armeria GRPC service implementation class?

### ISSUE THREAD

**Issue by TamaraVaradjanin** [line/armeria#1374]
I am using Armeria with Spring boot and I want to use CRUD operations from my repositories in GRPC service implementations. It doesn't work with Autowired annotation.

**Comment by trustin** [comment]
Hello! How did you instantiate your service implementation? Could you paste some code?

**Comment by TamaraVaradjanin** [comment]
Hello. I solved this problem, it was about Spring Boot version and some dependencies. I'm getting GRPC service bean from Spring application context (when adding service to ServerBuilder) with injected JPA repository and it works.

**Comment by trustin** [comment]
Thanks for reporting back in spite of my late response!

On the other hand, I'm curious what your experience with Armeria so far is like. Is it serving your job well? I wonder if there is any missing or good-to-have features in your mind. 🙇
