### ISSUE TITLE
HttpServerIdleTimeoutHandler can keep an idle connection open.

### ISSUE THREAD

**Issue by trustin** [line/armeria#14]
Currently, `HttpServerIdleTimeoutHandler` is added *after* `HttpObjectAggregator`.  This yields an interesting behavior; when `pendingResCount` is 0, the request (usually the first request of a connection) must be received within `<idleTimeoutMillis>` milliseconds, because `HttpObjectAggregator` will not produce anything until a full HTTP message is built.

I think this behavior is fine, although it sort of looks like an unintended side effect.

However, I see the following edge case:

1. The client sends the first request. (`pendingResCount` becomes 1)
2. The server did not send the first response yet and the client starts to send the second request
3. The server did not send the first response yet again, the client sends the second request partially, and then stops sending anything.
4. `HttpServerIdleTimeoutHandler.channelIdle()` will be invoked, but it will be ignored because `pendingResCount` is 1.
5. The server sends the first response finally (`pendingResCount` becomes 0), but the client did not send anything since the step (3).
6. `HttpServerIdleTimeoutHandler.channelIdle()` will be invoked again, but will be ignored again because it's not the first event this time (see the `evt.isFirst()` check.)

A quick fix would be to remove the `evt.isFirst()` check, but I wonder if we had a good reason for having it in the first place. Do you remember why, @inch772?

**Comment by inch772** [comment]
I remember as it was  intended to prevent  duplicated invoke of ``ctx.close`` which considered ``IdleStateEvent`` can fired multiple times.
Is it better checking close proceed or not instead using ``evt.isFirst()``?

**Comment by inch772** [comment]
I will try to modify remove  ``evt.isFirst()`` from check logic. also check side effect about we call ``ctx.close()`` multiple-times.

**Comment by inch772** [comment]
Sorry to my miss explains. I found ``HttpServerIdleTimeoutHandler`` working expected even the situation that you assumed.
If channel receive or write  ``IdleTimeoutHandler`` set ``firstAllIdleEvent`` to ``true`` which value decide ``evt.isFirst()`` as true or not. 
In edge case step 4 make ``firstAllIdleEvent`` to ``false``.
but step 5( send response) make ``firstAllIdleEvent`` to ``true``.
As a result step 6. cause ``HttpServerIdleTimeoutHandler.channelIdle() `` invoke with ``evt.isFirst()`` as true. So channel can be closed by ``HttpServerIdleTimeoutHandler``

* related codes
https://github.com/netty/netty/blob/92dee9e500bc141162e6c3a6ef91d8d22e50c449/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L264
https://github.com/netty/netty/blob/92dee9e500bc141162e6c3a6ef91d8d22e50c449/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L105

I make a pull request for test this case.
https://github.com/line/armeria/pull/19

**Comment by trustin** [comment]
You are correct. I mis-thought that we are using readerIdleTimeout only. Merged #19. Thanks for digging deep!
