### ISSUE TITLE
Cannot issue HTTP request with escaped slashes in path

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1416]
I think it happened somewhere around #1356 but whereas previously `HttpClientDelegate` sent the user's request path correctly, now it decodes the user's path, which is not correct. It means currently it's not possible to issue a request with, for example, escaped path parameters as they get decoded and sent as a raw path instead.

While refactoring `PathAndQuery` I guess we forgot that `HttpClientDelegate` also uses it for sanitizing.

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java#L172

**Comment by anuraaga** [comment]
By the way, an example URL that cannot be used with the current behavior

https://content.googleapis.com/storage/v1/b/telemetry-data-dev/o/satellites%2F1%2Fantennas%2F9%2F1346001%2Ffull.bin

**Comment by anuraaga** [comment]
Interestingly the test fails with 404 before and after https://github.com/line/armeria/compare/master...anuraaga:no-sanitize?expand=1

I have a feeling the server side has the same problem where it is decoding escaped slash characters before routing.

**Comment by anuraaga** [comment]
For context, my proposed fix is to not overwrite the URL in `HttpClientDelegate` - as long as the URL is valid it seems like too low a layer to rewrite the request as the user may have a reason for inputting what they did.

**Comment by trustin** [comment]
Should `%2F` and `/` treated differently? I thought they should be treated identically..

**Comment by anuraaga** [comment]
Hmm - I'm not too sure what the spec says, but I guess it would be impossible to support slashes in a path parameter if it's not escaped.

**Comment by anuraaga** [comment]
Ah but I should be able to use it in the test for the change I linked - let me try it.

**Comment by trustin** [comment]
> In this case, it's an object storage server so the API is /storage/v1/b/telemetry-data-dev/o/ and the last path param is the filename to save the object - it's common to have slashes in a filename for object storage. Defining the regex like that wouldn't make sense.

Why doesn't it make sense? The capture group `path` will capture the complete filename including the slashes in it.

> Also, for what it's worth I don't need to define such a server, but I'm trying to use an armeria HTTP client with an external server (Google Cloud Storage API), I guess it's not unreasonable for a server to expect slashes in requests to be escaped which is currently not possible at all.

Ah, I see. I agree that such heavy sanitization isn't necessary and may even alter the original intention of the client. Perhaps it's time to split the logic.

**Comment by anuraaga** [comment]
Yeah that makes sense - the server side looks ok, and it's just that servers out there may treat `/` and `%2F` differently, which is a problem for the client.

**Comment by trustin** [comment]
OK! Interested in sending a PR for this or should I take a stab?

**Comment by anuraaga** [comment]
Was able to tweak the test to work in my PR :D
