### ISSUE TITLE
trimShadedJar doesn't work with openjdk 11 on Ubuntu

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1420]
I am using OpenJDK 11 from the Ubuntu [PPA](https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa) and ran into an issue with shading.

OpenJDK 11.0.1 Linux

```bash
$ ./gradlew publishToMavenLocal
```

```
> Task :core:trimShadedJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:trimShadedJar'.
> java.io.IOException: Can't read [/usr/lib/jvm/java-11-openjdk-amd64/jmods/java.datatransfer.jmod] (Can't process class [module-info.class] (Unsupported version number [55.0] (maximum 54.0, Java 10)))

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
```

**Comment by anuraaga** [comment]
There have been bugs with PPA openjdk in the past, if it seems like a bug in the JDK let's close.

**Comment by trustin** [comment]
It's ProGuard that does not support Java 11 byte code version. It seems to take a liitle bit longer...

We may want to replace ProGuard with Shadow plugin's minimization feature, but it was not possible to include other modules' test classes into dependency analysis last time I checked..

**Comment by trustin** [comment]
Fixed some time ago. :-)
