### ISSUE TITLE
Add log availability for writing first byte and reading first byte from channel

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1421]
I am trying to debug a lot of untraced time in spans (e.g., time between client send <-> server receive) and it would be very useful to have wire send (ws) and wire receive (wr) annotations which I believe are semi-standard annotations added by other zipkin instrumentation. For armeria, I think it would involve adding FIRST_BYTE_SENT and FIRST_BYTE_RECEIVED request log availability, propagate `RequestContext` into the `Http*Encoder` classes and call the log methods just after writing to the channel, or receiving from it. If there is anywhere more appropriate than the encoders (ideally it should be done in the very last actual netty channel handler but not sure if we can propagate request context that far) let me know.

With such callbacks, it'd be simple to also update the zipkin library to add annotations during those events. If the general idea seems fine, would be glad to implement.

/cc @adriancole

**Comment by adriancole** [comment]
we had a chat and one low-hanging fruit is at least on client side do
"ws" "wr" annotations such as finagle does. This is easier client side
than server side.

There's another doc on modeling certain things with spans, this is
more thinking might be worth it
https://docs.google.com/document/d/1yIo_zZvMyAS8J7bpCz85h-FISwU0Jr-Zu-POIvp7B9E/edit

**Comment by trustin** [comment]
Sounds like a good idea! Will be very useful for us as well.
