### ISSUE TITLE
Findings about ByteBufHttpData

### ISSUE THREAD

**Issue by trustin** [line/armeria#1428]
I found that `Http2RequestDecoder` produces `ByteBufHttpData` while `Http2ResponseDecoder` makes an array-based copy. I thought using `ByteBufHttpData` in `Http2ResponseDecoder` may improve the performance, but surprisingly it reduced the throughput noticeably:

#1424:
```
Benchmark                        (clientType)   Mode  Cnt      Score     Error  Units
DownstreamSimpleBenchmark.empty        NORMAL  thrpt  100  50075.398 ± 451.960  ops/s
```

#1424 + Using `ByteBufHttpData` in `Http2ResponseDecoder`:

```
Benchmark                        (clientType)   Mode  Cnt      Score     Error  Units
DownstreamSimpleBenchmark.empty        NORMAL  thrpt  100  47030.161 ± 388.290  ops/s
```

So, I got interested and ran the same test with `ByteBufHttpData` removed from `Http2RequestDecoder`, and got the following result:

#1424 + Not using `ByteBufHttpData` in `Http2RequestDecoder` (i.e. no `ByteBufHttpData` for inbound traffic)

```
Benchmark                        (clientType)   Mode  Cnt      Score     Error  Units
DownstreamSimpleBenchmark.empty        NORMAL  thrpt  100  49812.047 ± 317.448  ops/s
```

If I remember correctly, this contradicts the previous numbers reported by @anuraaga. Perhaps JVM optimization or improvements in Netty (~e.g. https://github.com/netty/netty/pull/8393~ Test was run with Netty 4.1.30, so this optimization did not affect the numbers.) has changed the game?

**Comment by anuraaga** [comment]
I think most of the benefit from having byte buf data comes for larger payloads - I would expect the empty benchmarks to mainly exercise general connection handling and byte buf optimizations shouldn't affect it too much. It's interesting to see the response decoder number change that much though - admittedly I haven't looked into client performance at all yet, I use clientType == OKHTTP still to focus on server behavior and not trigger upstream's performance hole.

I guess there might still be a difference in the large payload benchmark?

https://github.com/line/armeria/blob/master/benchmarks/src/jmh/java/com/linecorp/armeria/grpc/downstream/LargePayloadBenchmark.java

**Comment by trustin** [comment]
I ran `LargePayloadBenchmark` and found `ByteBufHttpData` has better performance clearly. Not sure why we have penalty on the client-side decoder, but that's another story. Thanks.

**Comment by trustin** [comment]
Re: Worse result using `ByteBufHttpData` in `Http2ResponseDecoder` - I ran the benchmark a few more times and it seems like it's kind of random. In some run it's faster and in some other run it is not. Just a Hotspot whim?
