### ISSUE TITLE
Expose TransportType to users?

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1438]
I needed to write a TCP client in an armeria server and ended up using the `TransportType` internal class to also take advantage of `CommonPools`. Since we expose `CommonPools`, does it make sense to expose `TransportType` for this sort of use case? Maybe it's overkill, just want to get it out there.

```java
    var workerGroup = CommonPools.workerGroup();
    var bootstrap = new Bootstrap();
    bootstrap.group(workerGroup);
    // NOTE(rag): This is an internal API, but should be stable. Will see about exposing it to
    // users.
    bootstrap.channel(TransportType.socketChannelType(workerGroup));
    bootstrap.option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT);
    bootstrap.option(ChannelOption.SO_KEEPALIVE, true);
    bootstrap.handler(
        new ChannelInitializer<SocketChannel>() {
          @Override
          protected void initChannel(SocketChannel ch) {
            ch.pipeline().addLast(new Handler());
          }
        });

    channel = bootstrap.connect(target.getHost(), target.getPort()).syncUninterruptibly().channel();
```

**Comment by trustin** [comment]
Sounds OK to me. How about moving to `armeria.common`?

**Comment by anuraaga** [comment]
I'm also thinking of just adding methods to `EventLoopGroups` -> `serverChanneLClass`, `socketChannelType` and `datagramChannelType`. The other methods seem like they'd never have any use for users. What do you think about just adding those three methods to `EventLoopGroups`, which just calls into `TransportType` for the corresponding methods?
