### ISSUE TITLE
Propagate gRPC stacktrace using DebugInfo proto

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1471]
There seems to be a semi-official protocol for propagating stacktraces through gRPC using DebugInfo

https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/errorhandling/DetailErrorSample.java#L78

We should add support to the server to populate a stacktrace into DebugInfo and the client to reconstruct a `Throwable` cause from it.

**Comment by anuraaga** [comment]
I am having second thoughts on this - currently setting verbose responses will let normal logging, like `LoggingClient` but with this proto it requires special handling. The proto is only a list of strings so it's tricky or not possible to reconstruct a proper `Throwable` in the client - I would probably end up parsing it and stuffing it into `message` there anyways to make sure it gets logged.

Any thoughts on this?

**Comment by trustin** [comment]
You mean putting the stack trace into both `grpc-message` and `DebugInfo`?

**Comment by trustin** [comment]
Shouldn't a gRPC exception be recorded in `RequestLog.responseCause`?

**Comment by anuraaga** [comment]
I read more at the example and found this snippet

https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/errorhandling/DetailErrorSample.java#L52

I think the recommendation is to use an application-specific proto, not necessarily `DebugInfo` itself. This makes sense to me since `DebugInfo` is basically just repeated string and doesn't seem to provide much value IMO.

I'm thinking of creating an armeria-specific proto with enough information to reconstruct `StackTraceElement` in the client and attaching a `Throwable` as the cause when decoding an error status. That way, logging should work fine since the stack trace will be logged as the cause of the `Throwable` by logging libraries, similar to how currently they log the stack trace as the message itself.

How does this sound?

**Comment by trustin** [comment]
Sounds good to me.
