### ISSUE TITLE
Armeria removes ContentLength header when performing PUT requests without content

### ISSUE THREAD

**Issue by sschepens** [line/armeria#1476]
When performing a PUT http request without content and with Content-Length=0 with armeria, the Content-Length header gets removed [here](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java#L247). This was added in #226 which speaks of GET requests, but this logic is being applied to all request methods, including PUT, POST, etc., which are supposed to have content.

**Comment by trustin** [comment]
IIRC an absence of `content-length` header means an absence of message body in HTTP, so it's not a protocol violation, but I agree that adding `content-length: 0` to the requests with the methods which are supposed to have content.

**Comment by trustin** [comment]
Oh, and sorry about the late reply. :pray:

**Comment by sschepens** [comment]
thanks!
