### ISSUE TITLE
Add CIDR based `Predicate<InetAddress>`

### ISSUE THREAD

**Issue by trustin** [line/armeria#1490]
Once #1467 is merged, we could add a utility class that provides static factory methods that creates `Predicate<InetAddress>` from a CIDR notation, such as `192.168.0.0/24`. We could perhaps fork `org.jboss.netty.handler.ipfilter.CIDR`.

**Comment by hyangtack** [comment]
Need to update [documentation](https://line.github.io/armeria/server-basics.html) as well.
