### ISSUE TITLE
Implement advanced request mapping

### ISSUE THREAD

**Issue by trustin** [line/armeria#150]
Like various web frameworks, it would be useful to have path variable mappings:

``` java
ServerBuilder sb = ...
sb.serviceAt("/a/{foo}/b/{bar}", ....);
...
ctx.mappedVariables().get("foo");
```

Need to do the survey on well known path mapping notations such as:
- http://guides.rubyonrails.org/routing.html
- http://docs.spring.io/autorepo/docs/spring/4.2.x/spring-framework-reference/html/mvc.html
- http://www.sinatrarb.com/intro.html#Routes
- https://www.playframework.com/documentation/2.5.x/JavaRouting

**Comment by taicki** [comment]
For HttpServices, HTTP methods are defined together when declaring routes in usual web frameworks. That may need to be considered when implementing advanced request mapping.

**Comment by trustin** [comment]
It's probably a better idea to implement this sort of advanced routing in an `HttpService` implementation, as you said.
