### ISSUE TITLE
Create an abstraction for a LoggingContext containing request properties

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1510]
Currently, armeria natively exports many useful attributes to logback logs

https://github.com/line/armeria/blob/master/logback/src/main/java/com/linecorp/armeria/common/logback/BuiltInProperty.java

But since these are hard-coded into the logback implementation itself, it can't be reused for log4j users. Could we add to a `RequestContext` a layer that accumulates key/value pair that logging layers can read without special processing?

Here is a similar idea, but misses out on armeria's built-in logging, which would be very tedious to duplicate.

https://github.com/curioswitch/curiostack/blob/master/common/server/framework/src/main/java/org/curioswitch/common/server/framework/logging/RequestLoggingContext.java#L39

**Comment by trustin** [comment]
How could we let a user decide which built-in properties or context attributes to export automatically? Currently, it's part of Logback appender's configuration. I wonder if it's appropriate to move this configuration into the core API or if we can just provide something similar for Log4J, given that there are not many logging frameworks to support.

**Comment by anuraaga** [comment]
IMO core API seems fine since we have many logging features there already, like `LoggingService`. To be honest, I was surprised to find https://github.com/line/armeria/blob/master/logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporter.java in logback package since it doesn't touch any logback APIs at all and it's a ton of code to possibly duplicate into log4j implementation.

Creating a shared artifact for that or just duplicating might be fine, but also I do think there'd be a lot of convenience if we could offer `requestCtx.logCtx().put("entityId", id)` so it's very easy for business logic to add additional tags without worrying about threads. Does that make it worth putting it into core?

**Comment by trustin** [comment]
> IMO core API seems fine since we have many logging features there already, like `LoggingService`. To be honest, I was surprised to find https://github.com/line/armeria/blob/master/logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporter.java in logback package since it doesn't touch any logback APIs at all and it's a ton of code to possibly duplicate into log4j implementation.
>
> Creating a shared artifact for that or just duplicating might be fine

Perhaps we could clean up the common export logic a little bit and move it to `armeria.common` or into a utility method of `RequestContext`? e.g. `Map<String, String> ctx.exportProperties(...properties to export...)`

> but also I do think there'd be a lot of convenience if we could offer `requestCtx.logCtx().put("entityId", id)` so it's very easy for business logic to add additional tags without worrying about threads. Does that make it worth putting it into core?

`RequestContext` already extends `AttributeMap` which overlaps with it to some extent. How about replacing `AttributMap` with our own interface which defines a key which tells if its value needs to be exported to logging framework or to the String representation of `RequestContext`? e.g.

```java
private static AttributeKey<String> ENTITY_ID =
        AttributeKey.of("entityId", /* exported */ true);
private static AttributeKey<ComplexObject> COMPLEX_OBJECT = 
        AttributeKey.of("...", true, complexObject -> "stringified: " + complexObject.propX());
```

**Comment by anuraaga** [comment]
Yeah using a special `AttributeKey` like that looks quite nice.

**Comment by trustin** [comment]
I may work on this issue this week.

**Comment by ikhoon** [comment]
@trustin If you didn't start yet, I'd like to take a look. 😉

**Comment by trustin** [comment]
The groundwork for adding support for Log4J2 is now done.
