### ISSUE TITLE
Content decoding server decorator

### ISSUE THREAD

**Issue by codefromthecrypt** [line/armeria#1521]
I think I eventually request this issue on all http frameworks :)

Most of the time you see (gzip) encoding filters on servers and decoding filters on client. However, POST requests are often gzipped. I scratched around and didn't see a server-side content decoder. Would be nice!

**Comment by trustin** [comment]
Related: https://github.com/line/armeria/issues/692

**Comment by adriancole** [comment]
yeah #692 seems same, just this is more impl related side of the coin

**Comment by trustin** [comment]
Seems like this has been fixed already in #3087, right? Please feel free to reopen if it's not the case.
