### ISSUE TITLE
thfirt and grpc can be converted to each other？

### ISSUE THREAD

**Issue by wansuiye** [line/armeria#1564]
I wonder if armeria can support that thfirt and grpc can be converted to each other.

**Comment by trustin** [comment]
Hi! Thanks for you interest. Thrift and gRPC are serialization formats very different from each other and thus it is not possible to perform an automatic conversion between the two formats. However, if you wrote the definitions for both Thrift (`.thrift`) and gRPC (`.proto`) then you can run both on Armeria without creating two server instances.

**Comment by trustin** [comment]
Please feel free to reopen if you think your question needs further answer.
