### ISSUE TITLE
Immutable HttpHeaders and Cookies

### ISSUE THREAD

**Issue by trustin** [line/armeria#1567]
`HttpHeaders` in Armeria is mutable. Although it is convenient to use, it sometimes leads us to a surprising behavior when it's modified by an unexpected place.

To address such issues, I'd like to propose to make `HttpHeaders` immutable, which means modifying an `HttpHeaders` will result in a new `HttpHeaders` instance. The following is an example of the API I have in mind:

```java
// Mutable headers. Behaves like current HttpHeaders do.
MutableHeaders mh1 = MutableHeaders.of().add("name", "value");

// Immutable headers. Does not have methods like 'set()'.
Headers ih1 = ImmutableHeaders.of("name", "value", ...);

// Conversion to immutable headers.
Headers ih2 = mh1.toImmutable();

// Conversion to mutable headers.
MutableHeaders mh2 = ih2.toMutable();
assertThat(mh2).isEqualTo(mh1);
assertThat(mh2).isNotSameAs(mh1); 

// Mutation of immutable headers.
Headers ih3 = ih2.mutate((MutableHeaders h) -> {
    h.set("name", "new-value");
    ...
});

// One-time mutation.
Headers ih4 = ih2.mutator().set("name", "new-value");
```

Thoughts? I'd like to get as much feed back (e.g. what could be a problem when we do this?) as possible because this will be a big breaking change. To be honest, I may even fail to refactor Armeria itself because Armeria itself relies on mutability of `HttpHeaders` in some places.

Note that I removed `Http` from the type names, which may need an additional discussion as well.

**Comment by southernkasaist** [comment]
How about using `builder` way like lombok style?
e.g., 
```java
Headers headers = ImmutableHeaders.builder().add("name1", "value1").build();
Headers other = headers.toBuilder().add("name2", "value2").set("name1", "value3").build();
```

**Comment by tobias-** [comment]
1. Please litter the methods in ImmutableHeaders with JSR-305 annotations such as `@javax.annotation.CheckReturnValue`as it really helps avoiding trivial mistakes.
2. Please consider doing it "Kotlin-style" where the Kotlin List (comparable to ImmutableHeaders) doesn't even have the add methods, but the MutableList (comparable to MutableHeaders) does. In Kotlin, if you need to mutate a List, you will have to make it mutable by doing `fooList.toMutableList()` before doing add. Unless a method/parameter is explicitly MutableList, it will be a List, which will not even have those methods.

**Comment by trustin** [comment]
@tobias- wrote:
> Please litter the methods in `ImmutableHeaders` with JSR-305 annotations such as `@javax.annotation.CheckReturnValueas` it really helps avoiding trivial mistakes.

We already use `@Nullable` everywhere, but didn't have a chance to think about `@CheckReturnValues`. What methods do you think deserves that annotation? If any methods with non-void return type deserves it, then I guess there's no point of annotating it, i.e. if everybody's hero, nobody is.

> Please consider doing it "Kotlin-style" where the Kotlin List (comparable to ImmutableHeaders) doesn't even have the add methods, but the MutableList (comparable to MutableHeaders) does. 

Yes, that's the plan. 😉

**Comment by trustin** [comment]
Realized that we have the same problem with `Cookies` and `Cookie`, so updated the title of this issue.

**Comment by tobias-** [comment]
> We already use `@Nullable` everywhere, but didn't have a chance to think about `@CheckReturnValues`. What methods do you think deserves that annotation? If any methods with non-void return type deserves it, then I guess there's no point of annotating it, i.e. if everybody's hero, nobody is.
> 
Well, in the case of methods on immutable objects, all methods calls that don't do anything with the result are a guaranteed waste of cpu-cycles, and most likely a bug, so the mundanes would be methods that mutate the object's state.

> > Please consider doing it "Kotlin-style" where the Kotlin List (comparable to ImmutableHeaders) doesn't even have the add methods, but the MutableList (comparable to MutableHeaders) does.
> 
> Yes, that's the plan. wink
I was unclear, but hopefully you understood it anyway. What I mean is that I would like MutableHeaders to inherit ImmutableHeaders. I think that would help in the refactoring as well, as you can just change parameter types and return types and 95% of the way.

**Comment by trustin** [comment]
> What I mean is that I would like MutableHeaders to inherit ImmutableHeaders.

That would make `headers instanceof ImmutableHeaders` yield `true` even if `headers` is a `MutableHeaders`, which would cause quite a bit of confusion.

**Comment by trustin** [comment]
Will try to take a stab on this soon

**Comment by anuraaga** [comment]
@trustin I noticed upgrading to 0.80.0, decorators started to see an immutable `HttpHeaders` when doing something like a `FilteredHttpResponse`. I see in the release notes that `AggregatedHttpMessage` has an immutable instance but don't see anything related to decorators. Just wondering, was it an intended change? It was quite breaking for me :) It did make me think that for such a change, it would probably be ideal if there was one stage where mutation operators logged a warning and another where the change actually happens since `UnsupportedOperationException` can't be caught until runtime

**Comment by trustin** [comment]
@anuraaga Oops! Sorry about the inconveniences. We should have thought once more when making that change..

My idea for the change proposed in this issue was basically to trigger a bunch of compilation errors by removing all mutator methods from `HttpHeaders`, but I guess it's not a great idea for our users. :-)

How about this:

1. Make the `HttpHeader` given to decorators mutable again. (I think I need your help on this. Would you mind letting me know where to look?)
2. Prepare a migration path:
   a. Add some methods like `toMutable()`, `toBuilder()` or `mutate()` to `HttpHeaders`.
   b. Add `MutableHttpHeaders` and `HttpHeadersBuilder`.
   c. Log a warning with some suggestion when a user calls the deprecated self-mutating methods in `HttpHeaders`.
3. Cut a release with (1) and (2).
4. Wait for a few releases and remove the deprecated methods.

3. Add

**Comment by anuraaga** [comment]
I personally don't need the decorator's behavior restored as I've already updated them all, so if no one else has had problems, maybe it's ok now no strong opinion there.

But for reference, this sort of change was required to avoid `UnsupportedOperationError` in a decorator

https://github.com/curioswitch/curiostack/pull/274/files

**Comment by anuraaga** [comment]
And indeed, if `HttpHeaders.add` didn't exist at all, this code would have broken at compile time and that would have been fine for me, build breaks are easy to fix runtime breaks are the scary ones.

**Comment by trustin** [comment]
This is a rough preview of the new API:

- `HeaderGetters` - provides the getters to `Headers` and `HeadersBuilder`
  - [HeaderGetters.java](https://github.com/trustin/armeria/blob/immutable_headers/core/src/main/java/com/linecorp/armeria/common/HeaderGetters.java)
  - [RequestHeaderGetters.java](https://github.com/trustin/armeria/blob/immutable_headers/core/src/main/java/com/linecorp/armeria/common/RequestHeaderGetters.java)
  - [ResponseHeaderGetters.java](https://github.com/trustin/armeria/blob/immutable_headers/core/src/main/java/com/linecorp/armeria/common/ResponseHeaderGetters.java)
- `Headers` - immutable HTTP/2 headers
  - [Headers.java](https://github.com/trustin/armeria/blob/immutable_headers/core/src/main/java/com/linecorp/armeria/common/Headers.java)
  - [RequestHeaders.java](https://github.com/trustin/armeria/blob/immutable_headers/core/src/main/java/com/linecorp/armeria/common/RequestHeaders.java)
  - [ResponseHeaders.java](https://github.com/trustin/armeria/blob/immutable_headers/core/src/main/java/com/linecorp/armeria/common/ResponseHeaders.java)
- `HeadersBuilder` - builds a `Headers`
  - [HeadersBuilder](https://github.com/trustin/armeria/blob/immutable_headers/core/src/main/java/com/linecorp/armeria/common/HeadersBuilder.java)
  - [RequestHeadersBuilder](https://github.com/trustin/armeria/blob/immutable_headers/core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java)
  - [ResponseHeadersBuilder](https://github.com/trustin/armeria/blob/immutable_headers/core/src/main/java/com/linecorp/armeria/common/ResponseHeadersBuilder.java)

Note that `Headers` now have two new subtypes `RequestHeaders` and `ResponseHeaders`. They are essentially same, but they are different in which shortcut methods they expose. It was inspired by @anuraaga's suggestion about separating `AggregatedHttpMessage` into `AggregatedHttpRequest` and `AggregatedHttpResponse`.

The following is the example usage:

```java
RequestHeaders h = RequestHeaders.of(HttpMethod.GET, "/foo");
RequestHeaders h = RequestHeaders.of(HttpMethod.GET, "/foo",
                                     HttpHeaderNames.ACCEPT_ENCODING, "gzip",
                                     HttpHeaderNames.AUTHORITY, "foo.com");
RequestHeaders h = new RequestHeadersBuilder(HttpMethod.GET, "/foo")
    .add(HttpHeaderNames.ACCEPT_ENCODING, "gzip")
    .add(HttpHeaderNames.AUTHORITY, "foo.com")
    .build();

RequestHeaders h = h.toBuilder()
                    .add(HttpHeaderNames.USER_AGENT, "baz")
                    .build();

RequestHeaders h = h.mutate(mutator -> {
    mutator.add(HttpHeaderNames.USER_AGENT, "baz");
    mutator.remove(HttpHeaderNames.ACCEPT_ENCODING);
});
```

**Comment by trustin** [comment]
`HttpHeaders` is now immutable. Time to make `Cookie` and `HttpParameters` immutable. 🚀
