### ISSUE TITLE
Allow adding "service-less" decorators to path patterns

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1579]
Currently, decorators must be applied directly to services, or to the server to apply to all services in the server. I often find it tedious to have to apply the same decorator to multiple services, e.g., multiple services served until `/internal`. It also makes writing frameworks more difficult since any framework-specific services must be exposed to users to allow them to decorate if they have custom authentication needs, or similar.

It would be cool if we could register decorators to path patterns - armeria finds the services that match a path along with any decorators that match it and applies the decorators to the service before executing. This came to mind again during #1578 where the framework provides actuator endpoints, but it isn't possible for users to add custom authentication, unless exposing some API for customizing the services which is tedious.

**Comment by trustin** [comment]
Probably a duplicate of #582, which is a nice feature to have.

**Comment by anuraaga** [comment]
Ah yup - thanks for linking!
