### ISSUE TITLE
How to use armeria in Undertow

### ISSUE THREAD

**Issue by AsinRay** [line/armeria#1582]
How to use armeria in Undertow?

**Comment by trustin** [comment]
Armeria has its own networking layer which is independent from Undertow, which means Armeria and Undertow will run separately on two different HTTP(S) ports.

Unlike Tomcat and Jetty, Undertow does not provide a way to switch its networking engine. Therefore, it is not possible to embed Undertow into Armeria, either.

**Comment by trustin** [comment]
If you are interested in using Undertow and Armeria together because of Undertow's Servlet support, you may want to consider switching to Tomcat or Jetty and embed it into Armeria using `TomcatService` or `JettyService`, which allows you to serve Servlet-based application with Armeria.
