### ISSUE TITLE
Provide a way to get request body in service method.

### ISSUE THREAD

**Issue by hyeonjames** [line/armeria#1584]
Currently, Armeria provides a `StringRequestConverterFunction`, `ByteArrayRequestConverterFunction` by default to get the request body.

However, it is only for specific types

A user may want to get it for other types, too ( e,g. `application/json`, `application/xml` etc )

**Comment by tmdgus0118** [comment]
It'd be better if it supports `byte[]`, `ByteBuf`, `char[]` etc

**Comment by jongmin92** [comment]
I'm working on it.
