### ISSUE TITLE
Add method/class name to metric for Retrofit

### ISSUE THREAD

**Issue by hyeonjames** [line/armeria#1591]
When using retrofit, a user may want to get class and method name in metrics. 
(I guess RpcRequest/Response already shows class/method name but HttpRequest/Response doesn't )

**Comment by kojilin** [comment]
Retrofit put `Invocation.class` tag in `okhttp3.Request`, so we can call `request.tag(Invocation.class);` at `ArmeriaCallFactory#doCall`. 
https://github.com/square/retrofit/blob/a8e37897b3326e7748622a5867e775003bb6e15e/samples/src/main/java/com/example/retrofit/InvocationMetrics.java#L55

But currently we can't pass any extra information to HttpClient for setting attribute to RequestContext/RequestLog to reuse `MetricCollectingClient`.
