### ISSUE TITLE
Documentation bug for accessLogWriter

### ISSUE THREAD

**Issue by tobias-** [line/armeria#1595]
Very minor.

https://line.github.io/armeria/server-access-log.html 
```
sb.accessLogWriter(AccessLogWriters.common());
```
and
```
sb.accessLogWriter(AccessLogWriters.combined());
```
doesn't exist anymore. It requires a shutdown flag and also `AccessLogWriters` (with an s) is deprecated in favour of `AccessLogWriter`. true seems to be default for that flag.

**Comment by tmdgus0118** [comment]
Thanks for the issue!
I need to add a new component in the document for this [PR](https://github.com/line/armeria/issues/1574).
Let me fix it together.

**Comment by trustin** [comment]
Being handled by @tmdgus0118 at #1574
