### ISSUE TITLE
JMX integration plan?

### ISSUE THREAD

**Issue by freesoft** [line/armeria#16]
I saw armeria LINE_DevDay2015 PDF mentioning the necessary of JMX integration for the library. Do you guys have any follow up on this? Wondering if you guys want to build JMX stuff into library from the scratch or want to use existing JMX libraries like Netflix Servo or Dropwizard Metrics?

**Comment by blmarket** [comment]
I'm trying to integrate armeria with Dropwizard Metrics, I'll post update here.

**Comment by trustin** [comment]
@blmarket Thanks, Heon! :-)

**Comment by freesoft** [comment]
I think you guys already talked each other in person, but what metrics is going to be necessary here? success fail # or ratio per given time window? # of timeout?

**Comment by blmarket** [comment]
Current target is success/failure count as well as response time histogram. (xx% percentile) please leave a note if need more.

**Comment by trustin** [comment]
You might want to take a look into what Finagle has done.

https://twitter.github.io/finagle/guide/Metrics.html

**Comment by trustin** [comment]
Seems like we have a pretty solid metric collecting decorator implementation now. What would be the next step? What are in my mind are:

- Export JVM and O/S stats via Dropwizard Metrics.
  - Use existing exporter implementation if someone implemented it already.
- Integrate all metrics into `DocService`.
- Export Dropwizard Metrics registry via JMX.

**Comment by trustin** [comment]
This has been basically resolved since we added metric support using Micrometer, which provides JMX registry: https://javadoc.io/doc/io.micrometer/micrometer-registry-jmx/1.0.0-rc.7
