### ISSUE TITLE
Can't run single test of Parameterized test when delegating builds to Gradle in IntelliJ

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1601]
I'm not sure if this is a bug in Gradle or IntelliJ or something in the armeria configuration, but when I set IntelliJ to delegate tests to Gradle with Settings > Build, Execution, Deployment > Build Tools > Gradle > Runner, I can't run a single test out of a parameterized one.

For example, if I run `HttpServerStreamingTest.testTooLargeContentToNonExistentService` by pressing the green button next to the method, I get

```
Execution failed for task ':core:test'.
> No tests found for given includes: [**/HttpServerStreamingTest**](exclude rules) [com.linecorp.armeria.server.HttpServerStreamingTest.testTooLargeContentToNonExistentService](filter.includeTestsMatching)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
```

**Comment by anuraaga** [comment]
It's fine to workaround by using IntelliJ runner for tests (a bit annoying since for some reason Gradle runner is a global setting, not project-level one...) but I thought this might become more important after reading that IntelliJ 2019.1 will default to using the Gradle runner

https://github.com/tbroyer/gradle-apt-plugin/commit/b96813adfaa59731ead938f8bd20b64314f0c661

**Comment by trustin** [comment]
I wonder if this is an IntelliJ IDEA issue. Didn't try the Gradle runner for quite a while because IntelliJ runner starts much faster..
