### ISSUE TITLE
Provide a way to configure content previewing to the specific service

### ISSUE THREAD

**Issue by minwoox** [line/armeria#1619]
Currently, a user can configure content previewing to the whole server using `ServerBuilder`. A user might want to enable content previewing to only the HTTP services when he or she has Thrift and HTTP services together.

**Comment by hyeonjames** [comment]
Let me solve this issue !

**Comment by trustin** [comment]
I think we will need to add a way to configure a service fluently, which is never implemented yet, like..

```java
ServerBuilder sb = new ServerBuilder();
sb.route().get("/greet/{name}")
          .contentPreview(..)
          .verboseResponses(true)
          .defaultResponseTimeout(...)
          .service(myService) // Terminates service construction
  .route()...
```

Just an idea that needs a lot more polishing though :-)

**Comment by hyeonjames** [comment]
> I think we will need to add a way to configure a service fluently, which is never implemented yet, like..
> 
> ```java
> ServerBuilder sb = new ServerBuilder();
> sb.route().get("/greet/{name}")
>           .contentPreview(..)
>           .verboseResponses(true)
>           .defaultResponseTimeout(...)
>           .service(myService) // Terminates service construction
>   .route()...
> ```
> 
> Just an idea that needs a lot more polishing though :-)

that sounds a great idea. How about making a new issue and resolving them separately?

**Comment by trustin** [comment]
Sure. This issue will be dependent on the new issue, then, right?

**Comment by trustin** [comment]
Created #1649.
