### ISSUE TITLE
Replace quotes from OSX notes app with quotation mark

### ISSUE THREAD

**Issue by JunoJunho** [line/armeria#1622]
When I used armeria doc service, it supports to utilize REST API.
It only understands quotation mark " (U+0022) as string quotation. However, MAC OS X has different quotations like left double quotation “ (U+201C) if I make the example in notes app.

So, If there is no constraint rule, it is very helpful to support that armeria can automatically replace those quotation marks as ascii quotation mark.

**Comment by trustin** [comment]
That's an interesting idea. What about this:

1. Before sending the request, make sure the body is a valid JSON.
2. If valid, send it.
3. If not valid and the body contains the characters you mentioned, replace them and check if the body is a valid JSON.
4. If valid, send it.
5. If not valid, send the original body, as it would have been sent in the step 2.

..?

**Comment by trustin** [comment]
By the way, are you sure you wanna use OS X Notes app for keeping JSONs? I guess there are more developer-friendly note-taking apps in the market, such as:

- https://brettterpstra.com/projects/nvalt/
- https://boostnote.io/
- https://caret.io/

**Comment by JunoJunho** [comment]
The sequence seems rigorous.
I know that armeria already provides JSON validity check in Step 1, am I right?
If then, replacement job may be needed. Also, one thing that I have a question is that if the JSON is not valid, does aremeria need to send invalid JSON payload? I think more suitable way is that if the payload is invalid, print error message and do nothing.

**Comment by JunoJunho** [comment]
I gets used to utilizing OS X notes app, but I will try them. Thanks for recommendation 👍

**Comment by trustin** [comment]
> If the payload is invalid, print error message and do nothing.

That sounds OK to me.

**Comment by JunoJunho** [comment]
This issue can be closed.

**Comment by trustin** [comment]
May I know why you closed this issue?

**Comment by JunoJunho** [comment]
Since #1708 in this PR, header parse is fixed, I think this problem does not occur.
