### ISSUE TITLE
Log the client IP address behind reverse-proxies

### ISSUE THREAD

**Issue by tobias-** [line/armeria#1631]
This issue is really two parts.

The first part is discovering the ip address of the client. The current Armeria solution is based on searching through different sources for the first acceptable address that passes the filters. 

Problems:
1. I don't know the proxy's address given how GKE assigns the address I can't just filter it out. It's not a private address either.
2.  It may be susceptible to the following trick: `curl https://host/ -H 'x-forwarded-for: 8.8.8.8'` (untested). (basically forging the origin of the server)

Most logs seems to log the contents of the `x-forwarded-for` header verbatim to get around that. (which may be the correct solution tbh).

One solution that does the trick:
```kotlin
    // Takes the nth proxy/server from the end to find the real client ip
    fun RequestLog.remoteHost(proxyIndex: Int): String {
        val header = requestHeaders()[X_FORWARDED_FOR_HEADER] ?: ""
        val remoteSocketIp = (context().remoteAddress<SocketAddress>() as? InetSocketAddress)?.address?.toString() ?: "local?"
        val hosts = (header.splitToSequence(", ") + remoteSocketIp).toList()
        return if (hosts.size > proxyIndex) {
            hosts[hosts.size - 1 - proxyIndex]
        } else {
            // fallback to remote host, just to have some value
            hosts.last()
        }
    }
```
---

The second problem is how to get that ip into the access log. Most of the stuff in the log interfaces are package private so it's not just a matter of dropping in a function that provides that field into the log formats. I would've liked to just use the `AccessLogFormats.COMBINED`, make a copy of the list where I replaced the first entry, and then just create a method same as the `AccessLogWriter.combined()`, possibly via a 
```java
    static AccessLogWriter custom(List<AccessLogComponent> accessLogComponents) {
        ImmutableList<AccessLogComponent> logComponents = ImmutableList.toImmutableList(accessLogComponents);
        return requestLog -> AccessLogger.write(logComponents, requestLog);
    }
```

**Comment by tobias-** [comment]
This is the discussion that led up to the issue:
https://line-armeria.slack.com/conversation/C1NGPBUH2/p1551785804013500

**Comment by trustin** [comment]
@ikhoon will work on this.
