### ISSUE TITLE
gRPC server connection option: MAX_CONNECTION_AGE

### ISSUE THREAD

**Issue by sdual** [line/armeria#1636]
grpc-java provides an option `MAX_CONNECTION_AGE` to allow gRPC server to manage a duration of TCP connection. When a connection exceeds the `MAX_CONNECTION_AGE`, the server sends GOAWAY and terminates it.

```java
Server server = NettyServerBuilder.forPort(port)
     .maxConnectionAge(MAX_CONNECTION_AGE, TimeUnit.MILLISECONDS)
     .addService(...)
     .build();
```

https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md

Could armeria-grpc supoort this option?

**Comment by trustin** [comment]
Sounds like a good idea. I believe we could add more options related with server-side connection life cycle for all requests, not just gRPC.

FYI, there is currently only one knob for connection life cycle: `idleTimeout` which closes the connection if there is no request in progress for a certain amount of time.

**Comment by raidancampbell** [comment]
Adding my 2 cents here:  We're running code in a restricted environment that kills long-lived TCP connections after a while to prevent resource leakage.  The result is that the clients will try to use a TCP connection that was killed by some layer 4 infrastructure, and will fail.

Without this configuration, the client needs to implement retry logic: if this configuration were exposed, we could instead make a single server-side change to fix this.

**Comment by ikhoon** [comment]
I didn’t know we have this issue. 
I believe we have already been added this feature to Armeria since 0.99.7. #2747
https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.8.0/com/linecorp/armeria/server/ServerBuilder.html#maxConnectionAge(java.time.Duration)

**Comment by raidancampbell** [comment]
Ah, I was looking in the wrong section of the docs.  I'll have to give it a try and see if it helps

**Comment by ikhoon** [comment]
Feel free to comment on this issue if it is not working as expected. 😀
