### ISSUE TITLE
HttpFile and HttpFileService have different semantics for parsing resource URL

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1650]
I found that `HttpFile` does not work if a resource starts with `/` but `HttpFileService` strips it off

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpVfs.java#L39

I think the two should have same semantics to prevent confusion (I was expecting the same constant with a filename appended I was using with `HttpFileService` to work with `HttpFile` but it was ending up as not-found).

**Comment by anuraaga** [comment]
Also less important but it'd be nice if `HttpFile` could do serveCompressedFiles too for consistency

**Comment by trustin** [comment]
The issue with a leading slash is a bug indeed.
+1 for adding serveCompressedFiles.
