### ISSUE TITLE
Make StartStopSupport.start()/stop() accept an argument

### ISSUE THREAD

**Issue by hyangtack** [line/armeria#1673]
In some cases, we cannot set every objects required for start/stop when initiating a `StartStopSupport` instance. So it would be useful if we can pass an argument into `doStart()`/`doStop()` when calling its `start()`/`stop()` method. IMHO, we can add one more generic parameter to `StartStopSupport` for the argument.

**Comment by trustin** [comment]
Fixed in #1675
