### ISSUE TITLE
Is bytebuddy needed at runtime for grpc?

### ISSUE THREAD

**Issue by adriancole** [line/armeria#1679]
byte-buddy is cool, but it is a >3MiB jar and is also frequently updated. Is this dep needed for armeria-grpc to operate?

```
[INFO] |  |  \- org.curioswitch.curiostack:protobuf-jackson:jar:0.3.1:compile
[INFO] |  |     \- net.bytebuddy:byte-buddy:jar:1.9.7:runtime
```

**Comment by anuraaga** [comment]
Nope, it's only if json gRPC is enabled (there was a bug before where it was always initialized even without enabling but should be fixed now).

**Comment by adriancole** [comment]
thanks!
