### ISSUE TITLE
Consider adopting NullAway into the build process

### ISSUE THREAD

**Issue by trustin** [line/armeria#1680]
See: https://github.com/uber/NullAway

**Comment by anuraaga** [comment]
Ah yeah now I remember this issue. Seems `NullAway` is a faster but potentially less precise checker good enough for almost all cases. But can't find any good resource listing out what cases it misses vs checker framework. Do you have any idea?

**Comment by trustin** [comment]
No. :smile: I didn't take a close look at all. IIRC JetBrains had some contract annotations, too. Not sure which is the best :thinking:

**Comment by ikhoon** [comment]
I tried to test and compare NullAway and the Checker Framework.

- The Checker Framework - It does not support Java 13 yet.
```
> org.checkerframework.javacutil.UserError: 
The Checker Framework cannot be run with JDK 13+.  You are using version 13. Please use JDK 8 or JDK 11.
```
So I don't think I need to go any further now.

- NullAway

It produces some useful error messages. But it could not cover all of our null checking code. 
For example, it does not recognize null checking in `checkArgument()`.

```java
checkArgument(foo != null, "foo is null");
foo.bar() // : error: [NullAway] dereferenced expression foo is @Nullable
```
https://github.com/uber/NullAway/issues/47

I am not sure that we can put NullAway into the build process.
Anyway, I am going to make a PR to fix true positive errors detected by NullAway. 😀

**Comment by anuraaga** [comment]
@ikhoon Since checker framework also can't be run together with error prone from what I understand, we'd have two builds anyways, and I guess with some configuration tweaks that could be set to Java 11. Probably not worth the trouble though, but I'm curious whether checker framework would catch `checkArgument`. Do you have a branch I can play with (or you can try playing with Java 11? :D)

**Comment by ikhoon** [comment]
> Since checker framework also can't be run together with error prone from what I understand,

It looks resolved in Error Prone 2.4.0
https://github.com/kelloggm/checkerframework-gradle-plugin#incompatibility-with-error-prone

> Do you have a branch I can play with (or you can try playing with Java 11? :D)

Yeah, let up push the branch tested in locally,

**Comment by ikhoon** [comment]
@anuraaga This is https://github.com/ikhoon/armeria/tree/nullness 😀

**Comment by trustin** [comment]
#5830 needs to be merged to close this.
