### ISSUE TITLE
Scroll down to the debug form when a DocService URL contains a request.

### ISSUE THREAD

**Issue by trustin** [line/armeria#1682]
When I share my DocService URL which contains an encoded request body (e.g. http://127.0.0.1:8080/docs/#/methods/com.example.FooService/methodBar/POST?request_body=%7B%7D), I expect a user who opens the URL will see the debug form without scrolling down to it. Currently, a user has to manually scroll down the method page to see the debug form.

**Comment by SooJungDev** [comment]
I'll work on it
