### ISSUE TITLE
Export the metrics about `blockingTaskExecutor`.

### ISSUE THREAD

**Issue by trustin** [line/armeria#1683]
We could expose the metrics about `ServerConfig.blockingTaskExecutor()` stats to Micrometer. Could use: https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java

**Comment by jrhee17** [comment]
working on this:)

**Comment by kojilin** [comment]
just add code like below in ServerConfig constructor?
```
ExecutorServiceMetrics.monitor(this.meterRegistry, this.blockingTaskExecutor,
                                       "armeriaBlockingTaskExecutor");
```

**Comment by trustin** [comment]
Yeah. Something like that. Maybe we need to check if the executor is already monitored as well?

**Comment by imasahiro** [comment]
Can I handle this issue?

**Comment by trustin** [comment]
Sure. It's all yours unless someone else is working on it already.

**Comment by slovdahl** [comment]
> Yeah. Something like that. Maybe we need to check if the executor is already monitored as well?

Was anything related to this ever fixed?

**Comment by slovdahl** [comment]
Answering my own question: yes, it was fixed in `ServerConfig` using this construct:
```java
if (!(blockingTaskExecutor instanceof TimedExecutorService)) {
    blockingTaskExecutor = ExecutorServiceMetrics.monitor(meterRegistry, blockingTaskExecutor,
                                                          "armeriaBlockingTaskExecutor");
}
```
