### ISSUE TITLE
Use Java 9's stack-walking API to reduce the overhead of getting full stack trace in Thrift TEXT serialization format.

### ISSUE THREAD

**Issue by trustin** [line/armeria#1686]
In `StructContext`, we need to acquire the class name from the stack trace using `Thread.current().getStackTrace()`:

- https://github.com/line/armeria/blob/armeria-0.82.0/thrift/src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java#L104-L164

However, `getStackTrace()` is a high-overhead operation since it has to walk the call stack up to its root. We could leverage Java 9's stack-walking API so we can stop climbing the call stack when we found what we want.

See https://dzone.com/articles/whos-calling-me-an-overview-of-stack-walking-api-i for more information about Java 9 stack walking API.

Note that we still need to fall back to the old implementation if running on Java 8, so you might need to add some abstraction layer which allows switch between two different stack-walking implementations.

**Comment by anuraaga** [comment]
This reminds me of the `SystemInfo` change we made recently - if we add more features targeting newer Java versions, it's probably important to tweak the build so we can do it with class loading instead of reflection which can be tedious or slower.

**Comment by ByeongweonMoon** [comment]
I will handle this.

**Comment by moonchanyong** [comment]
I will take this issue.
