### ISSUE TITLE
Support for setting preservingProtoFieldNames in GrpcService when both protobuf and json wire formats are used with the GRPC service

### ISSUE THREAD

**Issue by karthikraman22** [line/armeria#1696]
Currently the GrpcService initialisation via the builder doesn't allow the option of preserving Proto field names in the output. If we enable the default constructor of the GrpcService to allow the option of setting preservingProtoFieldNames then the same can be passed onto GrpcJsonUtil. This would be helpful if we don't need to modify every Proto file to include json_name option.

**Comment by trustin** [comment]
I guess this might require an update in [protobuf-jackson](https://github.com/curioswitch/curiostack/tree/master/common/grpc/protobuf-jackson)?

**Comment by karthikraman22** [comment]
Not really. The MessageMarshaller from protobuf-jackson already has support for "preservingProtoFieldNames". Its the GrpcJsonUtil.jsonMarshaller implementation that needs to be updated to pass the attribute as below

    public static MessageMarshaller jsonMarshaller(List<MethodDescriptor<?, ?>> methods) {
        final MessageMarshaller.Builder builder = MessageMarshaller.builder()
                .omittingInsignificantWhitespace(true)
                .ignoringUnknownFields(true)
                .preservingProtoFieldNames(true);

**Comment by anuraaga** [comment]
Yup think we just need to add and propagate an option for it - thanks a lot for investigating it!

Leaning towards adding a generic `Consumer<MessageMarshaller.Builder> jsonSerializerCustomizer` option. @trustin seems ok?

**Comment by trustin** [comment]
@anuraaga Yes. Sounds like a good idea. I'm curious if it is a good default to turn this on.

**Comment by karthikraman22** [comment]
I would welcome that as a default option.

**Comment by anuraaga** [comment]
Sorry for the long delay, I'm going to start working on this and should have a change ready by tomorrow.

I'm not going to change the default since while there isn't anything in the gRPC spec related to JSON encoding, the protobuf spec states the default is lower camel case
https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by trustin** [comment]
Fix has been merged. :-)

**Comment by karthikraman22** [comment]
Thank you Armeria team.

**Comment by trustin** [comment]
Our pleasure. Please let us know if the fix works or not once the next release is out (hopefully tomorrow). Do you have any other things in your mind? It'd be nice if we can improve further. :wink:
