### ISSUE TITLE
Consider separate messages for AggregatedHttpMessage request / response

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1702]
When using an `AggregatedHttpMessage` that is a response, `status` is always set. It's a bit tedious that `status` is `@Nullable` because in the request case, it wouldn't be populated, but in the response case it always is, meaning having to always do a no-op null check to satisfy nullness checks.

**Comment by trustin** [comment]
I like the idea. Interested in sending a pull request? It'd be basically to create `AggregatedHttpRequest/Response` that extends `AggregatedHttpMessage`.
