### ISSUE TITLE
How should I handle UnprocessedRequestException in RetryStrategy?

### ISSUE THREAD

**Issue by sh1n1chi8acker** [line/armeria#1710]
I am writing custom RetryStrategy seeing https://line.github.io/armeria/client-retry.html.
And I have a question about handling UnprocessedRequestException.
I would like to retry when UnprocessedRequestException is raised.

```
class MyRetryStrategy implements RetryStrategy {
    ...
    @Override
    public CompletionStage<Backoff> shouldRetry(ClientRequestContext ctx, @Nullable Throwable cause) {
        if (cause != null) {
            if (cause instanceof ResponseTimeoutException ||
                cause instanceof UnprocessedRequestException) {
                return CompletableFuture.completedFuture(backoff);
            }
        }
        ...
    }
} 
```
Then should I peel a cause like this?
```
 if (cause instanceof ResponseTimeoutException ||
     cause instanceof UnprocessedRequestException ||
     Exceptions.peel(cause) instanceof UnprocessedRequestException) { // <-- required ?
```
I found code snippet about handling UnprocessedRequestException at
https://github.com/line/armeria/blob/6df5616dcbeb3314163e683bd18706af369bab0b/core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java#L72

Thanks

**Comment by trustin** [comment]
As far as I know, you do not need to peel `cause`. However, you may want to peel the exceptions like `CompletionException`, `ExecutionException` and `InvocationTargetException` when handling other exceptions that may be raised in the middle of a `CompletionStage` chain. Therefore, I'd recommend you to peel in the first place:

```java
@Override
public CompletionStage<Backoff> shouldRetry(ClientRequestContext ctx, @Nullable Throwable cause) {
    if (cause != null) {
        cause = Exceptions.peel(cause);
        if (cause instanceof ResponseTimeoutException ||
            cause instanceof UnprocessedRequestException) {
            return CompletableFuture.completedFuture(backoff);
        }
    }
    ...
```

Please let us know if you encounter the case where an `UnprocessedRequestException` is wrapped by other exception, so we can investigate.

**Comment by sh1n1chi8acker** [comment]
@trustin 
Thank you for giving me good advice. I will try that.

It would be helpful to peel `cause` before calling `shouldRetry(ClientRequestContext ctx, @Nullable Throwable cause)`.

**Comment by trustin** [comment]
Good to hear that it was helpful. 😄
However, I think Armeria should not peel the cause because some users still might find the existence of wrapper exceptions useful to determine how the exception occurred. For example, `InvocationTargetException` would indicate the exception occurred during a reflective operation.

**Comment by trustin** [comment]
I added a small tip about `Exceptions.peel()`: https://github.com/line/armeria/pull/1712#issuecomment-482524101
