### ISSUE TITLE
Using 'builder()' factory method instead of constructor

### ISSUE THREAD

**Issue by trustin** [line/armeria#1719]
Currently, we instantiate a builder by calling a constructor or a static method in a builder class:

```java
Server server = new ServerBuilder()
        .foo()
        .bar()
        .build();
```

I wonder if it was a good idea or we need to reconsider this decision in favor of having `builder()` method:

```java
Server server = Server.builder()
                      .foo()
                      .bar()
                      .build();
```

The pros of `builder()` are:

- We can easily align at `'.'`, which is better in terms of aesthetics.
- We do not need to import `ServerBuilder` if we chain all.

**Comment by eonezhang** [comment]
I like the `Server.builder()` way

**Comment by trustin** [comment]
Let me make the proposed change.

**Comment by trustin** [comment]
`builder()` or `newBuilder()`? Protobuf uses `newBuilder()` and Guava uses `builder()`. Which one is better?

**Comment by anuraaga** [comment]
+1.001 for `builder` vs +1 for `newBuilder` :)

**Comment by trustin** [comment]
Just came back from Spain and it reads like 1001 vs 1 :rofl:

**Comment by 4whomtbts** [comment]
I'm working on this

**Comment by trustin** [comment]
The remaining builder classes that need migration:

- `ClientBuilder`
- `DefaultClientBuilderParams` 
- `ServerListenerBuilder`
- `HttpAuthServiceBuilder`
- `SimpleCompositeServiceBuilder`
- `SimpleCompositeRpcServiceBuilder`
- `CorsPolicyBuilder`
- `CorsServiceBuilder`
- `DocServiceBuilder`
- `HttpFileBuilder`
- `HttpFileServiceBuilder`
- `LoggingServiceBuilder`
- `JettyServiceBuilder`
- `ArmeriaRetrofitBuilder`
- `KeyStoreCredentialResolverBuilder`
- `SamlServiceProviderBuilder`
- `TomcatServiceBuilder`
- `ZooKeeperUpdatingListenerBuilder`

**Comment by 4whomtbts** [comment]
It has been on progress since this monday. Apologize for for slow progress (__)

**Comment by ikhoon** [comment]
@4whomtbts It's good to be back! I think you need to know some changes in #2335. 
1) Please make sure your current branch is up to date from the master branch. Lots of class which have `HTTP` keyword have been deprecated.
2) `HttpAuthServiceBuilder` and `HttpFileServiceBuilder` have been done, you may want to skip them.
3) This issue is scheduled to apply before [release 1.0.0](https://github.com/line/armeria/milestone/151). Maybe in the middle of January. 😉

I'm looking forward to your next PR. Cheer up! 
---

- `ClientBuilder`
- `DefaultClientBuilderParams` 
- `ServerListenerBuilder`
- ~`HttpAuthServiceBuilder`~
- `SimpleCompositeServiceBuilder`
- `SimpleCompositeRpcServiceBuilder`
- `CorsPolicyBuilder`
- `CorsServiceBuilder`
- `DocServiceBuilder`
- `HttpFileBuilder`
- ~`HttpFileServiceBuilder`~
- `LoggingServiceBuilder`
- `JettyServiceBuilder`
- `ArmeriaRetrofitBuilder`
- `KeyStoreCredentialResolverBuilder`
- `SamlServiceProviderBuilder`
- `TomcatServiceBuilder`
- `ZooKeeperUpdatingListenerBuilder`

**Comment by 4whomtbts** [comment]
> @4whomtbts It's good to be back! I think you need to know some changes in #2323.
> 
> 1. Please make sure your current branch is up-to-date from the master branch. Lots of class which have `HTTP` keyword have been deprecated.
> 2. `HttpAuthServiceBuilder` and `HttpFileServiceBuilder` have been done, you may want to skip them.
> 3. This issue is scheduled to apply before [release 1.0.0](https://github.com/line/armeria/milestone/151). Maybe in the middle of January. 😉
> 
> I'm looking forward to your next PR. Cheer up!
> 
> * `ClientBuilder`
> * `DefaultClientBuilderParams`
> * `ServerListenerBuilder`
> * ~`HttpAuthServiceBuilder`~
> * `SimpleCompositeServiceBuilder`
> * `SimpleCompositeRpcServiceBuilder`
> * `CorsPolicyBuilder`
> * `CorsServiceBuilder`
> * `DocServiceBuilder`
> * `HttpFileBuilder`
> * ~`HttpFileServiceBuilder`~
> * `LoggingServiceBuilder`
> * `JettyServiceBuilder`
> * `ArmeriaRetrofitBuilder`
> * `KeyStoreCredentialResolverBuilder`
> * `SamlServiceProviderBuilder`
> * `TomcatServiceBuilder`
> * `ZooKeeperUpdatingListenerBuilder`

Yes. My local branch is currently up-to-date.  
Thank you for fill me in!

**Comment by trustin** [comment]
Once #2352 is merged, these are probably the last:

- ClientBuilder
- DefaultClientBuilderParams
- new SimpleCompositeService(...)
- new SimpleCompositeRpcService(...)
- new DocService()
- new ArmeriaRetrofitBuilder(...)
- KeyStoreCredentialResolverBuilder

They are somewhat trickier than others, so let me handle them by myself.

**Comment by trustin** [comment]
Need to replace contants with factory methods as well:

- `EventCount.ZERO`
- `ClientCacheControl.*`
- `ServerCacheControl.*`
- `PrometheusMeterRegistries.defaultRegistry`
- `AuthTokenExtractors.*`
- `CorsConfig.DISABLED`

**Comment by 4whomtbts** [comment]
> Once #2352 is merged, these are probably the last:
> 
> * ClientBuilder
> * DefaultClientBuilderParams
> * new SimpleCompositeService(...)
> * new SimpleCompositeRpcService(...)
> * new DocService()
> * new ArmeriaRetrofitBuilder(...)
> * KeyStoreCredentialResolverBuilder
> 
> They are somewhat trickier than others, so let me handle them by myself.

Ok.  I got it.
