### ISSUE TITLE
tracing: http.url tag is curious

### ISSUE THREAD

**Issue by adriancole** [line/armeria#1733]
"http.url" is elsewhere a valid addressable URL. We issue a pattern that is probably surprising to some people. Ex. from zipkin self-tracing `"http.url":"none+h1c://localhost:9411/api/v2/traces"` I would have expected `http://localhost:9411/api/v2/traces`

Is this too hip? or should we clarify in zipkin that "http.url" must be in URL syntax, but might not be addressable?

**Comment by trustin** [comment]
That's a good point. Which tag should we use then to specify the detailed scheme?

**Comment by adriancole** [comment]
On Mon, Apr 22, 2019 at 10:04 AM Trustin Lee <notifications@github.com>
wrote:

> That's a good point. Which tag should we use then to specify the detailed
> scheme?
>
>
We don't have a precedent for this. our http tags are http.lower_snake_case

**Comment by trustin** [comment]
If you have a suggestion for a good name, then I'd like to use it.

**Comment by adriancole** [comment]
sorry, but what do you call "none+h1c" is there any RFC or other library that uses the same pattern?

**Comment by trustin** [comment]
It came from Arch Linux: https://wiki.archlinux.org/index.php/VCS_package_guidelines#VCS_sources

How about this:

- Use http or https in http.url
- Add http.scheme which is one of: h1, h1c, h2, or h2c
- Add http.serfmt stands for serialization format such as tbinary

**Comment by adriancole** [comment]
I guess this is closest to protocol. ex `Upgrade: h2c`

note that we likely will change to the normal HttpTracing in the other
github issue, which wouldn't set this tag (and need to index it for
every request) by default.

However, a helper that adds this could be made easy enough even if
only for armeria.

**Comment by trustin** [comment]
protocol sounds good to me. What could be the full tag name?

- `http.protocol`
- `net.protocol`
- `protocol`

**Comment by adriancole** [comment]
I'd guess http.protocol as we have rarely things top-level

**Comment by trustin** [comment]
Sorry that I'm late. Let me try to take care of this one tomorrow before cutting a new release.

**Comment by trustin** [comment]
Fixed via #1762
