### ISSUE TITLE
Allow specifying `SslContext` customizer with `ServerBuilder.tlsSelfSigned()`.

### ISSUE THREAD

**Issue by trustin** [line/armeria#1738]
We forgot to allow specifying a TLS customizer with `ServerBuilder.tlsSelfSigned()` in #1717 :sweat_smile: Probably better working on this after #1737 is merged, though.

**Comment by sivaalli** [comment]
Hi @trustin , this is to add a new method like `ServerBuilder.tlsSelfSigned(Consumer<? super SslContextBuilder> tlsCustomizer)` right? So that users do not have to do this:

```
ServerBuilder sb = ....
sb. tlsSelfSigned().tlsCustomizer().build()
```

**Comment by trustin** [comment]
Actually, we do not need to resolve this issue anymore thanks to the new `tlsCustomizer()` method. Forgot to close this. :sweat_smile:
