### ISSUE TITLE
Provide a way to get `ClientRequestContext` without using a decorator.

### ISSUE THREAD

**Issue by trustin** [line/armeria#1739]
Currently, a user has to insert a decorator to access the `ClientRqeustContext` or its `RequestLog`. For example:

```java
HttpClient client = new HttpClientBuilder(...)
    .decorator((delegate, ctx, req) -> {
        // Access ctx and ctx.log()
    })
    .build();
```

It would be pretty convenient if a user can do this:

```java
HttpClient client = HttpClient.of(...);
HttpResponse res = client.get("/");
ClientRequestContext ctx = ClientRequestContext.get(res);
```

**Comment by geminiKim** [comment]
Hi :)
I was wondering about this issue while looking into Armeria.
I think it is simple to solve this task if the HttpResponse has a RequestContext.

like:
```
// ClientRequestContext.java

    static ClientRequestContext get(HttpResponse res) {
        if(res instanceof DecodedHttpResponse) { 
            return ((DecodedHttpResponse) res).getRequestContext();
        } else {
            return null; // But there is not perfect.
        }
    }


// DecodedHttpResponse.java

    private final ClientRequestContext requestContext;

    public DecodedHttpResponse(EventLoop eventLoop, ClientRequestContext requestContext) {
        this.eventLoop = eventLoop;
        this.requestContext = requestContext;
    }

    public ClientRequestContext getRequestContext() {
        return requestContext;
    }
```

I wonder about your opinion on the right way.

**Comment by minwoox** [comment]
Hello @geminiKim, thanks for the good suggestion.!
But, the returned `HttpResponse` couldn't be `DecodedHttpResponse`.
It can be `DeferredHttpResponse`, `FilteredHttpResponse`, `DuplicatedHttpResponse` or `HttpDecodedResponse` depending on the decorators that a user specified.
I think we have to consider all of these situations because otherwise, the user would get the `ctx` only in certain circumstance. :-)
By the way, are you using Armeria? 😄

**Comment by geminiKim** [comment]
@minwoox  I understand and agreed, Thank you for good feedback, It is really help for me :D
I’m not yet using Armeria (in production), just started to studying to learn good code and the contribution :)

I think I'll ask you a lot of questions. Thank you in opinion. :D

**Comment by minwoox** [comment]
Got it. I hope you will be able to use Armeria in production one day. :-)
For this issue, I think we can wrap the `HttpResponse` with the class which has the original `HttpResponse` and `ClientRequestContext` in `DefaultHttpClient`.
```
public final class HttpResponseWithClientRequestContext implements HttpResponse {
	private final ClientRequestContext ctx;
	private final HttpResponse delegate;

	...

	public CompletableFuture<AggregatedHttpResponse> aggregate() {
		return delegate.aggregate();
	}

	...
}
```
Not sure, if it's a good idea though. 😅 Have to ask to @trustin first. 😄

**Comment by minwoox** [comment]
Had a chat with @trustin and we have to consider `RpcResponse` as well.
Also, there's a chance that the client is wrapped by another layer, so I think this is a very difficult issue to solve. 😢 We need to think about it a little bit more. 😅

**Comment by geminiKim** [comment]
@minwoox Thank you for shared specific feedback. 😄👍

**Comment by minwoox** [comment]
Because any implementations of an `HttpResponse` can be returned using a decorator, I think there are two ways to solve this:
- Let the `HttpResponse` have the `ClientRequestContext` if it's in the thread-local when the response is created
- Wrap the returned `HttpResponse` somewhere (perhaps in `UserClient`?) if it does not have the `ClientRequestContext`
  ```java
  // Do not have to wrap this.
  class DecodedHttpResponse extends ... implements RequestContextHolder {...}
  // Other cases.
  class HttpResponseWithClientRequestContext implements HttpResponse, RequestContextHolder {...}

  // And getter

  public interface ClientRequestContext {
      @Nullable
      ClientRequestContext get(HttpResponse res) {
          if (res instance of RequestContextHolder) {...}
          ...
      }
  }
  ``` 

What do you think?
