### ISSUE TITLE
armeria 's postion in  a web application 

### ISSUE THREAD

**Issue by zhanlandetian** [line/armeria#176]
is there a way to place a http proxy stand before armeria server to speak json protocol for remote client ? or am i  use choose the wrong tools here ? dose armeria supposed to fit for a intranet micro service ? for internet users how do we use armeria properly?

**Comment by trustin** [comment]
If I understood your question correctly, Armeria can be placed anywhere. It can serve its requests behind reverse proxies. It could also face the internet traffic without reverse proxies if you wish. I may be able to give you a better answer if you could describe your configuration more clearly, though.

**Comment by zhanlandetian** [comment]
thanks for your reply, trustin.

we want to upgrade our inner services to asynchronously ,these services are currently using jetty as web server to serve our mainline restful web services with json protocol synchronously . Mainline restful services are serving our remote app client (like ios,android apps). Inner services are play an utility role for the mainline service.

i found armeria fit well as our inner service server(so dose finagle stacks ,but lots of us can't speak scala language), so that the mainline service could use armeria client to invoke the inner service server asynchronously.

the question is that , is that possible to replace our mainline restful service with armeria despite of its thrift protocol centrically  ?  the mainline service used to ouput json content to the remote apps, how can adjust this to let armeria output jsons  content asynchronously ?

**Comment by trustin** [comment]
I see. As you see in [HttpService](https://github.com/line/armeria/blob/armeria-0.19.0.Final/src/main/java/com/linecorp/armeria/server/http/HttpService.java) and its subtypes, you can write a pure HTTP service. It means you can write an arbitrary HTTP service with it.

However, it has some shortcomings:

- It's not as convenient as other REST frameworks such as Finatra, Spark and Spring MVC.
- It currently does not support large content streaming, although I'm working on it right now.

**Comment by wangjunfei** [comment]
hi trustin,
 in my opinion, armeria should used as inner service framework behind the enterprise firewall,  it can be asynchronous or not .  but commonly how to combine this type of inner service with the mainline services (service usually face the internet traffic ) ?  and armeria speaks thrift protocol ,usually mainline service  speaks http protocol ,how do they communicate with each other ?

**Comment by trustin** [comment]
It really depends on your technical decision on your architecture, so I'm not sure I can give you one single definitive answer for your question. One thing I can think of is using Armeria as an L7 switch server, similar to Linkerd.
