### ISSUE TITLE
Question: what is functionality to execute every hour, minute?

### ISSUE THREAD

**Issue by JunoJunho** [line/armeria#1763]
Hi, I want to execute some tasks in every hour or minute (periodically) with different parameters.

In the Spring, Task and TaskExecutor is what I want to use, but I don't know which function is such like this.

**Comment by minwoox** [comment]
You can use `ScheduledExecutorService` to schedule a job:
```java
final ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
executor.scheduleAtFixedRate(() -> {
    System.err.println("This is executed every 1 minute.");
}, 0, 1, TimeUnit.MINUTES);
```

If your job is not a blocking task and is triggered by an event in your service, you could use `EventLoop` which extends `ScheduledExecutorService`:
```java
// ServiceRequestContext ctx = ...;
ctx.eventLoop().schedule(() -> {
    System.err.println("This is executed after 1 hour.");
}, 1, TimeUnit.HOURS);
```

If this is not the answer you were looking for, please feel free to let me know. :-)

**Comment by JunoJunho** [comment]
I think this is what I look for.

Thanks 👍

**Comment by minwoox** [comment]
Nice to hear that. Thanks :-)
