### ISSUE TITLE
Can I add or remove service from server dynamically

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#1765]
one use case may be as follows:
I production, we don't add the `DocService` to our `server`, but for trouble shooting, we want to enable the `DocService` for temp usage.

so is there any way to add/remove `Service` to `Server` dynamically?

**Comment by trustin** [comment]
That's an awesome suggestion. :-)

It is currently not possible to configure service bindings dynamically although some mid-complexity refactoring will make it possible. 

However, if you just want to disable or enable a certain service at runtime, you could just write a decorator which rejects all requests until enabled at runtime?

**Comment by trustin** [comment]
@eonezhang Did the suggested workaround work for you? Let us know what you think. :smile:
