### ISSUE TITLE
Does documentation for RetryClient loss some detail?

### ISSUE THREAD

**Issue by JunoJunho** [line/armeria#1781]
https://line.github.io/armeria/client-retry.html

In above link, I do not get any difference between two code chunks except import statements.

If you have any other intention, please tell me and let me fix.

**Comment by minwoox** [comment]
Hello @JunoJunho, thanks for the report.
Unfortunately, they are different examples. The first one uses `ClientBuilder` so the `build()` method has a parameter `HttpClient.class`. Meanwhile, the second one uses `HttpClientBuilder` so the `build()` method does not take any parameter.

**Comment by minwoox** [comment]
But the scheme part of the URI is different when using `ClientBuilder` and `HttpClientBuilder`. The scheme should start with `none+http(s)` for `ClientBuilder` and `http(s)` for `HttpClientBuilder`. So I think it's better to update those examples. Would you mind sending a PR for that?

**Comment by JunoJunho** [comment]
Ah, there is a difference. I totally did not notice that.

Firstly, I though that if there is a difference in that topic, then it should be related with `RetryClient`. What you said is difference between `ClientBuilder` and `HttpClientBuilder`. I am not sure still about on it.

Anyway, I will happily prepare for that PR.

**Comment by trustin** [comment]
Much appreciated (in advance :stuck_out_tongue_winking_eye:), @JunoJunho!

**Comment by JunoJunho** [comment]
We can end this issue!

**Comment by trustin** [comment]
Nice work, @JunoJunho :rocket:
