### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by freesoft** [line/armeria#18]
Since Armeria is RPC library for client/server, it would be great if the library has integrated throttling feature so that server/client can properly manage incoming traffic if they have to. ( unless Armeria already have one, haven't seen it though )

**Comment by trustin** [comment]
We have an option in `ServerConfig.maxPendingRequests()` which is not implemented yet. The plan is to have a configurable policy which tells Armeria what to do when the server is busy enough. (e.g. stop reading, returning 503, applying CoDel, etc)
