### ISSUE TITLE
String-based headers/content sanitizer implementation

### ISSUE THREAD

**Issue by trustin** [line/armeria#1810]
It would be convenient if we provide a simple headers/content sanitizer which filters the stringified headers/content. For example, a user had to implement a sanitizer like the following:

```java
   @Nonnull
   public static String changeLogWithoutSensitiveData(@Nonnull Object request) {
       String requestMessage = request.toString();

       if(!isRequireFiltering(requestMessage)) {
           return requestMessage;
       }

       return filterSensitiveData(requestMessage);
   }

   private static boolean isRequireFiltering(@Nonnull String message) {
       if(removeContentNames.stream().noneMatch(message::contains)) {
           return false;
       }

       return true;
   }

   @Nonnull
   private static String filterSensitiveData(@Nonnull String message) {
       Matcher matcher;

       for(Pattern pattern : removeContentRegxs) {
           matcher = pattern.matcher(message);
           message = matcher.replaceAll("");
       }

       return message;
   }
```

We could make the following changes:

- Change the return type of header sanitizers from `HttpHeaders` to `?` so that a user can return any object such as `String`.
- Provide an abstract sanitizer implementation that converts headers or content to a `String` and filters it as instructed by its abstract methods such as `boolean needsSanitization()` and `String sanitize(String)`.
  - Provide a concrete implementation that implements `needsSanitization()` and `sanitize()` to filter the `String` using regular expression(s).
- Add some convenience methods to `LoggingClient/ServiceBuilder` and `RequestLog.toString*()`:

  ```java
  new LoggingClientBuilder()
          .requestContentSanitizer(Pattern.compile(...),
                                   Pattern.compile(...))
          ....
  ```

**Comment by trustin** [comment]
Fixed via #1879

**Comment by joongsoo** [comment]
I doing this issue

**Comment by amitvc** [comment]
@trustin I can implement this. I am new to the project but I am interested in contributing. Can I take this please?

**Comment by trustin** [comment]
@amitvc Hi! That sounds great. How about coming first with some API proposal (some rough API examples) so we can make sure your pull request will be not too far from what we imagined?

Another question out of curiosity: Are you using Armeria or considering to use it?

**Comment by amitvc** [comment]
@trustin Hello! I will send the proposal by today and get some examples. 
I am evaluating Armeria. I am a big fan of netty and have used it before.

**Comment by amitvc** [comment]
@trustin why is https://github.com/line/armeria/pull/1879 PR mentioned in here ? The header content sanitization will happen in the Request object sent to the server?

**Comment by trustin** [comment]
> why is #1879 PR mentioned in here ?

It was a mere mistake. Please ignore. :sweat_smile: 

> The header content sanitization will happen in the Request object sent to the server?

It happens when logging takes place by `LoggingClient` or `LoggingService`.

**Comment by amitvc** [comment]
Thanks @trustin 😅 
I think I understand what we are trying to do here.

**Comment by amitvc** [comment]
@trustin I already see code changes under #1879  have addressed 
`Change the return type of header sanitizers from HttpHeaders to ? so that a user can return any object such as String.`

**Comment by amitvc** [comment]
@trustin Would the sanitizers always be regex patterns or we want them to be generic enough so they can accept user-defined functions?

**Comment by trustin** [comment]
@amitvc The sanitizers are already a `Function`: https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java#L54-L61 The goal of this issue is to provide a regex-based sanitizer implementation. Makes sense?

**Comment by amitvc** [comment]
@trustin Yes it does. In your example you have mentioned a user can configure one or more regex patterns. We do want to support that type of configuration? If there are more than one regexes the input will pass through all of them and get sanitize at each stage.

**Comment by trustin** [comment]
Yep, that sounds good!

**Comment by amitvc** [comment]
@trustin There is a PR for this issue https://github.com/line/armeria/pull/2721
