### ISSUE TITLE
UNIX domain socket support

### ISSUE THREAD

**Issue by trustin** [line/armeria#1837]
From @huydx 

> I have a use case which uses nginx as a sidecar proxy and it may be better to use domain sockets instead of network sockets.

**Comment by max904-github** [comment]
I do have a similar use case! It should be feasible to do as Netty fully supports this.

**Comment by trustin** [comment]
Yeah, would be nice to have this feature to work nicely with sidecars such as Envoy, Linkerd, nginx, etc.

**Comment by chris-ryan-square** [comment]
Any news on this?  

For now, for my purposes, I've written a proxy server listening on the domain socket transferring everything to the Armeria port (based off the netty proxy server example: https://netty.io/4.1/xref/io/netty/example/proxy/package-summary.html).  

Works, but obviously it's not ideal to have an extra step there.

**Comment by ikhoon** [comment]
Thanks to @trustin, it is fixed by #4846.
