### ISSUE TITLE
DocService annotated http paths are mangled if not exact

### ISSUE THREAD

**Issue by tobias-** [line/armeria#1856]
This line mangles all annotated http paths that aren't exact.
https://github.com/line/armeria/commit/35416c2b77fd020ee37c4c42d582b142400bbefd#diff-3b29757cfa7d6be5d3ca726a154114b1R54

will chop off the first 6 characters of the path mangling it badly. While the path may not be usable anyway, it will not give a unexpected 404 or 405 error message.

@minwoox If you're doing https://github.com/line/armeria/issues/1855 anyway, this might be an easy fix?

**Comment by tobias-** [comment]
Example:
`/foo/{baar}` -> `/docs/baar}/`

**Comment by minwoox** [comment]
This is not related with #1855, but should be an easy fix. Thanks!
