### ISSUE TITLE
Simple way to get http parameter (from query string or form data) without using annotation ?

### ISSUE THREAD

**Issue by practice** [line/armeria#1861]
https://line.github.io/armeria/server-annotated-service.html#getting-an-http-parameter

The document above says how to get HTTP parameters, but it seems there is no way to get HTTP parameters without using annotation.

Actually, I'm evaluating Armeria under Clojure environment and I would like to avoid having to use annotation.

Any idea?

**Comment by minwoox** [comment]
Hello! @practice. Thank you for using Armeria!
I'm sorry but there's no convenient way to retrieve HTTP parameters for now. We will provide a utility for that later. Before that, you could just use the logic here. https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedValueResolver.java#L1203-L1239

**Comment by practice** [comment]
Thank you for guiding me to the source. Now I am translating the logic to Clojure way.
