### ISSUE TITLE
Add Client.as which can return a decorated client in the form of one of its decorations.

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1883]
Same as `Service.as` but for client.

**Comment by adriancole** [comment]
we may end up needing this in order to untangle some client related dependencies. ex we have some commands that need to happen with the same base client config, specifically AWS endpoint lookup prior to making a connection pool out of the results.

**Comment by jyblue** [comment]
Hello,
I would like to handle this issue :simple_smile:

**Comment by trustin** [comment]
@jyblue Sure. Please go ahead!

**Comment by jyblue** [comment]
Here is my question.

Expected usage of `Client.as` is 
``` java
Client decoratedClient = new MyClient().decorate(LoggingClient.newDecorator());

MyClient myClient = decoratedClient.as(MyClient.class);
LoggingClient loggingClient = decoratedClient.as(LoggingClient.class);
```
which is same as `Service.as`.

In this case, do we need `Client.decorate()' as well?
or 'Client.as' just enough?

**Comment by trustin** [comment]
@jyblue `Client.as()` should be enough, because how we construct a `Client` is different from how we construct a `Service`.

**Comment by jyblue** [comment]
@trustin Thank you for answer. I opened PR for this issue.
