### ISSUE TITLE
More metrics about DNS queries sent by Armeria

### ISSUE THREAD

**Issue by trustin** [line/armeria#1887]
We currently only record the time taken for DNS queries. A user wants to learn more, such as:

- the number of DNS queries
- the number of connection attempts that required a domain name resolution

with some tags for aggregation, e.g.

- Success or failure
- DNS error code
- UDP or TCP
- Query type (A, AAAA, CNAME, ...)

Please let us know if you have anything to add.

**Comment by trustin** [comment]
Related: https://github.com/line/armeria/issues/1921

**Comment by trustin** [comment]
We could also allow the customization of meter tags.

**Comment by Untaek** [comment]
Working in progress.

**Comment by amitvc** [comment]
@trustin It looks to me we will have to implement DnsQueryLifecycleObserver which will be responsible for capturing metrics about DNS queries. We will need a custom DnsQueryLifecycleObserverFactory that returns a new DnsQueryLifecycleObserver that is responsible for capturing metrics. Is there a standard way in armeria code base that we use to capture metrics ? Also how are we going to expose the captured metrics for DnsNameResolverBuilder? 
You have mentioned in the description for the ticket above that "record the time taken for DNS queries". Can you please direct me to the class that is doing this?

**Comment by trustin** [comment]
@amitvc We use Micrometer to record metrics. Your `DnsQueryLifecycleObserver` will require a `MeterRegistry` at its construction time, which could be acquired from `ClientFactory` (see `ClientFactory.meterRegistry()`).

We currently collect the time taken for DNS queries in `(Default)RequestLogBuilder.session()` via `ClientConnectionTimings`. You could record the metrics for the DNS query duration there, again using `MeterRegistry` from the `ClientFactory`.

I hope this makes sense. Please feel free to let me know if you need more help. :smile:

**Comment by amitvc** [comment]
@trustin ClientConnectionTimings records timings for each connection. 

- the number of DNS queries
Are we measuring the total number of DNS queries[different DnsRecordType] made within scope of single client request? 

the number of connection attempts that required a domain name resolution
This seems like a global metric. We want to measure number of connection attempts that require DNS resolution. Is this a metric that is required to be kept for a client pool? Not sure about this one.

**Comment by trustin** [comment]
@amitvc 

> the number of DNS queries - Are we measuring the total number of DNS queries[different DnsRecordType] made within scope of single client request?

I think it's OK to have the counters in the scope of `ClientFactory`, i.e. no need to track individual requests.

> the number of connection attempts that required a domain name resolution - This seems like a global metric. We want to measure number of connection attempts that require DNS resolution. Is this a metric that is required to be kept for a client pool? Not sure about this one.

Probably OK to keep it in the scope of `ClientFactory` as well? A user could compare it with the total number of requests sent. What do you think?

**Comment by amitvc** [comment]
@trustin I am trying to understand how clients use the ClientFactory in real-world scenarios. Do they use HttpClientFactory implementation to create and manage httpClients as and when they are needed?  I see httpClientFactory has HttpClientDelegate which has the ClientConnectionTimingsBuilder that I need. I am trying to figure out how DnsQueryLifecycleObserver into play here.

**Comment by trustin** [comment]
@amitvc `ClientConnectionTimingsBuilder` is for request-scoped timings, so you don't need to touch that. All we need to do here is to implement `DnsQueryLifecycleObserver` to record the metrics into `MeterRegistry` of `ClientFactory`.

**Comment by amitvc** [comment]
@trustin I have created a draft PR for this https://github.com/line/armeria/pull/2880
This is not complete but wanted to get your opinion if I am heading in right direction

**Comment by amitvc** [comment]
What I can confirm that my DefaultDnsQueryLifecycleObserver callbacks are being called correctly. But I need ClientConnectionTimings like facility to capture actual timings for dns queries.
