### ISSUE TITLE
Expose ClientFactory params

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1890]
When trying to write a unit test to verify some builder logic configures `ClientFactory` correctly, I found that I can't seem to read the settings of a `ClientFactory`. It should probably have a `.options()` method, similar to how a `Client` has `options()`.

**Comment by trustin** [comment]
A user might want to build a new `ClientFactory` which inherits an existing `ClientFactory`'s settings, while overriding a certain option only. /cc @delegacy
