### ISSUE TITLE
Confirm default of enabling http2 preface on client

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1891]
Just wanted to confirm using the http2 preface is a good default for an armeria client. I ran into not being able to connect to Elasticsearch V7 when this is enabled with

`com.linecorp.armeria.client.SessionProtocolNegotiationException: expected: http, reason: connection established, but session creation timed out:`

The error message doesn't really help debug and after being stuck for a while, I had the random idea of disabling the preface, which I think most users wouldn't ever find.

If there are servers where the preface doesn't work, is it actually a good idea to default to enabling it?

For reference, had failures in this build https://travis-ci.org/openzipkin/zipkin/builds/556693286?utm_source=github_status&utm_medium=notification

**Comment by anuraaga** [comment]
One thought I had is by reading this spec, IIUC it seems to recommend doing an upgrade request for plain text and use the preface for TLS. For reference, the issue I ran into was with plain text and I'm wondering if the default should differ for plain text vs TLS.

https://http2.github.io/http2-spec/#rfc.section.3.5

**Comment by trustin** [comment]
The problem with an upgrade request is that it *is* a real request that has to be handled by a service, which is why you were seeing #1895. If the first request of the connection is a big POST, we will suffer from the head-of-line blocking problem even if the server supports HTTP/2.

Also, some users set up an alarm for many 404 responses which can be triggered by an upgrade request.

I'm curious if ElasticSearch folks are aware of this issue. They need to send a response like Bad Request or Method Not Supported.

**Comment by trustin** [comment]
After reading the RFC a little bit, it seems loke we can use OPTIONS:

> If concurrency of an initial request with subsequent requests is important, an OPTIONS request can be used to perform the upgrade to HTTP/2, at the cost of an additional round trip.

**Comment by minwoox** [comment]
So is it okay to disable the preface since we changed to send OPTIONS in #1896?

**Comment by minwoox** [comment]
Perhaps we disable the preface and make a new page for performance tip and introduce enabling the preface there?

**Comment by trustin** [comment]
I found that gRPC-Java does not support HTTP/2 upgrade requests while investigating the build failures in #2849: https://github.com/grpc/grpc-java/issues/1087

Given that:

- gRPC, our major use case, is not ready for upgrade requests.
- Most HTTP/1 servers will not fail badly by HTTP/2 connection preface.
- Upgrade requests incur an additional round trip.

.. I'd like to keep the current behavior as it is, i.e. `useHttp2Preface = true` by default, unless there's strong objection.

**Comment by ikhoon** [comment]
> .. I'd like to keep the current behavior as it is, i.e. useHttp2Preface = true by default, unless there's strong objection.

+1 Even though the spec recommends to use HTTP/2 upgrade requests for cleartext, I think it is more important to work well with Armeria echo system using our default configuration.

**Comment by minwoox** [comment]
Oops~ 😅
