### ISSUE TITLE
Disparity between HttpHealthCheckedEndpoint and HttpClient can be confusing.

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1913]
This might be hard to solve, but we found some difficulties using `HttpHealthCheckedEndpointGroup` because it is separate from `HttpClient`. We configured the `HttpClient` with https, and decorators, but we also had to do the duplicate configuration on the `HttpHealthCheckedEndpointGroup` too, which we forgot at first. As it's redundant, it would be nice if this only had to be set once.

**Comment by trustin** [comment]
We could make `HttpHealthCheckedEndpointGroup` accept an `HttpClient` once we resolve #1143.

**Comment by trustin** [comment]
Not sure this is THE solution but at least it will make it trivial to use the same settings: https://github.com/line/armeria/pull/2019

**Comment by trustin** [comment]
Can't think of a good way to solve this. Should we close this now that it's relatively simple to use the same settings?

```java
HealthCheckedEndpointGroup.builder().clientOptions(webClient.options())...
```

**Comment by anuraaga** [comment]
The code is much better. I think we can leave the API at that.

It's still a bit unfortunate that it's easy to forget though. Do you think it's possible for a client to handle 4xx errors and if it is using a health checked endpoint group which doesn't have the same options, show a warning that the user may have missed this?

**Comment by trustin** [comment]
> Do you think it's possible for a client to handle 4xx errors and if it is using a health checked endpoint group which doesn't have the same options, show a warning that the user may have missed this?

Done in #2386
