### ISSUE TITLE
HTTP/1.1 requestLog doesn't record exception when getting ClosedSessionException

### ISSUE THREAD

**Issue by kojilin** [line/armeria#1914]
Testing with okhttp's MockWebServer.
`new MockResponse().setSocketPolicy(SocketPolicy.DISCONNECT_AT_START)`
`new MockResponse().setSocketPolicy(SocketPolicy.DISCONNECT_AFTER_REQUEST)`

Client side will get exception but there is no cause in RequestLog.

--
HTTP/2 works well with above socket policy.

**Comment by kojilin** [comment]
I will investigate this issue, due to I can't reproduce with separate test.

**Comment by trustin** [comment]
Thanks a lot, @kojilin!

**Comment by kojilin** [comment]
https://gist.github.com/kojilin/ed5daa7369833abc3d93d57a301b06b7#file-httpclientrequestlogwithclosedsessiontest-java-L62

<img width="1420" alt="スクリーンショット 2019-07-26 20 45 26" src="https://user-images.githubusercontent.com/863983/61949597-54b50880-afe6-11e9-8ccd-04086b4ad421.png">

not sure why h1c pass, maybe due to brave's integration test is using existing HttpClient?
