### ISSUE TITLE
Add new aliases`(get|post|head..)` for `(doGet|doPost|doHead..)` methods in AbstractHttpService

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#1923]
A user is able to add new service using `AbstractHttpService` with overriding the following methods.
* doOptions()
* doGet()
* doHead()
* doPost()
* doPut()
* doPatch()
* doDelete()
* doTrace()

This is an example codes.
```java
ServiceBuilder sb = ...
sb.service("/service/foo", new AbstractHttpService() {
    @Override
    protected HttpResponse doGet(ServiceRequestContext ctx, HttpRequest req) {
        return HttpResponse.of(HttpStatus.OK);
    }
});
```

`do` prefix like `doGet()` has been used by [servlet](https://tomcat.apache.org/tomcat-5.5-doc/servletapi/javax/servlet/http/HttpServlet.html) and jakarta ee for a long time. IMO, It looks like a little classical name. How about removing `do` prefix? `get()` is simple and clean without losing of its information.

We have discussed whether prefix `do` is needed. There are other opinions on this issue. 🤔 
* `doGet()` method  has another meaning. It is close to event handler than routing.
* `doGet()` is good, no reason to change it. 
* How about replacing `do` into another prefix like `handleXxx()` or `onXxx()`?

**Comment by minwoox** [comment]
Do we have a plan for this?

**Comment by ikhoon** [comment]
I thought we can utilize this as DSL. But I’m not sure this is a good change or not. 🧐

**Comment by ikhoon** [comment]
On second thought, I guess a separated layer for Kotlin DSL is needed, so we don’t need to change this. Let me close this issue. 🙏
