### ISSUE TITLE
Remove type parameters from Service and use HttpService and RpcService?

### ISSUE THREAD

**Issue by minwoox** [line/armeria#1926]
As @anuraaga said, some `static` `newDecorator` method's return type is 
`Function<lots and lots of stuff, with even more stuff>`.
Perhaps, we can simplify that by removing the type parameters which represent the types of `Request` and `Response` and use `HttpService` and `RpcService`.

**Comment by jyblue** [comment]
Hello, I'm working on this :-)

**Comment by trustin** [comment]
Please make sure to propose your change with examples before starting to make real changes since this is non-trivial.

**Comment by jyblue** [comment]
@trustin Sure, I will keep in mind.

**Comment by jyblue** [comment]
After talking with @trustin @ikhoon, I found that this issue needs more discussion.
So, I stop working on this issue. Thank you.

**Comment by trustin** [comment]
Fixed via #2254
