### ISSUE TITLE
Fail to :examples:static-files:test in uncommon case 

### ISSUE THREAD

**Issue by eugene70** [line/armeria#1934]
I had failed to build in my first try at the target ":examples:static-files:test".
After several attempt, I discovered the cause.
There is the file "index.html" at my home directory already.
And I found out that "index.html" recognized earlier than autoIndex.
After the file was removed, the build succeeded.

I think this is very trivial case, but failure is failure.
 
Ref1: [example.armeria.server.files.MainTest.java:50](https://github.com/line/armeria/blob/master/examples/static-files/src/test/java/example/armeria/server/files/MainTest.java#L50)

Ref2: [com.linecorp.armeria.server.file.HttpFileService.java:201](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/file/HttpFileService.java#L201)

**Comment by trustin** [comment]
Thanks for reporting and sorry for a late reply. :man_facepalming: We should fix this. :sweat_smile:

**Comment by ctk03272** [comment]
I'll work on it

**Comment by minwoox** [comment]
I'm not sure which PR fixed this issue. But I don't see this exception anymore so let me close this issue.
