### ISSUE TITLE
Make HttpData and/or AggregatedHttp* AutoCloseable

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1936]
okhttp makes their `ResponseBody` `Closeable`, which is convenient for pooled objects.

https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/

```java
try (AggregatedHttpResponse response = client.get("/").aggregateWithPooledObjects().join()) {
  System.out.println(response.contentUtf8());
}
```

instead of

```java
AggregatedHttpResponse response = client.get("/").aggregateWithPooledObjects().join()
try {
  System.out.println(response.contentUtf8());
} finally {
  ReferenceCountUtil.safeRelease(response.content());
}
```

However, users should still be free to use non-pooled without closing as we want the default case to be easy to use.
```java
AggregatedHttpResponse response = client.get("/").aggregate().join();
System.out.println(response.contentUtf8());
```
is equivalent to this which implements `close()` as a no-op.
```java
try (AggregatedHttpResponse response = client.get("/").aggregate().join()) {
  System.out.println(response.contentUtf8());
}
```

If we phrase the Javadoc well, I think we can keep the simple API while also providing this simpler mechanism to advanced users.

**Comment by adriancole** [comment]
I agree. this helps reduce the jargon and mechanical knowledge needed to understand before using the client.

while unrelated to this change I've been wondering if a more simple client interface could be exposed. For example, AggregatedHttpResponse isn't approachable outside folks familiar with netty mechanics. It is jargony. If there a more approachable api, for those who want efficiency, but don't enjoy the wrestling match between request and client scoped things or what's in the factory vs the client, or which functionality like scoping are available etc. I think basically we have choices to make.

Invest in making the hard api simpler or do that and also make a simpler api with less jargon for people who are less the "black t-shirt" releaser of references crowd :P

**Comment by adriancole** [comment]
ps I would wear that t-shirt once I stop struggling :P it would be a good shirt

**Comment by anuraaga** [comment]
I guess we'll want to do the proposed splitting of safe and unsafe APIs before 1.0.0. I have something in mind so will play with it.

**Comment by trustin** [comment]
Thanks, @anuraaga. I'm curious what changes will come. Since we added `SubscriptionOption`, the idea that came out of the discussion at https://github.com/line/armeria/pull/1938#pullrequestreview-268774847 might need some revision (or maybe not). Let me know once you have some prototype API.
