### ISSUE TITLE
Service discovery support (serversets, k8s, ..)

### ISSUE THREAD

**Issue by lzqdename** [line/armeria#194]
Hi, Does it support Service Discovery? 
For example ,buid on ZooKeeper,etcd or something else.
I think Service Discovery is a very important feature.

**Comment by trustin** [comment]
@shelocks recently introduced an extension point for that. You can register an `EndpointGroup` to `EndpointGroupRegistry` and then use `group:YourGroupName` in the 'host:port' part of the URL. e.g. `tbinary+http://group:MyGroup/...`

What's left is to implement an `EndpointGroup` that works for you. (ZK lookup, etc)

Interested in sending a PR?

**Comment by trustin** [comment]
Changed the subject of this issue and made it a feature request.

**Comment by trustin** [comment]
#707

**Comment by eugene70** [comment]
I am working on consul in this issue

**Comment by trustin** [comment]
I guess we're done except for etcd and Consul. Let me leave this issue open until etcd and Consul support are done.

**Comment by trustin** [comment]
Let me close this issue since we implemented most protocols now. I created #3224 for etcd, which is the last protocol standing.
