### ISSUE TITLE
Hard to know what host header will actually be sent

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1946]
While there may be some extra steps, I came up with a dance to figure out what host will actually be sent on the wire in https://github.com/openzipkin/zipkin-aws/pull/135/commits/bf291076dbe6c5a15810bf7fc24039e5958afb66

I don't think knowing the host in a decorator is a super-common use case, but AWS's signature algorithm does require it and it's currently quite magical understanding how to have this value (I needed the step debugger). Hopefully the current move-connection-to-front work can help with this too.

```
// Gets the host for use in signing. This requires a ceremony because Armeria doesn't reliably
  // provide this information.
  //
  // - Depending on whether the request comes from a health check or normal, ctx.endpoint().host()
  //   may be an IP address, while the actual host is in either HOST or AUTHORITY additional
  //   headers.
  //
  // - The host extracted from additional headers usually has a port attached, even for well-defined
  //   ones like HTTPS:443. Armeria strips this off in the end before sending the request it seems
  //   so we need to make sure to strip it here too.
static String host(ClientRequestContext ctx) {
    String host = ctx.additionalRequestHeaders().get(HOST);
    if (host == null) {
      host = ctx.additionalRequestHeaders().get(HttpHeaderNames.AUTHORITY);
    }
    if (host == null) {
      host = ctx.endpoint().host();
    }

     int colonIndex = host.indexOf(':');
    if (colonIndex >= 0) {
      host = host.substring(0, colonIndex);
    }

     return host;
  }
```

/cc @adriancole

**Comment by trustin** [comment]
Yeah i think we can move it as well. /cc @minwoox (who's working on it)

**Comment by trustin** [comment]
I think this issue can be closed now that a user can get the actual authority via `ClientRequestContext.endpoint().authority()`. Please feel free to reopen if you think it's not fixed yet.
