### ISSUE TITLE
Allow specifying the desired number of healthy endpoints to return for `HealthCheckedEndpointGroup`.

### ISSUE THREAD

**Issue by trustin** [line/armeria#1953]
When there are a lot of (e.g. thousands of) candidate endpoints, `HealthCheckedEndpointGroup` currently sends health check requests to all candidate endpoints. This it not efficient because it will create a large number of outgoing connections which will be idle in most time. We could:

- Allow a user specify the desired number of healthy endpoints to return.
- Send health check requests only as necessary.
  - For example, we could choose the endpoints randomly up to N and send health check requests only to them first, and then remove the unhealthy endpoints or add another random endpoint based on the health check result.

**Comment by monorisk** [comment]
I would like to solve this!

**Comment by trustin** [comment]
Fixed via #2177. Thanks again, @monorisk
