### ISSUE TITLE
Add a shortcut method for `Server.activePort().get().localAddress().getPort()`

### ISSUE THREAD

**Issue by trustin** [line/armeria#1956]
In our test cases, I see many many calls like this:

```java
server.activePort().get().localAddress().getPort()
```

We could provide a shortcut method for it, like:

```java
server.activeLocalPort()
```

A user might want to specify the desired session protocol as well:

```java
server.activeLocalPort(SessionProtocol.HTTPS)
```

**Comment by moonchanyong** [comment]
can I handle this issue?
