### ISSUE TITLE
Add more sampler implementations for `LoggingClient` and `LoggingService`

### ISSUE THREAD

**Issue by trustin** [line/armeria#1960]
Some time ago, we forked `Sampler` and its `CountingSampler` from Brave to allow a user to specify sampling rate when using `LoggingClient` or `LoggingService`. Since then, @adriancole has added more useful `Sampler` implementations we might need to fork again:

- https://github.com/openzipkin/brave/tree/master/brave/src/main/java/brave/sampler

This time, we have to move `com.linecorp.armeria.internal.logging.Sampler` to `com.linecorp.armeria.common.util`, so that we can expose `Sampler` in our public API.

**Comment by geminiKim** [comment]
Hi, I'm trying to solve this issue.

I have a question, some `Sampler (DeclarativeSampler, ParameterizedSampler)` needs to `brave.propagation.SamplingFlags`.

And ’SamplingFlags’ need to many classes of `brave`. `(InternalPropagation, TraceContext, Span ...)`

Which package do you think it is best to bring these classes?
Or `core` should be depended `brave`?

I will wait to your opinion, Thank you :D
