### ISSUE TITLE
Add literal value field for enum in internal documentation

### ISSUE THREAD

**Issue by Waynefn** [line/armeria#1966]
In internal documentation for enums `internal/docs/#/enums`,
there are only `Name` and `Description` field for enum types.
It would be more convenient if the literal value (for example, int value) for this enum name is also displayed,
since in most cases, we use that value to debug request and response.

**Comment by trustin** [comment]
That's a good idea. Are you interested in sending a pull request? :smile:

**Comment by Ta2Rim** [comment]
I'll work on it

**Comment by trustin** [comment]
@Ta2Rim Awesome!

**Comment by Waynefn** [comment]
Cool. I found the improvement just recently when I using it!
