### ISSUE TITLE
Add Fibonacci backoff implementation and update the default backoff spec

### ISSUE THREAD

**Issue by trustin** [line/armeria#1968]
See this tweet: https://twitter.com/sethvargo/status/1158838068805345280

We currently provide fixed, random and exponential backoff implementations and use exponential backoff as the default backoff:

- Backoff implementations: https://github.com/line/armeria/tree/master/core/src/main/java/com/linecorp/armeria/client/retry
- Default backoff spec: https://github.com/line/armeria/blob/fa3572a5698d5fcdca2dfe1295a23787bccffb7e/core/src/main/java/com/linecorp/armeria/common/Flags.java#L211-L212

We could add Fibonacci backoff implementation and update our default backoff specification.

**Comment by anuraaga** [comment]
Read the papers and not finding a really relevant reason to change the default - the papers are framed in terms of mobile networks, where a fixed amount of bandwidth is allocated among many devices and a backoff that doesn't exponentially become very large allows better allocation and higher throughput. If I understand correctly, retrying in this use case is common and expected. I think our backoff is mostly to give a backend time to cool-down in times of problems, and retrying is not common or expected - so maybe exponential still makes sense as a default, though adding the fibonacci implementation seems nice.

**Comment by trustin** [comment]
Thanks for the comment, @anuraaga. Yeah, at least we could add the Fibonacci implementation. Making it as a default is another story which needs more thought.

**Comment by thinkgruen** [comment]
hello, I saw flag on this issues and would like to give it a shot this week. 😃

**Comment by trustin** [comment]
Awesome! Feel free to let us know if you have any questions etc while working on it. :smile: By the way, are you using Armeria?

**Comment by thinkgruen** [comment]
So far no real questions, PR is almost ready. I just encountered some silly arithmetic stuff along the way where MAX_LONG / 3 * 3 < MAX_LONG, but this is not a magnitude to lose sleep over, i guess. 😄

As for your question: not actively atm. I am somewhat familiar with Netty already as well as a LINE user, so I thought it would be interesting to have a look into Armeria.
