### ISSUE TITLE
Searching for a type in javadoc leads to a 404 with "undefined" in URL

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1972]
When using the searchbox at http://line.github.io/armeria/apidocs/ if I click on a package result it's fine, but if I click on a type result, it goes to a 404 URL like this one

http://line.github.io/armeria/apidocs/undefined/com/linecorp/armeria/client/HttpClient.html

**Comment by trustin** [comment]
It's fixed at master but not released. :smile:

**Comment by anuraaga** [comment]
Cool thought that might be the case :)

**Comment by trustin** [comment]
New web site has been deployed and the search box works now.
