### ISSUE TITLE
ask a question : build fail for test.

### ISSUE THREAD

**Issue by erinyees** [line/armeria#1976]
I am trying to run armeria in my laptop by following the `CONTRIBUTING.md`.

but I have a problem.

I typed command `./gradlew build site` but it failed.
I got below error message.
`
> Task :logback:compileTestJava FAILED
C:\Users\Hanhg\Desktop\armeria\logback\src\test\java\com\linecorp\armeria\common\logback\RequestContextExportingAppenderTest.java:62: error: cannot find symbol
import com.linecorp.armeria.common.thrift.ThriftReply;
                                         ^
  symbol:   class ThriftReply
  location: package com.linecorp.armeria.common.thrift
C:\Users\Hanhg\Desktop\armeria\logback\src\test\java\com\linecorp\armeria\common\logback\RequestContextExportingAppenderTest.java:89: error: cannot find symbol
    private static final ThriftReply THRIFT_REPLY =
                         ^
  symbol:   class ThriftReply
  location: class RequestContextExportingAppenderTest
C:\Users\Hanhg\Desktop\armeria\logback\src\test\java\com\linecorp\armeria\common\logback\RequestContextExportingAppenderTest.java:90: error: cannot find symbol
            new ThriftReply(new TMessage("hello", TMessageType.REPLY, 1),
                ^
  symbol:   class ThriftReply
  location: class RequestContextExportingAppenderTest
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':logback:compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

I tried to find error in `RequestContextExportingAppenderTest.java` but there are not compilation error or warning.

What should I do in this situation?

It is my development environment.
Windows 10
IntelliJ IDEA 2019.1.1

**Comment by trustin** [comment]
That is really weird. Could you create a gist with the full build output and share it here so we know better what happened?

**Comment by erinyees** [comment]
here it is.

command : `./gradlew build site --debug`
[error_log_debug.txt](https://github.com/line/armeria/files/3479567/error_log_debug.txt)

command : `./gradlew build site`
[err_log_plain.txt](https://github.com/line/armeria/files/3479568/err_log_plain.txt)

**Comment by ikhoon** [comment]
> It is my development environment.
Windows 10
IntelliJ IDEA 2019.1.1

Could you share your java version?

**Comment by erinyees** [comment]
> > It is my development environment.
> > Windows 10
> > IntelliJ IDEA 2019.1.1
> 
> Could you share your java version?

It is solved! thanks @ikhoon , @trustin 
I installed Zulu openjdk-8 and openjdk-11 but I didn't changed JAVA_HOME environment path.
I changed openjdk-11 as default java so build well.

anyway, total building time is 23 minute in mine. is it normal?
I mean, it looks too slow to start in mine.

**Comment by trustin** [comment]
Good to know that you solved the problem. We'd better update our `CONTRIBUTING.md` and add some checks in `build.gradle` if we forgot to mention that we need JDK 11+ to build Armeria.

**Comment by trustin** [comment]
You can improve the build speed by adding `--parallel` option :-)

**Comment by erinyees** [comment]
> You can improve the build speed by adding `--parallel` option :-)

I tried `--parallel` option and it finished in 2 minutes.

thanks.
I will close this issue
