### ISSUE TITLE
Add status code to HTTP health check metrics

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1981]
While debugging a health check, we found it would be nice if metrics exported the http status code. I think it'd be simple to add.

/cc @adriancole

**Comment by young891221** [comment]
I'll work on it.

**Comment by trustin** [comment]
@young891221 Gentle ping

**Comment by jrhee17** [comment]
Let me close this issue since as of now I think the status code is exported by default. (Let me know if I'm wrong 🙏 )
