### ISSUE TITLE
Question: What is the proper way to run the examples?

### ISSUE THREAD

**Issue by Untaek** [line/armeria#1987]
Hi! I am newbie who want to start contribute Armeria.

Before starting, i'm trying to run examples in repository.

**_proxy-server_** example is just can start by
`./gradlew run` in my machine.

but I couldn't find proper way for others.

I use commands for **spring** examples:
```sh
./gradlew :examples:spring-boot-webflux:build
./gradlew :examples:spring-boot-webflux:bootRun
```

And others:
```sh
# add lines to build.gradle in example project directory.
apply plugin:'application'
mainClassName = "{classpath}.Main"

# after
./gradlew :examples:{example-name}:bootRun
```

Is there short commands or guides i missed to run examples?

**Comment by ikhoon** [comment]
If you are using IntelliJ IDEA, you can start the main method by taping on the run button. :-)

![image](https://user-images.githubusercontent.com/1866157/62833935-05770500-bc81-11e9-9df0-e22ff0c8b326.png)

Or did you use another IDE?

**Comment by Untaek** [comment]
Oh i didn't know that, Thank you @ikhoon. I'm using IntelliJ IDEA. 
How about adding commands for example?

**Comment by ikhoon** [comment]
> How about adding commands for example?

@Untaek That's a nice idea. I think it would be useful for other beginners. 
Could you add `mainClassName` command and make a PR? 😉

**Comment by Untaek** [comment]
Okay i'll try! Thanks for your kindness.
