### ISSUE TITLE
ByteArrayResponseConverterFunction clamped to two MediaTypes

### ISSUE THREAD

**Issue by tobias-** [line/armeria#1999]
The following snippet should imho work:
```
    @Get("/favicon.ico")
    @Produces("image/gif")
    private ByteArray favicon() {
        return new byte[0]
    }
```

It does not work however, because if the `contentType` isn't null, and isn't one of APPLICATION_BINARY or OCTET_STREAM, the converter will not be used.

Discussion about problem:
https://app.slack.com/client/T1NH00FK9/C1NGPBUH2/thread/C1NGPBUH2-1565946569.136900

**Comment by trustin** [comment]
Thanks, @tobias-. Let me look into this soon.
