### ISSUE TITLE
Use BOMs for the dependencies that distribute BOMs

### ISSUE THREAD

**Issue by trustin** [line/armeria#2011]
`netty-bom`, `jackson-bom` and maybe some other dependencies.

Need to make sure our POMs (including `armeria-bom` and all other artifacts) are generated correctly while working on this.

**Comment by anuraaga** [comment]
Found some more BOMs we should consider - if no qualms will send out a PR

- grpc
- dropwizard.metrics
- junit
- jetty

And for record ones I found we shouldn't use since they also manage transitive dependencies
- opensaml
- spring-boot
