### ISSUE TITLE
Use a single `HttpClient` instead of creating many in Retrofit integration

### ISSUE THREAD

**Issue by trustin** [line/armeria#2022]
We do not need to create different `HttpClient` instances for different authorities anymore, thanks to @ikhoon's recent work:

```java
HttpClient client = HttpClient.of();
client.get("https://www.google.com/");
client.get("https://www.amazon.com/");
```

We could make use of this improvement in our Retrofit integration, which currently creates a new `HttpClient` for each authority.

/cc @kojilin

**Comment by kojilin** [comment]
Because we can set ClientOptions for different authority, we need to prepare multiple client for that case. Curious if it's worth to do it.

**Comment by trustin** [comment]
Ah, yeah. Totally missed that. Thanks for the reminder. Closing, then. :bowing_man:
