### ISSUE TITLE
Per-service setting is not possible for annotated service

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2023]
A user can configure per-service settings using fluent `Route` API.
However, this is only for the services which implement `HttpService`, not for the annotated service.
We should provide a way for annotated service as well.

**Comment by sivaalli** [comment]
Hi @trustin @minwoox @ikhoon ,

I think what we could do is, add an annotation called `@Configuration` that has properties/fields that reflect all the settings that `Route` api supports. For example a user can declare `@Configuration(maxRequestLength = 1024, requestTimeoutMillis=5000)` like this on a service method. Instead of creating a new Annotation(in this example `@Configuration`), we can also introduce route specific properties on `@Path`. What do you think? 

If you guys have anything else in mind please feel free to share it so I can implement it.

**Comment by trustin** [comment]
How about just adding `buildAnnotated(Object)` to `ServiceBindingBuilder`?

**Comment by minwoox** [comment]
Hello, @sivaalli! Thanks for the suggestion. However, I think adding more annotations is the last thing I want to do. 😄 

Had a chat with @trustin and we thought adding a builder would be enough for this.
```java
ServerBuilder sb = Server.builder()
                         .annotatedService() // Not sure this is the best name.
                         .requestTimeoutMillis(5000)
                         .contentPreview(...)
                         ...
                         .build(object); // Return to the ServerBuilder
```

All the properties that a service might want to set separately are gathered in `AbstractServiceBindingBuilder` thanks to @ikhoon.
However, the builder for annotated service just cannot inherit from it because of `AbstractBindingBuilder` which `AbstractServiceBindingBuilder` is inherited from.
```java
- AbstractBindingBuilder
  - AbstractServiceBindingBuilder
    - ServiceBindingBuilder
```
So I think we have to tear off `AbstractServiceBindingBuilder` from `AbstractBindingBuilder` first. We can make an interface for the service configuration binding, so `ServiceBindingBuilder` implements the interface while extending `AbstractBindingBuilder`, and `AnnotatedServiceBuilder`(?) will implements the interface only.
What do you think?

**Comment by sivaalli** [comment]
Hi @trustin and @minwoox, I think I may have misunderstood this issue. So just want to reiterate the idea. For example, if this is my service:

```
class MyService{

    @Get("/foo")
    public HttpResponse foo(){
        return HttpResponse.of(200);
    }

    @Post("/bar")
    public HttpResponse bar(){
        return HttpResponse.of(200);
    }
}
```
and annotated service is registered using

```
Server server = new ServerBuilder().port(8080, SessionProtocol.HTTP).annotatedService("/hello", new MyService()).build();
```

Then, we should provide ability for user to

1. Configure different http settings for `/hello/foo`(for ex: requestTimeoutMillis =1000) and `/hello/bar`(for ex: requestTimeoutMillis =5000)
2. Configure http settings for anything under `/hello`

If I'm understanding this correct the point# 2 is what we are trying to achieve right? 

But your idea sounds good. I just wanted to make sure I understand this correctly before I start writing any code.

**Comment by minwoox** [comment]
> If I'm understanding this correct the point# 2 is what we are trying to achieve right?

Yes, we are going to provide #2 because this is per-service configuration not per-method configuration. :-)

> Configure different http settings for /hello/foo(for ex: requestTimeoutMillis =1000) and /hello/bar(for ex: requestTimeoutMillis =5000)

In this case, we are guiding like:
```java
class MyService{
    @Get("/foo")
    public HttpResponse foo(ServiceRequestContext ctx) { // or RequestContext.current()
        ctx.setRequestTimeoutMillis(1000);
        return HttpResponse.of(200);
    }
}
```

> Sorry If I'm saying things again and again but just wanted to make sure I understand this correctly before I start writing any code.

You are always welcome to ask us anything. :-)

**Comment by sivaalli** [comment]
Thank you @minwoox. I will start looking into this.
