### ISSUE TITLE
Propagate client TLS errors to users

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2025]
Currently, client TLS errors are logged but the user just gets a `ClosedSessionException` with no message or stack trace. TLS errors are generally not transient and are a result of a configuration error that the user needs to fix so we should propagate them as the cause of the exception.

Related https://github.com/openzipkin/zipkin/issues/2776

**Comment by trustin** [comment]
@jrhee17 and this one

**Comment by trustin** [comment]
Fixed via #2338

**Comment by trustin** [comment]
Thanks again, @jrhee17 !
