### ISSUE TITLE
Automatic disconnection after handling N requests

### ISSUE THREAD

**Issue by trustin** [line/armeria#203]
When an Armeria server serves requests behind an L4 load balancer, keeping the connection for too long can cause load imbalance between the servers, especially when one of the servers restarts.

One way to solve this problem is to use client-side load balancer or smarter L7 load balancer, but a user may not have such choices but using L4 load balancer which doesn't work well with long living connections.

To give more options to our users, we could add an option that configures an Armeria server to disconnect a connection after handling a certain number of requests.

Action items:
- Server sends a response with a `Connection: close` header or sends a `GOAWAY` frame after handling a configured number of requests.
- Server waits for the client to disconnect for a few seconds. (so that the client gets `TIME_WAIT` state)
  - If the client does not disconnect in time, server closes the connection.

**Comment by anuraaga** [comment]
Will this actually help balancing? I think it requires a large number of clients vs servers or it just means unbalanced load moves from one server to another. What do you think about also adding a setting to connect multiple times to the same IP?

**Comment by trustin** [comment]
> Will this actually help balancing? I think it requires a large number of clients vs servers or it just means unbalanced load moves from one server to another.

Correct. It won't help a lot when the number of clients is not large enough.

> What do you think about also adding a setting to connect multiple times to the same IP?

Like retrying a failed connection attempt?

**Comment by anuraaga** [comment]
Nah retrying will still be unbalanced (probably more unbalanced). I meant having multiple TCP connections to the same L4 load balancer - the more connections, the higher chance that they'll be somewhat balanced even when the # of clients is low.

**Comment by trustin** [comment]
>  I meant having multiple TCP connections to the same L4 load balancer.

Ah, I see. Yeah, that will help but we may not need that option given that we already create as many connections as the number of available event loops?

**Comment by anuraaga** [comment]
If I understand the event loop initialization correctly, the number of event loops will depend on the # of cores in the machine. For machines with a lot of cores, this is probably a good number of connections, but maybe not enough in many environments.

**Comment by jonefeewang** [comment]
is this feature decided to be done? if so, i will take it. Currently i am walking around to look for a chance to hack deeper with armeria :smiling_imp:

**Comment by trustin** [comment]
Very cool. It's all yours now, @jonefeewang !

**Comment by jonefeewang** [comment]
I found  class com.linecorp.armeria.client.http.Http2ResponseDecoder in core module   implements `public void onGoAwayReceived(int lastStreamId, long errorCode, ByteBuf debugData)` as a no operation way. which means our armeria  client dose not understand a http2 go_away frame. I am not sure is it a bug ?

**Comment by trustin** [comment]
> I found class com.linecorp.armeria.client.http.Http2ResponseDecoder in core module implements public void onGoAwayReceived(int lastStreamId, long errorCode, ByteBuf debugData) as a no operation way. which means our armeria client dose not understand a http2 go_away frame. I am not sure is it a bug ?

It's actually handled by Netty (and then Netty will call our no-op method) so we don't need to put anything there. Please let me know if it's not working as expected. Thanks!
