### ISSUE TITLE
AnnotatedHttpService: Allow `@PathPrefix` annotations in class scope

### ISSUE THREAD

**Issue by heowc** [line/armeria#2031]
I think it would be nice to be able to specify a prefix as an annotation without using pathPrefix.

For example.

```java
ServerBuilder sb = new ServerBuilder();
sb.annotatedService(new ForBarService());
//...
```
```java
@PathPrefix("/foo")
public class FooBarService {
    @Get
    @Path("/bar")
    public Object bar() { ... }

    @Get
    public Object fooGet() { ... }

    @Post
    public Object fooPost() { ... }
} 
```

I think there is an advantage to see the specified path at once.

**Comment by trustin** [comment]
That's a good idea. We currently use `@Path` for other type of path mappings such as glob and regex, so we have two options:

- Restrict the format of `@Path` when it's used at class level.
- Define a different annotation such as `@PathPrefix`.

I prefer the second option, but what do you think? /cc @ikhoon @minwoox

**Comment by ikhoon** [comment]
`@Path` at class level can give a user confused because of the glob. I also lean to `@PathPrefix` l. and we can use it method level too. 😀

**Comment by minwoox** [comment]
+1 for `@PathPrefix` :)

**Comment by sivaalli** [comment]
Hi, Is this something a first timer can work on? If yes, I'm more that happy to look at it

**Comment by minwoox** [comment]
@sivaalli Thanks for your interest!
Yes, I think and I hope it's not that difficult. But I think we need to ask @heowc that he is going to deal with this or not before you take this. 😉

**Comment by heowc** [comment]
@sivaalli Thanks for your opinion!
I will another PRs in progress and someday I will proceed this. 
but, If you need to this, I think it's not bad for you to deal with it. 👍

**Comment by sivaalli** [comment]
Thanks you @minwoox and @heowc for your thoughts. I will work on this. BTW excellent work creating armeria and open sourcing it.
