### ISSUE TITLE
What is the endpoint for grpc server that I'm running.

### ISSUE THREAD

**Issue by anirudhr95** [line/armeria#2033]
I have extended the GrpcServiceImplBase and I have over-ridden an method called getItem.

In my server, I have also bound this service, like so -

```java
public class ProducerServer {

    public static void main(String args[]) {
        ServerBuilder sb = new ServerBuilder();
        sb.http(4242);
        sb.service(
                new GrpcServiceBuilder()
                        .addService(new ProducerEndpointImpl())
                        .build()
                , LoggingService.newDecorator()
        );
        Server server = sb.build();
        server.start();
    }

}
```

and my GRPC implementation - 

```java
public class ProducerEndpointImpl extends ProducerServiceGrpc.ProducerServiceImplBase {

    @Override
    public void getItem(com.sourcesink.producer.ProducerRequest request,
                        io.grpc.stub.StreamObserver<com.sourcesink.producer.ProducerResponse> responseObserver) {

        byte[] fileContent = new byte[0];

        try {
            fileContent = Files.readAllBytes(Paths.get("/Users/anirudhr/generated.json"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        ProducerResponse response = ProducerResponse.newBuilder().
                                        setFile(ByteString.copyFrom(fileContent)).
                                        build();
        responseObserver.onNext(response);
        responseObserver.onCompleted();


    }

}
```

I get a name resolution failure on hitting the rpc endpoint through bloom - 

```
"error": "14 UNAVAILABLE: Name resolution failure"
```

My protobuf definitions - 
```protobuf
syntax = "proto3";

package producergrpc;

option java_package = "com.sourcesink.producer";
option java_outer_classname = "Producer";
option java_multiple_files = true;
option optimize_for = SPEED;

/*
    * Assuming Producer Response can be 1 file or more (In byte format)
*/

message ProducerResponse {
    bytes file = 1;
}

message ProducerRequest {

}

service ProducerService {
    rpc getItem(ProducerRequest) returns (ProducerResponse) {}
}
```

By bloom I mean this - [Bloom](https://github.com/uw-labs/bloomrpc)

**Comment by anirudhr95** [comment]
By bloom I mean this - [Bloom](https://github.com/uw-labs/bloomrpc)

**Comment by trustin** [comment]
I didn't try Bloom, but I guess it will be `127.0.0.1:4242` in your case. Did you try it already?

**Comment by anirudhr95** [comment]
<img width="1333" alt="Screenshot 2019-08-28 at 4 23 35 PM" src="https://user-images.githubusercontent.com/2638126/63849746-504a8980-c9b0-11e9-84eb-3dab96b4fb9c.png">

**Comment by anirudhr95** [comment]
> I didn't try Bloom, but I guess it will be `127.0.0.1:4242` in your case. Did you try it already?

Thanks for the quick response. I was just attaching the bloom tool screenshot. Yes I am running it at that URL. But I cannot figure out what I'm doing wrong. I guess the next step is for me to post my build.gradle if that is required - but I'll wait for your help (so that you can see if I have screwed up something in what I have posted so far ^)

**Comment by trustin** [comment]
How about removing `http://` and trailing `/`?

**Comment by anirudhr95** [comment]
Alright, that was it. I feel extremely silly now.

**Comment by trustin** [comment]
No worries. By the way, you can try our `DocService` which does the similar job with `Bloom`, except that you don't even need a `.proto` file:

https://line.github.io/armeria/server-docservice.html

**Comment by anirudhr95** [comment]
Oh wow. I did not know of this. I'll definitely give it a try.

Additionally, I have a question, this might not be the right place for it - but if need be, I'll create a new thread - 

Is there any way I can pass data to the service?

I have this definition right - 
`    public static void main(String args[]) {
        ServerBuilder sb = new ServerBuilder();
        sb.http(4242);
        sb.service(
                new GrpcServiceBuilder()
                        .addService(new ProducerEndpointImpl())
                        .build()
        );
        Server server = sb.build();
        server.start();
    }`

I want to have an array blocking queue (say) and put a bunch of files in them - and serve them to the user on each req one by one. But I would benefit a lot by having them in this queue. Problem is, I won't access to this on the service (and I imagine the service endpoint would only be called on the first request). But I can have the files in the queue before server start. 

Any elegant solution for this use case?

**Comment by anirudhr95** [comment]
Never mind. I guess I will make it a class-level variable and use getter and access it in the other place. I don't know why I went the pass data-route 😢
