### ISSUE TITLE
Add a decorator that allows a user translate an exception into a response.

### ISSUE THREAD

**Issue by trustin** [line/armeria#2046]
... which might be useful for our RPC (both gRPC and Thrift) and REST users. 

See #2044 for the context.

**Comment by trustin** [comment]
I wonder if it's a good idea to reuse `com.linecorp.armeria.server.annotation.ExceptionHandlerFunction` for other service types including gRPC, Thrift and non-annotated HTTP services. 

```java
// Common exception handler
ExceptionHandlerFunction exceptionHandler = ...;

// gRPC
final ServerBuilder sb = new ServerBuilder();
sb.service(new GrpcServiceBuilder()
        .addService(myGrpcService)
        .exceptionHandler(exceptionHandler)
        .build());

// HTTP
sb.service("/http", 
           ((HttpService) (ctx, req) -> ...)).decorate(
                   ExceptionFilteringService.newDecorator(exceptionHandler)));

// Thrift
sb.service("/thrift", THttpService.builder(...)
                                  .exceptionHandler(exceptionHandler)
                                  .build());
```

What I'm not sure about:

- What would be the expected behavior when the response is already committed (either partially or fully)?
- Is `GrpcServiceBuilder.exceptionHandler()` better than providing a `ServerInterceptor` implementation that translates an exception?
- Is `THttpServiceBuilder.exceptionHandler()` better than providing a decorating `RpcService` implementation that translates an exception?
- Is this feature really worth generalizing? Should we just let our users translate exceptions by themselves or use other proxy/AOP libraries?

Thoughts? /cc @anuraaga @ikhoon @imasahiro @kojilin

**Comment by anuraaga** [comment]
I don't think I would add new methods like `GrpcServiceBuilder.exceptionHandler`. I don't see a reason to special case the exception handler but require decorator for other concepts like auth.

Having the `ExceptionFilteringService` seems ok but indeed isn't so useful for RPC so maybe not such a valuable API.

**Comment by ikhoon** [comment]
This issue has been fixed by various improvements.
- Thrift: #3383
- gRPC: #3197
- HTTP: #3853
