### ISSUE TITLE
Make `EventLoopThreadFactory` more customizable

### ISSUE THREAD

**Issue by trustin** [line/armeria#2047]
A user sometimes want to decorate the `Runnable` of the `Thread` created by an `EventLoopThreadFactory`. If `EventLoopThreadFactory` were not `final`, he or she could do the following:

```java
new EventLoopThreadFactory(...) {
    @Override
    public Thread newThread(Runnable task) {
        return super.newThread(() -> {
            Thread.currentThread().setContextClassLoader(...);
            task.run();
        });
    }
}
```

We could allow a user specify a `Function<? super Runnable, ? extends Runnable>` when creating an `EventLoopThreadFactory`, so that he or she can perform an additional work before/after the `task` is run.

To achieve this, I'd like to introduce a builder:

```java
EventLoopThreadFactory.builder(...)
                      .daemon(true)
                      .priority(...)
                      .taskFunction(task -> {
                          Thread.currentThread().setContextClassLoader(...);
                          task.run();
                      })
                      .build();
```

.. and deprecate all its public constructors.

**Comment by jyblue** [comment]
I would like to tackle this. Thank you.
