### ISSUE TITLE
Is it possible to make gRPC stubs share a gRPC channel with the client factory of Armeria?

### ISSUE THREAD

**Issue by carlsagan21** [line/armeria#2049]
Hi Armeria team!

I want to know how I can create multiple gPRC stubs with a single shared gRPC channel.
AFAIK, gRPC channel is a heavy object, so creating a channel for an application is recommended. (Maybe I'm wrong)
https://github.com/grpc/grpc-java/issues/3268#issuecomment-317484178

But the client factory methods of Armeria, let's say [`GrpcClientFactory::newClient`](https://github.com/line/armeria/blob/master/grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientFactory.java#L101-L161), seems to create a channel and stub together. Did I miss sth?

I think it will be great if we can share a gRPC channel among all service stubs in an application!

**Comment by anuraaga** [comment]
Upstream gRPC channels have a lot of state associated like event loops.

But Armeria channels are very simple wrapper objects that use other Armeria business logic to implement gRPC. The channels use a shared clientfactory, which is Armeria's equivalent of the heavyweight aspects of the upstream netty channel, so there isn't a real efficiency penalty for having multiple of them.

**Comment by anuraaga** [comment]
Let us know if you have any other questions :)
