### ISSUE TITLE
Migrate TSlint to ESlint according to deprecation of TSlint

### ISSUE THREAD

**Issue by taejs** [line/armeria#2054]
https://github.com/palantir/tslint/issues/4534

TSLint is officially announced to be deprecated in 2019,
Now docs-client uses TSLint, so I think it would be great to migrate to ESLint.

**Comment by ikhoon** [comment]
That's a good idea. I’d like to listen to other folks opinion. :-)

**Comment by anuraaga** [comment]
Yup I think it's a good idea - it's been in my mind's backlog for a while.
