### ISSUE TITLE
Signal to know if a composite endpoint group is dynamic

### ISSUE THREAD

**Issue by adriancole** [line/armeria#2071]
In zipkin, we have this code which now looks at a deprecated type:

```java
    if (endpointGroup instanceof StaticEndpointGroup && endpointGroup.endpoints().size() == 1) {
      // Just one non-domain URL, can connect directly without enabling load balancing.
      return endpointGroup.endpoints().get(0);
    }
```

Later, we look at `DynamicEndpointGroup`, but it isn't precisely the opposite of static. For example, `CompositeEndpointGroup` can contain dynamic endpoint groups.

There's no clear signal I can tell if an endpoint group is fully comprised of IP addresses or not, at least not with relying on a deprecated type.

**Comment by anuraaga** [comment]
The new design is single endpoint, static endpoints, dynamic endpoints all have the same API. So you should be able to just call await on any endpoint group and not do any special casing. Do you think the isStatic is needed?

**Comment by adriancole** [comment]
hmm let me look. good point

**Comment by adriancole** [comment]
yep indeed. below base case looks super cheap. I will close this.

```
    @Override
    public CompletableFuture<List<Endpoint>> initialEndpointsFuture() {
        return CompletableFuture.completedFuture(endpoints);
    }
```
