### ISSUE TITLE
Fail HealthCheckedEndpointGroup.initialEndpointsFuture() when all hosts fail check

### ISSUE THREAD

**Issue by adriancole** [line/armeria#2075]
Right now, if the delegate to HealthCheckedEndpointGroup succeeds, by producing endpoints, but all of them fail a check, the `HealthCheckedEndpointGroup.initialEndpointsFuture()` is left uncompleted.

This seems to do with state management around https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java#L335

Basically, `healthyEndpoints` is empty and removing from empty doesn't incur an update. Nothing calls `setEndpoints` which completes the initial future.

I think we'd want some sort of exception to complete on error IFF we have cycled through all the hosts and none passed.

ex a message like `"couldn't connect any of " + delegate.endpoints()`

**Comment by anuraaga** [comment]
In #2074 I have it so the future is completed with empty endpoints. I think this makes more semantic sense than an exception - we've initialized our endpoints, they just happen to be empty. Users that want special behavior when the initial endpoints are empty can check `await().isEmpty()` and do something, or not if they'd prefer to continue and hope an endpoint comes back.

**Comment by adriancole** [comment]
works for me!

**Comment by anuraaga** [comment]
#2074 should address the underlying concern so closing this out
