### ISSUE TITLE
What is the channel object I'm supposed to pass to Stub class

### ISSUE THREAD

**Issue by anirudhr95** [line/armeria#2084]
I had raised a few other issues, but I think this is related to none of them (I might be wrong of course). I am trying a few other ways to get this to work for now.

Starting with my proto files:

```
syntax = "proto3";

package queue;

option java_package = "com.sink.queue";
option java_outer_classname = "queue";
option java_multiple_files = true;
option optimize_for = SPEED;

/*
    * Assuming Producer Response can be 1 file or more (In byte format)
*/

message ResponseFromQueueSource {
    repeated bytes file = 1;
}

message RequestFromSink {

}

service GetMessageFromQueue {
    rpc getItem(RequestFromSink) returns (stream ResponseFromQueueSource) {}
}
```

I tried hitting the endpoint with bloomRPC and it works great. Proof: 
<img width="703" alt="Screenshot 2019-09-17 at 9 41 27 PM" src="https://user-images.githubusercontent.com/2638126/65059651-009a2500-d994-11e9-8129-ca09785c74dc.png">

I am stuck here at this point - 
```
			new GetMessageFromQueueStub().getItem(RequestFromSink.newBuilder().build(),
					new StreamObserver<ResponseFromQueueSource>() {

						@Override
						public void onNext(ResponseFromQueueSource value) {
							log.info("Got resposne - {}", value);
						}

						@Override
						public void onError(Throwable t) {
							// TODO Auto-generated method stub

						}

						@Override
						public void onCompleted() {
							// TODO Auto-generated method stub
							log.info("Done");
						}
				
						
				
					});
```
If this run, it is AOK. However, the GetMessageFromQueueStub requires a Channel object as parameter.

```
  public static final class GetMessageFromQueueStub extends io.grpc.stub.AbstractStub<GetMessageFromQueueStub> {
    private GetMessageFromQueueStub(io.grpc.Channel channel) {
      super(channel);
    }

    private GetMessageFromQueueStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected GetMessageFromQueueStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new GetMessageFromQueueStub(channel, callOptions);
    }

    /**
     */
    public void getItem(com.sink.queue.RequestFromSink request,
        io.grpc.stub.StreamObserver<com.sink.queue.ResponseFromQueueSource> responseObserver) {
      asyncServerStreamingCall(
          getChannel().newCall(getGetItemMethod(), getCallOptions()), request, responseObserver);
    }
  }
```

I have no idea what this channel object I can pass to it might be. I saw the gRPC doc for Java - https://grpc.io/docs/tutorials/basic/java/ and it looks like the client object?  This is the example given. If I can figure out what the client is - maybe I can get something working.
```

public RouteGuideClient(String host, int port) {
  this(ManagedChannelBuilder.forAddress(host, port).usePlaintext());
}

/** Construct client for accessing RouteGuide server using the existing channel. */
public RouteGuideClient(ManagedChannelBuilder<?> channelBuilder) {
  channel = channelBuilder.build();
  blockingStub = RouteGuideGrpc.newBlockingStub(channel);
  asyncStub = RouteGuideGrpc.newStub(channel);
}
```

Or if I don't need it, I hope you can tell me that too :)

Sorry about the incessant queries. Besides the fix you have suggested (which is already merged to master i.e), I want to make sure I don't miss anything major so that I can get this to work.

**Comment by anuraaga** [comment]
It's probably a good idea to read through our docs which also document how to create the stub.

http://line.github.io/armeria/client-grpc.html

Basically you just need to use either `Clients` or `ClientBuilder` and don't need to worry about channels.
