### ISSUE TITLE
Make it possible to decorate clients and servers at URL context

### ISSUE THREAD

**Issue by adriancole** [line/armeria#2089]
Currently, the parts needed to resolve an http URL come from different objects at different availabilities, notably not yet accessible when constructing a decorating service. This makes it complicated, and difficult to do things such as request sampling.

For example, to get a client URL requires the following logic and availabilities:
* RequestLogAvailability.SCHEME
* RequestLogAvailability.REQUEST_HEADERS

```java
    public static String generateUrl(RequestLog requestLog) {
        if (!requestLog.isAvailable(RequestLogAvailability.SCHEME) ||
            !requestLog.isAvailable(RequestLogAvailability.REQUEST_HEADERS)) {
            return null;
        }
        final Scheme scheme = requestLog.scheme();
        final String authority = requestLog.authority();
        final String path = requestLog.path();
        final String query = requestLog.query();
        final SessionProtocol sessionProtocol = scheme.sessionProtocol();
        final String uriScheme;
        if (SessionProtocol.httpValues().contains(sessionProtocol)) {
            uriScheme = "http://";
        } else if (SessionProtocol.httpsValues().contains(sessionProtocol)) {
            uriScheme = "https://";
        } else {
            uriScheme = sessionProtocol.uriText() + "://";
        }

        final StringBuilder uriBuilder = new StringBuilder(
                uriScheme.length() + authority.length() + path.length() +
                (query != null ? query.length() + 1 : 0));

        uriBuilder.append(uriScheme)
                  .append(authority)
                  .append(path);

        if (query != null) {
            uriBuilder.append('?').append(query);
        }

        return uriBuilder.toString();
    }
```

I think decoration at a resolved http request abstraction is a better fit for things like metrics and tracing, and also notably can avoid accidental retries inside a decorator. For example, in OkHttp, there is a separate concept of network interceptor from application, where the former has access to network details more fundamentally required.

**Comment by trustin** [comment]
I think it's possible to get the request URI (as in Brave's `http.uri` tag) without much complexity. Let me try to send a PR for this soon.
