### ISSUE TITLE
Make it easier to work with absent values

### ISSUE THREAD

**Issue by adriancole** [line/armeria#2090]
One can imagine that it is not just less crufty, but more performant to be able to use data without sparkling guards around it. Notably, a large amount of code in brave parsers are defense around state conditions, sometimes checked multiple times, only to avoid throwing an exception.

My assumption is this an attempt to be like optional.get() in a lot of libraries which will make sure you die. It would be nice to have a non-death option which can return an "absent" value such as zero for a number.

See https://github.com/line/armeria/pull/2038#discussion_r326006242

**Comment by trustin** [comment]
I think it has been done via the recent `RequestLog` API update. Thanks for inspiration, @adriancole and @anuraaga
