### ISSUE TITLE
ServiceInvocationContext.current() return type

### ISSUE THREAD

**Issue by trustin** [line/armeria#21]
`ServiceInvocationContext.current()` currently returns `Optional<ServiceInvocationContext>`.

I find this inconvenient when I assume there's context available for the current thread:

    ServiceInvocationContext.current().get().eventLoop()...

Instead, we could make it just return `ServiceInvocationContext` and raise an exception when the context is not available.

However, in some cases, the caller does not want the exception raised. (See `HttpRemoteInvoker.eventLoop()`)

Perhaps we should:

- change the return type of `current()` and
- introduce an alternative method?

**Comment by trustin** [comment]
@inch772 @anuraaga PTAL

**Comment by anuraaga** [comment]
Yeah I agree that adding the .get() is a bit of a pain - an armeria server always has a context. I think changing to non-optional and raising a RuntimeException when it's not available is fine, in the rare cases where the exception may be raised, the caller can just check it - the code in HttpRemoteInvoker hardly changes between a null check and an exception check.

**Comment by trustin** [comment]
@anuraaga Instantiating an exception is expensive, though. We could pre-instantiate it with an empty stack trace, but I guess it's not a good idea.

**Comment by trustin** [comment]
Fixed by #25
