### ISSUE TITLE
`prefix` path mapping is overly strict.

### ISSUE THREAD

**Issue by trustin** [line/armeria#2116]
For example, if a user bound a service at `prefix:/docs`, the service
will get requests only when the request path starts with `/docs/`, which
means `/docs` will not be matched.

This is not a problem when there is no other mappings that match `/docs`
because Armeria will automatically redirect you to `/docs/`.

However, the following code will not work:

```java
// `/docs` will not be redirected to `/docs/` but handled by
// `HttpFileService`.
Server server =
    Server.builder()
          .service("prefix:/docs", new DocService())
          .service("prefix:/", HttpFileService.of(...))
          .build();
```

... because the `HttpFileService` will handle the request to `/docs`.

To address this issue, we need to introduce some special casing for the
path without a trailing slash.

However, the redirection should not occur when there's an explicit binding
for the path without a trailing slash:

```java
// `/docs` will not be redirected to `/docs/` but handled by
// `someOtherService`.
Server server =
    Server.builder()
          .service("prefix:/docs", new DocService())
          .service("/docs", someOtherService)
          .build();
```

**Comment by young891221** [comment]
I'll work on it!

**Comment by trustin** [comment]
@young891221 Thanks for your interest, but it seems like you showed your interest on another issue as well: https://github.com/line/armeria/issues/2117#issuecomment-535745866 It's be nice if you focus on one issue at the moment, so that other contributors have more choices. Which one would you choose?

**Comment by young891221** [comment]
I'm not `Good-First-Issue` target, so I'll choose this issue.
