### ISSUE TITLE
Version information in `DocService` index page is not sorted.

### ISSUE THREAD

**Issue by trustin** [line/armeria#2117]
Could be sorted for aesthetics' sake:

![image](https://user-images.githubusercontent.com/173918/65683043-44c5ad80-e097-11e9-8d59-17283fa0703f.png)

**Comment by young891221** [comment]
I'll work on it!

**Comment by rcsalome** [comment]
Hello. I have a quick fix for this. Will get a PR created. Thanks.

**Comment by beargummy** [comment]
Should this issue be closed?

**Comment by trustin** [comment]
Yes, indeed. Thanks for the heads up!
