### ISSUE TITLE
Override new `CompletableFuture` methods in Java 12 for `ContextAwareFuture`

### ISSUE THREAD

**Issue by trustin** [line/armeria#2119]
.. if we need to.

**Comment by ikhoon** [comment]
The following four methods were introduced with Java 12.
Please refer [Add exception handling methods to CompletionStage and CompletableFuture](https://bugs.openjdk.java.net/browse/JDK-8211010) for detail information.

The API spec:
* [default CompletionStage<T> exceptionallyAsync​(Function<Throwable,​? extends T> fn)](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/CompletionStage.html#exceptionallyAsync(java.util.function.Function))
* [default CompletionStage<T> exceptionallyAsync​(Function<Throwable,​? extends T> fn, Executor executor)](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/CompletionStage.html#exceptionallyAsync(java.util.function.Function,java.util.concurrent.Executor))
* [default CompletionStage<T> exceptionallyCompose​(Function<Throwable,​? extends CompletionStage<T>> fn)](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/CompletionStage.html#exceptionallyCompose(java.util.function.Function))
* [default CompletionStage<T> exceptionallyComposeAsync​(Function<Throwable,​? extends CompletionStage<T>> fn)](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/CompletionStage.html#exceptionallyComposeAsync(java.util.function.Function))
* [default CompletionStage<T> exceptionallyComposeAsync​(Function<Throwable,​? extends CompletionStage<T>> fn, Executor executor)](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/CompletionStage.html#exceptionallyComposeAsync(java.util.function.Function,java.util.concurrent.Executor))

`CompletableFuture` implements new methods using its own implementation.
https://github.com/openjdk/jdk/blob/2f2ec624a204cecb377d3033a489331d2b1fb3c0/src/java.base/share/classes/java/util/concurrent/CompletableFuture.java#L2364-L2388

https://github.com/openjdk/jdk/blob/2f2ec624a204cecb377d3033a489331d2b1fb3c0/src/java.base/share/classes/java/util/concurrent/CompletableFuture.java#L1056-L1080

I guess we have to override this. By the way, `CompletionStage` implements these methods using existing methods.

https://github.com/openjdk/jdk/blob/2f2ec624a204cecb377d3033a489331d2b1fb3c0/src/java.base/share/classes/java/util/concurrent/CompletionStage.java#L871-L877

I wonder why they override these methods.

**Comment by jatinAroraGit** [comment]
Hey there,
I can work on this.

**Comment by ikhoon** [comment]
@jatinAroraGit Thanks for your interest! 😀
A related issue on Java 9 is working. https://github.com/line/armeria/pull/2127
It uses [Multi-Release JAR Files](https://openjdk.java.net/jeps/238), so I think it would be nice working on this issue after merge that issue.

**Comment by trustin** [comment]
#2127 has been merged. Please begin your adventure, @jatinAroraGit!

**Comment by anuraaga** [comment]
I think we also need to change the compile JDK to Java 12 to go with the mrjar approach. Do you think it's ok?

I was going to possibily change it after https://github.com/line/armeria/pull/2126 which lays the groundwork for Java 12 on Travis

**Comment by trustin** [comment]
+1 for waiting for #2126. We could open a PR for this issue before #2126 is merged, merge it after #2126 is merged.

**Comment by kezhenxu94** [comment]
Years passed, I think @jatinAroraGit is not working on this anymore? Let me take over this

**Comment by ikhoon** [comment]
Sure, thanks in advance!
