### ISSUE TITLE
Naming of `Sampler.rateLimited(int)`

### ISSUE THREAD

**Issue by trustin** [line/armeria#2122]
I'm curious which is most natural:

- `Sampler.rateLimited(int samplesPerSecond)` (Current form)
- `Sampler.rateLimit(int samplesPerSecond)`
- `Sampler.rateLimiting(int samplesPerSecond)`

We also use `rate-limited` in specification strings, but I wonder which is most natural:

- `rate-limited=10` (Current form)
- `rate-limit=10`
- `rate-limiting=10`

I think the specification string should follow the factory method name for consistency, though.

**Comment by trustin** [comment]
Thoughts? @anuraaga, @ikhoon, @minwoox

**Comment by minwoox** [comment]
+1 for `rateLimiting`

**Comment by anuraaga** [comment]
`rateLimiting` seems good. A google search for "rate limited sampler" returns basically only results for "rate limiting sampler" :)

**Comment by ikhoon** [comment]
I googled too. 😀
https://en.m.wikipedia.org/wiki/Rate_limiting seems official expression like `Load Banlancing`.
