### ISSUE TITLE
Add `AbstractServerBuilder` for registering service and decorator 

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2133]
A service and a decorator are registered to default [virtual host](https://line.github.io/armeria/server-basics.html?highlight=virtual#virtual-hosts) with ServerBuilder.
Also, they are registered to a custom virtual host with VirtualHostBuilder.

* ServerBuilder
https://github.com/line/armeria/blob/9783253388f1818f982c7b4efc93ec9e97ebf68c/core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java#L997-L1004

* VirtualHostBuilder
https://github.com/line/armeria/blob/d741d9cbc300f2abf9fed8bd0457c15c76cdcd3c/core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java#L539-L547

After https://github.com/line/armeria/pull/2040 PR, we have a lot of duplication logic, so we need a new abstraction level to extract common logic. e.g.

```java
class ServerBuilder extends AbstractServerBuilder { ... }
class VirtualHostBuilder extends AbstractServerBuilder { ... }
```

Maybe we need a good idea for the builder's name than `AbstractServerBuilder`.

**Comment by trustin** [comment]
I guess we fixed this issue somehow. Let me close this for now, but please feel free to reopen it if you think there's something more left. @ikhoon

**Comment by ikhoon** [comment]
Thank you for reminding me. I also think this issue has been resolved. 👍
