### ISSUE TITLE
Raise build JDK requirement to Java 12

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2141]
We now have travis infrastructure for installing multiple JDKs, including ones not officially suported by travis. This opens up the possibility of raising our minimum JDK version to build Armeria to Java 12. This makes it simpler to work on supporting newer APIs like in #2119 

Shall we raise the requirement?

**Comment by trustin** [comment]
Sure. Why not? I'm also fine with jumping up to 13.

**Comment by anuraaga** [comment]
Me too but not Gradle until 6.0 ;)
