### ISSUE TITLE
Allow customizing DocService when using Spring Boot integration

### ISSUE THREAD

**Issue by trustin** [line/armeria#2185]
I don't remember exactly where, but someone asked if it's possible to add an example via DocServiceBuilder when using Spring Boot integration.

It is currently not possible because ArmeriaAutoConfiguration currently builds a DocService by itself without exposing any customization point.

We could allow a user to inject a Consumer or Supplier of DocServiceBuilder so that the user can customize the DocService built by ArmeriaAutoConfiguration, and thus it's not necessary to to use registration beans.

Adding good-first-issue label since it should be fairly easy for anyone who's familiar with Spring's dependency injection mechanism.

**Comment by yanghun0070** [comment]
If there is no working person, I want to work.

**Comment by trustin** [comment]
Fixed via #2327 by @Charliocat. Thanks again for reporting the problem.
