### ISSUE TITLE
About example pom file in manual site

### ISSUE THREAD

**Issue by not-for-me** [line/armeria#219]
HI, all
I'm submitting the issue about sample pom file in the official site.

In the pom file on the site, the *argLine.alpnAgent* option use *jetty.alpnAgent.option*
but, there is no property value of  *jetty.alpnAgent.option*.

Therefore, I just remove that part from my pom file and compile the source, it works normally.
Is it right to remove  *jetty.alpnAgent.option* property?

Here is the part of that code.

```xml
<properties>
   <!-- ... -->
    <!-- Dependency versions -->
    <armeria.version>0.21.2.Final</armeria.version>
    <logback.version>1.1.7</logback.version>
    <slf4j.version>1.7.21</slf4j.version>
    <tomcat.version>8.5.4</tomcat.version>
    <jetty.alpnAgent.version>2.0.4</jetty.alpnAgent.version>
    <jetty.alpnAgent.path>${settings.localRepository}/org/mortbay/jetty/alpn/jetty-alpn-agent/${jetty.alpnAgent.version}/jetty-alpn-agent-${jetty.alpnAgent.version}.jar</jetty.alpnAgent.path>
    <argLine.alpnAgent>-javaagent:${jetty.alpnAgent.path}=${jetty.alpnAgent.option}</argLine.alpnAgent>
  </properties>

```

Thanks in Advance.

**Comment by trustin** [comment]
You are correct. Let me update the documentation soon. Currently filling the holes in the documentation.

**Comment by trustin** [comment]
Fixed :-)
