### ISSUE TITLE
investigate virtualhost.defaultHostname

### ISSUE THREAD

**Issue by adriancole** [line/armeria#2202]
As far as poking around can tell, `SystemInfo.hostname()` is invoked only to satisfy when http2 is in use and a client or server didn't set the authority/hostname key. At the moment, this literally invokes a shell command, slowing server startup, by default.

Ex.
```
2019-10-21 20:48:57:164 [main] INFO SystemInfo - Hostname: macbook-pro-8.local (from 'hostname' command)
```

Somewhat similar to #2184, I wonder if this could be revisited, if it is pulling its weight, or if it could be safe to defer if it is.

**Comment by adriancole** [comment]
unscientifically (setting the defaultHostname explicitly and banging restarts), this brings best ever time down up to 20ms or so of the 500-600ms in armeria related startup.

```
2019-10-21 21:40:04:126 [main] INFO ZipkinServer - Started ZipkinServer in 1.495 seconds (JVM running for 1.876)
```

Total time in spring seems to be 1/3 (500-600ms) Armeria, and actually in our slim build we are not affected by #2184 as we hit a CNFE before it gets too expensive.

**Comment by adriancole** [comment]
PS "1/3 (500-600ms) Armeria" isn't to say it is spending too much time, almost all of our slim server is armeria. It is an interesting idea to see if zipkin slim could get to 1s, but in this case unless armeria can produce negative startup time, reducing here is not enough.

**Comment by trustin** [comment]
In Linux, `SystemInfo.hostname()` does not use the `hostname` command, so I think it will be OK in production? :sweat_smile: I tried to look for a way to get the current hostname reliably in OS X but it seems impossible without JNI. Let me know if you have a better idea on this.

**Comment by adriancole** [comment]
basically, I would suggest deferring this, so that unless an accurate hostname is required, no forks. Not sure how often accurate hostnames are needed anyway in os/x :P

**Comment by trustin** [comment]
Agreed. It is currently loaded when a new `Server` is built, but I guess we can defer it.

**Comment by anuraaga** [comment]
While looking at Gradle release notes, I randomly found out that our hostname is the fastest possible hostname on Mac OS X apparently - did we know we were doing that? ;)

https://github.com/gradle/gradle/pull/11134/files

Also noticed that our hostname is already computed lazily (it's a singleton in an inner class) so users can set the `defaultHostName` which should prevent it from running at all. If I'm not missing anything, let's go ahead and close this issue.

**Comment by trustin** [comment]
Nice finding! Let me close it then. :laughing:
