### ISSUE TITLE
Typo of an example on line.github.io

### ISSUE THREAD

**Issue by ylgrgyq** [line/armeria#2204]
Hi folks,

Thanks for this great lib.

This is an issue about a typo on the web site: https://line.github.io/armeria. I scanned all the repositories [here](https://github.com/line) but failed to find the repository for https://line.github.io/armeria. So I leave this issue here. If this is an inappropriate place, please let me know and I will happily move this issue to the right place even taking a PR. Thanks.

At [this page](https://line.github.io/armeria/advanced-production-checklist.html), there are some socket options to tune for production. The example is :
```java
// Server-side
ServerBuilder sb = Server.builder();
sb.channelOption(ChannelOption.SO_BACKLOG, ...);
sb.channelOption(ChannelOption.SO_SNDBUF, ...);
sb.channelOption(ChannelOption.SO_RCVBUF, ...);
```

But the `ChannelOption.SO_SNDBUF` option is for `sb.childChannelOption()` instead of `sb.channelOption()`. Otherwise, there's a warning log will show, like:

```
xx:xx:xx WARN  io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_SNDBUF' for channel '[id: xxxxxxx]'
```

**Comment by minwoox** [comment]
Yes, this is the right place. Thanks a lot, @ylgrgyq! Let me send a fix soon.!

**Comment by minwoox** [comment]
>  I will happily move this issue to the right place even taking a PR.

@ylgrgyq, I'm really sorry that I missed this comment. 😢 
We really appreciate that you found this and hope to see your PR next time. 😅

**Comment by ylgrgyq** [comment]
No worries my friend. It's good to see this fixed so soon.
Hope you have a good day! :grinning:
