### ISSUE TITLE
Accept URIs without `none+` and return URIs without `none+`

### ISSUE THREAD

**Issue by trustin** [line/armeria#2219]
I see usability issues with `none+` prefix in URI scheme:

- A user must specify a URL that starts with `none+` to create an `HttpClient` with a `ClientBuilder`.
  - We could assume `none+` exists when a user did not prepend it.
  - It becomes a little bit more ambiguous, I think it will not be that confusing. It's like removing 0 from 0.1 (= .1).
- `HttpClient.uri()` returns a URI that starts with `none+`, which is somewhat confusing. For example, a user cannot convert the returned URI into a URL:
  ```java
  HttpClient client = ...;
  client.uri().toURL(); // Fail
  ```

I'd like to:

- Make the `none+` prefix optional when creating a client.
- Make `ClientBuildParams.uri()` return a URI without the `none+` prefix.

**Comment by anuraaga** [comment]
Can't remember the discussion ;) I think allowing URL without `none+` for `ClientBuilder` makes sense, but I'd suggest `uri()` returns what the user entered, so including `none+` if they had it themselves. Losing user information seems weird to me.

**Comment by trustin** [comment]
> Losing user information seems weird to me.

I'm not sure I like this idea because the caller of `uri()` might not always be who created the client and might expect a consistent return value for the both cases (with/without `none+`).

**Comment by anuraaga** [comment]
Hmm that's true - in that case how about we add  `serializationFormat()` and `sessionProtocol()` (less important) to `ClientBuilderParams` and change `uri()` to never return `*+` even for non-http clients? That allows the pieces of information to be easily available and is the most consistent, so `.uri().toURL()` will always work.

I'm also a littler concerned about the `ClientBuilder` API after this change - I think I'd expect this to work

```java
new ClientBuilder("http://github.com")
  .serializationFormat(SerializationFormat.PROTO)
  .build(...)
```

Should we also make a change to allow that?

**Comment by trustin** [comment]
What if a user wants a URL with serfmt? Should we add a method like fullUri()?

**Comment by anuraaga** [comment]
I guess that seems like overkill - it seems fine to me then for `uri()` to return a `+` or not based on serialization format as proposed.

**Comment by rmohta** [comment]
@trustin Would like to work on this. 
In your description you have mentioned, 

> ClientBuildParams.uri() return a URI without the none+ prefix.

Is it to be done only for `none` SerializationFormat, or for all?
And if it's only for `none`, I am assuming it does not matter if it's armeria defaulting to none or client provided URI has none in serialization format?

I am assuming, you would like as mentioned in below tests?
```
    @Test
    public void nonePlusSchemePassed() {
        final HttpClient client = new ClientBuilder("none+https://google.com/").build(HttpClient.class);
        assertThat(client.uri().toString()).isEqualTo("https://google.com/");
    }

    @Test
    public void noSchemeShouldDefaultToNone() {
        final HttpClient client = new ClientBuilder("https://google.com/").build(HttpClient.class);
        assertThat(client.uri().toString()).isEqualTo("https://google.com/");
    } 
```

**Comment by ikhoon** [comment]
@rmohta Thanks for your interest. 

> Is it to be done only for none SerializationFormat, or for all?

IIRC, We have decided to apply only for `none`. 

>  I am assuming, you would like as mentioned in below tests?

That’s right! It would be a great. 

By the way, our HTTP client don't accept URL.
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/HttpClient.java#L229

 If we choose this policy, I guess creating an HTTP client from URL is more natural. 

```java
HttpClient client1 =...
URL url = client1.uri().toURL();
HttpClient client2 = HttpClient.builder(url)...build()
```

@trustin @minwoox WDYT?
