### ISSUE TITLE
Allow setting a slf4j logger for use by LoggingClient/Service

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2220]
Currently, we log to a static `Logger` for client and a deprecated request-specific one for server. We should keep this as the default but it would be nice to be able to set a `Logger` in the builder to allow writing unit tests for logs. This is especially important for testing sanitization logic.

**Comment by monorisk** [comment]
I would like to solve this!

**Comment by trustin** [comment]
@monorisk It's all yours now. :bowing_man:
