### ISSUE TITLE
Provide a way to invoke Thrift `*.AsyncIface` implementations via `blockingTaskExecutor`.

### ISSUE THREAD

**Issue by trustin** [line/armeria#2223]
We need something similar to `GrpcServiceBuilder.useBlockingTaskExecutor()` in Thrift, e.g. `THttpService.builder().useBlockingTaskExecutor(...).build()`.

/cc @delegacy

**Comment by delegacy** [comment]
Will prepare a PR soon.

**Comment by delegacy** [comment]
Sorry for a really long consideration, but... 😅 

 I'm thinking this does not introduce any advantage because normally users must implement `AsyncIface` in an asynchronous way. I feel like this feature just allows users to make mistakes. (blocking implementation in AsyncIface)

Any thought?

**Comment by anuraaga** [comment]
Agree that unlike gRPC thrift doesn't really need it since there are two types of interface classes.

**Comment by trustin** [comment]
Let me close this issue, then. Please feel free to create a new issue if the situation has changed.
