### ISSUE TITLE
Support OAuth2

### ISSUE THREAD

**Issue by iamazy** [line/armeria#2268]
Does armeria has any plan to support oauth2?

**Comment by trustin** [comment]
Hi @iamazy!

> Does armeria has any plan to support oauth2?

Why not? We want to implement the features useful to our users and there just wasn't a request for OAuth 2 support yet. Now we have one. :wink: 

We might not have enough time for implement OAuth 2 by ourselves this year, but we're happy to accept any pull requests, if you are interested.

**Comment by iamazy** [comment]
I'll work on it

**Comment by trustin** [comment]
@iamazy Just in case, is it just about checking the access token in the `Authorization` header? If that's the case, we have that feature already. Please see:

- [`HttpAuthService`](https://line.github.io/armeria/apidocs/com/linecorp/armeria/server/auth/HttpAuthService.html)
  - Can decorate other service to add authentication.
  - Built using `HttpAuthServiceBuilder`
- [`HttpAuthServiceBuilder`](https://line.github.io/armeria/apidocs/com/linecorp/armeria/server/auth/HttpAuthServiceBuilder.html)
  - Could use `addOauth2()`.

Or do you expect something more than this?

**Comment by iamazy** [comment]
It seems to meet my needs，thanks

**Comment by iamazy** [comment]
I tried the `HttpAuthService` and It works, But I don't think it can dynamic authenticate user who has authority to access the api according to given token，I need to extract authorities from token

**Comment by iamazy** [comment]
Does armaria has security framework like `spring security`?

**Comment by max904-github** [comment]
FYI, I have integrated ScribeJava OAuth framework with Armeria client. You can find it at https://github.com/max904-github/scribejava .
As OAuth 2 becomes more and more common for the enterprises (e.g. 5G core network), it would be nice to have end-to-end token management integrated directly into Armeria. Communications to OAuth server could be delegated to a third-party like ScibeJava, or could be implemented in Armeria as well.

**Comment by trustin** [comment]
@max904-github That sounds awesome. It'd be really cool if we have `armeria-scribejava` in our repository. Are you interested in working on this?

**Comment by trustin** [comment]
> Does armaria has security framework like `spring security`?

No. We hope to provide modules that integrate with well established security frameworks, though. Spring Security could be one of them, if we can use it without pulling in too much transitive dependencies.

**Comment by max904-github** [comment]
@trustin Sure. I can contribute. Let me advance further on my OAuth related project and I will try to come up with some proposal for Armeria integration.

**Comment by trustin** [comment]
Thanks a lot in advance, @max904-github. Please feel free to let us know if you encounter any issues while working on it. :bowing_man:

**Comment by trustin** [comment]
Thanks for closing, @iamazy. Did you have a chance to play with `armeria-oauth2`?

**Comment by iamazy** [comment]
> Thanks for closing, @iamazy. Did you have a chance to play with `armeria-oauth2`?

Yes, I'm willing to try it

**Comment by trustin** [comment]
@iamazy Looking forward to your feed back, then. :crossed_fingers:
