### ISSUE TITLE
Consider renaming RichPublisher

### ISSUE THREAD

**Issue by trustin** [line/armeria#227]
The name `RichPublisher` gives a user in impression that it is just a `Publisher` with some extra bells and whistles. However, it is actually a special variant of `Publisher`:

- It never repeats the stream like a cold `Publisher` can. It's gone once consumed.
- There's no point of subscribing in the middle of stream. i.e. there's no point of having more than one `Subscriber`.

To avoid the chance the name `RichPublisher` misleads users, I think we'd better rename it to something that reflects its nature better. Thoughts?

- `StreamingPublisher`
- `UnrepeatablePublisher`
- `Stream`
- `???Stream`
- `StreamedMessage`, `StreamMessage`, `StreamingMessage`

**Comment by blmarket** [comment]
-1 for `Stream` candidates as there is already stream in JDK

**Comment by trustin** [comment]
I'm leaning toward `StreamedMessage`. Please let me know if you have something in your mind. :-)

**Comment by anuraaga** [comment]
SGTM

**Comment by trustin** [comment]
Closed by #229
