### ISSUE TITLE
what happen in 0.96.0 ?

### ISSUE THREAD

**Issue by RyouZhang** [line/armeria#2270]
update to 0.96.0, I got a execepion:

classMethod FAILED
    java.lang.NoSuchMethodError: com.linecorp.armeria.server.grpc.GrpcServiceBuilder.build()Lcom/linecorp/armeria/server/ServiceWithRoutes;

**Comment by trustin** [comment]
Hi @RyouZhang. Sorry for the problem. We have some breaking changes in 0.96 which I will write write about in the release note soon.

**Comment by trustin** [comment]
The release note has been published. Please let me know if you have any issues while upgrading. :bowing_man: https://github.com/line/armeria/releases/tag/armeria-0.96.0
