### ISSUE TITLE
API inconsistency for creating request with new headers

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2278]
Currently, we have many factories in `HttpRequest` that take headers as the first parameter

```java
HttpRequest.of(RequestHeaders, HttpData...)
HttpRequest.of(RequestHeaders headers, Publisher<? extends HttpObject> publisher)
```

However updating a request, it's with a second parameter

```java
HttpRequest of(HttpRequest request, RequestHeaders newHeaders)
```

This seems inconsistent to me (error prone's default checks wouldn't allow this either I believe there might be an effective java entry about inconsistent overrides). However, much worse than that is that both methods compile for an `HttpRequest`

```java
HttpRequest.of(newHeaders, oldRequest);  // Broken
HttpRequest.of(oldRequest, newHeaders);
```

The first results in an object that returns `newHeaders` from the `headers()` method but publishes old headers. If I'm not mistaken, this wouldn't actually work.

I propose

- Remove HttpRequest of(RequestHeaders headers, Publisher<? extends HttpObject> publisher) since it seems like a low value-add API which is very hard to reason about since the publisher may publish headers. If keeping it, it could be changed to `Publisher<HttpData>` which satisfies the current single usage in the Armeria codebase, but that leaves an issue of trailing headers. I think using `Publisher` is advanced enough that expecting users to filter it could be enough

- Remove HttpRequest of(HttpRequest request, RequestHeaders newHeaders) and add `HttpRequest.withHeaders()`. I'm guessing the reason the argument order is inconsistent is the behavior is a little different, overriding instead of creating a new request. We could sidestep the confusion by moving it into an instance method.

**Comment by trustin** [comment]
> Remove `HttpRequest of(RequestHeaders headers, Publisher<? extends HttpObject> publisher)`. If keeping it, it could be changed to `Publisher<HttpData>`.

Hmm.. I'm not sure if removing this method help usability or if it's a good idea to disallow sending trailers. How about just renaming to `from()`?

> Remove HttpRequest of(HttpRequest request, RequestHeaders newHeaders) and add HttpRequest.withHeaders()

+1

**Comment by anuraaga** [comment]
I don't know if renaming helps so much - even then if the second parameter is an `HttpRequest`, it doesn't really work right. So I find it's too hard to use the API correctly, and don't know if it satisfies any general use case.

**Comment by trustin** [comment]
It's currently being used in some places like converting `Flux<>` into `HttpRequest/Response`, so I guess we can't just remove it but move it somewhere. Any suggestions?

**Comment by anuraaga** [comment]
I couldn't find a usage with `HttpResponse` (at least not one that overrides headers like this one). The usage for `HttpRequest` literally filters to `HttpData` - perhaps the best evidence that it's appropriate to just change to `of(RequestHeaders, Publisher<? extends HttpData>`?

`return doCommit(execute(() -> HttpRequest.of(headers.build(), body.map(factoryWrapper::toHttpData))));`

**Comment by trustin** [comment]
I'm not sure it's a good idea to change the type parameter from `HttpObject` to `HttpData`. It just happens to work for WebFlux and it may not for some other integration cases.

How about just changing the parameter order of `of(HttpRequest, RequestHeaders)` to `of(RequestHeaders, HttpRequest)` and add some `instanceof` check to `of(RequestHeaders, Publisher)`?

**Comment by trustin** [comment]
i.e.

```java
of(RequestHeaders newHeaders, Publisher<...> publisher) {
    if (publisher instanceof HttpRequest) {
        return of(newHeaders, (HttpRequest) publisher);
    } else { ... }
}

@Deprecated
of(HttpRequest request, RequestHeaders newHeaders) {
    return of(newHeaders, request);
}

of(RequestHeaders newHeaders, HttpRequest request) { ... }
```

**Comment by trustin** [comment]
Once the deprecated `of()` is removed, the reported ambiguity would be gone.

**Comment by trustin** [comment]
On the other hand, I like the idea of replacing `of(HttpRequest request, RequestHeaders newHeaders)` with `HttpRequest.withHeaders()`, which would remove the necessity of `of(RequestHeaders newHeaders, HttpRequest request)`, but maybe it doesn't harm to keep it given it can be paired with `of(RequestHeaders, Publisher)`? :thinking:

**Comment by trustin** [comment]
It also makes me think we can deprecate/remove `HttpRequest.of(AggregatedHttpRequest)` and add `AggregatedHttpRequest.toHttpRequest()` (and same for `HttpResponse`). What do you think?

**Comment by anuraaga** [comment]
I like the idea of using `to**` like that.

I'm still not convinced about `Publisher` - I point out the Flux example since it seems to be the only way to reliably use the API right now. If the `Publisher` happened to publish request headers, it seems like it would be broken with very vague behavior. Should `PublisherBasedHttpRequest` be filtering the published outputs to filter out `RequestHeaders`?

**Comment by trustin** [comment]
Sent #2283 to address this issue to some extent.
