### ISSUE TITLE
How does one configure a PROXY to use for HTTP(S) clients?

### ISSUE THREAD

**Issue by slyphon** [line/armeria#2320]
I'm sorry if this is covered in the documentation already, I've spent about an hour looking through the source and docs and can't figure out how to do this. There are examples for how to make a service that acts as a proxy, but not how to configure a client to use a proxy (as far as I can tell).

I'm using a library that's in turn using armeria to talk to google cloud services using gRPC. At my company, we use an "egress proxy" in production. With curl we can use the `http_proxy` environment variable to set the proxy address and credentials. I'm trying to figure out how to do something similar (i.e. figure out where to configure this) if the library I'm using gives me the ability to supply `com.linecorp.armeria.client.ClientFactory` and `com.linecorp.armeria.client.ClientOptions` to its constructor.

I was expecting something on either `ClientFactoryBuilder` or in `ClientOptionsBuilder` that would let me specify the proxy to use when making connections. I see that there's `proxy` mentioned in the `SessionProtocol` enum, but I can't figure out how to combine these things together.

Any help would be appreciated.

Thanks!

**Comment by minwoox** [comment]
Thank you for trying with Armeria!
I'm afraid to tell you that we don't support the proxy protocol on the client-side. We just made the server-side compatible with the proxy protocol.

I think it's not hard to implement it if we make it only work on HTTP protocol (not protocol-agnostic) but there was no demand for that. So we didn't implement it yet but we might work on this after we release 1.0. 😄 

Using `Forwarded` and `X-Forwarded-For` headers are the only way to relay the address of the original client at the moment with Armeria. 😢

**Comment by slyphon** [comment]
OK! That may be why i couldn't find it! Now I don't feel so dumb :)

**Comment by trustin** [comment]
Created an issue for you - https://github.com/line/armeria/issues/2321

**Comment by slyphon** [comment]
Cheers!

**Comment by trustin** [comment]
On, and *HI* from an ex-tweep! Happy to see an interest from there. :heart:

**Comment by slyphon** [comment]
Glad to see you're doing great things! :D

**Comment by trustin** [comment]
We have added support for SOCKS4/5 and HTTP CONNECT, but we don't have PROXY support yet. Created a dedicated issue for it since #2321 has been closed: https://github.com/line/armeria/issues/2589
