### ISSUE TITLE
Client-side proxy support

### ISSUE THREAD

**Issue by trustin** [line/armeria#2321]
Related: #2320 

We could add support for various proxy protocols to our clients:

- HTTP CONNECT method
- SOCKS
- HAProxy
- Different from the above 3, but usual HTTP proxies

**Comment by trustin** [comment]
@jrhee17 What about this issue? You asked me about a client-side issue that would help you understand client-side internals and thus might be it.

**Comment by kojilin** [comment]
Curious about this issue, so we just need to add proxy option in ClientFactoyOption and add ProxyHandler here https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java#L102 ?

**Comment by jrhee17** [comment]
btw feel free to work on this issue if you need to use it 😄 I think I will need at least a month to start this issue if I tackle it

**Comment by trustin** [comment]
@kojilin I guess so, although I didn't try it by myself. :smile:

**Comment by jrhee17** [comment]
@kojilin did you want to work on this? 👀  I think I can start working on this if not.

**Comment by kojilin** [comment]
@jrhee17 oh, no problem :)

**Comment by kojilin** [comment]
To avoid confusing, yes, you can work on this issue.

**Comment by jrhee17** [comment]
Thanks! 🙇👍😄

**Comment by trustin** [comment]
Created a follow-up issue: https://github.com/line/armeria/issues/2589
