### ISSUE TITLE
Cannot stop server with gRPC service in 0.97

### ISSUE THREAD

**Issue by andrey-tpt** [line/armeria#2324]
Hi guys,

Could be red herring but I was playing with Armeria 0.97 a bit (like it was recommended in https://github.com/line/armeria/issues/2319). It looks like that that I can't stop a server with single gRPC service, line (1) from the code below never returns. 

```java
ServerBuilder sb = new ServerBuilder();
    Server server =
        sb.service(new GrpcServiceBuilder().addService(new PingService()).build())
            .port(1234, SessionProtocol.HTTP).build();

    CompletableFuture startFuture = server.start();
    startFuture.join();

    CompletableFuture stopFuture = server.stop();
    stopFuture.join(); //  (1)
```

The same code worked fine in 0.88. 

Sincerely,
Andrey

PS. The test is executed from IntelliJ Idea 2019.2 on openjdk 12.0.2+10

**Comment by ikhoon** [comment]
@andrey-tpt It is weird... I have tested this in my local environment, and it stopped normally.
My test environments:
* Java: OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
* IntelliJ: 2019.2
* Armeria versions: 0.97.0 and current master branch

**Comment by andrey-tpt** [comment]
> Could you give us more information about your environment?

@ikhoon Absolutely. What else can I share?

**Comment by ikhoon** [comment]
I'm not sure, but...
* Test result from the clean build.
* Test result from the command line execution.
* Your Operating System.
* warn or error stack trace?

**Comment by ikhoon** [comment]
+ Could you share your code on GitHub to reproduce?

**Comment by andrey-tpt** [comment]
After some tests it looks like that minor version of Netty makes all the difference

- Armeria 0.88 works fine with both 4.1.42.Final and 4.1.43.Final. 

- Armeria 0.97 works with 4.1.43.Final but for some reason I can't stop server on 4.1.42.Final. "Luckily" my 
project is on 4.1.42.Final. 

Can you try this?

**Comment by ikhoon** [comment]
> Armeria 0.97 works with 4.1.43.Final but for some reason I can't stop server on 4.1.42.Final and below (4.1.41.Final doesn't work as well). "Luckily" my project is on 4.1.42.Final.

Oh, thanks for the investigation! 🙇‍♂️ I think we need this discussion on how to handle the compatibility program.
Let us talk about next week.

**Comment by ikhoon** [comment]
I've tested Armeria 0.97.0 gRPC server with Netty 4.1.42.Final. It stopped normally. 🤔

**Comment by ikhoon** [comment]
Let me close this issue. If you have a problem with stopping a server, feel free to reopen this.
