### ISSUE TITLE
SessionProtocolNegotiationException when HTTP/2 is enforced

### ISSUE THREAD

**Issue by andrey-tpt** [line/armeria#2325]
Hi guys,

I tried to run 4 cases on the same private key and certificate - just a basic ping request / response over TLS.  Test setup is also straightforward - create client and server and then call remote 'ping' method in the loop 10*1000 times. 

1. Bare gRPC / Netty client and server takes ~ 1ms on average locally
2. Bare gRPC / Netty server with Armeria client (h2 protocol) also takes ~ 1ms on average locally
3. Armeria server with Armeria client (https protocol) takes ~ 3ms on average locally and 8ms in AWS us-east-1 - unacceptable performance for my case. I guess this is because the communication protocol is downgraded to h1. 
4. Armeria server with Armeria client (h2 protocol) fails with "SessionProtocolNegotiationException: expected: h2, actual: h1, reason: unexpected protocol negotiation result"  

Find it really surprising that Armeria can't talk to Armeria when H2 is enforced but Armeria client works fine with gRPC server and gives reasonable latency (2nd case). 

The server is configured like below: 

```java
 byte[] certPem = Files.readAllBytes(new File("/tmp/cert.pem").toPath());
 byte[] privPem = Files.readAllBytes(new File("/tmp/key.pem").toPath());
 ServerBuilder serverBuilder  =  Server.builder()
          .service(new GrpcServiceBuilder().addService(new PingService()).build());
 try (InputStream cert = new ByteArrayInputStream(certPem);
        InputStream priv = new ByteArrayInputStream(privPem))
 {
      serverBuilder = serverBuilder   
          .https(port)
          .tls(SslContextBuilder.forServer(cert, priv).build());
 }
 return serverBuilder.build();
```

Dependencies closure:
 - Armeria - 0.97
 - gRPC - 1.25
 - Netty - 4.1.43.Final
 - netty-tcnative-boringssl-static - 2.0.26.Final 

Sincerely,
Andrey

PS. Sorry for raising few issues recently - really like Armeria's model and want to use it in my projects.

**Comment by trustin** [comment]
> Sorry for raising few issues recently - really like Armeria's model and want to use it in my projects.

No worries, @andrey-tpt! We appreciate your issue reports and hope to fix them on time. :smile: 

> `.tls(SslContextBuilder.forServer(cert, priv).build())`

SSL context needs to be configured properly to make it functional in HTTP/2. `ServerBuilder.tls(SslContext)` is actually an advanced-user-only method, but we forgot to mention that properly. `ServerBuilder` also currently lacks the methods like `tls(InputStream, InputStream)` as you noticed. Let us fix this soon.

Meanwhile, as a workaround, could you try this:

```java
SslContext sslCtx = SslContextUtil.createSslContext(
        () -> SslContextBuilder.forServer(cert, priv),
        false /* forceHttp1 */,
        builder -> {});
serverBuilder.tls(sslCtx);
```

`SslContextUtil` is an internal class which is used for configuring an `SslContext` for HTTP/2.

**Comment by andrey-tpt** [comment]
Thank you very much, @trustin 🙇‍♂, this helped. Moreover the time to process ping requests is 1.5x lower compared to gRPC - this is very pleasant to see 👍 

I think one part of the problem is my assumption that SslContext can be constructed in the same way as with gRPC via SslContextBuilder. On the other hand, there's no mention of SslContextUtil on the wesbite and in any test class outside of SslContextUtilTest so it's relatively hard to discover even though the class appears to be very useful.

**Comment by trustin** [comment]
Nice! It's natural that `SslContextUtil` is not discoverable, because it's part of internal API. Let me try to fix this properly so you don't have to use it next time.
