### ISSUE TITLE
Migrate all tests in the examples to JUnit 5

### ISSUE THREAD

**Issue by trustin** [line/armeria#2346]
The `spring-boot-minimal-kotlin` example started using JUnit 5, but our example conversion script still uses JUnit 5. It'd be nice to migrate all examples to JUnit 5 for consistency.

**Comment by heowc** [comment]
Can I do it? 

In addition, I thought that after creating `spring-boot-minimal-kotlin`, it would be fine to remove [the checkstyle configuration](https://github.com/line/armeria/blob/master/examples/spring-boot-minimal-kotlin/build.gradle.kts#L36...L43).
