### ISSUE TITLE
Add gRPC reverse proxy server example

### ISSUE THREAD

**Issue by trustin** [line/armeria#2353]
.. which is similar to our HTTP reverse proxy server example.

**Comment by anuraaga** [comment]
@trustin Could you define more what a gRPC reverse proxy is? Would it just be a normal service implementation that delegates to another stub? In general, I make reverse proxies for gRPC services by using a normal HTTP reverse proxy.

**Comment by ikhoon** [comment]
It was originally requested in https://line-armeria.slack.com/archives/C1NGPBUH2/p1577719334033400

**Comment by anuraaga** [comment]
Thanks for the link! It does look like the original request was just for a normal HTTP proxy so maybe we already have the example, or it could be extended with rule matching.

For reference, here's an Armeria reverse proxy that allows simple path-based routing (perfect for gRPC) - https://github.com/curioswitch/curiostack/tree/master/gateway/server

**Comment by antongocode** [comment]
Apologies for commenting on a fairly old ticket, but where can I find the HTTP reverse proxy examples for armeria? This ticket is the top search result.

**Comment by ikhoon** [comment]
@antongocode You might want to see https://github.com/line/armeria-examples/blob/master/proxy-server/src/main/java/example/armeria/proxy/ProxyService.java

**Comment by roeniss** [comment]
Is there any work left to be done on this issue? As anuraaga said it's not obvious what reverse proxy for gprc is compared to normal one. To be more specific, I wonder why this issue got `good first issue` tag later.

**Comment by jrhee17** [comment]
I'm not sure what the original request was as the slack post seems to have expired.
Having said this, I think it could be meaningful if we can add an example of a `grpc-gateway` type reverse-proxy implementation using `armeria`'s grpc-json transcoding features.

**Comment by roeniss** [comment]
After half a year, I realize that I don't want to resolve this issue. Sorry for others who wanted to take this issue for such a delayed decision

**Comment by Bue-von-hon** [comment]
I'll create a PR for this issue until this weekend 🙂

**Comment by eottabom** [comment]
Is this issue valid?
Slack is expired and cannot be viewed.

What I understand is that the Reverse Proxy is located between the client and the gRPC server
I understand it as a role to forward client requests to the gRPC server and to forward server responses back to the client.

```
        List<Endpoint> backendServers = List.of(
                Endpoint.of("127.0.0.1", 50051),
                Endpoint.of("127.0.0.1", 50052)
        );


        GreeterGrpc.GreeterBlockingStub backendClient = GrpcClients.builder("gproto+http")
                .endpoints(backendServers)
                .build(GreeterGrpc.GreeterBlockingStub.class);


        GrpcService grpcService = GrpcService.builder()
                .addService(new GreeterGrpc.GreeterImplBase() {
                    @Override
                    public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver) {

                        HelloReply reply = backendClient.sayHello(req);
                        responseObserver.onNext(reply);
                        responseObserver.onCompleted();
                    }
                })
                .build();

        Server server = Server.builder()
                .http(8080)
                .service(grpcService)
                .decorator(LoggingService.newDecorator())
                .build();

        server.start().join();
```

Do you need an example like this?

**Comment by jrhee17** [comment]
>  I understand it as a role to forward client requests to the gRPC server and to forward server responses back to the client.

Right, but I actually think we don't even need the reverse proxy to understand gRPC and we could just proxy the HTTP requests/responses.

So gRPC client <-> HTTP proxy <-> gRPC server

> Is this issue valid?

Having taken another look at this issue, I think this could be more meaningful if we could add an integration test where a gRPC server with HTTP1 is behind an l7 envoy reverse proxy.

We could use `Testcontainers` in conjunction with envoy's `http_protocol_options.enable_trailers` to illustrate the configurations needed to configure an l7 proxy for armeria's gRPC over HTTP1.

**Comment by eottabom** [comment]
Isn't this how it works?

```
public class GrpcClientTest {

    private static Server server;
    private static GenericContainer<?> envoy;

    @BeforeAll
    public static void startServer() {
        // Start the gRPC server
        server = Server.builder()
                       .http(8080)
                       .service(GrpcService.builder()
                                           .addService(new HelloServiceImpl())
                                           .build())
                       .build();
        server.start().join();

        // Start the Envoy proxy using Testcontainers
        envoy = new GenericContainer<>("envoyproxy/envoy:v1.22.0")
                .withExposedPorts(9090)
                .withFileSystemBind("./envoy.yaml", "/etc/envoy/envoy.yaml")
                .waitingFor(Wait.forLogMessage(".*initialized.*", 1));
        envoy.start();
    }

    @AfterAll
    public static void stopServer() {
        server.stop().join();
        envoy.stop();
    }

    @Test
    public void testHelloService() {
        String envoyAddress = "http://" + envoy.getHost() + ":" + envoy.getMappedPort(9090);

        WebClient client = WebClient.of(envoyAddress);
        HelloServiceGrpc.HelloServiceBlockingStub helloService = GrpcClients.builder(client)
                                                                            .build(HelloServiceGrpc.HelloServiceBlockingStub.class);

        HelloReply reply = helloService.hello(HelloRequest.newBuilder().setName("JUnit").build());
        assertThat(reply.getMessage()).isEqualTo("Hello, JUnit");
    }
}
```

**Comment by jrhee17** [comment]
Looks more or less how I expect the test to look like 👍 I assume the test will be run for both HTTP1 and HTTP2.

**Comment by eottabom** [comment]
@jrhee17 
Is this what you mean?
