### ISSUE TITLE
Check for over-exposed APIs

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2360]
We noticed in https://github.com/line/armeria/pull/2343 that there is a public interface for controlling timeout marked as internal-only in Javadoc. Generally, we should be able to avoid that by using the `internal` package, but we may have some APIs that are exposed that shouldn't be.

A couple I found are
- DefaultServiceRequestContext
- DefaultClientRequestContext

I think users are supposed to use request context through their interfaces so do these need to be public classes? If we need to allow users to instantiate these objects, it follow our pattern better to have factory methods on e.g. `ServiceRequestContext` that returns `ServiceRequestContext` by creating `DefaultServiceRequestContext` instead of directly exposing the class I think. This would also allow hiding classes like `TimeoutController`

**Comment by minwoox** [comment]
I agree. We can even make `DefaultServiceRequestContext` package-local.

**Comment by trustin** [comment]
+1

**Comment by trustin** [comment]
For the classes that cannot be hidden, we could introduce annotations like `@UnstableApi` (similar to Guava's `@Beta`).

**Comment by trustin** [comment]
@anuraaga I found we expose protobuf-generated classes such as `Debug`, `StackElementProto` and `ThrowableProto` in `common.grpc`. Should we hide it from the public API?

**Comment by anuraaga** [comment]
I don't think we need to hide generated protos unless we actually hid protobuf itself too, which I guess isn't possible for gRPC.

In addition, for those classes I actually want us to commit to the protocol itself - Armeria transparently converts to domain objects but I think it's good if non-Java languages also can matshal those structs. For best UX I guess we would want to extract a module with only protos but in the meantime I hope we can treat the protos as public API.

**Comment by trustin** [comment]
OK. I think the name `Debug` sounds somewhat vague. Do you have a better name? I also would like to make protoc generate some Javadoc for `Debug` class, which is left empty at the moment.

**Comment by trustin** [comment]
The classes that could be hidden or annotated with `@UnstableApi`:

- `DefaultClientRequestContext` and `DefaultServiceRequestContext`
- `*Provider`
- `DefaultRpcResponse...`
- `DefaultRequestLog`
- `DocServicePlugin` and its related classes such as `*Info`

The classes that could be removed completely due to their dubious value:

- Everything in `server.logging.structured{,.kafka}`

**Comment by anuraaga** [comment]
Are you referring to the `Debug` outer class generated by `debug.proto`? Indeed, a relic of proto generation is putting everything inside a single class but we use `java_multiple_files` to avoid this and I couldn't find a reference using that outer class. I believe we could strip out that outer class in packaging if we want to, or otherwise rename debug.proto to a mangled name.

Let me know if this is actually what you're referring to ;)

**Comment by trustin** [comment]
Yeah, that's what I'm referring to. :smile:

**Comment by trustin** [comment]
Another question: Should we hide our Jackson `JsonSerializer` implementations from the public API? We annotate the eligible types with `@JsonSerialize` and `@JsonDeserialize` already.

**Comment by trustin** [comment]
@minwoox @ikhoon @anuraaga It's good time to go through the public API and add what you want to hide to this issue.

**Comment by trustin** [comment]
Note to self: Make sure most classes are `final` so that we have more freedom to add methods to them later.

**Comment by trustin** [comment]
I think we took enough number of passes to review the API visibility. 🤞
