### ISSUE TITLE
Split WebClient into blocking / async versions?

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2364]
An idea came to mind (inspired by one @adriancole made about async vs not being global decisions rather than call-site ones), would it make sense to split `WebClient` into these three versions?

- `BlockingWebClient`, always returns `AggregatedHttpResponse`
- `AsyncWebClient`, always returns `CompletableFuture<AggregatedHttpResponse>`. `ClientOption`s to specify whether to pool or not, and whether to use the newly added `ClientRequestContext.root().contextAwareExecutor()` when aggregating.
- Streaming `WebClient`, always returns `HttpResponse`

I guess users either always use blocking, or always use async, so it can be annoying to always have to call e.g., `.aggregate().join()`. And the above naming happens to be backwards compatible :) It's similar to gRPC's client stubs.

I think a similar concept could be applied to decorators too, but I guess it could be harder to reason about. A clean API doesn't come to mind for them yet.

**Comment by trustin** [comment]
Sounds good to me all in all.

`AsyncWebClient` doesn't sound nice to me though.. `AggregatingWebClient`? :thinking:

**Comment by trustin** [comment]
These new clients could be created via two ways - via `WebClient` or `Clients`:

```java
WebClient client = ...;
BlockingWebClient blockingClient = client.withBlocking();
AsyncWebClient asyncClient = client.withAggregation();

// or
BlockingWebClient blockingClient = Clients.newClient(...., BlockingWebClient.class);
```

**Comment by ikhoon** [comment]
`BlocingWebClient` has been added in #4021.

**Comment by ikhoon** [comment]
`RestClient` added in #4263 fully supports the requirements of `AsyncClient`.
