### ISSUE TITLE
Using ClientFactoryOptions causes NPE during client connection

### ISSUE THREAD

**Issue by max904-github** [line/armeria#2385]
`ClientFactoryOptions.DEFAULT` overrides the defaults set by `ClientFactoryBuilder` which causes NPE (at `HttpChannelPool` constructor) during client connection, which makes `ClientFactoryOptions` impossible to use.

**The code to reproduce the issue:**

```
  ClientFactoryBuilder clientFactoryBuilder = ClientFactory.builder();
  clientFactoryBuilder.options(ClientFactoryOptions.of()); // or any other "of" method
  clientBuilder.factory(clientFactoryBuilder.build());

```
**The exception thrown during client connect:**

```
  java.lang.NullPointerException
    at com.linecorp.armeria.client.HttpChannelPool.<init>(HttpChannelPool.java:109)

```
**The code that throws NPE (`HttpChannelPool.<init>`):**

```
  this.connectTimeoutMillis = (Integer)baseBootstrap.config().options().get(ChannelOption.CONNECT_TIMEOUT_MILLIS);
```

**Analysis:**

`ClientFactoryBuilder` sets some defaults during the construction [`ClientFactory.builder()` --> `new ClientFactoryBuilder()`].
More specifically it sets `CHANNEL_OPTIONS` with a default `CONNECT_TIMEOUT_MILLIS` as following:

```
  connectTimeoutMillis(Flags.defaultConnectTimeoutMillis());
```

In the debugger I see the following after executing `ClientFactory.builder()`:
```
  options = {java.util.LinkedHashMap@2624}  size = 1
   {com.linecorp.armeria.client.ClientFactoryOption@2629} "CHANNEL_OPTIONS" -> {com.linecorp.armeria.client.ClientFactoryOptionValue@2630} "CHANNEL_OPTIONS={CONNECT_TIMEOUT_MILLIS=>3200}"
```

On a contrary, `ClientFactoryOptions` defines its own set of defaults (via its `DEFAULT_OPTIONS`) which defines empty `CHANNEL_OPTIONS` as following:

```
  ClientFactoryOption.CHANNEL_OPTIONS.newValue(new Object2ObjectArrayMap<>()),
```

When `ClientFactoryBuilder#options()` method invoked with any `ClientFactoryOptions` it will override previous `CHANNEL_OPTIONS` default.
Then, it empties `CHANNEL_OPTIONS`, while `CONNECT_TIMEOUT_MILLIS` expected by `HttpChannelPool` and possibly by other places.

In the debugger I see the following after executing `clientFactoryBuilder.options(ClientFactoryOptions.of())`:
```
  {com.linecorp.armeria.client.ClientFactoryOption@2629} "CHANNEL_OPTIONS" -> {com.linecorp.armeria.client.ClientFactoryOptionValue@2688} "CHANNEL_OPTIONS={}"
```

**Expectation:**

1. The use of `ClientFactoryOptions` should not cause any failure. `ClientFactoryOptions` defaults should not override any defaults set by `ClientFactoryBuilder`.
2. The solution should only take those options defined by the user and apply those to `ClientFactoryBuilder`.
3. `HttpChannelPool` should not fail with NPE when some expected configurations are missing. It should provide reasonable problem indication or/and fall back to a default.

**Current Workaround:**

Avoid using `ClientFactoryOptions` and use individual user defined options as a collection of `ClientFactoryOptions` and add those to `ClientFactoryBuilder` via `ClientFactoryBuilder#option()` method as following:

```
  Collection<ClientFactoryOptionValue<?>> clientFactoryOptions = ...
  if (clientFactoryOptions != null && !clientFactoryOptions.isEmpty()) {
    clientFactoryOptions.forEach(clientFactoryBuilder::option);
  }
  clientBuilder.factory(clientFactoryBuilder.build());
```

**Comment by max904-github** [comment]
It's latest 0.97.0 release

**Comment by minwoox** [comment]
Thanks a lot @max904-github for the detailed information.
Could you send the fix for us? If you couldn't we can take this. Just let us know. 😄

**Comment by max904-github** [comment]
No, I don't have a fix for this. Currently, I'm using the workaround I've described.
There are several problems to solve here. Most importantly, the contradiction between ClientFactoryOptions and ClientFactoryBuilder defaults. It seems, ClientFactoryOptions should only carry some user defined options and possess no defaults.
It would make sense for someone with much better knowledge than me to fix this. Let me know if you need any help though.

**Comment by ikhoon** [comment]
> ClientFactoryOptions should only carry some user defined options and possess no defaults.

That's a good point even though the documentation said it is default options.
https://github.com/line/armeria/blob/bd28eb2499c9149613098de17bc1479919dc3fd7/core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java#L103-L108

Maybe we need `ofDefault()` or `empty()`. Let me fix this issue. :-)

**Comment by max904-github** [comment]
The issue is not just in `ClientFactoryOptions.of()` method. I used it to demonstrate the problem. Actually, I needed to use `ClientFactoryOptions.of(Iterable<ClientFactoryOptionValue<?>> options)` method and supply my custom options. The result was the same as all those `ClientFactoryOptions` methods populate the defaults. I ended up bypassing the `ClientFactoryOptions` due to this problem.
