### ISSUE TITLE
Log requestHeaders when it's failed to send the headers

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2389]
Currently, if the request is not sent and failed, we just log the request cause and dummy headers. But we can log the request headers so that a user can get more information from the exception logs.

**Comment by andrey-tpt** [comment]
Isn't it fixed in 0.98.3 by https://github.com/line/armeria/pull/2517?

**Comment by minwoox** [comment]
Yes, it's fixed. Thanks for reminding. 😄
