### ISSUE TITLE
Provide `String` constants corresponding to `MediaType` constants

### ISSUE THREAD

**Issue by trustin** [line/armeria#2421]
From @tobias-

> Are there any plans for adding the more common types of media types as string constants for consumption with e.g. `@Produces` ? I know there's a pretty comprehensive list in `com.linecorp.armeria.common.MediaType`, but those are unusable by annotations.

Sounds like a good suggestion, as long as we can add some test cases that ensure the strings and `MediaType`s are in sync.

**Comment by JunoJunho** [comment]
I want to handle this issue.

Is it okay just make pull request for this issue?

**Comment by trustin** [comment]
Yes, please. Thanks a lot in advance, @JunoJunho!

**Comment by trustin** [comment]
Perhaps we could create a new constant class `MediaTypeNames` and put strings there.

**Comment by JunoJunho** [comment]
This can be closed?

**Comment by trustin** [comment]
Yes. :smile:
