### ISSUE TITLE
Implement new rawStatusCode methods on ServerHttpResponse

### ISSUE THREAD

**Issue by rstoyanchev** [line/armeria#2431]
The following change https://github.com/spring-projects/spring-framework/commit/547342b27d39efdb7ef6de068897b972e85c7b23 makes it possible to provide non-standard status codes as integer. However `ArmeriaServerHttpResponse` would need to implement the new methods in order to take advantage of this.

**Comment by trustin** [comment]
Thanks for pinging us. Are you interested in sending a pull request or shall we take care of it for you?

**Comment by rstoyanchev** [comment]
No, I won't have the time I'm afraid. Simple change but still.. Mainly I wanted to leave a ping since the default methods would otherwise hide it.

**Comment by trustin** [comment]
OK. I might want to ping you when the PR is ready. :bowing_man:

**Comment by trustin** [comment]
Seems like the commit was not released yet. Will revisit once 5.2.4 is released.

**Comment by monorisk** [comment]
@trustin 
May I try to solve this?
I would like to implement a `setStatusCode(Integer statusCode)` and then it will get non-standard `HttpStatus` by `HttpStatus.valueOf(statusCode)`.
If anyone has a good idea, please let me know. 🙇‍♂️

**Comment by ikhoon** [comment]
Spring framework has been released [5.2.4](https://github.com/spring-projects/spring-framework/releases/tag/v5.2.4.RELEASE). However, Spring Boot is not released with it yet.
