### ISSUE TITLE
Add HttpStatus.isSuccess

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2434]
As you know, I tend to be hesitant about shortcut methods, but this one does seem like it could help a lot since it's extremely common.

```java
class HttpStatus {

  /** Returns whether the {@link HttpStatus} is a success, with a status code of 2XX. */
  public boolean isSuccess() {
    return codeClass().equals(HttpStatusClass.SUCESS);
  }
}

**Comment by trustin** [comment]
How about adding other `is*()` methods as well?

**Comment by anuraaga** [comment]
I think they're less common but guess `isRedirect` and `isError` would be good too. Not sure it's worth splitting client and server error for such shortcuts
