### ISSUE TITLE
Add a static constructor for FailFastException

### ISSUE THREAD

**Issue by jrhee17** [line/armeria#2440]
We would like to be able to create mock tests for cases when circuitbreaker is opened.
However, it seems like `FailFastException` is `final`, and doesn't have any public static constructors.
It would be great if `FailFastException` had a method like `ClosedSessionException.get`

```
public static FailFastException get(CircuitBreaker circuitBreaker) {
    return new FailFastException(circuitBreaker);
}
```

Let me know if this is something you guys are open to considering 🙇

**Comment by trustin** [comment]
Sounds good to me. I think it's just OK to make the constructor public, add Javadoc and add `requireNonNull()` on the parameter.

**Comment by JunoJunho** [comment]
Can I handle this issue?

**Comment by JunoJunho** [comment]
I just have a simple curiosity on the constructor's visibility.

Is there any reason to make the constructor as default?
