### ISSUE TITLE
Rename `ClosedPublisherException` to `ClosedStreamException`?

### ISSUE THREAD

**Issue by trustin** [line/armeria#2447]
`ClosedStreamException` sounds more aligned with HTTP's notion of 'stream' and our type `StreamMessage`. I think we can also make `ClosedSessionException` extend `ClosedStreamException`, because a closed session inherently means that the stream has been closed.

**Comment by ikhoon** [comment]
👍 That is a nice idea. The name of `ClosedStreamException` may explain the error situation in HTTP/2 stream better.
