### ISSUE TITLE
Add more options to `ArmeriaRetrofitBuilder`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2481]
To build Armeria Retrofit with a specified `ClientFactory`, a user should create a `WebClient` which is a little verbose:
```java
ClientFactory factory = ...;
// Before 0.98.0
new ArmeriaRetrofitBuilder(clientFactory);
// After 0.98.0
ArmeriaRetrofit.builder(WebClient.builder(...).clientFactory(factory)...);
```
Perhaps, we can provide more setters to build Armeria Retrofit more conveniently.

**Comment by trustin** [comment]
We could make `ArmeriaRetrofitBuilder` extend `AbstractClientOptionsBuilder`. If a user created `ArmeriaRetrofitBuilder` with `WebClient`, we could merge two `ClientOptions` into one.

**Comment by ikhoon** [comment]
Let me take a look. 😀
