### ISSUE TITLE
Throttling failure response status shall be configurable

### ISSUE THREAD

**Issue by max904-github** [line/armeria#2482]
Currently `503 - Service Unavailable` failure response status hardcoded by com.linecorp.armeria.server.throttling.ThrottlingService. The response status should be driven by the configured strategy and it shall permit using `429 - Too Many Requests` as a more appropriate and more common throttling status.

**Comment by trustin** [comment]
Agreed, @max904-github. Any objections? /cc @minwoox @ikhoon @imasahiro @kojilin @anuraaga ?

**Comment by imasahiro** [comment]
no objection!

**Comment by ikhoon** [comment]
I agreed too. It looks nice!

**Comment by max904-github** [comment]
I can work on it, if no one else wants to take it.
I will put the failure response status (`HttpStatus`) on the strategy (`ThrottlingStrategy`) and keep `HttpStatus.SERVICE_UNAVAILABLE` as a default for backward compatibility.

**Comment by trustin** [comment]
Thanks, @max904-github. It'd be awesome if you could send a pull request for this issue. I think we can use `TOO_MANY_REQUESTS` as a default and explain that in our release note.

**Comment by anuraaga** [comment]
The current throttler is a global throttler so default of 503 seems fine, there's nothing wrong with the client when the server runs into an event causing it to loadshed globally.

429 seems good for client-unit throttling which this issue doesn't look like it'll touch so recommend not changing the default.

**Comment by trustin** [comment]
Doesn't it depend on how a user implements `ThrottlingStrategy` and how the decorator is applied?

**Comment by anuraaga** [comment]
Yes but our batteries included throttling strategy is a global limit and is what we have in the docs

http://line.github.io/armeria/advanced-production-checklist.html

I think for internal RPC, global load shedding is by far the most common and with external RPC maybe not. Most of our defaults tend towards internal RPC though.

These seem like good reasons to stick with 503.

**Comment by max904-github** [comment]
Posted a PR. Kept the default to `SERVICE_UNAVAILABLE`.
