### ISSUE TITLE
Confusing behavior when constructing clients

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2493]
We've added some client creation shortcuts in #2396 but I wonder if it hasn't resulted in some spaghetti.

I feel that this code doesn't produce the intended result

```java
ClientFactory factory = ClientFactory.builder().useHttp2Preface(false).build();
ClientOptions options = ClientOptions.builder().responseTimeoutMillis(timeout).build();  // Ends up being essentially equivalent to default client options, but I thought I'm only specifying response timeout
WebClient.builder(...)
  .factory(factory) // Want to use custom factory
  .options(options) // But custom factory gets overridden by ClientFactory.ofDefault(), which is highly surprising
  .build();
```

Probably related to #2483 (though I found it coincidentally, heh)

**Comment by anuraaga** [comment]
I think we should remove factory from `WebClientBuilder` if we want to keep it on `ClientOptions`. It's too hard to grok this relationship otherwise.

**Comment by trustin** [comment]
Such pitfall exists in all other properties in the builder. The reason it became a problem is because `factory` was not an option before. If `useHttp2Preface` was not an option before, a similar problem would occur as well. How about just updating release note to add some warning about this?

**Comment by anuraaga** [comment]
I generally use defaults so haven't run into this in much code but did in Zipkin and I don't see a reason users won't continue to run into it.

Perhaps `ClientOptions.Builder` should initialize as empty, not defaults? The code snippet above is too surprising to just leave to javadoc or release notes IMO.

**Comment by trustin** [comment]
I understand your concern and I agree that the problem stems from the idea that all option properties in `AbstractOptions` must be present at construction time. Let's fix this before 1.0.

**Comment by anuraaga** [comment]
Also, I find it unintuitive understanding what is a property of a subclass, safe from overriding from clientoptions (path, etc) and what isn't. I guess this may be an argument for composition vs inheritance. But as long as the above surprising snippet gets fixed I'm ok.

**Comment by trustin** [comment]
> Also, I find it unintuitive understanding what is a property of a subclass, safe from overriding from clientoptions (path, etc) and what isn't. 

Could you elaborate on this?

**Comment by anuraaga** [comment]
Currently, when using the builder, I have to think about whether a method on the builder is safe to call before `options`. This is because they all exist on the class but only some are overridden by options.

But yeah if we change the behavior so calling options doesn't completely clobber, it should be ok.

**Comment by trustin** [comment]
Ah, OK. Thanks for explanation. Makes sense.
