### ISSUE TITLE
Provide more ways to customize `RequestContextExporter`.

### ISSUE THREAD

**Issue by trustin** [line/armeria#2512]
Currently, a user can export built-in properties and context attributes into the map entries with pre-defined keys. For example, `BuiltInProperty.CLIENT_IP` is always exported to `client.ip`. However, a user sometimes want to export it to a different key.

To fix this issue:

- We could allow a user provide an alternative key string for a property.
- We could allow a user provide a custom logic for further customization, e.g. `Function<RequestContext, Map.Entry<String, ?>>`.
  - We need to find a way to expose this functionality to logging framework integrations. Maybe putting some Java code into `logback.xml` and compiling it?

**Comment by trustin** [comment]
Another idea from @andrewoma:

> I think something along the lines of:
> `<export>custom.my_name:com.foo.Bar</export>` where `com.foo.Bar` is something that implements `Function<RequestContext, Object>` would be the kind of thing I'm after.

**Comment by andrewoma** [comment]
A related issue is that it would be great to name exported properties whatever the user wishes. We use JSON structured logging and having `.` in the name of fields is a little cumbersome for tooling.
