### ISSUE TITLE
`RequestContextExporter` does not work with `AttributeKey` created with `newInstance()`

### ISSUE THREAD

**Issue by trustin** [line/armeria#2513]
Reported by @andrewoma:

> it seems you have to create your key in the form of
> ```
> AttributeKey.valueOf(Context.class, "FOO")
> ```
> The `AttributeKey.newInstance(Context.class)` form isn't supported and that took me quite some debugging to realise

(in `RequestContextExporter`)

**Comment by trustin** [comment]
Another problem which could be resolved together:

> Another gotcha of the custom attributes - you can't map the same attribute twice with different string functions, e.g.
> ```xml
> <export>attrs.request_id:com.example.Context#KEY:com.example.ContextRequestIdString</export>
> <export>attrs.trace_id:com.example.Context#KEY:com.example.ContextTraceIdString</export>
> ```
> Only the `attrs.request_id` is output

**Comment by ikhoon** [comment]
Let me take a look. 😀

**Comment by ikhoon** [comment]
>> The `AttributeKey.newInstance(Context.class)` form isn't supported and that took me quite some debugging to realise

Had chat with  @andrewoma, ans the exact API usage was `AttributeKey.newInstance(Context.class.getName())`

**Comment by trustin** [comment]
`newInstance()` fails when there is an `AttributeKey` with the same name. When you use `RCEA`, it will use `AttributeKey.valueOf()` to instantiate an `AttributeKey`, which may happen before a user's `newInstance()` call. As a result, `newInstance()` will trigger an `IllegalStateException` and thus a user will see an unexpected behavior.

The workaround for this issue is for the user to use `valueOf()` rather than `newInstance()`.

**Comment by trustin** [comment]
[This issue](https://github.com/line/armeria/issues/2513#issuecomment-588593453) has been resolved in #2521, though. Thanks for reporting, @andrewoma! :bowing_man:
