### ISSUE TITLE
Allow `*ClientBuilder.path()` even when created with a URI

### ISSUE THREAD

**Issue by trustin** [line/armeria#2525]
Currently, the `path()` call in the following code will throw an exception:

```java
WebClient.builder("http://127.0.0.1:8080")
         .path("/foo")
```

.. because `path()` is currently allowed only when a builder is created with an `Endpoint`.

However, I feel like we don't really need to prohibit `path()` but could just concatenate, e.g.

```java
WebClient.builder("http://127.0.0.1:8080")
         .path("/foo") // URI becomes http://127.0.0.1:8080/foo

WebClient.builder("http://127.0.0.1:8080/foo/")
         .path("/bar") // URI becomes http://127.0.0.1:8080/foo/bar
``

We need to define the case of multiple `.path()` calls though:

```java
// /foo/baz or /foo/bar/baz ?
WebClient.builder("http://127.0.0.1:8080/foo/")
         .path("/bar")
         .path("/baz")
```

I'm somewhat in favor of concatenating multiple `.path()` calls, inserting/deduplicating slashes between them automatically. Thoughts?

/cc @mauhiz

**Comment by anuraaga** [comment]
Concatenating paths seems a bit weird to me.

I'd vote for removing the path method and adding it as a parameter next to the factories that accept `Endpoint`.

It also brings a larger question as to us having several places where we do a runtime check even though it's not impossible to do a compile one, though may for example complicate inheritance or something (have several different types of builders for a type). I wonder if it's worth fixing this one location if we have the similar practice throughout the API.

**Comment by mauhiz** [comment]
I understand the point of passing a hostname or endpoint separately from the rest of URL, but as most kind of clients will call varying paths, is there a point in passing a path or an URL at `ClientBuilder` level?

**Comment by anuraaga** [comment]
@mauhiz I guess thrift clients are a common one that only access one path - without setting the path at the `ClientBuilder` level, thrift wouldn't work.

**Comment by mauhiz** [comment]
I see. Trying to make same API for REST client and Thrift client ... hits this kind of conundrum

**Comment by minwoox** [comment]
Concatenating two paths that are set using `path(...)` seems weird to me too.

Retrofit supports concatenating paths set from the constructor and `path()` method but the logic is a little bit hard to understand. https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Retrofit.java#L496-L543
For example,
```java
WebClient.builder("http://127.0.0.1:8080/foo/")
         .path("/bar") // URI becomes http://127.0.0.1:8080/bar

WebClient.builder("http://127.0.0.1:8080/foo/")
         .path("bar") // URI becomes http://127.0.0.1:8080/foo/bar
```

So I think if it's possible to remove `path(...)` method from the builder, I would go for it. 😄

**Comment by ikhoon** [comment]
Removing `path(...) from builder sounds nice to me. 👍
```java
WebClient.builder(SessionProtocol.HTTP, Endpoint.of("127.0.0.1", 8080),  "/foo/" )
WebClient.builder(SessionProtocol.HTTP, Endpoint.of("127.0.0.1", 8080))
WebClient.builder("http://127.0.0.1:8080/foo/")
```

**Comment by trustin** [comment]
Optionally requiring a path when constructing a builder with an `Endpoint` and removing `builder.path()` sound good to me, although it will make the `builder()` methods somewhat crowded. Any other ideas?

**Comment by anuraaga** [comment]
I'd personally lean towards longer factories with compile time safety vs shorter ones with runtime safety in general. +1 to the crowded methods
