### ISSUE TITLE
Add HTTP multipart content support

### ISSUE THREAD

**Issue by trustin** [line/armeria#253]
There's no HTTP multipart content support available in Armeria. Would be nice to have. Perhaps using commons-fileupload? Should look into other web application frameworks for better API design as well.

**Comment by gotchazipc** [comment]
Do you mean multipart/form-data encoding on the client? And... do what about other multipart mime types? (e.g. multipart/x-www-url-encoded)

**Comment by trustin** [comment]
Let's solve them together in this issue.

**Comment by trustin** [comment]
The point is that we need to provide a user-friendly API for accessing query parameters encoded in various commonly-used encodings. The API would need to provide moderate level of abstraction so that the user doesn't need to worry too much about the underlying encoding details, although he or she should be allowed to access them if he or she wants.

**Comment by gotchazipc** [comment]
OK, Thank you.  Let me clarify the requirements. 

1) We need some user-friendly API for HTTP Client that can handle query parameters and other stuffs of http request.  
2) The new APsI should provide enough features, and should hide too-much detailed things . 

For example, composing multipart/form-data request with local files should be sent with some  input paths/streams, names, optional mime types of the files. Users may access some complex things like the part-headers of each file.  

It seems that I have to start working with investigate some commony APIs for file uploading first.

**Comment by trustin** [comment]
> 1) We need some user-friendly API for HTTP Client that can handle query parameters and other stuffs of http request.

It's actually about `HttpService` but yeah, we could also improve the client-side API. It's your call.

> It seems that I have to start working with investigaimg some commonly used APIs for file uploading 
first.

Yes. That'd be a great starting point.

Thanks for your interest!

**Comment by gotchazipc** [comment]
Oh... Sorry, (as a newcomer) I could not think about server-side, for I thought that all non-rpc (thrift or grpc) requests are handled by Jetty/Tomcat server that can handle all http requests of any content-types.  Adding features on `HttpService` would be completely different story from client-side, I guess (and would be a really tough job for me, probably). I'll concentrate on client-side for now. If you have any suggestions, please let me know. Thank you.

**Comment by trustin** [comment]
Cool. Looking forward to your PR. :-)

**Comment by anuraaga** [comment]
@trustin Think we need to give this a think to see if it will require changing the API before 1.0

**Comment by trustin** [comment]
@anuraaga I was rather thinking of adding an extra API for this after 1.0. What API changes do you expect?

**Comment by anuraaga** [comment]
Yeah that would be the needed check :) Just need to confirm it will all be separate API. One thought that comes to mind is supporting multiple objects in `AggregatedHttpRequest` though if it's a different class than we're good.
