### ISSUE TITLE
Undeprecate `ctx.setRequest/ResponseTimeout()`?

### ISSUE THREAD

**Issue by trustin** [line/armeria#2535]
We got some internal inquiry about what should a user do instead of `ServiceRequestContext.setRequestTimeoutMillis(long)`. IIUC the current API, it has to be:

```java
final requestStartTimeMillis = 
    ctx.log().ensureAvailable(RequestLogProperty.REQUEST_START_TIME)
             .requestStartTimeMillis();
ctx.setRequestTimeoutAt(Instant.ofEpochMillis(requestStartTimeMillis + timeout);
```

... which is not ideal.

On the other hand, I found a bug where the current `setRequestTimeoutMillis()` implementation uses `extendRequestTimeout()`, which means the timeout will not be set when there's no timeout scheduled yet.

**Comment by ikhoon** [comment]
> On the other hand, I found a bug where the current setRequestTimeoutMillis() implementation uses extendRequestTimeout(), which means the timeout will not be set when there's no timeout scheduled yet.

Oops, Let me check this.

**Comment by anuraaga** [comment]
I remember suggesting not having `extend` and only having `set` since `set`(`get` + `delta`) seems reasonable compact and very readable. But didn't get any feedback on that. I'd still recommend it.

I think it's also good to confirm with the user though whether they actually want `setTimeout`. I do strongly believe that 90% of users actually want `setTimeoutAfter` which we have.

**Comment by anuraaga** [comment]
Sorry for accidentally closing issue >< On mobile it's just one mistouch when wanting to scroll the page.

**Comment by KarboniteKream** [comment]
> I think it's also good to confirm with the user ...

We don't _really_ need `setTimeout()`, as our current logic is implemented in a decorator, which is executed at the start of the request, so the behavior should be virtually the same as `setTimeoutAfter()`.

**Comment by anuraaga** [comment]
Just wondering, if you had never seen the `setTimeout` method before (I'm guessing you did while upgrading to latest version of Armeria and cleaning up deprecations), would you have found using `setTimeoutAfter` awkward?

I've seen several cases where users use `setTimeout` wrongly assuming it sets it based on the current time creating a bug and haven't heard the opposite yet - I'm wondering how many users really want `setTimeout`.

Either way, having a fourth way of setting timeout seems too much, so if we want it, lean towards deprecating `extend` in favor of a good old fashioned `set(get+delta)`.

**Comment by trustin** [comment]
> But didn't get any feedback on that. I'd still recommend it.

Sorry about no feedback! :sob: 

> Either way, having a fourth way of setting timeout seems too much, so if we want it, lean towards deprecating extend in favor of a good old fashioned set(get+delta).

+1. Perhaps we need a better name than `set*Timeout()` to avoid confusion?

**Comment by trustin** [comment]
At second thought, extend() is not same with set(get+delta) because it special-cases when current timeout is 0.

**Comment by KarboniteKream** [comment]
@anuraaga Yes, I've only come across the method during the upgrade.

Personally, `setTimeout()` and `setTimeoutAfter()` sound the same, just from the name. On one hand, setting the timeout from request start makes more sense, but only if you set it at the beginning (before serving the request). It wouldn't make much sense using this method later, as the timeout could already have been reached.

So I think it makes more sense setting the timeout relative to the current time, however, it could be "dangerous" if `setTimeoutAfter()` is called later in the pipeline. For instance, if you have a potentially long-running decorator (let's say 500 ms) and the second decorator is the timeout configuration (let's say 300 ms), the user might think they're setting the timeout to 300ms, but the request could timeout after 800 ms instead (500 + 300).

**Comment by ikhoon** [comment]
> Either way, having a fourth way of setting timeout seems too much

Agreed. When I was working on #2343 , I thought there are too many options to set timeout.

> However, it could be "dangerous" if setTimeoutAfter() is called later in the pipeline. 

How about adding `ServiceRequest.elapsedTime()`? then the user can determine whether to extend timeout or not.

I prefer:
* Maintain `setTimeouAfter()` and `clearTimeout()`. 
* Deprecate `extendTimeout()`, `setTimeoutAt()`, `setTimeout()`.
* Add `elapsedTime()`

**Comment by trustin** [comment]
I don’t think setTimeAfter and elapsedTime can replace setTimeout or setTimeoutAt, because they both depend on ‘current time’, which changes every moment.

Also, setTimeoutAfter called in a decorator is not same with setTimeout. setTimeAfter will most likely cancel the existing timeout and schedule a new one, but setTimeout can retain the old timeout if a user specified the same timeout value.

**Comment by trustin** [comment]
How about:

- Removing setTimeoutAt() which seems not used often
- Adding an enum like TimeoutMode, whose value is FROM_NOW, FROM_START or EXTEND.
- Providing two variants of setTimeout()
  - setTimeout(Duration) - shortcut for setTimeout(FROM_NOW, duration)
  - setTimeout(TimeoutMode, Duration)
- Keeping clearTimeout()

..?

**Comment by ikhoon** [comment]
> * Removing setTimeoutAt() which seems not used often

+1, Agreed

> Adding an enum like TimeoutMode
```java
setTimeout(FROM_NOW, duration)
setTimeout(FROM_START, duration)
setTimeout(EXTEND, duration)
```
`FROM_NOW` is natural, but `FROM_START` and `EXTEND` are a little awkward. 

```
// Instead of `FROM_START`, I'm not sure these are better 😅
setTimeout(RESET, duration)
setTimeout(TOTAL, duration)
setTimeout(MAX, duration)

// Instead of `EXTEND`
setTimeout(ADD, duration)
```

> Keeping clearTimeout()
+1

**Comment by trustin** [comment]
- Reset - We talked about this before and @anuraaga (or someone else?) said it sounds same with just 'set'.
- Total, max - Sounds not right.
- Add - why is it any better than extend? 'Adjust' may be better, though.

**Comment by anuraaga** [comment]
For some reason I can't come to love this enum, but I guess it's ok. It's probably just preference towards deadline than timeouts which is a long sailed ship.

I think making this enum consistently `from` helps it a lot if possible. Maybe this

```java
enum TimeoutAdjustment {
  /** Sets a timeout to be a given amount of time from the current time as returned by {@link System#nanoTime}. */
  NOW,

  /** Sets a timeout to be a given amount of time from when the current request began processing. */
  START,

  /** Sets a timeout to be a given amount of time from the end of the currently set timeout. */
  CURRENT // Or CURRENT_END?
  ;
}
```
