### ISSUE TITLE
Trailers is added to ResponseHeaders when there's no content

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2544]
Related: https://github.com/line/armeria/pull/2372#discussion_r386025977

I found out that the additional trailers is added to `ResponseHeaders` when the content of the response is empty.
I think we implemented this because of gRPC service that sends trailers only when in certain circumstances. https://github.com/line/armeria/blob/master/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L323

However, I think a user may want to send the response with just `ResponseHeaders` and trailers because it does not violate the [spec](https://tools.ietf.org/html/rfc7540#section-8.1).

Perhaps, we can just add the trailers to `ResponseHeaders` in the gRPC service only and remove the trailers from ctx so that `HttpResponseSubscriber` is able to send `ResponseHeaders` and trailers when it should.

/cc @anuraaga, @jyblue

**Comment by anuraaga** [comment]
Yeah this seems reasonable. Maybe an option when creating the context could control the behavior of merging trailers with headers or not.

**Comment by minwoox** [comment]
Can I just handle it in gRPC specially and more generalize later when I find out that this is needed in HTTP services as well? 🤔
