### ISSUE TITLE
Discussion:  Naming  rules for export keys in `BuiltInProperty` 

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2545]
[BuiltInProperty](https://github.com/line/armeria/blob/25a5e751f470e38bb86720f7a77c5b3cd531d882/core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java#L37) has various predefined export keys. Some of the property is prefixed by `req` or `res` as a convention. `req.path`, `req.query` and `req.method` are only used for the request side so they could be `path`, `query` and `method`. Also `res.status_code` could be `status_code` without loss of meaning.

By the way, `RequestContextExportingAppender` supports regular expression for specifying an export key pattern such as `*` or `req.*`. https://line.github.io/armeria/advanced-logging.html
If we remove `req` and `res` prefix, a user who wants to get a request side only, should enumerate all properties.

Any thoughts on this? prefer to keep current conventions or remove a redundant prefix for simplicity?

**Comment by julnamoo** [comment]
> `req` and `res` +1

I prefer `req` and `res` prefix because it sounds obviously!

**Comment by trustin** [comment]
Should we close this or..?

**Comment by minwoox** [comment]
Yes, let's close this. I'm not against it. 😄

**Comment by ikhoon** [comment]
Yeah, let me close this. 😀
