### ISSUE TITLE
Consider a way to control timeout without scheduler

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2547]
Sometimes users make `ServiceRequestContext` mock instead of using `ServiceRequestContextBuilder`.
They wanted to return true always when they call `ServiceRequestContext.isTimedOut()` or it meets certain conditions.

It is not recommended to mock `ServiceRequestContext` because of its complexity. 

* Expose the `TimeoutController` to `ServiceRequestContextBuilder`?
* Add `ServiceRequestContextBuilder.isTimedOut(boolean)` to configure it?
* I'm not sure these are good. Any other thoughts?

By the way `DefaultServiceRequestContext` has `timedOut` flag.
I think we can remove it in favor of `TimeoutController.isTimedout()`
https://github.com/line/armeria/blob/95217b3b61d92bec6ced49286fd8a7d88e5dc259/core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java#L457-L467

**Comment by trustin** [comment]
timeout -> timedOut

**Comment by minwoox** [comment]
> Add ServiceRequestContextBuilder.isTimedOut(boolean) to configure it?

+1
