### ISSUE TITLE
Support for Dropwizard 2.x

### ISSUE THREAD

**Issue by joschi** [line/armeria#2554]
Armeria is currently supporting Dropwizard 1.3.x which is in maintenance mode and won't receive any non-critical updates:
https://github.com/line/armeria/blob/6f21290a3e6e3bb2af22d8a9061d472dcabda545/dependencies.yml#L139-L171

Would there be interest in supporting Dropwizard 2.x, either additionally to Dropwizard 1.3.x or updating the existing integration?

**Comment by minwoox** [comment]
Thanks @joschi for letting us know!

> Would there be interest in supporting Dropwizard 2.x, either additionally to Dropwizard 1.3.x or updating the existing integration?

I prefer to just update the existing one but @cricket007 might have an idea about this.

**Comment by trustin** [comment]
Depending on how breaking 2.x is, we could use the similar approach we did for Spring Boot 1 and 2 or for RxJava 3 and 2.

**Comment by cricket007** [comment]
I made the PR just days before 2.0 was cut. 

I'd trust @joschi, a Dropwizard contributor, as more of an authoritative decision maker than myself 😅

**Comment by joschi** [comment]
@trustin We tried to make Dropwizard 2.0.x as backward-compatible as possible.

In a local branch I succeeded using Dropwizard 2.0.2 as a drop-in replacement for Dropwizard 1.3.19 in Armeria.

The question is, whether the users of Armeria are mainly using Dropwizard 1.3.x or 2.0.x.
We could start by copying the Dropwizard 1.3.x sub-module to enable using both. The code would (at least in the beginning) be identical.

**Comment by trustin** [comment]
If the code is identical, we could use the approach we used for `armeria-thrift`, which means we can host all source code in `armeria-dropwizard` and add a new module `armeria-dropwizard1` with `build.gradle` that look like this:   https://github.com/line/armeria/blob/master/thrift0.9/build.gradle
