### ISSUE TITLE
Support `@LocalArmeriaPort`, `@LocalArmeriaPorts`

### ISSUE THREAD

**Issue by heowc** [line/armeria#2561]
I'm working on a [PR](https://github.com/line/armeria/pull/2502) to allow Armeria internal services and spring actuators to only be allowed on certain ports. But I faced one problem.

When I specify a random port, I can't tell it clearly. So in Armeria, it would be nice to provide annotations like `@LocalArmeriaPort` and `@LocalArmeriaPorts` like `@LocalServerPort` as Spring Boot provides. 
~~Also, this task will bind to that port when `management.server.port` is set, and it would be nice to use` @LocalManagementPort`.~~

This is likely to be a cornerstone for future features that will be added.

See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-discover-the-http-port-at-runtime
See [`@LocalRSocketServerPort`](https://github.com/spring-projects/spring-boot/pull/18287/files)

**Comment by heowc** [comment]
I found out that if you specify 0 in `management.server.port`, in Armeria you will not know which port is used by `management.server.port`. So I think a field should be added to `ServerPort` to know this. 

what do you think? 🤔

**Comment by trustin** [comment]
I like the idea of having `@LocalArmeriaPorts`. We could check the type of the injection target to determine to inject a single `ServerPort` or a set of `ServerPort`s.

On the other hand, how can we know which `ServerPort` is for management?

**Comment by heowc** [comment]
When specifying a port, there is a way to advertise itself.

To do this, we need to add the specific field(ex. `type`) to `ServerPort`, or wrap `ServerPort` and add the specific fields to it. because I think I need to work [here](https://github.com/line/armeria/blob/86888fec43caafa4153814826386d17c9fcfda89/core/src/main/java/com/linecorp/armeria/server/Server.java#L654...L691) to clarify the specified port.

**Comment by trustin** [comment]
How about adding such field to `LocalArmeriaPorts`? e.g. `@LocalArmeriaPorts(management = true)` (`false` by default)

**Comment by heowc** [comment]
I'm not talking about bringing Spring Boot specific notion of 'management'  into Armeria's core API. Of course, I may not have understood it well.

Suppose I specified the following port:

Armeria
- ServerPort (8080)
- ServerPort (0)?

Spring Actuator
- ServerPort (0)?

When the port specified by Armeria is 8080, 0 and the port specified by Spring Actuator is 0, two random ports are assigned. However, it is not known which port is the port specified by Spring Actuator. So let's add a `type` field to make this clear. (The field name does not have to be `type`.)

Armeria
- ServerPort (8080, "armeria")
- ServerPort (0, "armeria")

Spring actuator
- ServerPort (0, "spring-actuator")

**Comment by trustin** [comment]
I'm not sure I like the idea of adding something to `ServerPort`. The notion of management port is not part of Armeria core, so I think it's better being contained in the Spring integration module.

**Comment by heowc** [comment]
Hmm .. If so, what do you think of changing the port from Spring integration module to a random port if the port is set to 0?

This solution is not perfect in timing, but it adds nothing to `ServerPort`.

**Comment by heowc** [comment]
Rethinking, it seems that `management.server.port` should be included after [the PR](https://github.com/line/armeria/pull/2502) or it should be included.

This is because allowing a port allows all other routes to access.
