### ISSUE TITLE
Annotated Services with arbitrary type parsers

### ISSUE THREAD

**Issue by tobias-** [line/armeria#2574]
In Armeria there is a very hardcoded list of allowed parameter types in e.g. path and query (basically enums + boxed primitive types). While this list can always be handled in the service implementation by manually transforming the type from `String`, it makes the method signature less explicit. Compare the information you get from `Long` vs `CompanyId` just by the type.

In Jersey/Jaxrs (which we still use in some places), they have the same limitations but also use reflections to allow any type which have a single string constructor or single string method `fromString(String)`. I'm assuming they picked this to avoid collision with `valueOf(String)`, but their exact reasons are not known to me.

My suggestion is that Armeria can fall back to something similar (constructor/method) that has to exist on the class.

**Comment by tobias-** [comment]
This is related to #2573

**Comment by trustin** [comment]
We could do two things:

- Allow a user specify value converters. It's currently hard-coded: https://github.com/line/armeria/blob/7f263ac107544d3f010a82e9f182df4d875bfcc1/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java#L40-L75
- Add a built-in fallback converter that tries the static factory methods named `of(String)`, `valueOf(String)` and `fromString(String)`.

@tobias- What kind of collision would `valueOf(String)` cause?

**Comment by tobias-** [comment]
> 
> @tobias- What kind of collision would `valueOf(String)` cause?

Having a "web-converter" from Enum-classes comes to mind, but like I said, their reasons are not known to me.

**Comment by trustin** [comment]
I think this issue can be done in two steps.

1. Write the conversion code that looks up and invokes the static factory methods such as `fromString(String)` or the constructor with a single `String` parameter. Add it into `supportedElementTypes`.
   - At this point, we can close #2574 (this issue).
2. Introduce `ParamConverterFunction` to make parameter conversion extensible. (#3140)
   - At this point, a user can define his or her own converter function. For example:
     - A user can define a converter that converts a single query parameter into a `List<String>`. It's currently not possible to do this because the handling of `List` is hard-coded as documented [here](https://armeria.dev/docs/server-annotated-service/#getting-a-query-parameter) (Find 'multiple'.)
     - A user can define a converter that converts a query parameter into a custom type `FooBar`.
