### ISSUE TITLE
blocking response reading in StreamingCallSubscriber

### ISSUE THREAD

**Issue by AnonymousVovus** [line/armeria#2575]
Can you please explain implementation of StreamingCallSubscriber in armeria-retrofit2. Why there is blocking response reading is implemented? Are there any plans for asynchronous / reactive stream IO?

I found old issue #1296 with sad story about blocking at read.  
Relevant comment is https://github.com/line/armeria/pull/1296#pullrequestreview-138529736

Thanks!

**Comment by trustin** [comment]
Hi! It's because Retrofit's internal is implemented in a blocking way. We can't make it asynchronous unless they fix theirs.

**Comment by AnonymousVovus** [comment]
Thanks for answer!

**Comment by trustin** [comment]
My pleasure. I hope you are enjoying Armeria. Please let us know if you need any additional questions or feed back.
