### ISSUE TITLE
Provide a way to exclude certain routes/services from route decorators

### ISSUE THREAD

**Issue by trustin** [line/armeria#2595]
For example, a user might not want to let `LoggingService` from logging the requests sent to `HealthCheckService`.

We could provide a decorator implementation which skips the next decorator when the current request matches a certain route or the execution chain contains a certain service instance/type.

To implement this feature, we might need to improve the `Service.unwrap()` API, e.g. add `unwrap()` without parameters, which always unwraps one layer.

**Comment by ikhoon** [comment]
This was fixed by #3562 and #3081
