### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by sdual** [line/armeria#2600]
I'm attempting to set the timeout as the following code. But a timeout seems not to work properly. Even if a request takes longer than the specified timeout, the server does not terminate it.

Is this a bug, or is my setting wrong?

```java
@Get("/hello")
 public HttpResponse hello(ServiceRequestContext ctx, QueryParams params) {
   ctx.setRequestTimeoutAfterMillis(timeout);

   // do something.

   return HttpResponse.of(HttpStatus.OK, MediaType.PLAIN_TEXT_UTF_8, "OK");
 }
 ```

**Comment by minwoox** [comment]
Hello! Thanks for the report!. Could you tell us which version you are using, please?

**Comment by trustin** [comment]
What happens if you annotate the method with `@Blocking`? My guess is that you performed a time-consuming blocking operation in `// do something` part, which blocked the event loop from processing timeout events.

**Comment by sdual** [comment]
@trustin @minwoox Thank you for your advice! I'm using 0.98.4.
I annotated the method with @Blocking and the timeout was working properly by this change.
I read the PR https://github.com/line/armeria/pull/2187. Does the annotated service have to be annotated with @Blocking?


```java
@Get("/hello")
@Blocking
public HttpResponse hello(ServiceRequestContext ctx, QueryParams params) {
  ctx.setRequestTimeoutAfterMillis(10 * 1000);

  try {
    Thread.sleep(20 * 1000);
  } catch (InterruptedException e) {
  }

  return HttpResponse.of(HttpStatus.OK, MediaType.PLAIN_TEXT_UTF_8, "OK");
}
```

**Comment by ikhoon** [comment]
You don’t need to add `@Blocking` annotation if your code works asynchronously. 
The `Thread.sleep(..)` will block the event loop. 
To test timeout I’d recommend to use `HttpResponse.delayed(...)`

**Comment by ikhoon** [comment]
If you get to know eventloop, please the EventLoop and threading model in Netty in Action. 😀 https://livebook.manning.com/book/netty-in-action/chapter-7/

**Comment by sdual** [comment]
@ikhoon Thanks! I'll check the book.
