### ISSUE TITLE
Provide more ways to run with Context

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2611]
In our codebase, we push `RequestContext` and immediately run some code with try-with-resources.
For example:
```java
try (SafeCloseable ignored = ctx.push()) {
    logger.trace(decorate(msg));
}
```
If `RequestContext` provides `run(Runnable)` or `call(Callable)` we can reduce boilerplate code and simplify it.
```java
ctx.run(() -> logger.trace(decorate(msg));
```
This is inspired by gRPC Context API.  
https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html#run-java.lang.Runnable-

**Comment by anuraaga** [comment]
Seems like a nice method to add, though maybe not so helpful in our codebase specifically since we would probably still generally pick the former for better performance. Want to make sure no one picks up this issue and rewrites all the current usage at the same time as adding the method :)

**Comment by ikhoon** [comment]
> since we would probably still generally pick the former for better performance

Good point, we create an additional `Runnable` object to use `ctx.run()`. 

> Want to make sure no one picks up this issue and rewrites all the current usage at the same time as adding the method

I think we don't need to change the current usage in our code base. Let's just give more options to our users. 😀

**Comment by JunoJunho** [comment]
Is the requirement just wrapping this try clause using `SafeCloseable` ?

**Comment by ikhoon** [comment]
The `RequestContext.push()` already returns `SafeCloseable`. 
I meant if a user wants to execute a function with `RequestContext`, he/she can do it by:

```java
// 1. use makeContextAware
// wrap the given Runnable with request context
Runnable contextAwareRunnable = ctx.makeContextAware(() -> {
    logger.trace(decorate(msg));
});
...

// can execute returned Runnable with request context later
contextAwareRunnable.run();

// 2. use push
// immediately push current request context to context storage such as ThreadLocal 
try (SafeCloseable ignored = ctx.push()) {
    logger.trace(decorate(msg));
}
```

I think we can give users another option. 
```java
Runnable r = () -> {
   // some logic should run with request context
}

ctx.run(r);
```

This seems a shortcut for ctx.makeContextAware(r).run(), I can avoid to create additional Runnable.
And I think we can also for other functional interfaces i.e, `Supplier`, `Callable`... 😀

**Comment by JunoJunho** [comment]
I am still not sure why this feature is required.

This issue is for providing handy interfaces ?

You said that this can be reduced additional runnable interface creation. (Maybe reusing existing runnable instance, right?) Still, I could not come up easily the situation is.

**Comment by jongmin92** [comment]
Could I handle this issue?

**Comment by ikhoon** [comment]
Sure, please take a look! 🙇‍♂️
