### ISSUE TITLE
Context-awareness of `ServiceRequestContext.blockingTaskExecutor()` 

### ISSUE THREAD

**Issue by trustin** [line/armeria#2629]
Unlike `ctx.eventLoop()` or `ctx.executor()`, `blockingTaskExecutor()` returns a context-aware executor, which is inconsistent.

How about:

- renaming `blockingTaskExecutor()` to `contextAwareBlockingTaskExecutor()` or
- adding an optional `boolean contextAware` parameter to `blockingTaskExecutor()`,

.. while making `blockingTaskExecutor()` return a non-context-aware version?

We could also add a context-aware version of `eventLoop()` and `executor()`. What do you think?

**Comment by anuraaga** [comment]
I'd lean towards removing the non-context-aware versions and remove the `contextAware` prefixes. Having all items returned from a context being context aware seems nice semantically. And the cost of a couple wrapper objects shouldn't be so bad.

**Comment by trustin** [comment]
I then wonder if we should use a different type than plain `EventLoop` or `ScheduledExecutorService` to prevent a user from using it for out-of-context situation. :thinking:

**Comment by minwoox** [comment]
> using it for out-of-context situation. 🤔

If so, perhaps we can guide to use other APIs? such as `CommonPools`? 🤔
