### ISSUE TITLE
Add metrics about `PooledByteBufAllocator`

### ISSUE THREAD

**Issue by trustin** [line/armeria#2633]
Netty already exposes the metrics about its `PooledByteBufAllocator`. We could expose that information into Armeria's Micrometer metrics: https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocatorMetric.java

**Comment by Bue-von-hon** [comment]
May I continue with this issue?

**Comment by ikhoon** [comment]
Yes, please.
