### ISSUE TITLE
User-agent header is not changeable.

### ISSUE THREAD

**Issue by gotchazipc** [line/armeria#266]
While digging into code, I found that <code>HttpClientDelegate</code> always set User-Agent header with a fixed value, over-writing existing one. Is this behavior intended? It would be nice to make the value customizable.

**Comment by trustin** [comment]
It's a bug if a user cannot override it using `ClientOption.HTTP_HEADERS` option.

**Comment by gotchazipc** [comment]
Fixing the bug, I found that <code>ClientOption.HTTP_HEADERS<code> precedes headers from request. The behavior prevents to set some 'default' value to client options to be overrided by requests. Is it a bug, too?

**Comment by trustin** [comment]
That's a good question, and it leads to the bigger one: Do we need `ClientOption.HTTP_HEADERS`? Can't we achieve the same thing using decorators? Maybe should we replace `HTTP_OPTIONS` with a `DecoratingClient` implementation?

**Comment by gotchazipc** [comment]
If we can provide a simple & customizable decorator that manipulates request header, the <code> HTTP_HEADERS</code> option could be deprecated or removed, someday. Using decorator is more flexible than using (fixed) headers option, but it will make code a  little bit more verbose, I think. 

If we preserve <code>ClientOption.HTTP_HEADERS</code>, new decorator will change request header before filling request headers with <code>HTTP_HEADERS</code>. Although the decorator can do everything that <code>HTTP_HEADERS</code> does, having both of them looks not so bad. Users may create some 'dynamic' header value for a request (e.g. request counter) with the decorator, and set fixed header value to it with <code>HTTP_HEADERS</code>.

**Comment by trustin** [comment]
The HTTP_HEADERS option has a problem with derived clients. Consider the following case:

```java
HttpClient client = Clients.newClient("none+http://...", HttpClient.class, .... HTTP_OPTIONS);
HttpClient derivedClient = client.withOptions(...HTTP_OPTIONS...);
```

Let's say a user want to add a few more headers to the original client. It's not very convenient to achieve that with `ClientOptions` because you can only replace an option.

With a decorator, we can provide much more flexible and fluent API. For example:

```java
clientBuilder.decorate(HttpRequest.class, HttpResponse.class,
        new HttpHeaderInjectingClientBuilder()
                .add(headerToAdd, value)
                .set(headerToReplace, value)
                .buildDecorator());
```

We may also revisit the client decoration API in the future to remove the first two type parameters in decorate(), but that's another story.

**Comment by gotchazipc** [comment]
Thanks for advice. I could not think about derived clients. 

Creating a new <code>DecoratingClient</code> looks interesting and a little bit complex, for it requires to understand delegation/decoration chain system in the client quite well. How about piling another issue to discuss on it?

**Comment by trustin** [comment]
> Creating a new <code>DecoratingClient</code> looks interesting and a little bit complex, for it requires to understand delegation/decoration chain system in the client quite well. How about piling another issue to discuss on it? 

Sure. No problem.

**Comment by gotchazipc** [comment]
PR has merged. I'll pile another issue for 'HttpHeaderInjectingClient'
