### ISSUE TITLE
Adding version information to User-Agent string 

### ISSUE THREAD

**Issue by gotchazipc** [line/armeria#267]
I've implemented a ant task in pom.xml to create Version.java with project version. (This one will remove a to-do item in <code>HttpHeaderUtil</code>) 

There are several known ways to pass version information to runtime. Simply creating a source file with ant will do and does not require to change pom.xml a lot, since armeria uses maven-antrun-plugin already. Using manifest information seems to fail sometimes, especially in maven test phase. 

Anyone interested?

**Comment by trustin** [comment]
I'd prefer using a Groovy script because we already use the groovy plugin already as well, and we hope to migrate to Gradle in the not-so-distant future.

**Comment by gotchazipc** [comment]
I've wrote a groovy-script and fixing test cases which checks user-agent header value. The changes conflicts with PR #270.
