### ISSUE TITLE
Consider always adding major version of library to non core artifact

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2676]
Some of artifact IDs of modules are published with the major version of certain libraries such as RxJava, Tomcat, Thrift.
We don't explicitly append the major version to artifact ID if it is the latest version.

The latest major version of RxJava is 3. That means `armeria-rxjava` will support RxJava 3. If users want to use an older version of RxJava such as RxJava 2, they should append the major version of RxJava to `armeria-rxjava`.

* `armeria-rxjava` supports RxJava 3
* `armeria-rxjava2` supports RxJava 2

This is not a problem when a user adds `armeria-rxjava` dependency for the first time for RxJava 3.
What if RxJava releases version 4?
We have to change to `armeria-rxjava` to `armeria-rxjava3`, `armeria-rxjava` will support RxJava 4.
If the user upgrades the Armeria version, the version of RxJava will be unexpectedly upgraded to RxJava 4 from 3.

To resolve this issue, we can always add the major version to the artifact ID.
This is not limited to the major version. Since some of our modules support minor versions such as tomcat8.5, thrift0.9

**Comment by minwoox** [comment]
I prefer adding the version number because we cannot handle it when the new version comes out without breaking change.

**Comment by trustin** [comment]
Sorry about my bad decision in the past. +1 for appending the major version.

**Comment by anuraaga** [comment]
Also a time to discuss `armeria-contrib` org and moving out some repos? It's a loo-ot of modules that we have to keep up to date for every Armeria release and doesn't feel sustainable.

Particularly related to this, if modules always have major version attached, it's simple to just copy the code out to a new repo for legacy ones that don't really need to be updated every time Armeria releases.

**Comment by minwoox** [comment]
> Also a time to discuss armeria-contrib 

That's a good idea. After we release 1.0, there's no breaking changes, so we don't have to update all modules to the latest.

**Comment by trustin** [comment]
Yeah, I agree that we can move the modules we do not want to support anymore to a separate place.

However, this doesn't mean that we need to move the modules for **all** old versions (e.g. tomcat8.5). The modules we want to support will should stay here. I'd like to consider such a separate place would be used only for archival purposes.
