### ISSUE TITLE
Refine module structure

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2677]
I want to discuss:
- Putting related modules into one directory. For example:
  - `rxjava2` and `rxjava3` under `rxjava` directory. (`thrift` and `dropwizard` as well)
  - service discovery modules under `discovery` directory.
- Changing the name of ZooKeeper artifact from `armeria-zookeeper` to `armeria-zookeeper-discovery`

Currently, I'm implementing service discovery using Eureka.
While I'm working on it, I was wondering if we need a separate directory for discovery because the number of discovery modules might get increased.
We are going to have at least three different discovery in the near future:
- Consul
- Eureka
- ZooKeeper

If we have them all under the `discovery` directory, it will be a little better to maintain those.
For the other modules, we have all Spring modules in `spring` directory.
But we didn't for others such as rxjava, thrift and dropwizard. I was wondering if we need to do the same approach. (rxjava tends to be grown #2676)

For the second, the name of `armeria-zookeeper` is a little vague, because ZooKeeper can be used in various ways, unlike Eureka which is just for service discovery.

**Comment by minwoox** [comment]
For me, I'd like to put the discovery module into one directory at least.
Also, I want to change the artifact name to `armeria-zookeeper-discovery` or something else, but not strong on it.

**Comment by ikhoon** [comment]
Spring or RxJava are grouped by their dependency. However, Consul, Eureka, ZooKeeper are grouped by discovery functions.

I'm not sure which approach is better for us. 


> I want to change the artifact name to armeria-zookeeper-discovery

+1, It seems clearer.

**Comment by minwoox** [comment]
> However, Consul, Eureka, ZooKeeper are grouped by discovery functions.

Yes, exactly. I'm not strong on this neither. 😄

**Comment by minwoox** [comment]
As @anuraaga commented https://github.com/line/armeria/issues/2676#issuecomment-618280781, we might move all discovery modules to the new repository because there's not so much chance code is changed. 🤔

**Comment by trustin** [comment]
> Spring or RxJava are grouped by their dependency. However, Consul, Eureka, ZooKeeper are grouped by discovery functions. I'm not sure which approach is better for us.

That's a good point. Let me think about this and come back later.

> As @anuraaga commented https://github.com/line/armeria/issues/2676#issuecomment-618280781, we might move all discovery modules to the new repository because there's not so much chance code is changed.

We need to keep the modules we want to maintain and support in this repository. At our community scale, such a repository can be abandoned really easily.

**Comment by trustin** [comment]
So, how about this, for consistency:

- Name all modules as `armeria-<dependency>`, e.g.
  - `armeria-junit4`, `armeria-junit5`, `armeria-zookeeper`, ...
- Name common modules as `armeria-common-*`, e.g.
  - `armeria-common`, `armeria-common-testing`, `armeria-common-discovery`, ...

..?

**Comment by minwoox** [comment]
> armeria-<dependency>, armeria-common-*

Sounds good to me. 😄
