### ISSUE TITLE
Logging decorator factories should match semantics of empty builder

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2696]
We deviated the behavior of the factories and builders a long time ago to preserve backwards compatibility of factories before we added the builders, but at the time we figured the better default for successful requests is `TRACE` to reduce log spam. So we should change the factory finally to just call `builder().build()` to reduce confusion of the defaults. This would mean either the factory's behavior changes to TRACE successful log entries, or the builder needs to be changed so successful log entries are INFO.

**Comment by trustin** [comment]
I found that difference strange, too. Would be nice to sort it out before 1.0.

**Comment by trustin** [comment]
@imasahiro @kojilin Thoughts?

**Comment by kojilin** [comment]
The factory is like `LoggingClient#newDecorator` ? Sounds reasonable to change at 1.0.0 for breaking change.

**Comment by minwoox** [comment]
> This would mean either the factory's behavior changes to TRACE successful log entries,

+1 for this. 😉
