### ISSUE TITLE
Allow binding an annotated service method without a path

### ISSUE THREAD

**Issue by trustin** [line/armeria#2708]
(From @KarboniteKream)

Let's assume we have the following annotated service:

```java
Server.builder()
      .annotatedService("/my/service", new Object() {
          @Get("/")
          String root() {
              return "hello";
          }
      });
```

In this case, `GET /my/service` will not work while `GET /my/service/` will. To be precise, `GET /my/service` will be redirected to `GET /my/service/`, i.e. a client needs to handle redirects.

Although this is working as intended, but it'd be nice if a user is allowed to handle a request at `/my/service` as well. What would be the best way to support this use case? Here are some ideas:

- Allow specifying an empty path, e.g. `@Get("")`
  ```java
  @Get("") @Get("/")
  String root() { ... }
  ```
- Allow leaving a path as unspecified, e.g. `@Get` without `@Path` annotation
  ```java
  @Get @Get("/")
  String root() { ... }
  ```

I'm slightly in favor of the former, but let me know what you think.

**Comment by heowc** [comment]
I will work on it 😊
