### ISSUE TITLE
Add a way to disable TLS verification for certain hosts only

### ISSUE THREAD

**Issue by trustin** [line/armeria#2722]
From OkHttp 4.7.0:

> `HandshakeCertificates.Builder.addInsecureHost()` makes it easy to turn off security in private development environments that only carry test data. Prefer this over creating an all-trusting `TrustManager` because only hosts on the allowlist are insecure. From our DevServer sample:
>
> ```kotlin
> val clientCertificates = HandshakeCertificates.Builder()
>     .addPlatformTrustedCertificates()
>     .addInsecureHost("localhost")
>     .build()
>
> val client = OkHttpClient.Builder()
>     .sslSocketFactory(clientCertificates.sslSocketFactory(), clientCertificates.trustManager)
>     .build()
> ```

**Comment by tumile** [comment]
Hi, I just opened a PR to address this issue. Please check it out. Thanks!
