### ISSUE TITLE
Building a project via Maven / Shade and Armeria as a dependency requires certain order in pom.xml

### ISSUE THREAD

**Issue by andrey-tpt** [line/armeria#2731]
If "armeria" package is not the first in the list of dependencies in pom.xml among other "armeria-*" packages then the code consistently fails on an attempt to construct a client.

E.g. 
  ```
  <dependency>
      <groupId>com.linecorp.armeria</groupId>
      <artifactId>armeria-grpc</artifactId>
      <version>0.99.4</version>
    </dependency>
   <dependency>
      <groupId>com.linecorp.armeria</groupId>
      <artifactId>armeria</artifactId>
      <version>0.99.4</version>
    </dependency>
```

consistently leads to 

```
! java.lang.ExceptionInInitializerError: null
! at com.linecorp.armeria.client.ClientOption.<clinit>(ClientOption.java:69)
! at com.linecorp.armeria.client.AbstractClientOptionsBuilder.factory(AbstractClientOptionsBuilder.java:120)
! at com.linecorp.armeria.client.ClientBuilder.factory(ClientBuilder.java:147)
...
Caused by: ! java.lang.NullPointerException: null
! at com.linecorp.armeria.internal.common.ArmeriaHttpUtil.<clinit>(ArmeriaHttpUtil.java:225)
```

I think this happens because by default Shade plugin will keep the first `com.linecorp.armeria.versions.properties` it encounters and will not merge the files from other packages together. Therefore there is no "armeria" key in the map and the code [1] in ArmeriaHttpUtil fails with NPE

Observed in v. 0.99.4 

[1] https://github.com/line/armeria/blob/armeria-0.99.4/core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java#L223

**Comment by trustin** [comment]
Should be fixed in 0.99.6. Please feel free to reopen if it's still an issue. :bow:
