### ISSUE TITLE
Support java.time.Period type as a `@Param` in annotated service

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2760]
It will be convenient if a user can specify `java.time.Period` as a `@Param`:
```java
class MyAnnotatedService {
    @Get("/data")
    HttpResponse getAllDataDuringThePeriod(@Param Period period) {...}
}
```
We might use the format specified [here](https://docs.oracle.com/javase/8/docs/api/java/time/Period.html#parse-java.lang.CharSequence-)

**Comment by ghkim3221** [comment]
I can do it 🙋‍♂️

**Comment by minwoox** [comment]
Thanks! It's all yours. 😄 
You might want to look at `AnnotatedServiceTypeUtil`.
Also, we might need to change `AnnotatedDocServicePlugin` to support `Duration` in DocService as well. 😉
