### ISSUE TITLE
`GrpcMeterIdPrefixFunction`?

### ISSUE THREAD

**Issue by trustin** [line/armeria#2762]
Originally suggested by @okue 

It'd be nice to have a dedicated `MeterIdPrefixFunction` implementation for gRPC, so that the tag for `grpc-status` is added automatically.

**Comment by okue** [comment]
To make [`MeterIdPrefixFunction`][1] easier to customize,
how about adding some functions to [`MeterIdPrefixFunction`][1]?

```java
static MeterIdPrefixFunction ofDefault(
    String name,
    BiConsumer<MeterRegistry, ? super RequestOnlyLog> consumer
) {
    ...
}
```

or

```java
default MeterIdPrefixFunction andThen(
    Function3<MeterRegistry, ? super RequestOnlyLog, MeterIdPrefix, MeterIdPrefix> consumer
) {
    ...
}
```

[1]: https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java

**Comment by trustin** [comment]
That's a good idea. I like the latter. What do you think, @line/dx?

**Comment by ikhoon** [comment]
I also prefer the `andThen` version. But Java does not have `Function3` or triple function. We might need a customizer interface.

**Comment by okue** [comment]
Now, we can set `grpc-status` to `MeterIdPrefix` easily using `MeterIdPrefixFunction#andThen(MeterIdPrefixFunctionCustomizer)`.

BTW, is it better to offer `GrpcMeterIdPrefixFunction`?
If so, should `GrpcMeterIdPrefixFunction` use `andThen`, or optimize something..?

**Comment by trustin** [comment]
That's a good question. I think it will be useful to provide one out of the box. It'd be nice if we have an optimized version, but we will have to refactor a little bit to de-duplicate the common logic from the default prefix function. Alternatively, we could duplicate a little bit and just write some tight test cases.

**Comment by ikhoon** [comment]
I prefer `GrpcMeterIdPrefixFunction` because `grpc-status` can be gotten from:
- headers if a response body is empty
- trailers if a response body is not empty and the protocol is normal gRPC
- last of bodies if a response body is not empty and the protocol is gRPC-Web

**Comment by trustin** [comment]
How could we get the `grpc-status` trailer from a gRPC-Web response?

**Comment by trustin** [comment]
Probably worth getting this done before 1.0 to solve the gRPC-Web trailer handling problem..

**Comment by minwoox** [comment]
Let me work on this after finishing #2911

**Comment by okue** [comment]
When using gRPC with `armeria-spring-boot`, all services are decorated with `MeterIdPrefixFunction.ofDefault`.
I'd be happy if `GrpcMeterIdPrefixFunction` is used for gRPC services.

https://github.com/line/armeria/blob/armeria-1.0.0/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java#L131-L132
