### ISSUE TITLE
Add `RequestLog.serviceName()`

### ISSUE THREAD

**Issue by trustin** [line/armeria#2768]
`RequestLog.name()` was a great addition that provides a universal human-readable name of a request. However, it currently only reveals a method name. It would be nice if we also provide a similar API for getting the name of a service. For example:

```java
Server.builder()
      .route()
          ...
          .defaultServiceName("MyService")
          .build(myService)
      .annotatedService()
          ...
          .defaultServiceName("MyService2")
          .build(myAnnotatedService)
      ...
```

If not specified, it could be auto-generated from the innermost class name, etc.

**Comment by trustin** [comment]
This may also greatly simplify our default `MeterIdPrefixFunction`, because we will not need tags like `route`.

**Comment by trustin** [comment]
We might need to add `serviceName` to `RequestLog`, because a single service instance might be providing multiple services, e.g. `GrpcService`.

**Comment by trustin** [comment]
@ikhoon found some inconsistency between Thrift and gRPC: `RequestLog.name()` returns `com.foo.bar.Service/method` for gRPC while `method` for Thrift.

This also leads to a question - Do we need a new field in `RequestLog` or should we just prepend service name to `name`? I think a dedicated field is better for now.

**Comment by ikhoon** [comment]
> Do we need a new field in RequestLog or should we just prepend service name to name? I think a dedicated field is better for now.

I prefer having dedicated fields. My suggestions are:

- `RequestLog.serivceName()` that returns an RPC service name or innermost class name for an annotated service.
- `RequestLog.methodName()` that returns only method name.
- `RequestLog.name()` that returns a combined service and method name.
  For example `com.foo.bar.Service/method`

**Comment by ikhoon** [comment]
Had chat on `methodName()` and not all services has method name such as: 
```
Server.builder()
      .service((ctx, req) -> {
          ...
          return HttpResponse.of(...);
      });
```


- RequestLog.serivceName() that returns an RPC service name or innermost class name for an annotated service.
- RequestLog.name() that returns only a method name or null if it is a plain Service.
- RequestLog.fullName() that returns a combined service and name. (ex: `com.foo.bar.Service/method`)
