### ISSUE TITLE
Remove StreamMessage.drainAll?

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2782]
I was looking through the codebases for usage of `drainAll` and couldn't find any that seemed important (most were testing the `drainAll` method itself). Let me know if I missed any.

`drainAll` seems to be a poor version of `aggregate`, is there any use case we imagine for `drainAll`?

**Comment by trustin** [comment]
It's used in some test cases for ensuring the exact publication of elements. Maybe it's better using other testing libraries for reactive streams, but it's pretty handy.

**Comment by anuraaga** [comment]
I see - what do you think about moving it to `armeria-testing`? We could even make a method that works like `assertThat(stream).drainsTo()` or similar.

Not a great reason, but main reason I noticed this is not wanting to add yet more methods like `drainAllWithSubscribedObjects` 😅

**Comment by trustin** [comment]
How about moving `drainAll` to `testing-internal` or replacing its usage with `StepVerifier`, then? I guess most users will be OK with using `aggregate()`.

**Comment by minwoox** [comment]
Let's `(re|)move`.

**Comment by minwoox** [comment]
Let me work on this. 😉
