### ISSUE TITLE
Support `server.shutdown` property of Spring Boot

### ISSUE THREAD

**Issue by heowc** [line/armeria#2784]
I heard that Spring Boot has released [`2.3.0.RELEASE`](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#graceful-shutdown). And the following properties have been added to the version.

- `server.shutdown`
- `spring.lifecycle.timeout-per-shutdown-phase`

Armeria also seems to need to support this property. What do you think?

See https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/spring-boot-features.html#boot-features-graceful-shutdown

**Comment by trustin** [comment]
Hi @heowc! That's a good idea. How would our graceful shutdown option be mapped to theirs?

**Comment by heowc** [comment]
We offer two options for graceful shutdown (`quietPeriod`, `timeout`).

In fact, this is ambiguous because there is only one property(`spring.lifecycle.timeout-per-shutdown-phase`) provided by Spring Boot. So how about mapping the two options to the same value?

**Comment by trustin** [comment]
That sounds OK to me. We can adjust later if needed.

**Comment by eonezhang** [comment]
you guys are quick responders.
