### ISSUE TITLE
Feature mismatches between binding builders and Spring registration beans

### ISSUE THREAD

**Issue by trustin** [line/armeria#2787]
We recently added many service-level configuration options to our fluent service binder. However, they are missing in our Spring registration beans, e.g. `AccessLogWriter`.

This means:

- We have to add the same set of properties to registration beans when we update our service binding API.
- We have to update the code that translates the registration beans into our service binding API.

.. which are just a bunch of boilerplate code that does not add much value in my opinion. I'm curious if Spring community really prefers registration beans to `ArmeriaServerConfigurator`. If so, what value does it bring Armeria+Spring users beyond following the convention?

This issue was discussed briefly at https://github.com/line/armeria/issues/1704#issuecomment-481236467 without clear conclusion, and I'd like to get to some conclusion before 1.0.

**Comment by minwoox** [comment]
> which are just a bunch of boilerplate code that does not add much value in my opinion.

I agree with it. So I really want to remove the APIs. But I'm extremely worried because there are so many users using it. 😭

**Comment by trustin** [comment]
`com.linecorp.armeria.spring.MeterIdPrefixFunctionFactory` could be removed as well now that we have `ServiceConfig.defaultServiceName()`.
