### ISSUE TITLE
Support java.time.Duration type for `@Param` annotation

### ISSUE THREAD

**Issue by ghkim3221** [line/armeria#2792]
As follow-up of #2783 (#2760), how about also support `java.time.Duration` type for `@Param` annotation?

```java
class MyService {

    @Get("/data")
    HttpResponse getAllDataDuringTheDuration(@Param Duration duration) {
        ...
    }
}
```

**Comment by heowc** [comment]
In addition to this, it would be better to support the classes in the [`java.time` package](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html).

**Comment by trustin** [comment]
SGTM. Please go ahead 😄
