### ISSUE TITLE
Add an annotation that specifies the default service name

### ISSUE THREAD

**Issue by trustin** [line/armeria#2809]
It would be nice if there's an annotation that overrides the default service name in an annotated service:

```java
@ServiceName("myService")
public class MyService {
    @Get("/")
    public String get() { ... }

    @ServiceName("myPostService")
    @Post("/")
    public String post() { ... }

    @Delete("/")
    public String delete() {
        // Can be overridden programmatically.
        ServiceRequestContext.current().logBuilder().name("myDeleteService", "delete");
        ...
    }
}
```

**Comment by ikhoon** [comment]
> ```java 
> @Delete("/")
> public String delete() {
>     // Can be overridden programmatically.
>     ServiceRequestContext.current().logBuilder().name("myDeleteService", "delete");
>     ...
> }
> ```

`RequestLog.name()` and `RequestLog.serviceName()` was set before serving an annotated service.
Users have to override it programmatically using a decorator.
