### ISSUE TITLE
`PooledHttpRequest/Response` overhead

### ISSUE THREAD

**Issue by trustin** [line/armeria#2859]
`DefaultPooledHttpRequest/Response` seems to have the following hidden(?) overheads comparing to the old `SubscriptionOptions.WITH_POOLED_OBJECTS` approach:

- It always filters all elements using `FilteredStreamMessage`, increasing the level of indirection.
- It always wraps all elements with `PooledHttpData`, even if it's just an array-backed one, causing additional object allocation and reference counting overhead. This can be a problem especially on the client side or when decorators are in action.

Safety is a good thing, and I don't have any solid numbers about this, but I'm concerned that the overhead may diminish the performance gain hard-earned by reducing memory copies. Why would advanced users use `Pooled*` classes when they are using this API for more throughput and they can squeeze more out by just using `InternalSubscriptionOptions.WITH_POOLED_OBJECT` directly? They are supposed to be advanced users anyway. 🤔

**Comment by anuraaga** [comment]
I think wrapping came out of this comment ;)

https://github.com/line/armeria/pull/1938#pullrequestreview-268774847

Compared to the size of payloads where the pooling helps, I guess the wrapper objects are pretty small and wouldn't worry too much as a user of it, but it's definitely something that came to mind.

**Comment by trustin** [comment]
> I think wrapping came out of this comment ;)

Yeah, the problem though is that I didn't think much about the overhead of wrapping all `HttpData` instances. 😅 

Anyways, this overhead is something we need to keep in mind and optimize somehow.

For example, we could:

Make all package-private `StreamMessage` and `HttpData` implementations also implement `Pooled*` so that wrapping does not occur at all and we do not need to use `FilteredStreamMessage`.

**Comment by trustin** [comment]
Probably solved by #2882 and #2892. Let's continue the discussion at #2892.
