### ISSUE TITLE
Hard to find feature documentation on mobile

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2871]
I had a lot of trouble finding documentation on features like gRPC on mobile because

- There are two hamburger menus
- There is a Jump to drop-down with light text that I missed for a while. I think its uncommon to have to expand twice, once hamburger and once again

![Screenshot_20200703-201904](https://user-images.githubusercontent.com/198344/86464993-ab38d400-bd6b-11ea-8fdd-62778ec864a6.png)
![Screenshot_20200703-201909](https://user-images.githubusercontent.com/198344/86464999-ad029780-bd6b-11ea-9361-c4722236428b.png)

**Comment by anuraaga** [comment]
By the way the first thing I did was click Features which went to something else.

**Comment by trustin** [comment]
That's a good point, @anuraaga. Let me try to redesign the navigation over the weekend (if possible).

**Comment by trustin** [comment]
What's your browser/OS by the way? Slack and Github icons are not vertically aligned correctly.

**Comment by anuraaga** [comment]
Ah sorry for missing, this is Firefox Beta on Android
