### ISSUE TITLE
ArmeriaSettings.enableMetrics doesn't work with ArmeriaServerConfigurator (Spring integration feature)

### ISSUE THREAD

**Issue by okue** [line/armeria#2873]
[com/linecorp/armeria/spring/ArmeriaSettings.java#L304-L308][1] says _"Whether to decorate all services with MetricCollectingService"_, but it seems that only services registered via `XxxServiceRegistrationBean` are automatically decorated with `MetricCollectingService`.

It would be good if armeria do either
- decorate all services with `MetricCollectingService` if `ArmeriaSettings.enableMetrics` is true
- or remove this flag `ArmeriaSettings.enableMetrics`

[1]: https://github.com/line/armeria/blob/armeria-0.99.8/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java#L304-L308

**Comment by ikhoon** [comment]
> decorate all services with MetricCollectingService if ArmeriaSettings.enableMetrics is true

+1 

Previously each registration bean has its own `MeterIdPrefixFunction` via `MeterIdPrefixFunctionFactory` for `serviceName`. I guess it is hard to apply global `MetricCollectingService` using single `MeterIdPrefixFunction`. 

But now Armeria injects `serviceName` automatically via #2768. That means we can add `MetricCollectingService` on the top level with a default value such as `MeterIdPrefixFunction.ofDefault("armeria")`

Additionally, `ArmeriaSettings.enableMetrics` not only adds `MetricCollectingService` to a `XxxServiceRegistrationBean` but also exposes Prometheus or Dropwizard metrics.

**Comment by trustin** [comment]
Thanks a lot for fixing this issue, @imasahiro :bow:

**Comment by okue** [comment]
Thanks!!
