### ISSUE TITLE
When passing through h1->h2 proxy, Armeria authority and hostname are wrong

### ISSUE THREAD

**Issue by tobias-** [line/armeria#2877]
After passing my http1.1 request through a HAproxy (2.1.7), Armeria sets the following values:
```
requestContext.routingContext().hostname() = "web-fa2a2eb-67f5bf8bc5-tnjf6"
requestContext.requestHeaders().authority()  = "web-fa2a2eb-67f5bf8bc5-tnjf6:8443"
requestContext.requestHeaders().get("host") = "example.com"
requestContext.requestHeaders().get(":authority") = "web-fa2a2eb-67f5bf8bc5-tnjf6:8443"
```

web-fa2a2eb-67f5bf8bc5-tnjf6 is the internal hostname of the Armeria server
example.com is the hostname of the external request

To test this, simply make a snakeoil-cert (or use any other pem), set the path in the haproxy.cfg below, start armeria on port 8444 and curl port 8443.

The following two following lines show the problem
```
curl https://localhost:8443 -k --http2
curl https://localhost:8443 -k --http1.1
```

NB. HAproxy has changed how they handle `Host` and `:authority` headers relatively recently. Using E.g. 2.0.x (the latest available in ubuntu) will NOT produce the same result as newer HAproxy versions (e.g. 2.1.7). They said this was in response to discovering that they handled it incorrectly before. I previously reported this as https://github.com/haproxy/haproxy/issues/716, because I was under the impression that this was a bug in HAproxy.

Example haproxy.cfg (may be run as normal user)
```
global
    log stdout format raw daemon debug
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
frontend web
    bind :8443 ssl alpn h2,http/1.1,grpc-exp crt /path/to/any/x509_cert_including_key.pem
    use_backend armeria
backend armeria
    balance roundrobin
    option forwardfor
    server server1 localhost:8444 ssl verify none alpn h2 check check-alpn http/1.1
```

**Comment by tobias-** [comment]
Forgot to mention that this bug had a partial fix in 
https://github.com/line/armeria/pull/2850

**Comment by trustin** [comment]
Should be fixed now. Thanks for reporting, @tobias- !

**Comment by tobias-** [comment]
Thank you for quick resolution!

@trustin @minwoox
