### ISSUE TITLE
Typo in document "Using Armeria with Spring WebFlux"

### ISSUE THREAD

**Issue by ghkim3221** [line/armeria#2896]
In the document [Using Armeria with Spring WebFlux](https://armeria.dev/docs/advanced-spring-webflux-integration/), the `dependencyManagement` of Gradle example seems wrong:

AS-IS:
```
dependencyManagement {
    imports {
        mavenBom '0.99.8'
        mavenBom '4.1.50.Final'
    }
}
```

TO-BE:
```
dependencyManagement {
    imports {
        mavenBom 'com.linecorp.armeria:armeria-bom:0.99.8'
        mavenBom 'io.netty:netty-bom:4.1.50.Final'
    }
}
```

**Comment by okue** [comment]
This typo is fixed by https://github.com/line/armeria/pull/2874.

**Comment by ghkim3221** [comment]
Oh, thank you 😃
