### ISSUE TITLE
Overload Functions.compose() to compose more than 2 functions

### ISSUE THREAD

**Issue by trustin** [line/armeria#29]
/cc @synk @inch772 

Currently, `Functions.compose()` composes two functions only. It would be more useful if it can compose more than 2 functions. We could use varargs, but we would lose compile-time type safety. Perhaps we could add several overloaded methods that accepts the specific numbers of functions. Maybe up to 9?

**Comment by synk** [comment]
:pray:

**Comment by trustin** [comment]
Fixed via #34
