### ISSUE TITLE
gRPC web text support

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2911]
- https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md#protocol-differences-vs-grpc-over-http2
- https://grpc.io/blog/state-of-grpc-web/#feature-sets

Note that gRPC web text support server-side streams, unlike gRPC web.

**Comment by anuraaga** [comment]
For reference, it seemed like it'd be simple to add support for it but base64 decoding seemed like a huge refactor.

To clarify, gRPC web also supports streams, just not the Google official client library. gRPC web text was added to support streams on IE10 IIRC. 

The improbable client is in general better written so I'm sad that Google forked the ecosystem with this strange text protocol :(

**Comment by anuraaga** [comment]
That doesn't mean Armeria shouldn't support it but should be clear on the motivation :) I'd generally recommend docs on our side to point at the improbable client though

**Comment by minwoox** [comment]
> To clarify, gRPC web also supports streams, just not the Google official client library. gRPC web text was added to support streams on IE10 IIRC.

Oops, I thought gRPC web doesn't support the server-side streams. Thanks for clarifying that.

> That doesn't mean Armeria shouldn't support it but should be clear on the motivation 

It was just me that wanted to understand how gRPC works internally by implementing this feature. 😄 
Let me work on this. If there's a regression on performance or design, I will abandon it.
