### ISSUE TITLE
Provide a way to get notified when a request is timed out

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2937]
Currently, when a request is timed out, users could get notified using:
- Register callback using `ServiceRequestContext.setRequestTimeoutHandler(callback)`.
  But this is not recommended because it overrides the default behavior of the internal timeout task.
  As like the Javadoc of `setRequestTimeoutHandler()` said, users should close a response manually.
- Check the response cause using 
  ```java
  ctx.log().whenComplete().whenComplete((log, cause) => {
      if (cause == ResponseTimeoutException.get()) {
          // release some resources and cancel some tasks when a request is timed out.
      }
  });
  ```

This is not a convenient way to listen to a timeout event.
I think we could add `whenTimedOut()` to `RequestContext`
```java
interface RequestContext {
    CompletableFuture<Void> whenTimedOut();
}

ctx.whenTimedOut().thenRun(() => {
   // release some resources and cancel some tasks when a request is timed out.
});
```

**Comment by trustin** [comment]
Are we removing `ctx.set*TimeoutHandler()` then?

**Comment by ikhoon** [comment]
> Are we removing `ctx.set*TimeoutHandler()` then?

That sounds good. Let me try it.
