### ISSUE TITLE
Use Caffeine in `RefresingAddressResolver`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2970]
Currently, `RefresingAddressResolver` removes DNS caches that are not hit during the TTL.
If we use caffeine, we can keep them a little longer than TTL while refreshing DNS after TTL is passed.

**Comment by jrhee17** [comment]
🙋

**Comment by masonshin** [comment]
@jrhee17 May I handle this issue? Actually, I have some works while checking the related issues.
If you have already done so, no problem~

**Comment by jrhee17** [comment]
Sure, all yours 👍

**Comment by minwoox** [comment]
rock scissors paper?
🤣
