### ISSUE TITLE
Set `TCP_USER_TIMEOUT` by default.

### ISSUE THREAD

**Issue by trustin** [line/armeria#2976]
Read https://github.com/grpc/proposal/blob/master/A18-tcp-user-timeout.md for the background. We could do the same for all TCP/IP sockets we use. We could:
- Add the default value of `TCP_USER_TIMEOUT` option to `Flags`
- Set it in the constructors of `ClientFactoryBuilder` and `ServerBuilder`.

**Comment by trustin** [comment]
@jrhee17 If you're looking for something interesting, you might want to give this one a try. You might want to:

- look into all epoll/specific options in Netty and enable some of them with sensible defaults.
- add some generic flag for default socket options instead of adding one flag for each.

**Comment by amitvc** [comment]
@jrhee17  @trustin if no one has picked up this issue I can start work on it.

**Comment by jrhee17** [comment]
> if no one has picked up this issue I can start work on it.
Sure, go for it 👍

**Comment by amitvc** [comment]
> @jrhee17 If you're looking for something interesting, you might want to give this one a try. You might want to:
> 
> * look into all epoll/specific options in Netty and enable some of them with sensible defaults.
> * add some generic flag for default socket options instead of adding one flag for each.

@trustin Looks like netty uses this option when epoll and keepalive is enabled. See details here 
https://github.com/grpc/grpc-java/pull/5599

Can you please point me to classes where we use TCP/IP sockets? Do we use nio based SocketChannels or we use netty's SocketChannels?

**Comment by trustin** [comment]
@amitvc We use Netty `SocketChannel`s. 

We specify `ChannelOption`s for `ServerSocketChannel`s and `SocketChannel`s here on the server side: https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/Server.java#L451-L462

For the client side, check this out: https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java#L123-L127

We could first check if a user specified the `TCP_USER_TIMEOUT` option explicitly. If a user did not specify the option, we could set the option with the default value. Otherwise, we could use the option value the user specified. (Could do the same for other options you're gonna set by default.)

**Comment by jrhee17** [comment]
Interesting article by cloudfare

Basically they recommend to:
1) enable `SO_KEEPALIVE`
2) set `TCP_USER_TIMEOUT = TCP_KEEPIDLE + TCP_KEEPINTVL * TCP_KEEPCNT`

Ref: https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/#keepaliveswithtcp_user_timeoutareconfusing

**Comment by jrhee17** [comment]
Note: Won't think about server-side for this iteration since `TCP_USER_TIMEOUT` (and other timeout related options) only apply to client-side.

### Application layer
- `maxConnectionAgeMillis`: terminates the connection if a specified time passes
- `idleTimeoutMillis`: terminates the connection if a specified time passes since a connection is idle (and there are no in-flight request/responses)
- `pingIdleTimeNanos`: sends a ping if a specified time passes

**Additional conditions from `ClientFactoryBuilder`**
- `idleTimeoutMillis = min(idleTimeoutMillis, maxConnectionAgeMillis)`
- disabing ping if `pingIntervalMillis >= idleTimeoutMillis`

### Objective
Add socket settings such that it doesn't interfere with the above settings. At the same time, socket-level settings should help the application layer operates correctly (i.e. close lingering connections, ping when the connection is idle)

### Current idea
```
def setupDefaultSocketOptions:
  if defaultFlag = false or user_set(TCP_USER_TIMEOUT, SO_KEEPALIVE, TCP_KEEPIDLE, TCP_KEEPINTVL):
    return
  if idleTimeoutMillis > 0 or maxConnectionAgeMillis > 0:
    TCP_USER_TIMEOUT = max(idleTimeoutMillis, maxConnectionAgeMillis)
  if pingIntervalMillis > 0:
    SO_KEEPALIVE = 1
    TCP_KEEPIDLE = pingIntervalMillis
    TCP_KEEPINTVL = pingIntervalMillis # setting TCP_KEEPCNT may not be too important - TCP_USER_TIMEOUT will dominate if enabled anyways.
```

I'll get started on this idea - if you have any concerns do let me know 🙏

**Comment by minwoox** [comment]
> Note: Won't think about server-side for this iteration since TCP_USER_TIMEOUT (and other timeout related options) only apply to client-side.

I missed this. 😅

**Comment by trustin** [comment]
Thanks for the detailed idea. That is very useful!

> Won't think about server-side for this iteration since TCP_USER_TIMEOUT (and other timeout related options) only apply to client-side.

I thought `TCP_USER_TIMEOUT` is applicable to server-side as well? Can't you set it by using `ServerBootstrap.childOption()`?

> ```
> if idleTimeoutMillis > 0 or maxConnectionAgeMillis > 0:
>     TCP_USER_TIMEOUT = max(idleTimeoutMillis, maxConnectionAgeMillis)
>   if pingIntervalMillis > 0:
>     SO_KEEPALIVE = 1
>     TCP_KEEPIDLE = pingIntervalMillis
>     TCP_KEEPINTVL = pingIntervalMillis # setting TCP_KEEPCNT may not be too important - TCP_USER_TIMEOUT will dominate if enabled anyways.
> ```

- `maxConnectionAgeMillis` is often a very large value. Shouldn't it just be `TCP_USER_TIMEOUT = idleTimeoutMillis`?
- `KEEPALIVE` settings sounds reasonable.
