### ISSUE TITLE
RequestContext.setAttr should return previous value if present

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#2997]
Similar to Map.put

**Comment by trustin** [comment]
Should we return `null` or root context's value when the context doesn't have its own value? I guess it should be the latter but just in case it's unclear. 🤔

**Comment by anuraaga** [comment]
Yeah returning what `getAttr` would have returned seems to make sense to me.

For reference, I thought of this while working on this change, where it would be a small threadlocal lookup optimization.
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/979/files#diff-8b0d34ddeaf7f366eeb03b07f0da0aa4R38

**Comment by trustin** [comment]
I found that `setAttrIfAbsent()` basically does not take the root context into account. This means, even if there's an attribute A in the root context, `setAttrIfAbsent(A, value)` will set the `value` successfully. Same applies to `computeIfAbsent()`.

Wouldn't it be inconsistent if `setAttr()` returns the value retrieved from the root context? I'm not sure if it's a good idea to return its 'own' old value given that it can be another source of confusion.

Should we change the behavior of `setAttrIfAbsent()` and `computeAttrIfAbsent()` to look for the root context? If so, should we make this thread-safe, like acquiring two nested locks (`synchronized (rootCtx) { synchronized (childCtx) { ... } }`?

**Comment by anuraaga** [comment]
Yeah definitely shouldn't make them inconsistent. Semantically, I would expect `IfAbsent` to check the root, the child is supposed to "just contain" what's in the root so it's not absent if it's in the root. The threadsafe might be tough but I think it's unavoidable 😿

**Comment by trustin** [comment]
It looks like some users are using `setAttrIfAbsent()` and `computeAttrIfAbsent()` for both client and server side contexts to set some IDs, which means they still need the version with the old behavior if we change their behavior, e.g. `setAttrIfOwnAbsent` and `computeAttrIfOwnAbsent`. For symmetry, we will need something similar for `setAttr()`.. like `<some nice name>`.

All this complication makes me wonder if it's a good idea to provide `set/computeAttrIfAbsent()` at all. Should we remove `*IfAbsent()` and make `setAttr()` behave like originally suggested here? The users of `set/computeAttrIfAbsent()` could implement it using `hasOwnAttr()` and `setAttr()`, although thread safety will be lost (i.e. should do it by themselves).

Thoughts?

**Comment by minwoox** [comment]
If it's possible, I want to remove the complicated APIs.
I think other libraries do not have such APIs.
For example, this is [Context](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/util/context/Context.java) from Reactor.

**Comment by anuraaga** [comment]
+1 to removing. Would need to see the code to be sure, but it sounds like just `setAttr` should work for IDs in general - IDs are truth, it's weird that you would ever need to rely on someone else's truth, conceptually speaking. So the ifAbsent methods may just be providing confusion too.

**Comment by trustin** [comment]
They all just set the attribute in a decorator, so I guess it's safe to use `setAttr()`. If in doubt, could be guarded with `hasOwnAttr()`.
