### ISSUE TITLE
Allow `LoggingClient` to configure logger name

### ISSUE THREAD

**Issue by ghkim3221** [line/armeria#3029]
Users can configure own `logger` to `LoggingClient` and `LoggingRpcClient`.
Additionally, I think it is more useful if user can configure only logger's name. If `loggerName` is configured, Armeria will create using that name. Of course it can be done by passing `logger`, but i just want some kind of short-cut.
How do you think?

Example:
 - AS-IS:
   ```java
   private static final Logger logger = LoggerFactory.getLogger("com.example.MyLogger");
   LoggingClient.builder()
                .logger(logger)
                .build();
   ```
 - TO-BE
   ```java
   LoggingClient.builder()
                .loggerName("com.example.MyLogger")
                .build();
   ```

**Comment by minwoox** [comment]
That sounds good to me.
We have to make sure that both `logger` and `loggerName` are not set together.

**Comment by anuraaga** [comment]
> We have to make sure that both logger and loggerName are not set together.

This seems to make the API a lot more complex, the detail of only being able to set one actually leaks to the user. Is it worth such a small short-cut?

One of the reasons for removing shortcuts from `RequestLog` is because many of them had lifecycle requirements that made them complex as an API - they weren't pure shortcuts. This is similar I think.

**Comment by trustin** [comment]
I think this is a pure shortcut in this case. No need to do state management, i.e. this should be allowed:

```java
builder.logger(LoggerFactory.getLogger(...))
       .logger("com.example.foo");
```

**Comment by trustin** [comment]
Why? Because a user should be able to build a builder template, pass it somewhere else and let its properties be overridden.

**Comment by anuraaga** [comment]
Ah yeah if overriding without checks sounds nice

**Comment by minwoox** [comment]
Yeah, it sounds good.

**Comment by ghkim3221** [comment]
Very nice 👍
