### ISSUE TITLE
`DocServiceConfigurator` beans with the same name are overriden

### ISSUE THREAD

**Issue by KarboniteKream** [line/armeria#3033]
When using multiple `DocServiceConfigurator` beans with Armeria 1.0, only one `DocServiceConfigurator` is applied if they have the same name:

```java
@Bean
public DocServiceConfigurator docServiceBean() {
    return builder -> builder.exampleRequests(firstExample());
}

@Bean
public DocServiceConfigurator docServiceBean() {
    return builder -> builder.exampleRequests(secondExample());
}
```

In this example, `DocService` will only contain the example requests in `secondExample()`. This occurs when [`allowBeanDefinitionOverriding`](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/SpringApplication.html#setAllowBeanDefinitionOverriding-boolean-) is enabled in Spring.

This could be a problem when different services and their corresponding example requests are defined in separate classes, so as a workaround (and maybe the only solution for Spring), the user should make sure to use different names for the `DocServiceConfigurator` beans.

**Comment by ikhoon** [comment]
Spring only allows customizing the `@Component`-style bean names.
https://stackoverflow.com/questions/33079455/how-do-i-specify-a-beannamingstrategy-with-spring-boot
That means there is no workaround in Armeria side at the moment.
I think it would be better to turn off `allowBeanDefinitionOverriding` or add test cases for preventing further mistakes. 

Thanks for reporting @KarboniteKream 🙇‍♂️
