### ISSUE TITLE
UnionMap can return multiple values for same key?

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#3044]
Not too sure but looking at the code

https://github.com/line/armeria/blob/master/logback/src/main/java/com/linecorp/armeria/common/logback/UnionMap.java#L111

`UnionMap` returns a set of entries which is the union of two maps. But since entry-comparison is for key/value pairs, I think this set will have entries from both maps even when a key is duplicated. Presumably it should be deduping on the key only.

**Comment by anuraaga** [comment]
BTW, I solve it in a copy of the code here

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1165/files#diff-8b7756d159c5ffa3012c5c264eb5ab00R114

**Comment by minwoox** [comment]
> Presumably it should be deduping on the key only.

Agreed. We gotta fix that. 😄
