### ISSUE TITLE
Provide a way to cancel client request.

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3046]
We have `ClientRequestContext.timeoutNow()` to trigger timeout immediately.
Similarly, it might be good to add `ClientRequestContext.cancel()` which cancels the current client request in case a user cannot easily cancel or abort the response such as https://github.com/line/centraldogma/blob/master/client/java/src/main/java/com/linecorp/centraldogma/internal/client/AbstractWatcher.java#L224

**Comment by tumile** [comment]
Hi, I notice there is a `failEarly` implementation in `DefaulClientRequestContext`. Would `cancel` use the same logic (I assume without the `Throwable`) or does it have other requirements as well? 
https://github.com/line/armeria/blob/6ad7fe3dc6ce924d77f977bf6d5a06d26b38e8f9/core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java#L310-L316

**Comment by minwoox** [comment]
Thanks, @tumile for your interest.
I think it's going to work exactly as `ClientRequestContext.timeoutNow()` does except raising `CancellationException` instead of `ResponseTimeoutException`. 😄

**Comment by tumile** [comment]
Do you mean it should also use the `TimeoutScheduler` to schedule the cancellation? 😀 I plan to use `HttpRequestSubscriber#fail` to cancel the request like so.
```java
@Override
public void operationComplete(ChannelFuture future) throws Exception {
    // If a message has been sent out, cancel the timeout for starting a request.
    cancelTimeout();

    try (SafeCloseable ignored = RequestContextUtil.pop()) {
        // Check if request has been cancelled
        if (ctx.isCancelled()) {
            fail(new CancellationException());
        }
...
```
My question is I'm not sure `operationComplete` is a good place to put the check, as I'm not sure when this method is called. Sorry I'm still trying to wrap my head around the Armeria's architecture 😅

**Comment by minwoox** [comment]
If ctx is canceled after the request is fully sent (i.e waiting to get a response fully), the response is never canceled.
So I think we should use a different approach.

> Do you mean it should also use the TimeoutScheduler to schedule the cancellation?

I'm not sure if we can rename `TimeoutScheduler` to something else and generalize for this purpose (cancel or timeoutNow which just abort the response with the different exception), but it's worth trying.
What I meant was that we should do the same approach as `TimeoutScheduler` does.
(It maintains the state of a request and cancel it if necessary.)

**Comment by tumile** [comment]
I think we can provide the current state of Scheduler in `TimeoutTask#run` and the implementation can decide which exception to abort with accordingly. How about this?
```java
public interface TimeoutTask extends Runnable {
    default void run() {
        run(state); // TIMED_OUT if timeoutNow() or CANCELLED if cancel()
    }

    void run(State state);
}

// HttpResponseWrapper
private TimeoutTask newTimeoutTask() {
    return new TimeoutTask() {
        public void run(TimeoutScheduler.State state) {
            ...
            if (state == TimeoutScheduler.State.CANCELLED) cause = new CancellationException();
            delegate.close(cause);
        }
```
