### ISSUE TITLE
Fail if both armeria-spring-boot2-starter and armeria-spring-boot2-webflux-starter used

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3056]
If they both are used by mistake, two different servers are created and each server will serve respectively with the different ports.
So we should prohibit that circumstance.

**Comment by minwoox** [comment]
Also, because the usage of property files is different from each other, we should consider unifying them or at least add more documentations.

**Comment by minwoox** [comment]
If so, I think the response reached here https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java#L295
because `Http1ResponseDecoder` is only added to the pipeline right before an HTTP headers is sent. 🤔

**Comment by heowc** [comment]
How about adding `@ConditionalOnNotWebApplication` to `ArmeriaAutoConfiguration`? 🤔

**Comment by trustin** [comment]
> How about adding `@ConditionalOnNotWebApplication` to `ArmeriaAutoConfiguration`? 🤔

Will this help when a user wants to run a Spring MVC app on top of Armeria's Tomcat?

**Comment by heowc** [comment]
Oops... I was mistaken. I thought I could put options like `ConditionalOnWebApplication`. 😅

In another opinion, for example Spring Boot can have two dependencies, mvc and webflux, and mvc is automatically chosen first if you don't specify a specific type. To do this in Armeria as well, we need to increase the priority for `ArmeriaAutoConfiguration` and conditionally check the Armeria Server Bean created by each.

**Comment by trustin** [comment]
@heowc That sounds good to me. Are you going to work on it?

**Comment by heowc** [comment]
Yes. I'll work on it. 👌

**Comment by trustin** [comment]
Awesome. Thanks as always, @heowc :bow:
