### ISSUE TITLE
Should we exclude health check requests from metrics by default?

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3061]
If a user uses Armeria client and server, the duration for a health check request is 60 seconds by default.
This might confuse the user that something is wrong with the server because a request takes so long if he/she monitors the request metric together.

**Comment by trustin** [comment]
For Spring Boot and Dropwizard integration, or all `TransientService`s?

**Comment by minwoox** [comment]
I forgot that we have `TransientService`. 😄 
Yeah, I think it's good to exclude all `TransientService`s by default.

**Comment by trustin** [comment]
Do you think we need to make the new behavior configurable? (with the default of exclusion)

**Comment by minwoox** [comment]
That's a good question. Yeah, we need to make it configurable because some might want to include those requests too. 😄
