### ISSUE TITLE
Q. Does armeria + grpc-reactor require the response be written from armeria's event loop?

### ISSUE THREAD

**Issue by jrhee17** [line/armeria#3090]
I have an armeria server serving requests using grpc-reactor and have to say it's looking pretty good so far 👍 

All seemed to work well, except I found that some responses were disappearing without any indications in logging.

After looking at armeria+grpc-reactor examples, I am guessing the response should be written via armeria's event loop.

https://github.com/line/armeria/blob/464521caef452c0d04e7bbb262dceb8dfce2d7e3/examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/HelloServiceImpl.java#L81

I would like to check if my understanding is correct before moving forward

**Comment by ikhoon** [comment]
> I am guessing the response should be written via armeria's event loop.

There is no constraint on implementing gRPC stub. The given example publishes elements via event loop for context propagation. 

The stream messages seem to be completed before delivering to downstream. 🤔

**Comment by jrhee17** [comment]
Huh.. seems to be a regression then. Removing that line fails the test

**Comment by trustin** [comment]
Yup, streaming from any threads (including non-event-loop ones) should not fail. It sounds like a bug.

**Comment by ikhoon** [comment]
@jrhee17 Are you looking into this issue? If not, I will take a shot. :-)

**Comment by jrhee17** [comment]
Feel free to take 😃
