### ISSUE TITLE
Spring boot actuator health configurations do not work when armeria-spring-boot2-actuator-starter is included 

### ISSUE THREAD

**Issue by rickyrattlesnake** [line/armeria#3122]
When `armeria-spring-boot2-actuator-starter` is added to the project which already has `org.springframework.boot:spring-boot-starter-actuator`

`armeria-spring-boot2-actuator` seems to overrides the behavior of the spring-boot actuator `actuator/health` endpoint.

Applying spring boot specific configurations (https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#writing-custom-healthindicators) e.g.
```
management.endpoint.health.status.http-mapping.down=503
management.endpoint.health.status.http-mapping.fatal=503
management.endpoint.health.status.http-mapping.out-of-service=503
```
no longer work. 

(working healthcheck queried from POSTMAN without `armeria-spring-boot2-actuator`)
![image](https://user-images.githubusercontent.com/4549582/96666445-de4ab600-13a2-11eb-926c-c7885ac17bc9.png)

(healthcheck queried from POSTMAN with `armeria-spring-boot2-actuator`, expecting a `503` with a down status)
![image (1)](https://user-images.githubusercontent.com/4549582/96666447-df7be300-13a2-11eb-9a8d-497c887ff06c.png)

**Comment by minwoox** [comment]
@rickyrattlesnake Sorry about not responding to this issue for a long time. 
I think it's been fixed and it should work now. Could you check this again, please?
/cc @policeman-kh

**Comment by trustin** [comment]
@minwoox Could you let us know which PR or commit fixed this issue?

**Comment by ikhoon** [comment]
I think #3997 applied to [1.14.0](https://armeria.dev/release-notes/1.14.0/) would resolve the problem.
