### ISSUE TITLE
Can I apply armeria retrofit to the Android?

### ISSUE THREAD

**Issue by cha7713** [line/armeria#3123]
error-------------------------------------------------------------------------
Execution failed for task ':app:kaptGenerateStubsDebugKotlin'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Failed to transform armeria-1.1.0.jar (com.linecorp.armeria:armeria:1.1.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
-----------------------------------------------------------------------------

Is the usage wrong even though I entered it as below in build.gradle?

implementation platform('com.linecorp.armeria:armeria-bom:1.1.0')
implementation 'com.linecorp.armeria:armeria-retrofit2'

**Comment by ikhoon** [comment]
Hi! @cha7713 We've not tried Amreria with Android yet. 
Could you share a reproducible code or a full stacktrace?

**Comment by cha7713** [comment]
I've made a sample project, so there's nothing much to it.
Thank you for your answer.
