### ISSUE TITLE
Provide a way to configure `HealthCheckService` in the Armeria Spring integration

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3130]
When users use `HealthCheckService` with Spring Boot, they can only set the path of health check like the following.
```yml
armeria:
  health-check-path: /monitor/l7check
```

If users want to customize the `HealthCheckService`, they have to disable the path and add `HealthCheckService` manually.
By adding `HealthCheckServiceConfigurator` bean, users can customize it using `@Bean` method style.
```java
@Bean
public HealthCheckServiceConfigurator healthCheckService() {
    return builder -> {
        // customize the HealthCheckerServiceBuilder
    }
} 
```

**Comment by ghkim3221** [comment]
Let me try 😄

**Comment by ikhoon** [comment]
Thanks, @ghkim3221 . It is all yours!
