### ISSUE TITLE
Provide a way to set decoration order

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3137]
The order of decoration depends on the order of insertion.
https://armeria.dev/docs/client-decorator#the-order-of-decoration
A decorator inserted later has a higher priority for the client-side.
In contrast, a routing decorator inserted earlier has a higher priority for the server-side.

If a decorator has an explicit order, it would be useful for designing a complex decorating chain.
For example:
```java
Server.builder()
      .decorator(LoggingService.newDecorator(), 1)
      .decorator(EncodingService.newDecorator(), 2)
      ...
      .build()
```

**Comment by heowc** [comment]
Can I work on it?

**Comment by ikhoon** [comment]
Sure! 
These are some points you need to consider:
- There are many places that decorators can be injected. Please check those points before implementing this feature. 
- If unorderd decorators are mixed with ordered decorators, maybe we can give them the lowest order.
- RoutingDecorators are assembled dynamically when a request is received.
  https://github.com/line/armeria/blob/2e792f9c0bac03b59771a6f93b4b3da0936887c2/core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java#L67

**Comment by heowc** [comment]
I have a question.

In [`Decorator`](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/annotation/Decorator.java) used by annotated service There is already order related logic.

I think this should also be ordered, but it seems a bit vague. 🤔

**Comment by ikhoon** [comment]
That's a good question.
The annotated decorators are strongly bound to a class or method of annotated service. I think we can give them the lowest priority.

Let's say we have the following service which uses decorators in various places.
```java
@Decorator(DecoratorA.class)
class MyAnnotatedService {
    @Decorator(value = DecoratorB.class, order = 1)
    @Decorator(value = DecoratorC.class, order = 2)
    @Get("/foo")
    public String foo() {
    }
}

Server.builder()
      .annotatedService()
          .decorator(new DecoratorD())
          .decorator(new DecoratorE())
          .build(new MyAnnotatedService())
     .decorator("/foo", new DecoratorF());
     .decorator("/foo", new DecoratorG();
```

If the server receives a request on "/foo" path, the request will be passed through:
```
RouteDecoratingService -> DecoratorF -> DecoratorG -> -> decorated MyAnnotatedService
```
And in the decorated MyAnnotatedService:
```
DecoratorE -> DecoratorD -> DecoratorA -> DecoratorC -> DecoratorB -> foo() method
```
The overall decorator chain would be:
```
F -> G -> E -> D -> A -> C -> B
```

If we give order to decorator, it could be change the order of decorator within its definition scope.
```java
@Decorator(DecoratorA.class)
class MyAnnotatedService {
    @Decorator(value = DecoratorB.class, order = 1)
    @Decorator(value = DecoratorC.class, order = 2)
    @Get("/foo")
    public String foo() {
    }
}

Server.builder()
      .annotatedService()
          .decorator(new DecoratorD(), 1)
          .decorator(new DecoratorE(), 2)
          .build(new MyAnnotatedService())
     .decorator("/foo", new DecoratorF());
     .decorator("/foo", new DecoratorG());
```
Now the decorator chain will be:
```diff
- F -> G -> E -> D -> A -> C -> B
+ F -> G -> D -> E -> A -> C -> B
```

Does it make sense?

**Comment by heowc** [comment]
Wow! Thank you for the detailed description.
This will really help me a lot. 😎

**Comment by heowc** [comment]
Here's a bit more discussion of the route decorator on this issue:
- Sort priorities only for the same path.
- Currently, there is a bug in which the last added route decorator is evaluated last. To go in a consistent direction, this must be the first to be evaluated. This must be corrected first 🤔

**Comment by trustin** [comment]
Created a new issue for evaluation order - #3160

**Comment by ikhoon** [comment]
Decorators are always executed in the reverse order of the insertion.
Some implementations did not flow the rule such as the routing decorator. It also gives confusion to users. 
Had chat this feature, which sets a decorator with an order, with other maintainers and we reached that this API can cause another confusion.
Please file an issue or leave a comment on this thread if an explicit order of decoration is necessary.
