### ISSUE TITLE
java.lang.IllegalArgumentException: URI with unknown scheme: 

### ISSUE THREAD

**Issue by person2713** [line/armeria#3139]
Hello everyone, i tried to use your project, but I cannot pass test phase, I always get 
`Constructor threw exception; nested exception is java.lang.IllegalArgumentException: URI with unknown scheme: http://127.0.0.1:8080/hello
`
but I took example from here https://armeria.dev/docs/client-thrift and it didn't work, it even cannot parse the url that you showed in example.

**Comment by trustin** [comment]
Hi! Could you share the repository that reproduces the problem? It sounds like some packaging problem.

**Comment by anandkulkarni428** [comment]
Hi! I am also facing the same issue in my project. 
Did the issue got resolved?
if yes let me know how you did it!
Thanks in advance!

**Comment by trustin** [comment]
My guess is that a user is shading the dependencies incorrectly so that the files under `META-INF` are lost during the packaging process. If that was not the case, please feel free to reopen this question or open a new one (given this question is fairly old now.)
