### ISSUE TITLE
Check user-friendlyness of adding gRPC health check to Armeria server

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#3146]
gRPC has a health check that follows the gRPC protocol

https://github.com/grpc/grpc-java/blob/master/services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java

While it's actually not that common for it to be supported, e.g., in k8s, some load balancers like AWS do support it so it'd be good to make sure it can be enabled fairly simply. Not sure if it's just adding the service or needs special work like the proto-reflection service integration.

/cc @kowshikn (and feel free to provide any and all suggestions you find :) )

**Comment by trustin** [comment]
Sounds like a good idea. Adding a service sounds better to me since a user needs to inject HealthCheckers.

**Comment by ta7uw** [comment]
May I try on this issue?
