### ISSUE TITLE
Tests related to metric export fail when changing to Spring Boot 2.4

### ISSUE THREAD

**Issue by heowc** [line/armeria#3147]
In Spring Boot 2.4 there are changes to the [Metrics export in integration test](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#metrics-export-in-integration-tests).

We use the in-memory MeterRegistry unless `@AutoConfigureMetrics` is specified when writing tests. But we can't use it because we can't use it for `boot1-autoconfigure`.

Therefore, I think you need to register the MeterRegistry as a bean when writing a test related to metric export. What do you think?

**Comment by trustin** [comment]
Sounds good to me. Does this relate to #3101 ? (I guess not)

**Comment by heowc** [comment]
> Sounds good to me. Does this relate to #3101 ? (I guess not)

Not relevant. This is simply a problem when changed to 2.4. The reason I mentioned this in #3101 is that I thought it would be more efficient to work after #3101.

Here's the situation I'm thinking of:
If I work before #3101, I can inject it into the metricRegistry bean I want to create a test after finding all the metric related auto configurations and disabling them. And after #3101, this code is unnecessary and should be deleted.

  If I work after #3101, I just need to write a test by injecting the metricRegistry bean I need.

**Comment by minwoox** [comment]
Sloved with
```java
@SpringBootTest(classes = NoMeterTestConfiguration.class, properties =
        "management.metrics.export.defaults.enabled=true") // @AutoConfigureMetrics is not allowed for boot1.

```
