### ISSUE TITLE
Armeria client can't connect to the server which doesn't support modern cipher suites

### ISSUE THREAD

**Issue by techno** [line/armeria#3157]
It seems Armeria client doesn’t have the way to connect servers which only supports ciphers in `HTTP2_BLACKLISTED_CIPHERS` even if on HTTP/1.1 connection.
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java#L187

I want to add acceptable cipher suites on client using `ClientFactory.builder().tlsCustomizer()`, because some ASP.NET server doesn’t support modern cipher suites (and HTTP/2). But Armeria rejected HTTP/2 blacklisted cipher suites and throw exception on `SslContextUtil.createSslContext()`. I think this restriction is too strict for clients.
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java#L178

About the HTTP/2 cipher suite blacklist, RFC7540 says

> An HTTP/2 implementation MAY treat the negotiation of any of the following cipher suites with TLS 1.2 as a connection error (Section 5.4.1) of type INADEQUATE_SECURITY:

but it’s not MUST or REQUIRED.
Probably the target of this blacklist is for server. I don’t think we need too strict cipher suite filtering on client side.
It's OK with filtering them on default value, but I think no need to throw exception for customized value, isn’t it?

Armeria should have a option to add blacklisted cipher suite for compatibility.

Additionally, `tlsNoVerify()` is too insecure for our application.

**Comment by techno** [comment]
Also the exception by
`webClient.get("https://<no modern cipher suites server>/").aggregate().get().status()`
is `com.linecorp.armeria.common.ClosedSessionException`.
Should it be `javax.net.ssl.SSLHandshakeException`?

**Comment by ikhoon** [comment]
> About the HTTP/2 cipher suite blacklist, RFC7540 says
>
> > An HTTP/2 implementation MAY treat the negotiation of any of the following cipher suites with TLS 1.2 as a connection error (Section 5.4.1) of type INADEQUATE_SECURITY:

Had chat with @minwoox and @trustin and we decided to keep the original policy and add an option such as `.tlsAllowUnsafeCiphers()` for compatibility.



> Also the exception in this case is unkindness.
> `webClient.get("https://<no modern cipher suites server>/").aggregate().get().status()` throws `com.linecorp.armeria.common.ClosedSessionException`.
> Should it be `javax.net.ssl.SSLHandshakeException`?

That makes sence. I think `SSLHandshakeException` could be a cause of the `ClosedSessionException`.
