### ISSUE TITLE
IPV6 with scope id

### ISSUE THREAD

**Issue by windmeup** [line/armeria#3158]
Endpoint accepts the ipv6 address with scope id, like xxxxxxxxxxxxxxxxxxxxx%2, but downstream calls use the Endpoint's host without scope id: 

io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Invalid argument: xxxxxxxxxxxxxxxxxxxxxx%2

**Comment by trustin** [comment]
That sounds like a bug. Thanks for reporting.
