### ISSUE TITLE
Replace jakarta.annotation with javax.annotation

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#3162]
jakarta.annotation released 2.0 which moves all the packages to `jakarta.` from `javax.`. I don't know why they even made releases with the old names if they were going to do this, but we can expect dependency problems in the future if libraries start targeting 2.0. So we should probably switch to the classical artifact https://search.maven.org/artifact/javax.annotation/javax.annotation-api/1.3.2/jar

**Comment by trustin** [comment]
Sounds good to me.
