### ISSUE TITLE
HealthcheckEndpointGroup return empty endpoints if backend EndpointGroup refresh with different endpoints

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#3173]
I'm using 2 types of EndpointGroups (a DynamicEndpointGroup, [CentralDogmaEndpointGroup](https://github.com/line/centraldogma/blob/master/client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/CentralDogmaEndpointGroup.java) and static EndpointGroup) and combine them using OrElseEndpointGroup, and then wrap with HealthCheckedEndpointGroup.

```java
HealthCheckedEndpointGroup(CentralDogmaEndpointGroup.orElse(StaticEndpointGroup))
```

This HealthCheckedEndpointGroup initiate healthcheck request to static EndpointGroup at first (because CentralDogmaEndpointGroup is not ready yet) and after few seconds, once CentralDogmaEndpointGroup become ready, HealthCheckedEndpointGroup switches healthcheck target from endpoints from static EndpointGroup to endpoints from CentralDogmaEndpointGroup.
At this timing, HealthCheckedEndpointGroup return empty endpoints because
* Healthy endpoints of static EndpointGroup are already destoryed
* Healthcheck for endpoints of CentralDogmaEndpointGroup are not finished yet

Here is simple reproducer with a DynamicEndpointGroup.
```java
package test;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import com.google.common.collect.ImmutableList;

import com.linecorp.armeria.client.Endpoint;
import com.linecorp.armeria.client.endpoint.DynamicEndpointGroup;
import com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroup;
import com.linecorp.armeria.common.SessionProtocol;
import com.linecorp.armeria.server.ServerBuilder;
import com.linecorp.armeria.server.healthcheck.HealthCheckService;
import com.linecorp.armeria.testing.junit5.server.ServerExtension;

public class EndpointTest {
    @RegisterExtension
    public final ServerExtension server = new ServerExtension() {
        @Override
        protected void configure(ServerBuilder sb) {
            sb.service("/monitor/l7check", HealthCheckService.builder().build())
              .port(8080, SessionProtocol.HTTP)
              .port(8081, SessionProtocol.HTTP);
        }
    };

    static class TestEndpointGroup extends DynamicEndpointGroup {
        public void update(Endpoint endpoint) {
            setEndpoints(ImmutableList.of(endpoint));
        }
    }

    @Test
    void run() throws Exception {
        server.start();
        TestEndpointGroup d = new TestEndpointGroup();
        Endpoint oldEndpoint = Endpoint.of("localhost", 8080);
        Endpoint newEndpoint = Endpoint.of("localhost", 8081);
        // Start with `oldEndpoint`
        d.update(oldEndpoint);

        HealthCheckedEndpointGroup hc = HealthCheckedEndpointGroup
                .builder(d, "/monitor/l7check")
                .build();
        List<Endpoint> initialEndpoints = hc.whenReady().get(10, TimeUnit.SECONDS);
        assertThat(initialEndpoints).containsOnly(oldEndpoint);

        // Replace whole endpoints with `newEndpoint`. Here, HealthCheckedEndpointGroup destory healthchecker for `oldEndpoint` and start to send healthcheck to `newEndpoint`.
        d.update(newEndpoint);
        List<Endpoint> duringInitialHealthCheckForNewEndpoint = hc.endpoints();
        // At this moment, healthcheck request for `newEndpoint` is not finished yet and `oldEndpoint` is
        // already gone from healthyEndpoints. So, HealthCheckedEndpointGroup returns empty.
        assertThat(duringInitialHealthCheckForNewEndpoint).isEmpty();

        // Until healthcheck for `newEndpoint` finish, clients corresponding to HealthCheckedEndpointGroup
        // throws EmptyEndpointGroupException.
        Thread.sleep(100);
        // Once healthcheck for `newEndpoint` finish, back to normal.
        List<Endpoint> afterInitialHealthCheckForNewEndpoint = hc.endpoints();
        assertThat(afterInitialHealthCheckForNewEndpoint).containsOnly(newEndpoint);
    }
}
```

Suggestions:
- How about do healthcheck to newly appeared endpoints before remove endpoints (suggested by @ikhoon )
- Better to leave a log if HealthCheckedEndpointGroup destory all HealthCheckContext?
- and so on...

**Comment by minwoox** [comment]
Yeah, changing to the `orElseEndpointGroup` after the first health check is done seems nice.
@imasahiro Are you going to handle this?

**Comment by imasahiro** [comment]
@minwoox please feel free to handle it, if you want. I don't have enough time to handle this, at this week and next week..

**Comment by imasahiro** [comment]
IIUC, this was already resolved by https://github.com/line/armeria/pull/3181, right? @minwoox

**Comment by minwoox** [comment]
Ah exactly. Thanks for reminding me. 😄

**Comment by 4Jessie** [comment]
I also got the same issue recently. In our code, we are combining CentralDogmaEndpointGroup 
 and DnsAddressEndpointGroup in a OrElseEndpointGroup. Looking forward the resolution of the issue.  Thank you~
