### ISSUE TITLE
unresolved reference "GrpcHeaderNames" from document code

### ISSUE THREAD

**Issue by rolandblain** [line/armeria#3184]
hi

from https://armeria.dev/docs/server-grpc#grpc-web

```
import com.linecorp.armeria.common.grpc.GrpcHeaderNames
```

It's marked as a unresolved reference.

build.gradle :

```
implementation platform('com.linecorp.armeria:armeria-bom:1.2.0')
implementation 'com.linecorp.armeria:armeria-spring-boot2-webflux-starter'
implementation 'com.linecorp.armeria:armeria-grpc'
```

maybe the document update needed.

thanks.

**Comment by minwoox** [comment]
Thanks for the report. Let us update the document. 🙇

**Comment by minwoox** [comment]
Fixed by https://github.com/line/armeria/commit/353634acf1347390e7c82336ccbe4f34f419b561

**Comment by minwoox** [comment]
https://armeria.dev/docs/server-grpc#grpc-web
It's now fixed. 😄
