### ISSUE TITLE
Provide an option to Armeria client to keep the original header key

### ISSUE THREAD

**Issue by ildartuykin** [line/armeria#3196]
We need a possibility to Armeria client not to convert headers to lowercase for HTTP/1, because some servers violate case insensitive HTTP/1 requirements.

**Comment by trustin** [comment]
Our `HttpHeaders` implementation currently stores all header names in lower-case for consistency and performance.
Would it solve your problem if we provide a way for a user to specify header name conversion policy for HTTP/1? e.g.

```java
ClientFactory.builder()
             .http1HeaderNaming(http2HeaderName -> {
               if (http2HeaderName.contentEquals("x-special-header")) {
                   return "X-Special-Header";
               }
               return http2HeaderName;
             })
             .build();
```

**Comment by ildartuykin** [comment]
Both variants looks good.

**Comment by trustin** [comment]
@ildartuykin Let us know if #3259 would solve this problem. :bow:
