### ISSUE TITLE
Why armeria prefer @Nullable to Optional?

### ISSUE THREAD

**Issue by alex-lx** [line/armeria#3198]
It's not an issue but a question, so feel free to close it if it not fit your issue policy :P.

1.  Armeria used Optional long long ago, and then change it to `xxxOrNull` style API. why you prefer this?
2. There're many @nullable variant in different library, like jsr305, jetbrains-annotations, could you, skillful developers, share your practice which and why to use one rather than another?

Big thanks!

**Comment by ikhoon** [comment]
Armeria removed `Optional` from the public API.
Please refer to the previous discussion and reason #2362 #2371

One of the reasons is that Armeria supports JDK languages well. Java is the main target language of Armeria. However, we don't want to limit the scope to Java.

Kotlin supports an awesome null-safety using `?`. It does not go well with `Optional`. Kotlin understands nullable annotations for Java libraries. https://kotlinlang.org/docs/reference/null-safety.html

For example: 
```kt
val b: String? = null
println(b?.length)
```

**Comment by ikhoon** [comment]
> There're many @nullable variant in different library, like jsr305, jetbrains-annotations, could you, skillful developers, share your practice which and why to use one rather than another?

We are also considering to adopt `jetbrains-annotations`. #2793 You can leave your opinion on that thread. 😀

**Comment by alex-lx** [comment]
> Armeria removed `Optional` from the public API.
> Please refer to the previous discussion and reason #2362 #2371
> 
> One of the reasons is that Armeria supports JDK languages well. Java is the main target language of Armeria. However, we don't want to limit the scope to Java.
> 
> Kotlin supports an awesome null-safety using `?`. It does not go well with `Optional`. Kotlin understands nullable annotations for Java libraries. https://kotlinlang.org/docs/reference/null-safety.html
> 
> For example:
> 
> ```kotlin
> val b: String? = null
> println(b?.length)
> ```

Thanks for your reply. It makes sense. How about dealing with pure Java code?
