### ISSUE TITLE
Return custom eror page when the execution time is long then armeria sends a response with 503

### ISSUE THREAD

**Issue by policeman-kh** [line/armeria#3209]
Our service, https://store.line.me using armeria and embedding tomcat service.
ref: https://armeria.dev/docs/server-servlet

When tomcat execution is long then ameria got timeout error, "503 Service Unavailable" message appears in browser.
We would like to response custom error page to users instead of "503 Service Unavailable" message.

As-Is:
Just  "503 Service Unavailable" message. It's not user friendly.

<img border="1" src="https://user-images.githubusercontent.com/20625903/100712735-95047200-33f6-11eb-9c2b-be9aa5e6c255.png">

To-Be:
Should be an error page with message and image. It's more user friendly. 
ex.twitter
![c9dd260c](https://user-images.githubusercontent.com/20625903/100712983-fb899000-33f6-11eb-810a-d2875086b4a3.png)

FYI: our service's code base is not public but I prepared a project with same architecture.
ref: https://github.com/policeman-kh/armeria_spring_web

**Comment by trustin** [comment]
Implemented via #3413
