### ISSUE TITLE
Provide a way to create non-official gRPC client stub

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3214]
Currently, Armeria gRPC client factory use reflections to find a stub factory method or constructor from the specified client type.
Armeria supports well-known client types already such as gRPC-Java, Reactive-gRPC, gRPC-Kotlin, and so on.

When users want to use a new gRPC client stub with Armeria gRPC client, we need to add a new reflection code to find `ServiceDescriptor` and a stub factory. I think this is not scalable.

If we introduce a `GrpcStubFactory`, users can easily integrate their gRPC stub with Armeria.
```java
interface GrpcStubFactory {
    // Should return a ServiceDescriptor to use gRPC JSON foramt
    @Nullable
    ServiceDescriptor serviceDescriptor();

    Object stub(Channel channel);
}

MyGrpcStub client = 
        Clients.builder(grpcUrl)
               .options(GrpcClientOptions.STUB_FACTORY.newValue(new GrpcStubFactory {
                    @Override
                    public ServiceDescriptor serviceDescriptor() {
                        return MyGrpcStub.SERVICE;
                    }

                    @Override
                    public Object stub(Channel channel) {
                        return MyGrpcStub.stub(channel);
                    }
               })
               .build(MyGrpcStub.class);
```

**Comment by trustin** [comment]
How about generalizing a little bit more and using SPI?

```java
interace GrpcClientStubFactory {
    // Return `null` if given with unsupported clientType.
    @Nullable
    ServiceDescriptor findServiceDescriptor(Class<?> clientType);

    Object newClientStub(Class<?> clientType, Channel channel);
}
```

We could go through all `GrpcClientStubFactory`s for a given `clientType` in `GrpcClientFactory.newClient()`.

**Comment by ikhoon** [comment]
> How about generalizing a little bit more and using SPI?

That is a good suggestion.

The original situation was that I tried to integrate Armeria gRPC server and client with community-driven gRPC stubs such as https://github.com/fiadliel/fs2-grpc.

The generated stub looks like:
```scala
// No super interface or class
trait HelloServiceFs2Grpc[F[_], A] {
  def hello(request: HelloRequest, ctx: A): F[HelloReply]
}

object HelloServiceFs2Grpc {
  def stub[F[_]: ConcurrentEffect](channel: Channel, callOptions: CallOptions = CallOptions.DEFAULT): HelloServiceFs2Grpc[F, Metadata] = {
    client[F, Metadata](channel, identity, _ => callOptions)
  }
}
```

If we use SPI, users could use the following:
```java
class MyGrpcClientStubFactory implements GrpcClientStubFactory {

    @Override
    public ServiceDescriptor findServiceDescriptor(Class<?> clientType) {
        if (clientType instanceof HelloServiceFs2Grpc) {
            return HelloServiceGrpc.SERVICE;
        }        
        if (clientType instanceof GreetingServiceFs2Grpc) {
            return GreetingServiceGrpc.SERVICE;
        }
        return null;
    }

    Object newClientStub(Class<?> clientType, Channel channel) {
        if (clientType instanceof HelloServiceFs2Grpc) {
            return HelloServiceFs2Grpc.stub[IO](channel);
        }        
        if (clientType instanceof GreetingServiceFs2Grpc) {
            return GreetingServiceFs2Grpc.stub[IO](channel);
        }
        // Should not reach here. 
        return null;
    }
}
```

**Comment by trustin** [comment]
Could be simplified into `.getClass().getName().endsWith("Fs2Grpc")` and some reflection?

**Comment by ikhoon** [comment]
I intented to offer a type-safer way so that users are easily to add by themself.
However, a generalized `GrpcClientStubFactory` via SPI also looks good to me. The reflection won't be that complicated.

**Comment by ikhoon** [comment]
A generic type parameter could not be properly handled by SPI. In the following code, the `IO` type could be changed to other types by users' choice.
```scala
GreetingServiceFs2Grpc.stub[IO](channel)
```

Is it not good if we support both SPI and `GrpcClientOptions.CLIENT_STUB_FACTORY`?
gRPC-Java, gRPC-Kotlin, Reactive gRPC, and ScalaPB can be provided by SPI.

**Comment by trustin** [comment]
> Does it look weird if we support both SPI and `GrpcClientOptions.CLIENT_STUB_FACTORY`?
> gRPC-Java, gRPC-Kotlin, Reactive gRPC, and ScalaPB can be provided by SPI.

I think that's fine.
