### ISSUE TITLE
`EndpointGroup` should be able to contain duplicate `Endpoints`?

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3230]
```java
final DynamicEndpointGroup endpointGroup = new DynamicEndpointGroup();
endpointGroup.setEndpoints(ImmutableList.of(Endpoint.of("127.0.0.1", 3333),
                                            Endpoint.of("127.0.0.1", 3333),
                                            Endpoint.of("127.0.0.1", 1111)));
assertThat(endpointGroup.whenReady().join())
        .containsExactlyInAnyOrder(Endpoint.of("127.0.0.1", 3333),
                                   Endpoint.of("127.0.0.1", 3333),
                                   Endpoint.of("127.0.0.1", 1111));
```
This is perfectly valid at the moment.
Shouldn't we prohibit the duplicate `Endpoints` in `EndpointGroup`?

**Comment by anuraaga** [comment]
I guess if a dynamic endpoint group, like DNS or zookeeper, happened to return multiple of the same endpoints (maybe a way of doing weighting without actual weights) it's best to respect it.

**Comment by minwoox** [comment]
Thanks! I guess I have to change to respect the duplicate endpoints then. 😄

**Comment by trustin** [comment]
I'm not sure which is better. Slightly leaning toward to respecting it.

**Comment by minwoox** [comment]
Let's allow the duplicate endpoints. Thanks all!
