### ISSUE TITLE
heads up: possible that ssl on linux is broken on ubuntu 20201210.0

### ISSUE THREAD

**Issue by ptrthomas** [line/armeria#3234]
we just observed that our CI broke on GitHub actions, the thread is here: https://github.com/intuit/karate/pull/1403#issuecomment-747302016

the tests that broke involved SSL

and this was when the ubuntu 18.04.5 version was auto upgraded from 20201129.1 to 20201210.0

when the os was forced to ubuntu 20.04 things are working again

sorry I don't have more details or a way to replicate, but wanted to give you this heads up

**Comment by hunainhafeez2016** [comment]
Thanks for sharing such a beautiful information with us.

<a href="https://gulfjobsvisas.com/jobs/fia-jobs">FIA jobs</a>

**Comment by ptrthomas** [comment]
an update, looks like the same problem when Ubuntu switched from  20.04: 20201210.0 to 20210123.1

this is for netty 1.3.0 - error message includes this: `javax.net.ssl.SSLException: Unsupported or unrecognized SSL message`

**Comment by trustin** [comment]
@ptrthomas Sorry to hear that. Does this problem go away with #3310?

**Comment by ptrthomas** [comment]
@trustin I'm relieved to report that this is not an issue with netty or native libraries. this really confused me for a while but it was a combination of things, when ubuntu + java versions changed, the ordering of junit execution changed and surfaced a problem in our ssl tests running in parallel with other tests. this took a while and was a huge pain to figure out

just FYI we are maven-shading armeria and all netty dependencies, it was tricky to figure out how to get the native binaries to still work, but seems okay - am mentioning this in case this helps as a reference for others

am closing this. thanks for checking in and the support !

**Comment by trustin** [comment]
Great to hear that it was not an Armeria/Netty problem after all. Please feel free to report any issues later!
