### ISSUE TITLE
How can i use armeria to create Bidirectional Async RPC

### ISSUE THREAD

**Issue by java-war** [line/armeria#326]
it means, server can send message to client use async mode and client to server.

**Comment by trustin** [comment]
Could you elaborate what 'bidirectional async' here means?

**Comment by java-war** [comment]
I want to do server send message to client use async mode and client to server. how can i do this!

**Comment by trustin** [comment]
Everything in Armeria is asynchronous and non-blocking. If you are experiencing a problem writing a client or a server using Armeria, please post your sample code and let us know what your problem exactly is.

**Comment by trustin** [comment]
Closing due to lack of information. Please send a new question with more information.
