### ISSUE TITLE
Add metadata to Endpoint

### ISSUE THREAD

**Issue by eisig** [line/armeria#3263]
The eureka (or consul) endpoint, does not keep the meata data of the service instance.
Sometime we need to filter endpoints by tags, or prefer  endpoint whith tags.

**Comment by trustin** [comment]
Sounds like a good idea. We currently use `AttributeKey` for such purposes, most notably in `RequestContext`. Do you think it will work for `Endpoint` as well?

**Comment by eisig** [comment]
I seems ok. But it seems that there is no  AttributeMap implement in armeria for general usage. the `com.linecorp.armeria.common.DefaultAttributeMap` is designed to work with RequestContext.

**Comment by minwoox** [comment]
Thanks a lot for your work on Eureka @eisig. 🙇‍♂️ 
> I seems ok. But it seems that there is no AttributeMap implement in armeria for general usage. the com.linecorp.armeria.common.DefaultAttributeMap is designed to work with RequestContext.

Yeah, you are right. We need to introduce a new mechanism to store the metadata in the Eureka endpoint.

> The eureka (or consul) endpoint, does not keep the meata data of the service instance.
Sometime we need to filter endpoints by tags, or prefer endpoint whith tags.

I didn't know about this. 😅  Could you give me a specific example of this, please?

**Comment by trustin** [comment]
> Yeah, you are right. We need to introduce a new mechanism to store the metadata in the Eureka endpoint.

We could generalize it a little bit or introduce a simplified version of it, as well as a public interface?

**Comment by minwoox** [comment]
> We could generalize it a little bit or introduce a simplified version of it, as well as a public interface?

Yeah, that's what I meant. 😄  We are using the map for `RequestContext` which is for just a request. So we need to use the generalized map for `EurekaEndpointGroup`.

**Comment by eisig** [comment]
> I didn't know about this. 😅 Could you give me a specific example of this, please?
1. Common  Tags "region", "zone"
2. custom tags "group",  "version"..

With metadata, we can implement custom EndpointSelectionStrategy to:
Prefer instance in the same  zone or group. 
choose to route traffics to special goup for debug or load test. 
Or maybe implement canary release.

**Comment by minwoox** [comment]
Thanks for the detail. 😄
