### ISSUE TITLE
New I-D ratelimit ref

### ISSUE THREAD

**Issue by ioggstream** [line/armeria#3264]
## Note

in https://github.com/ioggstream/armeria/blob/master/bucket4j/src/main/java/com/linecorp/armeria/common/throttling/ThrottlingHeaders.java#L30

you can reference the new I-D which is now under the IETF

     * <a href="https://tools.ietf.org/id/draft-ietf-httpapi-ratelimit-headers-00.html">RateLimit Header Scheme for HTTP</a>.

**Comment by trustin** [comment]
Related: #3255

**Comment by trustin** [comment]
We also might want to check all other draft links (if any) and update accordingly.

**Comment by trustin** [comment]
Fixed via #3374
