### ISSUE TITLE
Jetty JavaDoc broken link reported during build "configure" stage

### ISSUE THREAD

**Issue by max904-github** [line/armeria#3286]
Armeria build constantly print following messages to the output:

```
> Configure project :
Download https://www.eclipse.org/jetty/javadoc/current/package-list
Download failed: 404 Not Found
Download https://www.eclipse.org/jetty/javadoc/current/element-list
Download failed: 404 Not Found
```

Apparently `https://www.eclipse.org/jetty/javadoc/current/package-list` no longer exists.

**Comment by minwoox** [comment]
Thanks for the notice!
Yeah, I guess we can use `https://javadoc.io/doc/org.eclipse.jetty/jetty-server/latest/` instead.
They recently released version 11, so we will handle it at the next release. 😄
