### ISSUE TITLE
Allow specifying `Metadata` with `GrpcServiceBuilder.addExceptionMapping()`

### ISSUE THREAD

**Issue by trustin** [line/armeria#3307]
Related StackOverflow question: https://stackoverflow.com/questions/65838522/is-there-any-way-to-use-rich-error-model-for-grpc-service-in-armeria

It is currently not possible for a user to specify a custom `Metadata` when an exception is translated into a `Status` via the exception mapping function built from what's specified with `GrpcServiceBuilder.addExceptionMapping()`. It may be useful if a user can specify `Metadata` as well as `Status` when adding an exception mapping:

```java
GrpcService
  .builder()
  ...
  .addExceptionMapping(MyException.class, Status.INTERNAL_ERROR, myMetadata)
  .build();
```

We're gonna have to update the signature of `GrpcStatusFunction.apply()` to support this use case. `GrpcStatusFunction` is an unstable API fortunately (?).

As a workaround, a user can write an interceptor like [this](https://github.com/okue/grpc-samples-in-kotlin/blob/main/grpc-kotlin-armeria-spring/src/main/kotlin/example/kt/armeria/spring/ErrorHandlingServerInterceptor.kt) (Kotlin code by @okue).

**Comment by trustin** [comment]
CC @anuraaga, another gRPC expert in the community 😉

**Comment by okue** [comment]
To let users write error handling easily,
it'd good if users can handle `Metadata` attached to response with `GrpcStatusFunction`.

**Comment by trustin** [comment]
@okue Agreed. That's why I said:

> We're gonna have to update the signature of `GrpcStatusFunction.apply()` to support this use case.

:wink:

**Comment by trustin** [comment]
@okue, or are you suggesting that just updating `GrpcStatusFunction` is enough? i.e. no need to add overloaded `addExceptionMapping()`?

**Comment by okue** [comment]
Ah, I don't mention `addExceptionMapping()`.

**Comment by okue** [comment]
Currently, I tried updating the signature of `GrpcStatusFunction`. https://github.com/okue/armeria/pull/6

After refactoring, writing test cases and examples, I'll send a pull request.
