### ISSUE TITLE
Support GraalVM

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3321]
https://www.graalvm.org/
GraalVM is a high-performance runtime that provides significant improvements in application performance and efficiency which is ideal for microservices.

It probably works, but we haven't tried yet. 😅

**Comment by minwoox** [comment]
Is there anyone who has tried this before, please let us know. 😄

**Comment by joonhaeng** [comment]
@minwoox 

Yesterday, I built the binary using graalvm native (spring native) and executed it to check that it works. However, there were many things to configure related to jni and reflection. Below are the configurations I used at the time of building.

[spring-native-config.zip](https://github.com/line/armeria/files/11197856/spring-native-config.zip)

**Comment by ikhoon** [comment]
Closed by #5005
