### ISSUE TITLE
Provide well defined Grafana dashboard template

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3341]
Related https://grafana.com/grafana/dashboards/4701
If we provide a well-defined default Grafana dashboard template,
our users do not have to spend much time figuring out which metric they need.

**Comment by anuraaga** [comment]
Is it a duplicate of #2973? This has been requested for a long time :)

**Comment by minwoox** [comment]
Ah, I missed that. Yes, it's duplicated. 😅
