### ISSUE TITLE
Provide a way to send a customized response when timeout

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3352]
A user might want to send a different response when a request timed out.
For example, a user might want to send 200 status with an exception message when he/she uses a Thrift service.
It can be done using `ServiceRequestContext.whenRequestCancelling()`, but it's not easy to implement because he/she has to implement the subscriber considering backpressure.

**Comment by ikhoon** [comment]
Duplicate of #3209 ?

**Comment by minwoox** [comment]
Ah, yes. 😅
