### ISSUE TITLE
Provide a way to disable the default DNS metrics

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3368]
Some users might not want to monitor DNS metrics because the metrics could contain various domains as metric keys if a client sends requests to unspecified domains such as webhook domains or redirect locations.

As a workaround, the metics could be filtered by [meter filters](https://armeria.dev/docs/advanced-metrics/#excluding-certain-meters-created-by-armeria).
However, it would be better to disable the metrics if they don't need them.
For example:
```java
DnsResolverGroupBuilder.disableDnsQueryLifecycleObserverFactory()
```

**Comment by amitvc** [comment]
@ikhoon Since I added logic for DNS metrics to armeria I can pick up this issue.

**Comment by ikhoon** [comment]
Thanks a lot! 🙇‍♂️

**Comment by ikhoon** [comment]
@amitvc Gentle ping. Are you working on this? Otherwise, let me address this. Some LINE internal users wish to use this feature. 😆
