### ISSUE TITLE
Provide a way to fluently build an `HttpResponse`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3398]
`HttpResponse` only provides various factory methods. It would be convenient to add `HttpResponseBuilder` as like [`HttpRequestBuilder`](https://github.com/line/armeria/blob/461b0fad53e1515387ebbab56a09c4ec0ed20fe6/core/src/main/java/com/linecorp/armeria/common/HttpRequestBuilder.java#L29)
For example:
```java
HttpResponse.builder()
            .status(HttpStatus.OK)
            .content("Hello, Armeria!")
            .contentType(MediaType.PLAIN_TEXT_UTF_8)
            .setCookie(...)
            .header("headerName", "headerValue")
            .build();

Publisher<HttpData> content = ...
HttpResponse.builder()
            .ok()
            .content(content)
            .build(); 
```

**Comment by agrawroh** [comment]
@trustin Is it okay if I take a stab at this?

**Comment by ikhoon** [comment]
Sure, it's all yours. Thanks for your interest! ❤️

**Comment by ta7uw** [comment]
As this issue has not been handled for a long time after being commented on, I'm working on this issue.
