### ISSUE TITLE
how to write high performance http -> unary grpc proxy

### ISSUE THREAD

**Issue by douyux** [line/armeria#3411]
I want to write a gateway proxy, that can transfer http request to unary grpc reqeust for backend microservice
```
            >------- http request --->                 >------ unary grpc reqeust ---->
client                                       gateway                                              backend service
            >------- http response--<                 <------ unary grpc response ---< 
```
I wrote a demo with UnaryGrpcClient，but it's need aggregate both request and response in memory，how can i avoid aggregate?
```java
public class ProxyService implements HttpService {
    private final UnaryGrpcClient client;

    public ProxyService() {
        this.client = new UnaryGrpcClient(WebClient.of("http://127.0.0.1:7777"));
    }

    @Override
    public HttpResponse serve(ServiceRequestContext ctx, HttpRequest req) {
        CompletableFuture<HttpData> future = req.aggregate()
                .thenCompose(x -> {
                    byte[] body = x.content().array();
                    Demo.ClientRequest request = Demo.ClientRequest.newBuilder()
                            .setBody(ByteString.copyFrom(body))
                            .build();
                    byte[] payload = request.toByteArray();
                    return client.execute("/protobuf.ClientRequestService/request", payload);
                }).thenApply(HttpData::copyOf);
        return HttpResponse.of(ResponseHeaders.of(HttpStatus.OK), Mono.fromFuture(future));
    }
}
```

**Comment by ikhoon** [comment]
> but it's need aggregate both request and response in memory，how can i avoid aggregate?

- An aggregation for a request seems to be needed if you want to wrap a request payload with a unary gRPC message.
- If you don't want to aggregate the unary response, what you can do at the moment is forks our `UnaryGrpcClient`, removes the aggregation part, and return `HttpResponse` itself.
https://github.com/line/armeria/blob/3eef7032c7503c4525a73aa7c0148121859bab8b/grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java#L97-L115

**Comment by douyux** [comment]
@ikhoon thanks for the feedback，i agree with your point, that i can't avoid aggregate both request and response，because i want transfer data from one proto to difference proto.
