### ISSUE TITLE
Provide a way to convert an exception to the response per service

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3421]
We can use the global exception handler to convert an exception to the response by #3413.
```java
Server.builder().exceptionHandler((ctx, cause) -> {
    if (cause instanceof IllegalArgumentException) {
        return AggregatedHttpResponse.of(400));
    }
    ...
}
```
However, a user might want to specify the exception handler differently per service:
```java
sb.route().get("/foo").exceptionHandler((ctx, cause) -> ...);
sb.route().get("/bar").exceptionHandler((ctx, cause) -> ...);
```

Also, a user might want to specify the exception handler differently per virtual host:
```java
sb.virtualHost("baz.com)
  .exceptionHandler((ctx, cause) -> ...);
```

**Comment by minwoox** [comment]
Assigned to @yamamichid

**Comment by yamamichid** [comment]
Related PR: https://github.com/line/armeria/pull/3853

**Comment by jrhee17** [comment]
Handled by https://github.com/line/armeria/pull/4716
