### ISSUE TITLE
Make built-in MDC key `req.id` give `requestId` of root `ServiceRequestContext`

### ISSUE THREAD

**Issue by ks-yim** [line/armeria#3429]
Currently, MDC key, `req.id`, evaluates to `requestId` of `ClientRequestContext` even if it has `ServiceRequestContext` as its root. This undermines the benefit of using MDC as the logs within `ClientRequestContext` don't leave any contextual information of which service request they are scoped to.

I wonder if this is an intended behavior and I should introduce a custom MDC key to trace client logs within a span of service request.

If not, a simple fix for `BuiltInProperty.REQ_ID` will do the work:
```java
// AS-IS
REQ_ID("req.id", log -> log.context().id().text())

// TO-BE
REQ_ID("req.id", log -> log.context().root() != null ? log.context().root().id().text()
                                                     : log.context().id().text())
```

**Comment by ikhoon** [comment]
A request ID is designed to assign a unique key to every request. Therefore I don't think we can use a request ID as a trace ID.
If users need to group a set of requests which are created at the same scope of a `ServiceRequestContext`,
how about adding a new property such as `"req.traceId"` or `"req.rootId"`(need a better name) for that purpose?

**Comment by minwoox** [comment]
Yeah, we need a new property for the purpose.

Because of the `root()` of a `ClientRequestContext` could be `null`(the new property doesn't return `null` when the `root()` is `null`), I slightly prefer to use `req.trace_id`.
I'm worried about if there's someone who already uses the name though.

**Comment by trustin** [comment]
Request ID is not a trace ID to be precise, so `rootId` sounds better to me.

**Comment by minwoox** [comment]
Yeah, but `ClientRequestContext.root()` returns `null` if the ctx is created when there's no `ServiceRequestContext` in the thread local.
But the new property needs to return the id of the `ClientRequestContext` in such a case.
Isn't okay with that? Or should we change to return the `ClientRequestContext` when `ClientRequestContext.root()` returns `null`?

**Comment by ks-yim** [comment]
I think we should return `null` when `ServiceRequestContext` is `null` if we go with `req.rootId`.

**Comment by trustin** [comment]
Ah, yeah, that makes sense. Any better names?

**Comment by trustin** [comment]
`req.rootOrSelfId` ? :laughing:

**Comment by ks-yim** [comment]
`req.root_id` will be enough to serve my needs! Collecting only the ID of `ClientRequestContext` is of no use in our ordinary use cases. Can I work on adding the new built-in property?

**Comment by trustin** [comment]
@ks-yim Yeah, thanks a lot in advance!

**Comment by minwoox** [comment]
Just make sure that `req.root_id` return `null` if `ClientRequestContext.root()` returns `null`. Is that right?

**Comment by ks-yim** [comment]
> Just make sure that req.root_id returns null if ClientRequestContext.root() returns null. Is that right?

Right, I will work in that way!
