### ISSUE TITLE
`IllegalStateException` when `RequestContextHooks.enable()` is used with `armeria-webflux`

### ISSUE THREAD

**Issue by ks-yim** [line/armeria#3442]
#### Problem:
* `RequestContextHooks.enable()` being used with armeria's webflux integration causes an `IllegalStateException` from the second request and on if `@RequestMapping` accepts no arguments.
  ```java
  // IllegalStateException from the second call and on.
  @GetMapping("/")
  Mono<String> hello() { ... }

  // Works normally
  @GetMapping("/{dummyArg}")
  Mono<String> dummyArg(@PathVariable String dummyArg) { ... }
  ```

#### Cause:
* Re-used `Mono`, which has already been converted to `ContextAwareMono`, tries to push an old `ServiceRequestContext` though the current `ServiceRequestContext` is already there.
* _Spring Webflux_ re-uses `Mono` for _"empty-arg-request-mappings"_ in [`InvocableMethodHandler#EMPRY_ARG`](https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/InvocableHandlerMethod.java#L58)
* Minimal reproducible example : https://github.com/ks-yim/armeria-webflux-request-context-hook-example (See `HelloController`)
   - `GET /` - First request succeeds but following requests will fail. Reproducing the issue.
   - `GET /{dummyArg}` - Works normally.
   - `GET /{dummyArg}/with-reused-mono` - Will fail from the second requests and on. An attempt to verify the cause.

#### Workaround (Just an idea..):
* Make `RequestContextHooks` unwrap `ContextAwareMono/Flux`..?
* PR to webflux code

**Comment by ks-yim** [comment]
Oh, this may be fixed with this PR https://github.com/line/armeria/pull/3441

**Comment by ikhoon** [comment]
> Spring Webflux re-uses Mono for "empty-arg-request-mappings" in InvocableMethodHandler#EMPRY_ARG

Yes, the `EMPRY_ARG` was wrapped by ContextAwareMono. I didn't know that you opened a issue for that. I should've fixed it early or more lately to give you a chance to fix it. 🤣
