### ISSUE TITLE
Duplicate `javax.annotation` classes in the classpath when using `armeria-grpc`.

### ISSUE THREAD

**Issue by trustin** [line/armeria#3445]
It seems like `io.grpc` pulls in `jakarta.annotations` and `armeria-grpc` pulls in `javax.annotations`. They basically contains the same classes. We need to exclude `jakarta.annotations` or pull in `jakarta.annotations` in `armeria-grpc`.

**Comment by anuraaga** [comment]
Hmm - if gRPC is pulling it in transitively now (maybe it didn't back in the day hence why it's like it here), we may be able to change to `compileOnly `dependency on `javax.annotation` here same as all the other Armeria projects.
