### ISSUE TITLE
Support JSON Lines encoder for a stream response

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3446]
[JSON Lines](https://jsonlines.org/) is another JSON serialization format that can send a stream of JSON data.
Currently, Armeria only supports [JSON Text sequences](https://datatracker.ietf.org/doc/rfc7464/) format using [JsonTextSequences](https://github.com/line/armeria/blob/67c25e242e8604331bdd8696a97d26604eb114af/core/src/main/java/com/linecorp/armeria/server/streaming/JsonTextSequences.java#L63).
It would be nice to add a decoder that converts a stream of Java plain objects to JsonLines format.
```java
HttpResponse response = JsonLines.fromPublisher(StreamMessage.of(foo, bar));

```

As a separate issue, supporting annotation service is also useful for users.
```java
@ProducesJsonLines
public Publisher<MyObject> jsonLines() {
	return StreamMessage.of(foo, bar)
}
```

**Comment by ikhoon** [comment]
` application/x-ndjson` seems to be conventionally used for Mime type. https://stackoverflow.com/questions/51690624/json-lines-mime-type

**Comment by amitvc** [comment]
@ikhoon Can I please pick this issue ?

**Comment by ikhoon** [comment]
Sure. ❤️ I appreciate your enthusiastic contributions.

**Comment by amitvc** [comment]
@ikhoon I did some reading on the JSON lines encoding. [https://hackernoon.com/json-lines-format-76353b4e588d].
It seems to me the only difference between json lines and json text sequence is the RECORD_SEPARATOR character '0X1E'. I wonder if we should refactor and reuse the same code for both encoders with some changes to the RECORD_SEPARATOR?

**Comment by ikhoon** [comment]
(Had DM with @amitvc) The main difference between JSON Lines and JSON Text Sequences is 
- An object in JSON Text Sequences can be written as multiline strings
  ```
  RS{
    "foo": "bar"
  }LF
  ```
- An object in JSON Lins must be written as a single line with `\n`.
  ```
  { "foo": "bar" }\n
  ```


We can 1) convert an object into a `JsonNode` as an intermediate representation and 
2) serialize the `JsonNode` to a byte array using an internal `ObjectMapper`.
