### ISSUE TITLE
'Failed to force-initialize 'io.netty.channel.unix.Socket' message while using the armeria webflux sample project.

### ISSUE THREAD

**Issue by fclemonschool** [line/armeria#3457]
Hello, I am inquiring with an error while using the armeria webflux sample project.

[https://github.com/line/armeria-examples/tree/master/spring-boot-webflux](https://github.com/line/armeria-examples/tree/master/spring-boot-webflux)

When this sample project is executed without modification, 'Failed to force-initialize 'io.netty.channel.unix.Socket' message is displayed.

![image](https://user-images.githubusercontent.com/18299676/114808584-8c2f9e00-9de3-11eb-8602-4edaf0b77a4f.png)

[armeria_log.txt](https://github.com/line/armeria/files/6314962/armeria_log.txt)

There seems to be no problem with the use, but is this okay?

I am trying to use armeria for the first time, but I am anxious because this message is printed from the beginning.

If there is a problem, I hope it will be fixed.

**Comment by minwoox** [comment]
Thanks for the report. Let us fix that. 😄

**Comment by trustin** [comment]
Meanwhile, it's totally fine to ignore it.

**Comment by fclemonschool** [comment]
> Meanwhile, it's totally fine to ignore it.

Thank you! I'll ignore this message.
