### ISSUE TITLE
Make the number of boss I/O threads configurable

### ISSUE THREAD

**Issue by xyzker** [line/armeria#348]
In the Server.java file I saw "bossGroup = new EpollEventLoopGroup(1, bossThreadFactory);".
I wonder when the concurrency level is high, is only one thread enough for the server acceptor?
why not make it configurable?

**Comment by trustin** [comment]
It depends on how many server sockets you open and how many connections are expected to be accepted by them. Usually, a user opens less than just a few server sockets, so it might be just fine? I think it's a reasonable to add a configuration option for it, though. Let me change the subject of this issue and make it a feature request. Would you be interested in send a PR for this?
