### ISSUE TITLE
Scala extension method that converts `Map[CharSequence, String]` to `Iterator<Entry<>>`

### ISSUE THREAD

**Issue by trustin** [line/armeria#3499]
It is currently quite inconvenient when a Scala user tries to put multiple headers into `HttpHeadersBuilder` from a `Map`:

```scala
val headers: Map[String, String] = ...
val builder = HttpHeaders.builder()
headers.foreach { tuple => builder.add(tuple._1, tuple._2) }
```

It'd be nice if we add an extension method to `Iterable[(CharSequence, String)]` (and `Iterable[(String, String)]`?) so it's easier to convert it into an `Iterator[Map.Entry[CharSequence, String]]`:

```
builder.add(headers.mapEntryIterator)
```

**Comment by ikhoon** [comment]
Could we add a default method for `java.util.Map<String, String>` to `HettpHeadersBuilder` instead of adding a new extension method?
```java
interface HttpHeadersBuilder {
    default HttpHeadersBuilder add(Map<? extends CharSequence, String> entries) {
        return add(entries.entrySet());
    }
}
```

Users could use `scala.immutable.Map[String, String].asJava` with:
```scala
import com.linecorp.armeria.scala.implicits._
val headers: Map[String, String] = Map("foo" -> "bar")
val builder = HttpHeaders.builder()
val header = headers.asJava
builder.add(header)
```
