### ISSUE TITLE
Add `TYPE_USE` target to `@NonNullByDefault`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3527]
Armeria's `@NonNullByDefault` covers only `METHOD`, `PARAMETER`, and `FIELD`
even though Armeria does not return a collection or array that contains a nullable value.

Kotlin 1.5 supports nullability annotations with the `TYPE_USE` target for: 
- Arrays
- Varargs
- Fields
- Type parameters and their bounds
- Type arguments of base classes and interfaces

See https://kotlinlang.org/docs/whatsnew15.html#improvements-to-handling-nullability-annotations

I think it would be better to use `TYPE_USE` target in `@NonNullByDefault` for better type checking and Kotlin integration.

**Comment by trustin** [comment]
Sounds good to me. Please send out a PR :pray:

**Comment by ikhoon** [comment]
I'd be happy to. 😀
