### ISSUE TITLE
Add Brotli support to `{Encoding,Decoding}{Client,Service}`

### ISSUE THREAD

**Issue by trustin** [line/armeria#3544]
Brotli support is coming to Netty: https://github.com/netty/netty/pull/10960 We should add it to the following services and clients:

- `EncodingService`
- `DecodingClient`
- `DecodingService`

**Comment by heka1024** [comment]
I'll try this.

**Comment by trustin** [comment]
Thanks, @heka1024! It's all yours :rocket:
