### ISSUE TITLE
Support vnd.apache.thrift.*

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#355]
vnd.apache.thrift.* is yet another media type for thrift protocol definied at IANA.
See [vnd.apache.thrift.binary](http://www.iana.org/assignments/media-types/application/vnd.apache.thrift.binary),  [vnd.apache.thrift.compact](http://www.iana.org/assignments/media-types/application/vnd.apache.thrift.compact), and [vnd.apache.thrift.json](http://www.iana.org/assignments/media-types/application/vnd.apache.thrift.json).

Currently, only thrift js client supports this([link](https://github.com/apache/thrift/blob/master/lib/js/src/thrift.js#L387)). But if server side implementation supports this media type, it provides less confusion to non-armeria clients.

**Comment by kogecoo** [comment]
+1

**Comment by trustin** [comment]
Working on it

**Comment by trustin** [comment]
Should be fixed by #398
