### ISSUE TITLE
Should not swallow errors of `TransientService`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3551]
I got a report that `PrometheusExpositionService` is not working without any error logs.
I investigated the reason by debugging the code with some break points.
There was a dependency mismatch and the following line raised `NosuchMethodException`.
https://github.com/line/armeria/blob/198c247f2e9092601e920f900412f3cd1c70d7e0/core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java#L90

The error raised by `PrometheusExpositionService` was not logged, because the `TransientService`s are excluded from `LoggingService` by default.
It is difficult for users to detect errors early. Especially when they are upgrading Armeria versions.
  
I propose to change the sensible default behavior of `LoggingService` for the `TransientService`. 
- As-Is: Do not leave logs for requests served by the `TransientService`
- To-Be: Leave a log for a failed request(5xx Server Error) even though the request is served by `TransientService`.

**Comment by trustin** [comment]
:+1:

**Comment by minwoox** [comment]
👍 👍

**Comment by hexoul** [comment]
👍

**Comment by ikhoon** [comment]
> 👍 👍 👍

@hexoul Are you interested in sending a PR. 😆

**Comment by hexoul** [comment]
Oh I am interested in. 🤣  By the way, I would like to get a confirmation. In case of 5xx, should we log regardless of `TransientServiceOption.WITH_SERVICE_LOGGING` and `sample`? Or ignore [sampling](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java#L126) just?

**Comment by ikhoon** [comment]
>  In case of 5xx, should we log regardless of TransientServiceOption.WITH_SERVICE_LOGGING and sample?

We should respect the result of `sample` regardless of status.
