### ISSUE TITLE
Remove locks from `OAuth2Client`

### ISSUE THREAD

**Issue by ks-yim** [line/armeria#3571]
`OAuth2Client` uses ~a dedicated thread pool~ locks and optionally requires a dedicated thread pool(ref. [SerialFuture.java](https://github.com/line/armeria/blob/27f1d605bea0874bf0bd68962f5e405812ba55fd/oauth2/src/main/java/com/linecorp/armeria/internal/common/auth/oauth2/SerialFuture.java)) to solve the concurrency issue related to access token refresh where multiple requests try to update the same token concurrently after it gets expired.

We may want to remove the use of a dedicated thread pool and locks while leaving the code fully asynchronous.

Refer to [this thread](https://github.com/line/armeria/pull/2840#issuecomment-835514231) for the direction of improvement.

**Comment by max904-github** [comment]
This is not a defect.
`SerialFuture` **optionally** accept the `Executor`, but **does not require** it.
See:
```
public SerialFuture(@Nullable Executor executor) ...
```
`SerialFuture` is only an internal implementation. Another class to check is `TokenLifecycleManager`. The actual executor may be supplied via corresponding `OAuth2AuthorizationGrantBuilder`. See `AbstractOAuth2AuthorizationGrantBuilder`:
```
    /**
     * An optional {@link Executor} that facilitates asynchronous access token obtain and refresh operations.
     */
    @SuppressWarnings("unchecked")
    public final T executor(Executor executor) {
        this.executor = requireNonNull(executor, "executor");
        return (T) this;
    }

```
Nowhere it says or implies that the `Executor` (thread pool) is required.
These have been discussed in details during the PR review.

`SerialFuture` relies on moderate `ReentrantReadWriteLock` to serialize asynchronous execution (OAuth 2 operations must be serialized for the same token!). Anyone is free to propose an alternative (more efficient) asynchronous serial execution implementation. Using a cache has been proposed during the review, but as clarified by Ben Manes, this method does not guarantee serial execution. Besides, all the caches still use locks. I'm yet to see such implementation using no single lock.

**Comment by ks-yim** [comment]
@max904-github I've made a suggestion for improvement in your awesome PR though it was quite late.
You may find it in [this comment](https://github.com/line/armeria/pull/2840#issuecomment-835514231).

Following code contains the gist though I'd replace `AtomicBoolean` flag with `AtomicIntegerFieldUpdater` as suggested in the thread. 
```java
private volatile AccessToken token;
private final AtomicBoolean updating;

public CompletionStage<AccessToken> getAccessToken() {
    final CompletableFuture<AccessToken> future = new CompletableFuture<>();
    validateOrUpdate(future);
    return future;
}

private void validateOrUpdate(CompletableFuture<AccessToken> future) {
    if (token.isValid()) {
        future.complete(token);
        return;
    }
    if (updating.compareAndSet(false, true)) {
        issueAccessToken().whenComplete((newToken, cause) -> {
            if (newToken != null) {
                token = newToken;
            }
            updating.compareAndSet(true, false);
            if (cause != null) {
                future.completeExceptionally(cause);
            } else {
                future.complete(token);
            }
        });
        return;
    }
    final ScheduledFuture<Void> scheduledFuture =
            (ScheduledFuture<Void>) ctx.eventLoop().schedule(() -> validateOrUpdate(future),
                                                             getJitterDelay(),
                                                             TimeUnit.MILLISECONDS);
    scheduledFuture.addListener(scheduled -> {
        // handle cancellation and exceptions... 
    });
}
```

**Comment by max904-github** [comment]
Which class this code snippet relates to exactly? Could you provide a complete class/code sample (with all required dimensions)?
Not sure what you are trying to achieve by replacing locks with timers. Scheduling timers will still require some locks. Then you require extra CPU to service wakeups (and consequent context switching). Then, there will be an extra delay introduced to all blocked threads...
What do you think is the problem with the original code really? Let's imagine the situation where you have an expired token and a number of concurrent requests that rely on it. Until the token gets renewed, none of the requests can go through so those will have to to wait. You've suggested different waiting scheme which does not allow saving any resource (in fact it requires extra resource - extra timer thread to handle repeated scheduled tasks and extra CPU to handle those tasks).
As I mentioned earlier, the `Executor` is **optional**, so in case you do not supply it, one of the request threads will be consumed for handling the renewal process and notifying all other waiting requests.
Current `SerialFuture` implementation relies on the combination of read and write locks. Only renewing thread will acquire the `Write` lock to execute series of actions, while all other submitting threads will use only a `Read` lock to check the status (similarly to your `AtomicBoolean`) **concurrently**.
How frequently this situation may/will take place? Very infrequently, but depends on the token lifespan, which typically ranges from minutes to days. Is this a real concurrency or resource consumption issue? No.

Thank you for the PR comment but indeed it came quite late so I did not see it earlier. I'm glad you started using and improving `oauth2` module 👍

**Comment by ks-yim** [comment]
Thanks for the feedback, @max904-github.

First off, I am aware of the concurrency issue regarding token refresh and how the concurrent requests should be managed as you've just summerized in...:
>  Let's imagine the situation where you have an expired token and a number of concurrent requests that rely on it. Until the token gets renewed, none of the requests can go through so those will have to to wait. 

### Problem that I wanted to solve:
Imagine the case where your server application needs to manage a massive amount of user sessions and access/refresh tokens for each of them (ref. [Google OAuth2.0 Scenarios](https://developers.google.com/identity/protocols/oauth2#scenarios)). Let's say for some reason the authorization server becomes irresponsive or slow. The application, then, will easily get resource hungry and irresponsive as every token refresh request will spin up a thread in `Executor` or block an event loop if no `Executor` is supplied.

You may say this kind of problems can be solved by giving a shorter client timeout or by adopting a fail-fast mechanism, but these are not ideal solutions as Armeria's async nature enables us to do things better.

Armeria is capable of handling more than 10k concurrent connections without spinning up many threads and ideally we may want to leave its core logic runs only with `2 * # of CPU core` event loop threads.


### What can be improved?
This may answer your concerns with the following comment:
> You've suggested different waiting scheme which does not allow saving any resource (in fact it requires extra resource - extra timer thread to handle repeated scheduled tasks and extra CPU to handle those tasks).

Introducing CAS and periodic checks with back-off(by scheduling) is a common pattern in Armeria to solve concurrency issues and guarantees a serial execution flow as @trustin has already suggested in [your PR](https://github.com/line/armeria/pull/2840#discussion_r463041559). Armeria's [`RetryingClient.java`](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java#L146-L163) is a good example to see the same pattern.

And as long as I know, Netty event loop's scheduling mechanism is way more efficient than typical executor implementations and doesn't block its backing thread in any ways as it doesn't utilize lock nor timer. And  I am trying to leverage this when I do `ctx.eventLoop().schedule(...)`. You may refer to [`EpollEventLoop.java`](https://github.com/netty/netty/blob/d34212439068091bcec29a8fad4df82f0a82c638/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java) and its super types.


### Working code
I am yet to come with a fully working example here but hopefully I will share the code soon. I think most of the modifications will be on `TokenLifeCycleManager` or `AbstractOAuth2AuthorizationGrant` and a bit of changes in method signature seems inevitable so that those classes have access to `ClientRequestContext`.

**Comment by max904-github** [comment]
> The application, then, will easily get resource hungry and irresponsive as every token refresh request(per session) will spin up a thread in Executor or block an event loop if no Executor is supplied.

I think this (the possibility of an overload or resource exhaustion) requires some proof. Please explain how current solution will spin-up a thread for each token refresh request or block the event loop.

> as every token refresh request(per session) will spin up a thread in Executor

As I explained earlier, if an Executor configured, it will occupy exactly one thread to trigger token renewal (which is also async). No other thread will be blocked. If no Executor configured, one of the request client threads will be involved in triggering the token renewal, while the other threads will remain unblocked.  This will take place once per token renewal cycle.
Therefore, I don't think that the following statement is correct "every token refresh request(per session) will spin up a thread in Executor or block an event loop if no Executor is supplied".

> @trustin has already suggested in your PR

@trustin comment was related to a different code, not to the one you currently see.

> Armeria's RetryingClient.java is a good example to see the same pattern.

It's a good example of something else. Not sure how fail-and-retry pattern relates to the token renewal process. Nothing fails here, so nothing to be retried. There is another [Device Authorization Grant](https://datatracker.ietf.org/doc/html/rfc8628) which indeed involves polling of the Authorization Server. It might be sensible to apply such logic there.

> Imagine the case where your server application needs to manage a massive amount of user sessions and their access/refresh tokens for the resource server.

In such case it would make sense to configure graceful period for access token during which it's still going to be valid but could be renewed ("refreshBefore" configuration).

Finally, it would be nice to see your responses to the following points I have raised:

- Extra CPU consumption to service wake-ups (and consequent context switching) - if you have 100 client requests and each of those will schedule 100 tasks which wake up every millisecond to check the token status... Will it consume extra CPU for this? Will it exhaust/block event loop for a high number of concurrent requests and high re-scheduling rate?
- Then, there will be an extra delay introduced to all blocked threads - a few millisecond delay might be significant for latency sensitive apps. Will this introduce extra delays? Will it impact latency-sensitive apps?
- I understand your passion about Netty event loop scheduling capabilities, but it's arguable how constant scheduling and re-scheduling using this mechanism more efficient than concurrent ReadLock. Do you have any benchmarks supporting your theoretical assessments?

**Comment by ks-yim** [comment]
I realized that I got it completely wrong about what `SerialFuture` does after having another look at the code.
I am sorry that I confused you.

The points that I've made above are wrong in that:
* SerialFuture doesn't block the event loop even without a dedicated `Executor`.

Well, I still have to answer your questions though the discussion has started from my misunderstanding. 😅
* Scheduling a back-off task will be light enough to be scaled up to 1k+ level per event loop (I guess). It doesn't come with additional context switching as scheduling is just pushing a task into a priority queue bound to an event loop. It's not hopping threads. Obviously, we can't re-schedule the same back-off task forever and eventually need to drop the task after a decent number of retry attempts.
* It's hard to answer the 2nd and 3rd questions as I don't have any benchmarks. Just empirical evidence that the same approach adopted in `RetryingClient` scaled well in upstream failure + high traffic situations.

We may close the issue if you think this is not an improvement.

**Comment by trustin** [comment]
Thanks for the discussion. I'll check this PR this week. A general rule of thumb is to reuse the current or given event loop thread instead of allocating a dedicated thread pool, preferably without acquiring any lock. As a framework, it's desirable to provide a way to do something in a more efficient way as long as it doesn't degrade developer experience, even if the gain is not very large, because every little bit adds up.

**Comment by trustin** [comment]
Ah, this is not a PR. Sorry! So my opinion is that:

- Let's optimize it further if possible.
- Let's use Armeria's event loop threads instead of others if possible, because it's what users expect in Armeria.
- Let's drop the usage of locks if possible.

**Comment by ks-yim** [comment]
Thanks for chiming in, trustin. It would be good if we put discussion label on this.
And I should change the title as it is misleading as max stated.

**Comment by trustin** [comment]
I'd like to encourage you to send out a draft PR that shows your proposal so we can compare the old and new implementations. :rocket:

**Comment by ks-yim** [comment]
Thanks, @trustin. I will send a PR next week!
