### ISSUE TITLE
TransportTypeProvider false positive when another shaded version of netty is in classpath

### ISSUE THREAD

**Issue by mauhiz** [line/armeria#3572]
As Netty, like Guava, likes breaking binary compatibility every now and then, libraries that depend on Netty but have a slower release cycle have the habit of including a shaded version of it.
However, depending on the shading process, while the packages are renamed, `io.netty.versions.properties` may be included as-is.
So `TransportTypeProvider` would find several that file in the library with the shaded dependency and generate a warning.
I believe it's a false positive since shaded packages are not found by Armeria.

Suggestions:
- add an option to disable this warn (seems cleaner than having concerned users reconfigure their loggers)
- try harder to tell whether the included `io.netty.versions.properties` is part of a shaded library

**Comment by trustin** [comment]
Hey, thanks for creating this issue. So they shaded Netty JARs but they didn't rename `io.netty.versions.properties` files, right? That's a valid concern. I guess it's hard to know if a `io.netty.versions.properties` is part of a shaded JAR unfortunately given the variety of shade implementations.

How about adding a flag for this in `Flags.java` and explaining how to disable this warning in the WARN message?

**Comment by mauhiz** [comment]
Okay, a flag sounds good to me.
