### ISSUE TITLE
Multipart for annoated services

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3578]
[Multipart] was added to Armeria in [1.6.0](https://armeria.dev/release-notes/1.6.0) and it is programmatically used.
However, we did not implement multipart part messages in annotated services.
It would be useful to inject multipart data directly to the parameters of an annotated service.

I assume the following annotations are working when a content type is `multipart/form-data`.
```java
// Get string data from multipart bodies.
service("/data", (ctx, req) -> {
     Multipart.from(req).aggregate().thenApply(multiPart -> {
                            String data1 = multiPart.field("data1").contentUtf8();
                            String data2 = multiPart.field("data2").contentUtf8();
                            ...
                        }));
});

// Translated to `@Param String fileName`
@Post("/data")
public String stringField(@Param String data1, @Param String data2) {
    ...
}

```java
service("/upload", (ctx, req) -> {
    Multipart.from(req)
		     .bodyParts()
		     .map(bodyPart -> {
		         if (bodyPart.filename().equals("file1")) {
                     // Asynchronously write a Publisher to a file
		             CompletableFuture<File> file1 = writeToFile(bodyPart.content());
		         }
		     })
             ...
});

// Translated to `@Param File fileName` or `@Param Path fileName`
@Post("/upload")
public String upload(@Param File file1) {
    ...
}
```

**Comment by kojilin** [comment]
`@Param File file1` is preserve in temp folder and let user read from it?
  
And curious if its good to support single `MultiPart` method?(If we want Multipart, it means we can't use with aggregated result at same time?)

**Comment by ikhoon** [comment]
> @Param File file1 is preserve in temp folder and let user read from it?

Yeah, that's what I thought. Otherwise, we can add an option to ServerBuilder and a flag to set a folder for the temporary folder.

>  curious if its good to support single MultiPart method?

> if its good to support single MultiPart method?

I think so. It should be good to support single `Multipart` and `AggregatedMultipart`.

> If we want Multipart, it means we can't use with aggregated result at same time?

Does This mean to use `@Param File file1` and `Mutlipart` together like?:
```java
@Post("/data")
public String data(Mutlipart multipart, @Param String data) {
   ...
}
```
A `Multipart` could be subscribed only once. If want to see both the parsed result and multipart messages, `AggregatedMultipart` would be suitable for that case.
```java
@Post("/data")
public String data(AggregatedMultipart multipart, @Param String data) {
   ...
}
```

**Comment by kojilin** [comment]
> Does This mean to use @Param File file1 and Mutlipart together like?:  
Yes, so to avoid user figure out what combination works, maybe armeria doesn't provide this combination, or make document clear enough.
