### ISSUE TITLE
Add  a simple `StreamMessageAndWriter` for a dedicated event loop

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3587]
A `DefaultStreamMessage` is a thread-safe `StreamMessageAndWriter` for multiple producder.
Some technics are used for concurrency such as:
- `MpscChunkedArrayQueue`
  https://github.com/line/armeria/blob/f0252bd457cc5e4fd3e70382debfb8cbadd74bbb/core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java#L106
- Some volatile fields
https://github.com/line/armeria/blob/f0252bd457cc5e4fd3e70382debfb8cbadd74bbb/core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java#L89-L97
- CAS operations
  https://github.com/line/armeria/blob/f0252bd457cc5e4fd3e70382debfb8cbadd74bbb/core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java#L478

In some cases, we can write and read elements in a single event loop.
For example, the `HttpObject`s for `DecodedHttpRequest` and `DecodedHttpResponse` are always written in an event loop with `channelRead` event.
https://github.com/line/armeria/blob/002e24970fb71cbf7bb27697f95367499a19588c/core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java#L185
https://github.com/line/armeria/blob/6f93315ba003f167788d5f4f1c6d7464387444bc/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L248

Furthermore, we don't directly expose the `DecodedHttpRequest` and `DecodedHttpResponse` for gRPC services and clients. It also is subscribed by the event loop which is used for writing.
https://github.com/line/armeria/blob/207c5e038f59802dca769936a50e219a5fe308ea/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L645-L649
It would be efficient to add a non-thread-safe version of `StreamMessageAndWriter` and use it for handling encoding and decoding HTTP layer for gRPC service and client.

**Comment by minwoox** [comment]
We have tried to introduce the `StreamMessage` you described. Its name was `EventLoopStreamMessage`. https://github.com/line/armeria/pull/855#issuecomment-346567012.
However, IIRC, there's not so much gain from it so we removed that.
Let me find the benchmark. (Somehow, I couldn't find it, so if there's anyone who knows about it, please let us know. 😄 )

**Comment by ikhoon** [comment]
`EventLoopStreamMessage` forcibly executes all operations in an event loop.
What I meant was a `StreamMessage` that executes on a current thread(maybe an event loop) without concurrency control.
The caller has to control the serialized access like `HashMap`.

**Comment by jrhee17** [comment]
> Are you interested in implementing a Publisher of Reactive Streams?

Yes, let me take a look soon 👀

**Comment by ikhoon** [comment]
> we can't prevent subscribers from calling subscribe(), request() and close() on DecodedHttp[Request|Response].

That is true for HTTP protocol and REST. A HttpRequest and Response is directly exposed to users with `HttpService` and `WebClient`. Users can subscribe to the `Publisher` with their own `Subscriber`. Some thread safety is required for the `Publisher`.

However, We don’t expose our `HttpRequest` to users for gRPC services. 
- `ArmeriaServerCall` subscribes to `HttpRequest` with `ctx.eventLoop()` for decoding gRPC frames
- The decoded gRPC messages passed to the gRPC stub.

Though a service is RPC, a `HttpRequest` is exposed to users by decorators. But users can not subscribe to the `Publisher` directly because Armeria’s `StreamMessage` should be subscribed only once. I think the stream duplicator could take care of the safety for decorators. 

> One thing I think we can do is modify to not use MpscChunkedArrayQueue since write signals will only be performed from armeria event loops.

Agreed. We don’t need to use `MpscChunkedArrayQueue` for decoded request and response.

**Comment by jrhee17** [comment]
> However, We don’t expose our HttpRequest to users for gRPC services.

Agreed, let me try this idea out

> Agreed. We don’t need to use MpscChunkedArrayQueue for decoded request and response

Ran another iteration with `SpscChunkedArrayQueue`, I think results look promising

```
Benchmark                               (flowControl)  (num)                   (streamType)   Mode  Cnt       Score   Error  Units
StreamMessageBenchmark.jmhEventLoop              true     20         DEFAULT_STREAM_MESSAGE  thrpt       755337.323          ops/s
StreamMessageBenchmark.jmhEventLoop              true     20  UNSAFE_DEFAULT_STREAM_MESSAGE  thrpt       889255.554          ops/s
StreamMessageBenchmark.jmhEventLoop              true     50         DEFAULT_STREAM_MESSAGE  thrpt       331435.476          ops/s
StreamMessageBenchmark.jmhEventLoop              true     50  UNSAFE_DEFAULT_STREAM_MESSAGE  thrpt       393731.185          ops/s
StreamMessageBenchmark.noExecutor                true     20         DEFAULT_STREAM_MESSAGE  thrpt        91227.587          ops/s
StreamMessageBenchmark.noExecutor                true     20  UNSAFE_DEFAULT_STREAM_MESSAGE  thrpt        92408.814          ops/s
StreamMessageBenchmark.noExecutor                true     50         DEFAULT_STREAM_MESSAGE  thrpt        82189.921          ops/s
StreamMessageBenchmark.noExecutor                true     50  UNSAFE_DEFAULT_STREAM_MESSAGE  thrpt        83036.507          ops/s
StreamMessageBenchmark.notJmhEventLoop           true     20         DEFAULT_STREAM_MESSAGE  thrpt        94246.353          ops/s
StreamMessageBenchmark.notJmhEventLoop           true     20  UNSAFE_DEFAULT_STREAM_MESSAGE  thrpt        95641.915          ops/s
StreamMessageBenchmark.notJmhEventLoop           true     50         DEFAULT_STREAM_MESSAGE  thrpt        81611.846          ops/s
StreamMessageBenchmark.notJmhEventLoop           true     50  UNSAFE_DEFAULT_STREAM_MESSAGE  thrpt        84611.598          ops/s
```

**Comment by jrhee17** [comment]
Let me just think about server-side only first since I'm still trying to process everything.

So for grpc I think the flow is as follows:

```
DecodedHttpRequest -> DecodedHttpStreamMessage -> grpc/user land (ArmeriaServiceCall)
```

For `DecodedHttpStreamMessage`, I think making this thread-unsafe is no problem.

For `DecodedHttpRequest`, I think I need to understand your comment first

Currently, I'm thinking of two points:
1) The current code currently doesn't know whether a request is grpc (and whether to create a thread-unsafe `DecodedHttpRequest`) in `Http[1|2]RequestDecoder`. Maybe we can looks at a header value like `content-type` for this though.. I'll have to look into this.
2) IIUC decorators are applied before reaching `*GrpcService`. I guess this means if the user calls `subscribe`/`abort`, the grpc request fails to reach the designated grpc service. I guess I'm concerned if `HttpRequest` isn't thread safe, the request can be end up in a corrupted/undefined state (as opposed to cleanly failing to subscribe when reaching `*GrpcService`). Also I guess the user might implement his/her custom grpc logic in decorators (although this use-case seems unlikely)

> I think the stream duplicator could take care of the safety for decorators.

So I don't think I understood this point. I wonder if the intention of this comment is we could pass a `duplicator`-ed request for decorators.

---

Sorry about the frequent comments/questions 😅  

The past few days were very educational in terms of understanding how reactive streams/grpc works for armeria. Thanks for your patience as always 🙏

**Comment by ikhoon** [comment]
> The current code currently doesn't know whether a request is grpc (and whether to create a thread-unsafe DecodedHttpRequest) in Http[1|2]RequestDecoder. Maybe we can looks at a header value like content-type for this though..

- Prepration: Extract the media type defined in `GrpcSerializationProvider` to `MediaType` such as `MediaType.GRPC`, `MediaType.GRPC_JSON` and so on.
              It is also convenient to add a utility for gRPC media type - `mediaType.isGrpc()`.
https://github.com/line/armeria/blob/9e601afd504a4cb31f6e811cb66b9c535dd026d3/grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcSerializationFormatProvider.java#L35-L41

- Predicate: 
  1. `armeria-grpc` should be added as a dependency. We can statically know with `Class.forName("c.l.a.GrpcService")`.
  2. Use an unsafe `StreamMessage` if `req.contentType().isGrpc()` returns true.
 
> I guess this means if the user calls subscribe/abort, the grpc request fails to reach the designated grpc service. 

- `subscribe`
  - Users should not subscribe to a request/response using decorating a service. It prevents a gRPC service from subscribing to the stream. So `StreamMessageDuplicator` must be used for subscribing to a stream from outside of `Service`. The following Javadoc would help you learn the mechanism. 
  https://github.com/line/armeria/blob/87602a8d52bb94c8bfdec28f48687d3ee4100192/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageDuplicator.java#L29-L43
- `abort`
  - Good point. If users abort a stream outside of an event loop, that could result in a corrupted state such as a concurrent modification. How about forcibly executing `abort()` with in the event loop in `DecodedHttpRequest`.
    https://github.com/line/armeria/blob/dbfc1cdbbacb7c15d8128b5b40972de28a82930e/core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java#L48
    ```java
    void abort() {
	    if (executor.inEventLoop()) {
	        abort0();
	    } else {
	        executor.execute(this::abort0)
	    }
    }
    ```

**Comment by jrhee17** [comment]
> The current code currently doesn't know whether a request is grpc (and whether to create a thread-unsafe DecodedHttpRequest) in Http[1|2]RequestDecoder. Maybe we can looks at a header value like content-type for this though..

I'm thinking the client may set `content-type: application/grpc`, but the path mapping might not be to an actual grpc service (I guess this case is rare though)

> Users should not directly subscribe to a request/response during decorating a service. It prevents a gRPC service from subscribing to the stream. So StreamMessageDuplicator must be used for subscribing to a stream from outside of Service. The following Javadoc would help you learn the mechanism.

I understood this comment to mean: "users should not call `subscribe()` on a grpc `DecodedHttpRequest` directly when the request is destined for a grpc service".

---

I guess I think I understand the requirements for this issue more clearly now:
1) Let me limit the scope to introducing a thread unsafe version of `DecodedHttp[Request|Response]` as a first step.
2) To avoid surprises for users, run operations that potentially cause inconsistent state in the original event loop. This can cause an extra context switch for users using armeria "incorrectly" (i.e. subscribing to the `Http[Request|Response]` in decorators, receiving `content-type: grpc` for non grpc requests).

I think I have enough information to start drafting a PR now, let me know if I'm thinking about anything incorrectly 🙏

**Comment by ikhoon** [comment]
@jrhee17 decided to stop implementing this.
https://github.com/line/armeria/pull/3604#issuecomment-1183336592
