### ISSUE TITLE
Provide a way to set the root context path

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3591]
If a user wants to add a context path for all endpoints,
he/she has to add the prefix string to all service setters which is tedious.
If we provide a way to set the context path, it will be much easier:
```java
Server.builder()
      .contextPath("/api")
      .service("/foo", myService) // myService binds to "/api/foo"
      ...
```

**Comment by AngerM-DD** [comment]
Would it make sense to allow building 'sub routers'? It may end up just being some syntactical sugar but it would be great to have something like: 
```
val builder = Server.builder()
builder.<Add top level http functions>

val api = builder.subRouter("/api")
api.<Add your http handler functions that will get run under /api>
```
etc.

**Comment by vivekkothari** [comment]
Is this getting prioritised anytime soon?

**Comment by minwoox** [comment]
@AngerM-DD Oops, I missed your comment. 😅 
Yeah, I think that will be very useful to have the sub router. 

@vivekkothari I think nobody is working on this. Are you interested in sending a PR for this? 😆

**Comment by vivekkothari** [comment]
Hey, apologies but I am unable to find time to work on this. If anyone else want to pick this up, they can.

**Comment by minwoox** [comment]
Don't worry. 😉 Hope you can contribute next time. 😄

**Comment by kezhenxu94** [comment]
Hey @minwoox , I'm interested in this feature, any hint about how to implement this feature?

**Comment by ikhoon** [comment]
Thanks for your interest in this issue.
`Route.withPrefix(prefix)` will be added in the #4086.
In my opinion, we may need the feature to implement this.
For example:
```java
class ServerBuilder {
     ContextServiceBuilder contextPath(String contextPath) {
         return new ContextServiceBuilder(this, contextPath);
     } 
}
class ContextServiceBuilder {
    
    private final String contextPath;
    ...

    ContextServiceBuilder service(Route route, HttpService service) {
        // Prepends the contextPath to the given route.
        serviceConfigSetters.add(new ServiceConfigBuilder(route.withPrefix(contextPath), service));
        return this;
    }
}
```

**Comment by kezhenxu94** [comment]
@ikhoon thanks for the link!! That looks to be what I've been thinking about. Will watch that PR

**Comment by ikhoon** [comment]
@kezhenxu94 It is likely that you are not working on this at the moment. Could we take this issue? There is a demand for this from LINE internally. @bkkanq will work on this. 🙇‍♂️

**Comment by kezhenxu94** [comment]
> @kezhenxu94 It is likely that you are not working on this at the moment. Could we take this issue? There is a demand for this from LINE internally. @bkkanq will work on this. 🙇‍♂️

Sorry for the inactivity. Sure please assign other one and let me close this 🙇

**Comment by ikhoon** [comment]
On top of `contextPath()` builder API, we can provide a `context-path` property with Armeria Spring integration module.
```yaml
armeria:
  context-path: "/foo/bar"
```

**Comment by bkkanq** [comment]
(pong) 
@ikhoon nim, I'll update the draft PR next week..... sorry for being late 😓

**Comment by ikhoon** [comment]
No worries. @jrhee17 is also interested in the feature. He will lead you to finish it.
