### ISSUE TITLE
Add `ServerBuilder.loopbackPort(int)`

### ISSUE THREAD

**Issue by trustin** [line/armeria#3599]
A user often binds on a loopback port to serve internal use only requests. It is currently done with `port()` method:

```java
Server
  .builder()
  .port(new InetSocketAddress("127.0.0.1", 8080))
  ...
```

It could be useful to have a shortcut method `loopbackPort(int)`:

```java
Server
  .builder()
  .loopbackPort(8080)
  .loopbackPort(9090, SessionProtocol.HTTP, SessionProtocol.HTTPS)
  .loopbackPort(10100, Set.of(SessionProtocol.HTTP, SessionProtocol.HTTPS))
  ...
```

**Comment by anuraaga** [comment]
Out of curiosity what if there was `port(String, int)`? `port("127.0.0.1", 8080)` doesn't seem like many much more typing than `loopbackPort(8080)` but is flexible in any IP and doesn't require knowing what loopback means.

**Comment by trustin** [comment]
Hmmm, I wonder if "127.0.0.1" is always a good choice. Will there be a case where a user has to specify `"::1"` instead of `"127.0.0.1"` for IPv6 enabled systems? How about `localPort()` if `loopback` sounds too nerdy? :laughing:
