### ISSUE TITLE
Provide a way to transform an `HttpHeaders` and `HttpData` in `Http{Request,Response}`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3606]
Currently, we proivde `FilteredHttpRequest` and `FilteredHttpResponse` for tranforming a headers or data.
But it is a bit difficult to implement `FilteredHttp*` because users have to check the type of `HttpObject`.
Most users might not know the hierarchical relation between `HttpOject`, `HttpHeaders`, `ResponseHeaders` and `HttpData` 
```java
return new FilteredHttpResponse(response) {
        protected HttpObject filter(HttpObject obj) {
            if (obj instanceof ResponseHeaders) {
               ...
            } else if (obj instanceof HttpData) {
                ...
            } else {
                // Http trailers.
                assert obj instanceof HttpHeaders;
                ...
            }
            return obj;
        }
```

It would be convenient to provide dedicated transforming functions for `HttpRequest` and `HttpResponse`. 

- `Http{Request,Response}.mapHeaders(Function<? super ResponseHeaders, ? extends ResponseHeaders> f)` 
- `Http{Request,Response}.mapData(Function<? super HttpData, ? extends HttpData> f)`
- `Http{Request,Response}.mapTrailers(Function<? super HttpHeaders, ? extends HttpHeaders> f)`

```java
HttpResponse response = ...;
response.mapHeaders(headers -> {
    if (headers.isInformational()) {
        return ob;
    } else {
        return headers.toBuilder()...build();
    }
}).mapData(data -> {
    ...
});
```

I think `StreamMesage.filter(Predicate)` and `StreamMessage.map(Function)` could be used for implementing those functions.

**Comment by tobias-** [comment]
I believe all the classes extending `FilteredHttpResponse` in Armeria would benefit from being rewritten using those methods (or even being replaced outright).

**Comment by ikhoon** [comment]
By the way, it would be nice to handle this issue myself. Let me remove `good-first-issue` label from this.
