### ISSUE TITLE
"Error: Could not find or load main class" When importing the maven configuration

### ISSUE THREAD

**Issue by xtarx** [line/armeria#361]
After following the maven  [here](http://line.github.io/armeria/setup-maven.html) and running the main class I get this error

> Error: Could not find or load main class hiwi.trail.App

Note: When I remove all the dependancies from the POM.xml the project works completely fine.

**Comment by trustin** [comment]
That's interesting. Could you provide a simple project that reproduces the problem? (because I can't with mine.)

**Comment by xtarx** [comment]
Hello @trustin here is  a screenshot of what the project looks like 

![Screenshot](https://raw.githubusercontent.com/xtarx/iNeed-smart-fridge/master/Screen%20Shot%202017-01-05%20at%2011.13.24.png)

notice also the red circle on the project


project is attached [here](https://github.com/xtarx/iNeed-smart-fridge/raw/master/hiwi.armeria.zip)


Thanks in advance :)

**Comment by imasahiro** [comment]
Hmm.. I checked attached project with eclipse(Eclipse Java EE IDE for Web Developers, Version: Mars.1 Release (4.5.1), Build id: 20150924-1200) and IntelliJ, and both of them said it is ok..

<img width="732" alt="2017-01-06 10 32 50" src="https://cloud.githubusercontent.com/assets/73532/21704287/8ba13ed2-d3fb-11e6-8336-88d9ddd4f355.png">

**Comment by xtarx** [comment]
Yea my bad, but one thing I needed to do to make it work is add this to the POM dependencies 

`   <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>16.0.1</version>
        </dependency>
`

**Be careful because the latest version (19.0) at that time doesn't not work so it has to be 16**


Thanks @imasahiro  @trustin   I'll close the issue

**Comment by trustin** [comment]
@xtarx That's weird, as you see from the POM of armeria-core, it defines guava as the transitive dependency already: https://repo1.maven.org/maven2/com/linecorp/armeria/armeria/0.34.1/armeria-0.34.1.pom

**Comment by AshishGL** [comment]
xtartx You are a saviour bro ! Thanks big time!

**Comment by 8527230165** [comment]
Hi all,
I am getting this same error "Error: Could not find or load main class mavenproject.Testing". Can any help me out in this. See screenshot and code below:-
![error could not find or load main class](https://user-images.githubusercontent.com/38623434/50044853-c66fc000-00af-11e9-974c-02fcbe0e990b.jpg)
[MavenConfigure.zip](https://github.com/line/armeria/files/2682741/MavenConfigure.zip)
