### ISSUE TITLE
[Poll] Should we relax how we parse a boolean parameter in annotated services?

### ISSUE THREAD

**Issue by trustin** [line/armeria#3619]
Armeria currently allows only the following value as a valid input for a boolean query parameter:

- `true` and `false`
- `0` and `1`

We'd like to know if our validation is too strict for real world use cases. Please vote by adding *one or more* reactions to this issue to let us know what you think:

- :-1: - Don't change anything. It's good as it is.
- :laughing: - Treat non-zero integers, such as `-1` and `42`, as `true`.
- :tada: - Treat `yes` and `no` as `true` and `false`.
- :heart: - Treat `y` and `n` as `true` and `false`.
- :rocket: - Treat `on` and `off` as `true` and `false`.

This poll will be open until Jun 14th.
:arrow_down::arrow_down::arrow_down::arrow_down::arrow_down::arrow_down::arrow_down::arrow_down::arrow_down::arrow_down::arrow_down::arrow_down::arrow_down::arrow_down: Please vote now!

**Comment by AngerM-DD** [comment]
Are the string matches case insensitive?

**Comment by trustin** [comment]
> Are the string matches case insensitive?

Yes, they are.

**Comment by trustin** [comment]
Let me close this issue. Rest assured. Nothing's gonna change. :sweat_smile:
