### ISSUE TITLE
Lint for site documentation (*.mdx)

### ISSUE THREAD

**Issue by tobias-** [line/armeria#3620]
There's at least one lint rule that isn't enforced, max line length of 112 characters, but there might be more.

ikhoon suggested that eslint could be co-opted to check the `.mdx` as well. https://github.com/line/armeria/blob/b07cc7c9054d70b7debb1e4e1d29d994198bcd3c/site/package.json#L16

As I'm not a primary contributor, I'm unsure of if there are any other lint rules that should be enforced.

**Comment by ikhoon** [comment]
Probably, we can use https://github.com/mdx-js/eslint-mdx for `mdx` files.

**Comment by tobias-** [comment]
I think this is completely unimportant now that the framework used has been replaced twice since this was reported afaik
