### ISSUE TITLE
core module class `GracefulShutdownHandler` import wrong type of  HttpRequest 

### ISSUE THREAD

**Issue by jonefeewang** [line/armeria#363]
core module `GracefulShutdownHandler` import wrong type of  HttpRequest, cause method
 `boolean isRequestStart(Object msg) {
        return msg instanceof HttpRequest;
    }` useless. It should be `com.linecorp.armeria.common.http.HttpRequest` rather than `io.netty.handler.codec.http.HttpRequest`.

**Comment by trustin** [comment]
Doh! Care to send a PR?

**Comment by jonefeewang** [comment]
with pleasure!

**Comment by trustin** [comment]
I had a chance to read `GracefulShutdownHandler` today and it seems like graceful shutdown is pretty much broken since we started to support streaming. It basically does not handle any HTTP/2 requests.

I suggest extracting the core logic of `GracefulShutdownHandler` into some utility class such as `GracefulShutdownTracker`, keep it as a field of `HttpServerHandler` and update the state of `GracefulShutdownTracker` there.

**Comment by trustin** [comment]
@jonefeewang Given that this is more complicated than initially thought, please feel free to let me know if you do not have enough time for this. I can take over. :-)

**Comment by jonefeewang** [comment]
@Trustin
  Yes, please take it, I’m not fully ready for this.
  I also noted Armeria’s HttpRequest is http/2 stream, simple change it to
this may not complainant with http/1.1 or http/1.0.
  May be we can position GracefulShutdownHandler in a properly  place in the
pipeline  to let it be a netty's HttpRequest.  But it  may cost more time
for me  to figure out a correct way to this.

From:  Trustin Lee <notifications@github.com>
Reply-To:  line/armeria
<reply+002e4617110626fbd32c2bbd2d3025fc1f149342643fbdd892cf00000001148f12209
2a169ce0bf06a15@reply.github.com>
Date:  Thursday, January 12, 2017 at 17:45
To:  line/armeria <armeria@noreply.github.com>
Cc:  王 军飞 <jonefeewang@gmail.com>, Mention <mention@noreply.github.com>
Subject:  Re: [line/armeria] core module class `GracefulShutdownHandler`
import wrong type of HttpRequest (#363)

**Comment by trustin** [comment]
@jonefeewang OK!
