### ISSUE TITLE
[actuator] Uncaught exception in WebOperationService.invoke

### ISSUE THREAD

**Issue by mauhiz** [line/armeria#3633]
When the actuator operation is blocking and `operation.invoke` fails e.g. due to `MissingParametersException`, nobody knows about it, and the response eventually silently times out.
The resulting error 503 is quite hard to debug.

- fix error handling
- add logs

**Comment by minwoox** [comment]
Thanks for the report. Indeed, we need to catch the exception and handle it properly.
https://github.com/line/armeria/blob/master/spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java#L143
Are you sending a PR? 😄
