### ISSUE TITLE
On Springboot 2.5, the requests to /actuator/prometheus timeout with error 503

### ISSUE THREAD

**Issue by mauhiz** [line/armeria#3634]
```
val scraperRequest = RequestHeaders
                .builder(HttpMethod.GET, "/actuator/prometheus")
                // https://github.com/prometheus/prometheus/blob/v2.25.2/scrape/scrape.go#L616
                .add(HttpHeaderNames.ACCEPT, "application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1")
                .build()
        assertThat(httpClient.execute(scraperRequest)
                .aggregate().get()
                .status())
                .isEqualTo(HttpStatus.OK)
```

The actual error might be different once #3633 is fixed..

It seems the underlying cause is that SpringBoot 2.5+ requires an Accept header from Prometheus scraper, which is not forwarded as expected by `WebOperationService.getArguments`

**Comment by mauhiz** [comment]
It looks hard to fix without adding a compatibility layer for SpringBoot 2.5. They have added a `ProducibleOperationArgumentResolver` (implements `OperationArgumentResolver`) that just reads the `Accept` header for this purpose.

**Comment by minwoox** [comment]
> just reads the Accept header for this purpose.

If so, can we just read the `Accept` header from the `AggregatedHttpRequest` and add it to the `arguments`? https://github.com/line/armeria/blob/master/spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java#L142

Is there anything else exception `Accept` header that we need to extract from the request? 🤔

**Comment by mauhiz** [comment]
Not that I know of, but there's no guarantee they won't add more...

It's not very important actually since Armeria has its own `PrometheusExpositionService` and only Prometheus endpoint is affected so far, so maybe it can wait until you support SpringBoot 2.5 officially

**Comment by minwoox** [comment]
I guess so too. 😅
Yeah, we will upgrade to SpringBoot 2.5 soon. Thanks for the report. 😄
