### ISSUE TITLE
Split streaming API from `WebClient`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3649]
If a user receives a fully aggregated HTTP response, he or she should call `aggregate()`:
```java
WebClient client = ...;
CompleteFuture<AggregateHttpResponse> response = client.get("/some/path").aggregate();
```
It could be boilerplate to call `aggregate()` every time because most REST API returns
a unary HTTP response. I think we can improve this API design by splitting `WebClient`
and `StreamWebClient`. The original idea was suggested by @trustin.
```java
WebClient client = ...;
// Returns an aggregated response directly
CompleteFuture<AggregatedHttpResponse> response = client.get("/some/path");

// Switch to a streaming client. 
StreamingWebClient streamingClient = client.streaming();
// Returns an HttpResponse that can be subscribed by a Reactive Streams `Subscriber`
HttpResponse response = streamingClient.get("/some/path");
```

Furthermore, we can also provide a blocking `WebClient` for blocking services and tests.
```java
WebClient client = ...;
// Switch to a streaming client. 
BlockingWebClient blockingClient = client.blocking();
// Wait for an aggregated response until fully received.
AggregatedHttpResponse response = blockingClient.get("/some/path");
```

**Comment by anuraaga** [comment]
Sounds very familiar :P #2364

Don't think it needs to wait for 2.0.0, can leave `WebClient` as is and convert it to the wrappers as per @trustin's suggestion

**Comment by ikhoon** [comment]
> Sounds very familiar :P #2364

Oops... it is.

> Don't think it needs to wait for 2.0.0, 

But isn't it more convenient to provide `CompletableFuture<AggregatedHttpResponse>` as a default?
I thought we can wait for 2.0.0 because 2.0.0 might not be so far. 🤣

**Comment by anuraaga** [comment]
> But isn't it more convenient to provide

It provides some discoverably, but converting a `WebClient` with one method call isn't particularly less convenient I guess.

> because 2.0.0 might not be so far.

This is a scary statement, a year seems like still a small amount of time for Armeria users to end up with breakages. But while a 2.0.0 with some minor cleanups could be ok, I'd say you should wait 2-3 years completely breaking a fundemantal API like `WebClient` - 99% of users are probably using it, and 100% of them will have to refactor their codebases, often largely, to upgrade to the latest Armeria. Seems like very low bang for the buck here compared to the conversion methods.

**Comment by trustin** [comment]
We could probably maintain for another one or two years while working on 2.0? So far we only have a small set of ideas which didn't come true in any concrete form, so I'd expect it will not come any time soon, probably with many alphas and betas at least I guess.

**Comment by anuraaga** [comment]
Another one or two years sounds better :-) It is also a good reason to go with your proposed approach from #2364 I think as it does sound reasonable far off then (good thing).

**Comment by ikhoon** [comment]
`RestClient` added in #4263 which provides fluent APIs to automatically convert an `HttpResponse` into an object. Users we don't need to stream responses, `RestClient` would be a better choice.

We no longer need to split streaming API from `WebClient`.
