### ISSUE TITLE
Log all failure responses regardless of the sampler

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3666]
Currently, `LoggingService` uses the same sampling rate for the success and failure responses. 
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java#L124
It will be nice if we sample all failure responses and just samples for the success responses.

**Comment by trustin** [comment]
or we could keep two different samplers where the default sampler for the failed requests is `always`.

**Comment by minwoox** [comment]
> we could keep two different samplers

That also works. 👍
