### ISSUE TITLE
Allow overriding the default gRPC status to HTTP status rules for an unframed gRPC response

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3683]
An unframed gRPC service statically maps gRPC status to HTTP status based on https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto.
I got a question from Armera slack channel. https://line-armeria.slack.com/archives/C1NGPBUH2/p1625735446194500
> How can I map StatusRuntimeException to http status codes?

Unfortunately, the answer is no. We don't provide a way to customize the default mapping rules at the moment.
It would be nice to take a custom mapping function using `GrpcServiceBuilder`.

**Comment by ikhoon** [comment]
We can introduce an interface to let users override the mapping from gRPC status to HTTP status for unframed gRPC requests.
```java
interface UnframedGrpcStatusFunction {
    // The default mapping.
	static of() {
        return (ctx, status, cause) -> GrpcStatus.grpcStatusToHttpStatus(status);
    }

    // If null is returned, fallback to the default mapping.
    // 'cause' could be captured from `RequestLog.responseCause()`
    @Nullable
	HttpStatus apply(ServiceRequestContext ctx, Status status, @Nullable Throwable cause);

    default UnframedGrpcStatusFunction orElse(UnframedGrpcStatusFunction other) {
        return (ctx, status, cause) -> {
            // apply 'other' if the current status function returns null.
        };
    }
}


GrpcService.builder()
           .unframedGrpcStatusMapping(unframedGrpcStatusFunction);
```

The `UnframedGrpcStatusFunction` set via `GrpcServiceBuilder` could be used in `UnframedGrpcErrorHandler` with a breaking change.
As `UnframedGrpcErrorHandler` is an unstable API, we can add `UnframedGrpcStatusFunction` as the 4th parameter.
https://github.com/line/armeria/blob/ef93d4cbe1657c339875b1dbc970b2f8ef848087/grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java#L111

**Comment by jupiny** [comment]
Thanks for the detailed guide. Let me take this issue 😄

**Comment by jupiny** [comment]
> As UnframedGrpcErrorHandler is an unstable API,

One question, could you explain about this part? 😭
Currently, `unframedGrpcErrorHandler` can be set in `GrpcServiceBuilder`, can't it?

**Comment by ikhoon** [comment]
> > As UnframedGrpcErrorHandler is an unstable API,
> 
> One question, could you explain about this part? 😭 Currently, `unframedGrpcErrorHandler` can be set in `GrpcServiceBuilder`, can't it?

Yes, it is. Currently, the status mapping is hard-coded.
https://github.com/line/armeria/blob/ef93d4cbe1657c339875b1dbc970b2f8ef848087/grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java#L92
We need to pass `UnframedGrpcStatusFunction` to `UnframedGrpcErrorHandler` so that `UnframedGrpcErrorHandler` uses `UnframedGrpcStatusFunction` when building `HttpResponse`.
```diff
 public interface UnframedGrpcErrorHandler {
-    HttpResponse handle(ServiceRequestContext ctx, Status status, AggregatedHttpResponse response);
+    HttpResponse handle(ServiceRequestContext ctx, Status status, AggregatedHttpResponse response, UnframedGrpcStatusFunction statusFunction);
```

**Comment by jupiny** [comment]
Ah, sorry for the misunderstanding the meaning of `UnstableApi`;
I checked a description about `UnstableApi`.

```java
/**
 * Indicates the API of the target is not mature enough to guarantee the compatibility between releases.
 * Its behavior, signature or even existence might change without a prior notice at any point.
 */
 ```
 
 So you said I could add the breaking change simply. Thank you for answer 🙇
