### ISSUE TITLE
`noLint` option is not applied to `ktlintCheck` task

### ISSUE THREAD

**Issue by heowc** [line/armeria#3699]
`ktlintCheck` is the task ktlint runs. I think github-action should ignore this task, but it doesn't work that way.

- https://github.com/line/armeria/runs/3056219351#step:6:405

Also, `ktlintCheck` is not running in lint jobs.

- https://github.com/line/armeria/runs/3056218928

What do you think?

**Comment by ikhoon** [comment]
That sounds like a bug. It should run only in the lint jobs.
