### ISSUE TITLE
Support Sangria

### ISSUE THREAD

**Issue by karellen-kim** [line/armeria#3703]
I'm planning to start a project using the Armeria with Scala.
Armeria-graphql looks awesome. However, honestly, it was difficult to bind GraphQL-Java with Scala.
Does Armeria have any plan to support [Sangria](https://sangria-graphql.github.io/) for better integrating Scala with GraphQL?

**Comment by ikhoon** [comment]
Yeah, Scala has its own world. It would be better to use Sangria than Graphql-Java for Scala. 
We can add an integration module that binds Sangria GraphQL interpreter to Armeria HTTP server.
