### ISSUE TITLE
Serve GraphQL IDE  by Documentation service

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3706]
[GraphQL playground](https://github.com/graphql/graphql-playground) and [GraphiQL](https://github.com/graphql/graphiql) provide awesome features for GraphQL such as:
- Autocompletion 
- Error highlighting
- Browsing GraphQL document
 
Armeria's documentation service leverages GraphQL IDE to support browsing and invoking services.
If a `GraphqlService` is bound to a server, a `DocService` could render a GraphQL IDE rather than Armeria's default web console for GraphQL service.

GraphQL playground looks better but I also concern about the size of the packaged jar.
We need to find a good candidate by considering both usability and lightness.

**Comment by ikhoon** [comment]
@cnabro Any thoughts on this? I heard that you are actively using GraphQL with Armeria. 😄

**Comment by heowc** [comment]
I've been thinking about this too, but I couldn't come up with a suitable way.
And I've included GraphiQL in `DocService`, but UI is broken a lot. 😅

**Comment by ikhoon** [comment]
>  And I tried to include GraphiQL in DocService, but UI is broken a lot. 😅

Oh, I didn't know you've already tried it. I think it should be nice to add though it is not much beautiful.
Can you open a draft PR and let's improve it together. 😆

**Comment by heowc** [comment]
I'm a little worried because I rarely use react. 🤔

Anyway, when I tried, there were quite a lot of conflicts between the CSS we use and the CSS we use in GraphiQL.

If I have time, I'll give it a try. (I don't know if I can do it well...) But it's always okay for someone else to try.

**Comment by cnabro** [comment]
@ikhoon I'm looking forward to this feature 👍 , and I currently used and tried this way to request using `DocService`.
![image](https://user-images.githubusercontent.com/6916639/126098665-06568e8d-2477-41c6-b08e-d7c5dd9151be.png)
![image](https://user-images.githubusercontent.com/6916639/126098675-b3aacb85-c80f-4525-bd22-f1c62704cdaf.png)

But it's hard to use request something using json request for graphql schema.
![image](https://user-images.githubusercontent.com/6916639/126099676-922764ca-77a4-4673-a534-346563a5a656.png)

so I suggest simple feature like this ^^; (and Autocompletion, Error highlighting, etc..)
![image](https://user-images.githubusercontent.com/6916639/126099227-a003e8aa-9c88-4a27-a23e-ace7dfd417e6.png)

**Comment by ikhoon** [comment]
@cnabro As a workaround, we can add GraphQL playground manually at the moment.
https://github.com/line/armeria/pull/3704/files#diff-70e3975d79921104c007396435d88be16b5a01a7d32ef61641d3d6d8537b60b5R45-R46

**Comment by cnabro** [comment]
@ikhoon thanks, I'll apply it. 🙇

**Comment by ikhoon** [comment]
> I'm a little worried because I rarely use react. 🤔
> 
> Anyway, when I tried, there were quite a lot of conflicts between the CSS we use and the CSS we use in GraphiQL.
> 
> If I have time, I'll give it a try. (I don't know if I can do it well...) But It's okay for someone else to try.

Take your time. 😀 If you felt pressured, it wasn't meant to be.

**Comment by heowc** [comment]
It's not perfect, but I tried adding graphiql to the doc-client.
Because the themes specified in [the document](https://github.com/graphql/graphiql/tree/main/packages/graphiql#applying-an-editor-theme) could not solve the css broken, I temporarily applied external css.

https://github.com/SaraVieira/graphiql-material-theme

<img width="1676" alt="스크린샷 2021-08-12 오후 1 55 33" src="https://user-images.githubusercontent.com/22594101/129140231-3fc76612-9819-4a40-9af6-4246ea8fa5ba.png">

And the doc service was modified based on #3661 I was working on.

**Comment by heowc** [comment]
Perhaps it is possible to add a separate feature. 😆

**Comment by heowc** [comment]
I've been trying to embed GraphiQL, but I think other alternatives can work around this as well. 🤔

- iframe?
- another page?

**Comment by heowc** [comment]
It looks good to use `codemirror-graphql`. 🤔

![image](https://user-images.githubusercontent.com/22594101/129843117-a3a41baa-787d-4e09-8e43-d706b81f9dd2.png)

**Comment by ikhoon** [comment]
> It looks good to use codemirror-graphql. 🤔

Oh! 👍 It looks good. By the way, does it support browsing documentation?

**Comment by heowc** [comment]
> By the way, does it support browsing documentation?

It's probably not supported. 🤔

`codemirror-graphql` only supports autocomplete using schema, hints, and syntax checking.

**Comment by heowc** [comment]
As of graphiql 2.x, it seems you want to use `monaco` rather than `codemirror`.

- https://github.com/graphql/graphiql#proposed-ecosystem
- https://github.com/graphql/graphiql/tree/main/examples/monaco-graphql-webpack
- https://microsoft.github.io/monaco-editor/

**Comment by heowc** [comment]
Looking a little more, it seems that graphiql has added quite [a lot of features](https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/QueryEditor.tsx).

- We can take this and fix it or
- Just use GraphiQL as-is.

**Comment by heowc** [comment]
I have included [QueryEditor](https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/QueryEditor.tsx) component of GraphiQL in DocService. 😎

https://user-images.githubusercontent.com/22594101/130785067-4907bfee-90db-43ec-a58d-c28a82ff9fb9.mov

But I have one problem.

Schema information must be fetched from the server for autocomplete and highlighting, but it cannot be fetched if authentication processing is required.

How can I solve this? Could you give me an idea? 🤔

**Comment by heowc** [comment]
Due to `codemirror` (about 200KB) and `graphql` (about 200KB), the bundled JavaScript files are large. 😱 

as-is: **564KB**
to-be: **1020KB**

Already `armeria-core` (as of 1.11.0, 8.83MB) is quite large, so I have to reduce it.

**Comment by ikhoon** [comment]
400KB seems acceptable to me.
By the way, I was thinking of an idea that compresses the bundled js file with gzip when packaging the jar. 
The compressed file will be used itself if a client supports gzip. Actually, there is no modern web browser that does not support gzip. 
I could decompress and cache the unzipped result for a while when a client does not support gzip decompression.

**Comment by heowc** [comment]
> By the way, I was thinking of an idea that compresses the bundled js file with gzip when packaging the jar.

good idea! 😎 

We will be able to reduce the size considerably by using gzip.

**Comment by heowc** [comment]
I tried applying compression to `DocService` and `doc-client`. Due to this, it was confirmed that it was reduced to **about 300KB**.

See https://github.com/heowc/armeria/commit/7afddf042dce167cd0eaef3b840eecefb28bd7e9

**Comment by ikhoon** [comment]
I didn't know that we already had `serveCompressedFiles` option. 😆
By the way, it does not support automatic decompression at the moment.

**Comment by ikhoon** [comment]
Filed an issue for automatic decompression. #3804

**Comment by heowc** [comment]
If so, I will not apply `CompressionWebpackPlugin` until the mentioned feature is released.

**Comment by ikhoon** [comment]
Okay, let's apply `CompressionWebpackPlugin` once #3804 is implemented.
