### ISSUE TITLE
Add ability to change TLS settings with dynamic reconfiguration of service

### ISSUE THREAD

**Issue by amitvc** [line/armeria#3709]
With #3362 we introduced functionality to dynamically reconfigure the server without restarting it. This is a continuation of that feature. We would like to also like to be able to change TLS settings while dynamically reconfiguring the server. Currently, we are able to reconfigure a server endpoint by adding new routes. But these new routes take the existing TLS setting. A user might be interested to change the TLS settings when they reconfigure the server.

**Comment by trustin** [comment]
Looking forward to this feature to be implemented!

**Comment by jrhee17** [comment]
I believe this has been addressed with #4637
