### ISSUE TITLE
Improve `HttpHeaders` intenral container implementation to contain various types

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3711]
Currently, `HttpHeaders` internally holds headers as string values.
It stringifies an object into a string before adding the value to the internal container.
https://github.com/line/armeria/blob/e66c339c75de9884ecca734f74bc4420b663dccd/core/src/main/java/com/linecorp/armeria/common/StringMultimap.java#L699-L718
This implementation has a weakness when a non-string value is set to `HttpHeaders` and gotten later.
It deserializes the stringified value again.
For example:
```java
var headers = ResponseHeaders.of(HttpStatus.OK); // Convert 200 into "200" and;
headers.status();                                // Parse "200" into 200 again.
```
I saw this conversion from the flame chart.
![image](https://user-images.githubusercontent.com/1866157/126309245-fd638aed-db8e-4d7d-b7ee-56e058768837.png)

**Comment by trustin** [comment]
For the specific case of `header.status()`, we could make sure `ResponseHeaders.builder(HttpStatus)` cache the `HttpStatus`. We currently use `.add(HttpHeaderNames.STATUS, ...)` which can't cache the status.

**Comment by ikhoon** [comment]
Nice idea. Let me apply the idea. :-)

**Comment by trustin** [comment]
We could do the same for some other fields that are already being cached via certain setters.
