### ISSUE TITLE
`RequestLog` with `ContentPreviewingService` is not ended when `HttpStatusException` is thrown

### ISSUE THREAD

**Issue by ghkim3221** [line/armeria#3719]
When `ContentPreviewingService` is used, request is not ended if the request fails while routing. `LoggingClient` logs only request and `armeria.server.active.requests` meter increase.

With a little digging, I found that the problem occurred when `service.serve` in `HttpServerHandler` fails with `HttpStatusException`. Because `HttpStatusException` is not set to the `raisedException` not to log as cause, `HttpResponseSubscriber` is created with null `primaryCause`:
https://github.com/line/armeria/blob/9a66de992195a6f1d2fe11c798e9b1a1e31464b4/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L408-L412

So this response is ended without `primaryCause `: 
https://github.com/line/armeria/blob/9a66de992195a6f1d2fe11c798e9b1a1e31464b4/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L552-L558

Null `responseCause` can be problem when `RequestLog` is deferred with `RESPONSE_CONTENT` or `RESPONSE_CONTENT_PREVIEW` because their flags are not cleared:
https://github.com/line/armeria/blob/9a66de992195a6f1d2fe11c798e9b1a1e31464b4/core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java#L1320-L1326

So `whenComplete` futures are not satisfied and not completed. I think this is why the `RequestLog` is not ended.

But I don't have any good idea yet to fix while keeping not logging `HttpStatusException` 😅

**Comment by ikhoon** [comment]
This code has been changed a lot except for `DefaultRequestLog`.
https://github.com/line/armeria/blob/efb89d6e2a908a98d840ec511e457001ec0fc3cd/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L391-L413
Maybe not a good idea to fix this in the master branch. Let me fix this issue in #3674 together.
Will you review the changes when I am ready?

**Comment by ghkim3221** [comment]
Thanks @ikhoon. Please fix it 🙇‍♂️ 

> Will you review the changes when I am ready?

I will do my best to review.

**Comment by ikhoon** [comment]
The bug has been fixed in https://github.com/ikhoon/armeria/commit/cbb9accc5dba923a694edf2739ecc4f6ce655dbf
