### ISSUE TITLE
Split armeria-tomcat into armeria-tomcat and armeria-tomcat{75,80}

### ISSUE THREAD

**Issue by trustin** [line/armeria#374]
.. where:

- armeria-tomcat is for the latest stable Tomcat release
- armeria-tomcatXY if for the latest Tomcat X.Y release

**Comment by imasahiro** [comment]
FYI, tomcat-8.5.8 introduces new API, `OutputBuffer#doWrite(ByteChunk)` and `InputBuffer#doRead(ApplicationBufferHandler)`. So my guess is we also need to add tomcat858...?

**Comment by trustin** [comment]
@imasahiro That was the main cause of the creation of this issue actually. I guess it's too much effort to provide a separate module for micro versions, so I was thinking of supporting 8.5.8+ in armeria-tomcat and not supporting 8.5.[0-7]. What do you think?
