### ISSUE TITLE
ServerExtension.httpClient() that makes requests to a test server

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#3761]
I think it can be convenient for `ServerExtension` to have a method that returns a client (guess it would need both http and https versions) pointing at the test server to avoid fiddling with. This is particularly nice for requesting from a service to itself - during `configure`, `httpUri` doesn't resolve but just accessing `server.httpClient()` directly from a service would work.

**Comment by minwoox** [comment]
That's a good idea.
Currently, Central Dogma provides it. https://github.com/line/centraldogma/blob/master/testing/junit/src/main/java/com/linecorp/centraldogma/testing/junit/CentralDogmaExtension.java#L207
