### ISSUE TITLE
Use an `Content-type` header to encode an error mesasge in `UnframedGrpcService`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3777]
Currently, `UnframedGrpcService` returns an error message as plain text.
https://github.com/line/armeria/blob/54b70906bcd813f0b9b2c6715ad4086160ac49b2/grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java#L255-L272
It would be nice to return a JSON object if the content type is JSON compatible.
```json
{ 
   "code": "FAILED_PRECONDITION",
   "message": "Input validation failed"
}
```

**Comment by trustin** [comment]
A sensible response format sounds good to me, but it'd be even better if a user can send a custom response, too, probably by calling a builder method.

**Comment by ikhoon** [comment]
+1 That is also a good idea.

**Comment by JunoJunho** [comment]
Let me try this!

**Comment by ikhoon** [comment]
> Let me try this!

@vivekkothari who suggested this idea showed that he wanted to try this issue early in the Slack channel. 
https://line-armeria.slack.com/archives/C1NGPBUH2/p1629357253096700?thread_ts=1629275842.094200&cid=C1NGPBUH2
I missed updating his thought.
