### ISSUE TITLE
Deprecate Cookie.builder() and introduce a method secure defaults.

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#3788]
Just a suggestion.

I feel like Armeria's CookieBuilder makes it too easy to create an insecure service. Default of secure, http only, same site cookies and requiring a user to explicitly opt out would help prevent accidental cookie leaks without a real UX penalty when the use case does need something more lax.

**Comment by anuraaga** [comment]
An alternative to deprecating the method is to change the behavior with a flag to restore insecure defaults. It's technically breaking but doesn't need code change to work around and could be appropriate for enhancing security.

**Comment by trustin** [comment]
How about deprecating `.builder()` and adding `.secureBuilder()` until we have 2.0?
