### ISSUE TITLE
Allow AbstractHttpRequestBuilder to set path with empty string.

### ISSUE THREAD

**Issue by eisig** [line/armeria#3824]
We are migrating some http clients to WebClient.
And we have may urls in config files(or database) with path prefx, such as:
```
url1=http://host:port/test/issues
```
  We can not send a request without modify the url .
```
 WebClient.of(url1).prepare().get("") .execute();
```
We may write a helper to split the url to host and path. but we also need to send reuqest to sub path. It would make the code a little complicated.

So we use a  very hacking way to bypass the check at the moment. (/XX_PATH_TO_STRIP would remove by a  decorator).

```
path = Strings.isNullOrEmpty(path)? "/XX_PATH_TO_STRIP": path 
webclient.prepare().get(path) .execute();
```

**Comment by minwoox** [comment]
closed by #3942
