### ISSUE TITLE
CorsService's `Access-Control-Allow-Headers` wildcard compatibility

### ISSUE THREAD

**Issue by ghkim3221** [line/armeria#3839]
Users may configure `Access-Control-Allow-Headers` using `CorsServiceBuilder#allowRequestHeaders` and set `allowRequestHeaders` as wildcard (`*`) to allow all headers.

However, it has compatibility issue because [Internet Explorer, Safari and Firefox for Android don't support](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers#browser_compatibility):
![image](https://user-images.githubusercontent.com/15008311/135189963-142468c4-45c7-4740-a27e-ba3eea066de7.png)

So I guess that `CorsService` doesn't support allowing all headers. And it would be fixed by returning requested `Access-Control-Request-Headers` header and providing an option:
```java
allowAllRequestHeaders() {
  allowAllRequestHeaders(false);
}

allowAllRequestHeaders(boolean useWildcard) {
  ...
}
```

**Comment by ks-yim** [comment]
Other server frameworks(e.g. Spring, Express) allow all headers by default if allowed headers are not explicitly specified.
Wouldn't this also be a fine default for armeria too?

**Comment by ikhoon** [comment]
>  Wouldn't this also be a fine default for armeria too?

It could be a breaking change. We can consider the sensible default in Armeria 2.0.
I prefer to add `allowAllRequestHeaders()` at the moment.

**Comment by minwoox** [comment]
> Wouldn't this also be a fine default for armeria too?

Had a chat with @ikhoon and we thought specifying the headers in [safelisted request headers](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_request_header) could be a sensible default when `allowRequestHeaders` is not set.
What do you think about it? @ks-yim

**Comment by ks-yim** [comment]
Sounds good to me, WDYT @ghkim3221?

**Comment by ghkim3221** [comment]
You want to set `Access-Control-Allow-Headers` safelisted request headers in the given `Access-Control-Request-Headers` even `allowRequestHeaders` is not set, right?

**Comment by minwoox** [comment]
> Do we still need?

Oops, I missed that. Then, we don't have to specify the headers in the list. 😄

**Comment by ks-yim** [comment]
I thought you wanted to override additional restrictions 😄.
Even `application/json` is not allowed if `Content-Type` is not specified in the allowed header.

Either way is fine for me, though.

**Comment by minwoox** [comment]
>  @minwoox wanted to override additional restrictions

That's not what I wanted. I just didn't know about those headers could be ommited.

> Even application/json is not allowed if Content-Type is not specified in the allowed header.

That's true. In this case, the browser will set the `Content-Type` to `Access-Control-Request-Headers` and the response should contain `Content-Type` in `Access-Control-Allow-Headers` which means `Content-Type` needs to be set via `CorsServiceBuilder#allowRequestHeaders`.
