### ISSUE TITLE
Add `StreamMessage.mapAsync()`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3916]
Currently, `StreamMessage` provides limited operations such as `map`, `filter`.
Those operations are synchronous and can not handle asynchronous tasks.
`mapAsync` would be useful to transform data with extra information that is in external services.
```java
interface StreamMesage<T> {
    // The next item will be requested after the returned future is completed successfully.
    StreamMessage<U> mapAsync(Function<T, CompletableFuture<U>> function);
}
```

**Comment by sleeplesslord** [comment]
I'd like to work on this issue

**Comment by ikhoon** [comment]
Thanks in advance!
