### ISSUE TITLE
Expose Actuator `WebOperation` to  a port of internal services

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3919]
Actuator integration module only exposes `WebOperationService` to [`management.server.port`](https://docs.spring.io/spring-boot/docs/2.1.17.RELEASE/reference/html/production-ready-monitoring.html#production-ready-customizing-management-server-port).
https://github.com/line/armeria/blob/7626562204bd4311a1205df9d733203324355a96/spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java#L216-L222
@ghkim3221 [suggested](https://github.com/line/armeria/pull/3873#discussion_r728551742) servicing the `WebOperationService`s on Armeria's internal service ports.

We need the following steps to support the feature.
- Add `ACTUATOR` to `InternalServiceId`.
https://github.com/line/armeria/blob/7626562204bd4311a1205df9d733203324355a96/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/InternalServiceId.java#L32-L36
- Dynamically acquire internal service port with some reflection. The Actuator integration does not directly depend on the Spring integration.
https://github.com/line/armeria/blob/7626562204bd4311a1205df9d733203324355a96/spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java#L258-L264
- Bind `WebOperationService` to internal service port if `ACTUATOR` ID is specified and the port is activated.

**Comment by minwoox** [comment]
What's the expected behavior if `ACTUATOR` is specified while the port is not specified?

**Comment by minwoox** [comment]
> What's the expected behavior if ACTUATOR is specified while the port is not specified?

Like other internal services, I guess we need to bind the actuator to the default virtual host.
We need to update the Javadoc of `InternalServices` to describe the behavior when the port is not specified. 😉
