### ISSUE TITLE
Implement client-side upgrade handler without aggregating the entire HTTP objects.

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3923]
`HttpObjectAggregator` has been removed from the server-side HTTP/2 upgrader handler with #3913.
We can also apply the same approach to the client-side upgrade handler so that clients receive upgrade responses larger than 16384.
https://github.com/line/armeria/blob/755dc71b27099152be8efa352a4b5be4b35c768e/core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java#L323-L326
https://github.com/line/armeria/blob/755dc71b27099152be8efa352a4b5be4b35c768e/core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java#L111-L114

**Comment by doppany** [comment]
@ikhoon I have checked the comment above and #3913 codes and I have a question.
I wonder what the correlation between removing `UPGRADE_RESPONSE_MAX_LENGTH` & using `maxResponseLength` and upgrading the http2 protocol is. 🙏

**Comment by minwoox** [comment]
> I wonder what the correlation between removing UPGRADE_RESPONSE_MAX_LENGTH & using maxResponseLength and upgrading the http2 protocol is.

I guess we can set the value that is greater than  16384  to `ClientBuilder.maxResponseLength(...)`  so we can safely send an upgrade response whose length is greater than 16384. 🤔

**Comment by minwoox** [comment]
Had a chat with the team and we decided to close this issue.
We are sending the `OPTIONS * http/1.1` request for an upgrade and the request is treated as a ping or no-op as described in the spec: https://httpwg.org/specs/rfc9110.html#OPTIONS
So, there're not so many chances that the response of the upgrade request is large.
