### ISSUE TITLE
PrometheusExpositionService doesn't support OpenMetrics Format

### ISSUE THREAD

**Issue by AngerM** [line/armeria#3926]
The current exporter doesn't support OpenMetrics format. It's fairly simple and most of this is actually handled directly by the prometheus library itself via the TextFormat class. See: https://github.com/AngerM/ag_server/blob/main/base/src/main/kotlin/dev/angerm/ag_server/http/PrometheusHandler.kt 
Which I based off of https://github.com/prometheus/client_java/blob/master/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java
to support some of the query options, etc.

**Comment by ikhoon** [comment]
We can easily support OpenMetrics format using `TextFormat.writeOpenMetrics100()` when a client want to accept `application/openmetrics-text;`.
https://github.com/line/armeria/blob/198c247f2e9092601e920f900412f3cd1c70d7e0/core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java#L89-L92
Are you interested in sending a PR? 😆
