### ISSUE TITLE
Add `StreamMessage.of(inputStream, bufferSize)`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3937]
It would be nice if we provide a way to convert an `InputStream` to a `StreamMessage<HttpData>` that splits the binary by the `bufferSize`.
```java
static StreamMessage<HttpData> of(InputStream inputStream, ByteBufAllocator alloc, int bufferSize) {...}
```

**Comment by ikhoon** [comment]
We might need to take a dedicated blocking executor to read `InputStream`.

**Comment by nvidyala** [comment]
@minwoox Could I try my hand at this?

**Comment by minwoox** [comment]
It's all yours 😆

**Comment by nvidyala** [comment]
@minwoox I've been reading up on Reactive Streams and just wanted to confirm my understanding of the problem statement before I start coding the wrong thing 😆.

The same way that we can pass in a file to generate a StreamMessage using:
`static StreamMessage<HttpData> of(Path path, ByteBufAllocator alloc, int bufferSize)`
this issue requires a similar overload of the `of` method (as described by your initial comment). This would return a new class (which implements `StreamMessage`) that would be capable of taking an `InputStream` and return `bufferSize` bytes when `demand()` is invoked (along with the remaining logic for the subscriber & subscription).

Is my understanding of the approach correct?

**Comment by minwoox** [comment]
> This would return a new class (which implements StreamMessage) that would be capable of taking an InputStream and return bufferSize bytes when demand() is invoked

Yes, exactly. 😄 
You might want to take a look at https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/file/StreamingHttpFile.java
because it's implemented in that way.

**Comment by nvidyala** [comment]
Alright, that sounds good! 😄
Could you please assign this issue to me?

**Comment by minwoox** [comment]
> Could you please assign this issue to me?

All yours. 😉

**Comment by injae-kim** [comment]
Hi @nvidyala !
I made similar PR (way to adapt `StreamMessage` into `InputStream`) on #4059 and it may help to solve this PR! 😄

**Comment by injae-kim** [comment]
May I handle this issue? 🙇
