### ISSUE TITLE
Move up service routing to `Http{1,2}RequestDecoder`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3940]
If a service does not support a streaming request, we don't need to create a stream request using `DefaultStreamMessage` is more expensive than a fixed size request using `FixedStreamMessage`. We need more information on the service to create an optimized HTTP request. We don't know the service when initiating the request. Currently, we only utilize HTTP headers which only tells whether a request has a body.
https://github.com/line/armeria/blob/2920a1ddc2188f150a0d8b77de1d4e2e409997cf/core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java#L136-L145

On the other hand, a service could provide various information for a request such as input type and out type.
A service for a request is chosen in the `HttpServerHandler`
https://github.com/line/armeria/blob/2920a1ddc2188f150a0d8b77de1d4e2e409997cf/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L352-L358
It is after the creation of a request. If we can move the routing that finds the corresponding service to `Http{1,2}RequestDecoder`, we can create optimized HTTP requests using `FixedDecodedHttpRequest` that get the best out of `FixedStreamMessage`.

**Comment by jrhee17** [comment]
Handled by #3956
