### ISSUE TITLE
Internal service exposed even if it's not included in armeria setting

### ISSUE THREAD

**Issue by policeman-kh** [line/armeria#3944]
I found an issue that might be a bug.
The setting of Armeria internal services only include “metrics” like
```
armeria:
  internal-services:
    include: metrics
    port: 18080
```
However, internal service `healthcheck` which is not included in the setting still exposes with `18080` port.
I checked the behavior with `master` branch.

- to be: The internal service `healthcheck` does not expose with `18080` port.

And I found [a test case](https://github.com/line/armeria/blob/master/spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationInternalServiceTest.java) about that.

Both `metric` and `healthcheck` are included in internal-services which are exposed. 
So the current test case works well.
Maybe better to remove `healthcheck` from the setting and check if the status is `404`.

**Comment by ikhoon** [comment]
If a health check path is specified, a `HealthCheckService` will be bound to either 1) an internal port or 2) all ports of the default virtual host.
https://github.com/line/armeria/blob/7626562204bd4311a1205df9d733203324355a96/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java#L389
If `healthcheck` is not included in `internal-services.include`, it will be bound to the default virtual host.
All services registered in the default virtual host are copied to custom virtual hosts. The virtual service listening to the internal port is one of the custom virtual hosts.

The virtual host builder is so crowded already. I don't want to add methods with a flag to `ServerBuilder` for whether to copy or not of a service to custom virtual hosts. 
If you'd like to exclude `healthcheck` from internal port, you want to use either a decorator or manually set up internal services using a `ServerBuilder`.

**Comment by policeman-kh** [comment]
Thanks for answering.
I understood the current spec. 

If `xxx` is included in `internal-services.include`, it will be exposed to only the internal port.
If `xxx` is not included in `internal-services.include`, it will be exposed to all ports.

It looks ok to me. Let me close the issue.
