### ISSUE TITLE
Provide a way to disallow overriding endpoints with empty endpoints for `DynamicEndpointGroup`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3952]
A `DynamicEndpointGroup` could be empty because of misconfigured DNS records or consecutive health-check failures.
I think we can provide an option that prevents the existing endpoints from empty endpoints.
For example,
```java
public DynamicEndpointGroup(boolean allowEmptyEndpoints) {
    ...
}

DnsTextEndpointGroup.builder(...)
                    .allowEmptyEndpoint(false);
```
If `allowEmptyEndpoints` is set to false, empty endpoints should not be updated by `setEndpoints` 
https://github.com/line/armeria/blob/39e97e2686c76e8122f2c1ec6057abcd201a485b/core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java#L160

**Comment by doppany** [comment]
I will work on it 🤔 @ikhoon should I create a builder for `DynamicEndpointGroup`?

**Comment by ikhoon** [comment]
Commented on https://github.com/line/armeria/pull/3958#issuecomment-981418361
An abstract `DynamicEndpointGroup` builder could provide a consistent API for the subclasses of `DynamicEndpointGroup` builder.
