### ISSUE TITLE
Add `queryParams()` to `ServiceRequestContext`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3955]
It would be convenient to access query parameters from `ServiceRequestContext` like `pathParams`.
https://github.com/line/armeria/blob/bcb621e46c26f0ac84b4b820687383a99b509019/core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java#L251-L259
```java
interface ServiceRequestContext {
    QueryParams queryParams();
    String queryParam(String name);
}
```

**Comment by injae-kim** [comment]
can I try this issue? 😄 
cc. `@ikhoon`

**Comment by ikhoon** [comment]
Please, go ahead. 🙇‍♂️
