### ISSUE TITLE
Split `AmeriaServerCall` into `UnaryAmeriaServerCall` and `StreamingAmeriaServerCall`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3965]
[`ArmeriaServerCall`](https://github.com/line/armeria/blob/cb66bcc22de260b0a56144b1cec2219dc373227a/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java) handles unary/streaming requests and responses for gRPC services.
If we implement a `ServerCall` only for a unary call:
- Remove meaningless fields and operations in unary calls that are used for backpressure.
https://github.com/line/armeria/blob/cb66bcc22de260b0a56144b1cec2219dc373227a/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L103-L104
- Use a 1 to 3 fixed stream messages for an `HttpResponse` instead of `DefaultStreamMessage` 
  that have lower memory footprint and are faster.
- Be able to aggregate a request before decoding.

**Comment by jrhee17** [comment]
closed by #3956
