### ISSUE TITLE
DocService does not show the service name

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3977]
We can set the name of a service via `defaultServiceNaming`
```java
sb.annotatedService()
  .defaultServiceNaming(ServiceNaming.of("foo"))
  ...
```
However, DocService does not show the service name but it displays the class name.

**Comment by kojilin** [comment]
Curious if this is possible? IIUC, ServiceNaming can be decided by ctx and it's also possible to give different name for different method in same class.

**Comment by minwoox** [comment]
That's correct. We can't use `defaultServiceNaming` to modify the service name. 😅 
We might add a mapper that maps a class to the customized service name to `DocServiceBuilder` if there's a demand for that.
Let me close this for now. 😄

**Comment by ikhoon** [comment]
> Curious if this is possible?

I thought we can display service names specified by `@ServiceName("...")` but could not a general solution.
