### ISSUE TITLE
Support new URI variable syntaxes that Spring 5.0 added

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3994]
So that users who use Armeria Spring integration can leverage the feature.
https://www.baeldung.com/spring-5-mvc-url-matching#new-url-pattern-matchers-in-spring-50

**Comment by minwoox** [comment]
@policeman-kh  is implementing one of the syntaxes which is `/{*foo}` for fixing #3031

**Comment by minwoox** [comment]
Duplicate #2291

**Comment by trustin** [comment]
Added `duplicate` label to avoid confusion.
