### ISSUE TITLE
Provide a way to set media type for a file in FileService

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4001]
Users can serve a bunch of files using `FileService`:
```java
FileService.builder("/root/")...
```
When the file in the `/root/` directory is served(e.g. `/root/foo.webp`), the media type is determined by the `EXTENSION_TO_MEDIA_TYPE` in `MimeTypeUtil`: https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/file/MimeTypeUtil.java#L38
which means that users cannot set the media type for the files whose extensions do not belong to the map.
We can provide an interface so that users can set the media type using the path:
```java
public interface MimeTypeFunction {
    MediaType guessFromPath(String path);
    MediaType guessFromPath(String path, @Nullable String contentEncoding);
}
```
And then,
```java
MimeTypeFunction function = ...

FileService.builder("/root/")
           .mimeTypeFunction(function)
           .build();
```

**Comment by klurpicolo** [comment]
Hi @minwoox, I'd like to work on this feature. Could you please assign me?

**Comment by minwoox** [comment]
@klurpicolo It's all yours. 😄 Thanks for volunteering!
