### ISSUE TITLE
Provide a way to change the state of a CircuitBreaker

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4010]
So that users can dynamically close/open the circuit breaker to initiate particular downstream behavior as @batmanIsIronMan suggested.
Also, it's useful when we are testing.
Reference: https://github.com/Netflix/Hystrix/wiki/Configuration#circuitBreaker.forceOpen

**Comment by batmanIsIronMan** [comment]
thanks.
other great Reference: https://javadoc.io/static/io.github.resilience4j/resilience4j-circuitbreaker/1.7.1/io/github/resilience4j/circuitbreaker/CircuitBreaker.html#transitionToOpenState()

transitionToOpenState
transitionToClosedState
transitionToHalfOpenState
