### ISSUE TITLE
Send 400 Bad Request when HTTP2 cleartext ugprade contains an invalid `HTTP2-Settings`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4016]
As a follow-up issue mentioned in https://github.com/line/armeria/pull/3913#discussion_r781810461
We should send 400 Bad Request if an upgrade request contains duplicate `HTTP2-Settings`s.
https://github.com/line/armeria/blob/98e7450ce83f7094fb32dc42de7d3251ca1ab962/core/src/main/java/com/linecorp/armeria/server/Http2ServerUpgradeCodec.java#L91-L95

**Comment by ahnyujin** [comment]
Hi @ikhoon, May I try to fix this one?
I think I can solve this issue using `ServerErrorHandler.onServiceException` to send a 400 Bad Request response.

**Comment by ikhoon** [comment]
If we use `ServerErrorHandler`, `ServerErrorHandler.onProtocolViolation()` would be a good choice.
However, I don't see you can use `ServerErrorHandler` here. Since the connection is not established, we can't get an instance of the configured `ServerErrorHandler`.
How about directly using Netty's `FullHttpResponse` to send 400 Bad Request?
https://github.com/line/armeria/blob/e7be74e738a49448afe98773e1bbf7ab09080c2f/core/src/main/java/com/linecorp/armeria/server/HttpServerUpgradeHandler.java#L290

**Comment by ahnyujin** [comment]
Thanks for your kind reply @ikhoon.
You helped me understand the issue better. I'll try it!
