### ISSUE TITLE
get `ClassCastException` error when call `HttpResponse.toDuplicator()`

### ISSUE THREAD

**Issue by LiYing2010** [line/armeria#4030]
I created a service using armeria (latest version `1.13.4`)
and added a Decorating Service to dump HTTP Request/Response Log.

in this Decorating Service, I want to duplicate request/response so I can dump the request/response content to our log.

my code like this:

```
public class HttpLogDecoratingService extends SimpleDecoratingHttpService {
    @Override
    public HttpResponse serve(final ServiceRequestContext ctx, final HttpRequest originalReq) throws Exception {
        // duplicates a request stream to read repeatedly
        final HttpRequestDuplicator reqDuplicator = originalReq.toDuplicator();
        final HttpRequest req = reqDuplicator.duplicate(requestHeaders);
        ......

        final HttpResponse originalRes = unwrap().serve(ctx, req);

        // duplicates a response stream to read repeatedly
        final HttpResponseDuplicator resDuplicator = originalRes.toDuplicator();
        ......
        ......
    }
}
```

the `originalReq.toDuplicator()` part works just fine, but `originalRes.toDuplicator()` throws the following exception:
```
java.lang.ClassCastException: class com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator cannot be cast to class com.linecorp.armeria.common.HttpResponseDuplicator (com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator and com.linecorp.armeria.common.HttpResponseDuplicator are in unnamed module of loader 'app')
at com.linecorp.armeria.common.StreamMessageBasedHttpResponse.toDuplicator(StreamMessageBasedHttpResponse.java:22)
......
......
```

looks like the `originalRes` instance is something like:
```
StreamMessageBasedHttpResponse{
  delegate=com.linecorp.armeria.common.stream.FuseableStreamMessage@1a90bf0f
}
```

and it calls
(1) `NonOverridableStreamMessageWrapper.toDuplicator()` :
https://github.com/line/armeria/blob/81dcaa664ddf79d416873d9be881f51e385fb997/core/src/main/java/com/linecorp/armeria/internal/common/stream/NonOverridableStreamMessageWrapper.java#L78-L82

which in turn calls:
(2) `StreamMessageWrapper.toDuplicator()` 
https://github.com/line/armeria/blob/3588a5167689a4419d6018326db2d8e10f7b98c2/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java#L102-L106

which calls it's delegate:

(3) `StreamMessage.toDuplicator()`
https://github.com/line/armeria/blob/3588a5167689a4419d6018326db2d8e10f7b98c2/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java#L409-L418

which calls

(4) `StreamMessage.toDuplicator(EventExecutor)`
https://github.com/line/armeria/blob/3588a5167689a4419d6018326db2d8e10f7b98c2/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java#L420-L432
which return an instance of `DefaultStreamMessageDuplicator`

but at (1), it try to cast this instance to `D`
(which is `HttpResponseDuplicator` in `StreamMessageBasedHttpResponse`):
https://github.com/line/armeria/blob/81dcaa664ddf79d416873d9be881f51e385fb997/core/src/main/java/com/linecorp/armeria/common/StreamMessageBasedHttpResponse.java#L22-L23

that's why I get this error:
```
java.lang.ClassCastException: class com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator cannot be cast to class com.linecorp.armeria.common.HttpResponseDuplicator 
```

for now, I have to change my code, to make a work around like :
```
......
// duplicates a response stream to read repeatedly
final EventExecutor eventExecutor = originalRes.defaultSubscriberExecutor();
final long maxResponseLength = Flags.defaultMaxResponseLength();
final HttpResponseDuplicator resDuplicator = originalRes.toDuplicator(eventExecutor, maxResponseLength);
......
```

it will call `HttpResponse.toDuplicator(EventExecutor, long)`:
https://github.com/line/armeria/blob/3588a5167689a4419d6018326db2d8e10f7b98c2/core/src/main/java/com/linecorp/armeria/common/HttpResponse.java#L532-L536

and return an instance of `DefaultHttpResponseDuplicator`, then my code can work normally

**Comment by ikhoon** [comment]
Thanks for the thorough analysis. Are you sending a PR? If you are busy, I can deal with it.

**Comment by ikhoon** [comment]
Send #4032 to fix this.
