### ISSUE TITLE
`RoutingTrie` fails to navigate an `HttpService` mapped by a parameterized rest paths(`{*foo}`) pattern

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4034]
If a service is bound with a parameterized rest paths(`/foo/{*bar}`) pattern, 
`RoutingTrie` fails to find the target service when traversing the tree.
```java
@RegisterExtension
static ServerExtension server = new ServerExtension() {
    @Override
    protected void configure(ServerBuilder sb) {
        sb.decorator(LoggingService.newDecorator());
        sb.service("/foo/{*qux}", (ctx, req) -> {
            return HttpResponse.of(ctx.pathParam("qux"));
        });
    }
};

@Test
void test() {
    final WebClient client = server.webClient();
    final AggregatedHttpResponse response = client.get("/foo/bar/qux").aggregate().join();
    // 404 not found is returned.
    assertThat(response.status()).isEqualTo(HttpStatus.OK);
}
```
I think the first path of `Route.paths()` has to return 1) `/foo/*` so that `RoutingTrie` correctly builds 2) the trie tree.

1) https://github.com/line/armeria/blob/510a57b213de5590649fe1634f8ee3274f545a38/core/src/main/java/com/linecorp/armeria/server/Route.java#L148
2) https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/server/RoutingTrieBuilder.java#L211-L215

Note: As #3997 is not released yet, we don't need to mention this on the release note.

**Comment by ikhoon** [comment]
@policeman-kh Are you interested in looking at this issue?

**Comment by policeman-kh** [comment]
@ikhoon san

> Are you interested in looking at this issue?

Off course. Let me check this issue. 🙇

**Comment by ikhoon** [comment]
Thanks, @policeman-kh. ❤️
