### ISSUE TITLE
Add metric for expired TLS certificates

### ISSUE THREAD

**Issue by trustin** [line/armeria#4046]
We could add a Micrometer gauge that becomes non-zero when the server's TLS certificates are expired, so that our users can monitor and fix it as soon as possible.

We could also add a gauge for 'time to expire' which becomes negative when the certificates are expired.

**Comment by klurpicolo** [comment]
Hi @trustin, I'd like to try this one👋. 

Could you help guide me on how to get TLS certificates' expiration information? Thank you.

**Comment by trustin** [comment]
Hey, thanks a lot for your interest in this issue. I actually didn't look into the details on how this should be implemented, but I see a few options:

1. Create a new server-side `SSLEngine` from the `SslContext` and perform some test SSL handshake like we do in `VirtualHostBuilder.validateSslContext()`. On successful handshake, we retrieve the `SSLSession` object of the server-side `SSLEngine`.  `SSLSession.getLocalCertificates()` gives us the complete list of the server certificate chain. We down-cast it into `X509Certificate` and then we have accession to `getNotBefore` and `getNotAfter`, which are what we're looking for.
2. Given this all `ServerBuilder.tls()` methods require the reference to the key materials required for the construction of `SslContext`, we basically have the access to the certificates we're gonna use in the server. Therefore, we extract the information of the certificate before constructing `SslContext`.

I guess the first option is better because we can start from modifying `VirtualHostBuilder.validateSslContext()` because all the heavy lifting is done already there.

**Comment by trustin** [comment]
Maybe useful for extracting CN from the certificates: https://stackoverflow.com/questions/2914521/how-to-extract-cn-from-x509certificate-in-java

**Comment by klurpicolo** [comment]
@trustin Many thanks for useful information! Currently I'm working on it. By the way, I have questions that would like you to help.

- Is metric name "armeria.server.tls.expiration" good?
- Should I make it one value that be -1 if any certificate in chain is expired 
```
# HELP armeria_server_tls_expiration 0 if certificate is not expired, -1 if certificate is expired
# TYPE armeria_server_tls_expiration gauge
armeria_server_tls_expiration 0.0
```
  or separate for each certificate 
```
# HELP armeria_server_tls_expiration 0 if certificate is not expired, -1 if certificate is expired
# TYPE armeria_server_tls_expiration gauge
armeria_server_tls_expiration{CN="localhost",} 0.0
armeria_server_tls_expiration{CN="armeria.root.ca",} 0.0
```

**Comment by ikhoon** [comment]
> or separate for each certificate

Sounds good to me.

> Is metric name "armeria.server.tls.expiration" good?

I prefer `certificate`, e.g., `armeria.server.certificate.expiration`

> Should I make it one value that be -1 if any certificate in chain is expired

We can assume 1 is true and 0 is false. Therefore, `armeria.server.certificate.expiration 1.0` could mean a certificate is expired.

**Comment by klurpicolo** [comment]
@ikhoon Noted with thanks
