### ISSUE TITLE
HttpResponse.mapHeaders doesn't work with FileService redirect

### ISSUE THREAD

**Issue by tobias-** [line/armeria#4056]
The problem is that when using FileService and using `.mapHeaders` on the resulting `HttpResponse`, the headers will NOT be mapped if the response is a directory redirect. `.mapHeaders` works as intended if a normal `HttpResponse.ofRedirect()` is returned.

I've added a small test to try to show the problem: https://github.com/tobias-/armeria/pull/4

My example adds the header "foo: bar" to the example. For "200 OK" request, the header is added. For 307 temporary redirect, it is not.

**Comment by ikhoon** [comment]
You can use a failed `HttpResponse` with `mapHeaders`.
I recommend you use `.recover` to mutate headers in an `HttpResponseException`.
For example:
```java
var sb = Server.builder();

sb.decorator((delegate, ctx, req) -> {
    final HttpResponse response = delegate.serve(ctx, req);
    return response.recover(ex -> {
        if (ex instanceof HttpResponseException) {
            final HttpResponse httpResponse = ((HttpResponseException) ex).httpResponse();
            return httpResponse.mapHeaders(
                    headers -> headers.withMutations(builder -> builder.add("foo", "bar")));
        }
        return HttpResponse.ofFailure(ex);
    });
});
```
