### ISSUE TITLE
Is there any reason why armeria-thrift0.12 is not published?

### ISSUE THREAD

**Issue by luqasn** [line/armeria#4065]
We are using Thrift 0.12, and the repo contains a module for that, but it's not being published. Is this intentional?

https://github.com/line/armeria/blob/master/settings.gradle#L99

Thanks a lot for this great project!

**Comment by trustin** [comment]
It's because `amreria-thrift0.13` is compatible with Thrift 0.12, 0.11 and 0.10. You can just pull `armeria-thrift0.13` into your dependencies and override the transitive dependency. Please feel free to let us know if it doesn't work as expected.

**Comment by anuraaga** [comment]
Perhaps 0.12 tests could be migrated to a test suite to avoid confusion around its publishing

https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html

**Comment by trustin** [comment]
@anuraaga That's good to know. How did you come to know this stuff? :+1:
