### ISSUE TITLE
Programmatically configure `Flags` via SPI 

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4093]
The default value of some `Flags` could be changed by only JVM `-Dcom.linecorp.armeria.XXX` option such as `-Dcom.linecorp.armeria.verboseSocketExceptions=true`.
New options are constantly added to `Flags` according to various requirements and environments. Consequently, users find it difficult to override many options only via JVM options.
They may not want to frequently fix the options in their CI/CD tools.

If we provide an SPI interface and let users programmatically override the default value by implementing a configuration interface.
Users can take advantage of the benefits of reviewing the properties in the PR and managing it in the source set.

The following priority could be applied to the new configuration mechanism. 
1. Give JVM options the highest priority.
2. If a JVM option is not specified, checks the value in the configuration provided via SPI
3. Neither is set, the sensible default defined in `Flags` will be used.

**Comment by klurpicolo** [comment]
Hi, I'm interesting in this issue, Can I work on this?

Currently, I have 2 options in my mind. I'd like to get opinion from you.

First approach
- Make `FlagsProvider(1)` interface that return all of value that current `Flags` class provides.
- Extract all default values from `Flags` and put them in new class `DefaultFlagsValue` and encorage users to extend `DefaultFlagsValue` when they want to provide custom value.
- Update value priority as you describe in `Flags` class

Pros: Values corresponding to each flag is type safed.
Cons: `FlagsProvider(1)` Interface is really big. For trypical usecases that user might just want to override some values, they have to extends `DefaultFlagsValue`.

```java

//SPI interface
public interface FlagsProvider {

    int numCommonBlockingTaskThreads();

    long defaultMaxRequestLength();

    long defaultMaxResponseLength();

    boolean defaultUseHttp1Pipelining();

    //... and so on
}

class DefaultFlagsValue implements FlagsProvider {

    @Override
    public int numCommonBlockingTaskThreads() {
        return 0; //return default value
    }

    @Override
    public long defaultMaxRequestLength() {
        return 2; //return default value
    }

    @Override
    public long defaultMaxResponseLength() {
        return 3; //return default value
    }

    @Override
    public boolean defaultUseHttp1Pipelining() {
        return true; //return default value
    }
     //... and so on
}

//Users implementation
class CustomFlagsValue extends DefaultFlagsValue {

    @Override
    public int numCommonBlockingTaskThreads() {
        return 2; //custom value
    }

}

```

Second approach
- Create enum `FlagsCustomOption` to describe all values that can be customized
- Make `FlagsProvider(2)` interface that return Map<FlagsCustomOption,Object>

Pros: `FlagsProvider(2)` interface is small comparing to first approach. Moreover, user can just implement `FlagsProvider(2)` to provides custom values.
Cons: `Map<FlagsCustomOption,Object>` isn't type safe, users might provide wrong type that doesn't corresponding to `FlagsCustomOption` and result will be fallen back to default.

```java
//SPI interface
interface FlagsProvider2 {

    Map<FlagsCustomOption,Object> customFlagsMap();

}

enum FlagsCustomOption {

    numCommonBlockingTaskThreads,
    defaultMaxRequestLength,
    defaultMaxResponseLength,
    defaultUseHttp1Pipelining;
    //... and so on
}

//Users implementation
class FlagsProvider2Impl implements FlagsProvider2 {

    @Override
    public Map<FlagsCustomOption, Object> customFlagsMap() {
        Map<FlagsCustomOption, Object> map = new HashMap<>();
        map.put(FlagsCustomOption.numCommonBlockingTaskThreads, 10);
        map.put(FlagsCustomOption.defaultMaxRequestLength, 20L);
        map.put(FlagsCustomOption.defaultMaxResponseLength, 15L);
        map.put(FlagsCustomOption.defaultUseHttp1Pipelining, false);
        return map;
    }

}
```

If you have any suggestion, please let me know. Thanks!

**Comment by ikhoon** [comment]
I was thinking of the first approach in order to easily override the default options.
For example:
```java
public interface ArmeriaOptions {
    default int numCommonBlockingTaskThreads() {
        return 0; //return default value
    }

    default long defaultMaxRequestLength() {
        return 2; //return default value
    }
    ...
}

//Users implementation
class CustomArmeriaOptions extends ArmeriaOptions {
    @Override
    public long defaultMaxRequestLength() {
        return 3;
    }
}

class Flag {
    // Dynamically load AmeriaOptions
    static final ArmeriaOptions ARMERIA_OPTIONS = ServiceLoader.load(...);
   
    private static final long DEFAULT_MAX_REQUEST_LENGTH =
            getLong("defaultMaxRequestLength",
                    armeriaOptions.defaultMaxRequestLength(),
                    value -> value >= 0);

    public static long defaultMaxRequestLength() {
        return DEFAULT_MAX_REQUEST_LENGTH;
    }
}
```

The API consistency between `Flag` and `ArmeriaOptions` can be ensured with a test using reflection.

**Comment by klurpicolo** [comment]
Hi 👋 @ikhoon,

Thanks for the idea 🙏. Currently, I'm working on this, and I have questions.

- I want to add [junit-pioneer](https://github.com/junit-pioneer/junit-pioneer) library to project for setting JVM options(I want to use @ClearSystemProperty and @SetSystemProperty to set and clear system properties). I'll add its license and update gradle.build/dependencies.yml, is that Okay?
- There are 2 options in `Flags` that marked as deprecated( `annotatedServiceExceptionVerbosity() and useEpoll()` ). Should I still add them as part of the `ArmeriaOptions` SPI interface, or ignore them?

**Comment by ikhoon** [comment]
> I want to use @ClearSystemProperty and @SetSystemProperty to set and clear system properties

As a system properties are loaded once when `Flags` is initialized. So `@ClearSystemProperty` and `@SetSystemProperty` do not effectively change the default values of `Flags`.
We can use a custom class loader to re-evaluate the system properties. https://github.com/line/armeria/blob/4edffc8c11bd74665d652a1fd108d6a0307b6733/core/src/test/java/com/linecorp/armeria/common/FlagsTest.java#L92

> There are 2 options in Flags that marked as deprecated( annotatedServiceExceptionVerbosity() and useEpoll() ). Should I still add them as part of the ArmeriaOptions SPI interface, or ignore them?

It is OK to exclude the deprecated flags from `ArmeriaOptions`.

**Comment by klurpicolo** [comment]
I'm designing on how validation fallback logic should be but I can't decide 😅.

- if JVM option is invalid, Should it fallback to SPI interface (if user provides) or sensible default?
- Should value provided by SPI interface needed to be validated and if it fails then fallback sensible default too?

**Comment by ikhoon** [comment]
Your idea makes sense.
If an option is not valid, we should be able to leave the wrong option with the fallback value of SPI or the sensible default.
https://github.com/line/armeria/blob/55504bdf4f09b05adf07a16a076ec28e3fbfccf4/core/src/main/java/com/linecorp/armeria/common/Flags.java#L1460-L1475
