### ISSUE TITLE
Provide a way to run service code out of I/O event loops

### ISSUE THREAD

**Issue by trustin** [line/armeria#4099]
When service devs are not very familiar with asynchronous programming, it is very easy to drive Armeria's core event loops into havoc by blocking them.

Framework devs may want to make sure Armeria at least handle I/O and function normally for a certain set of core services, such as `PrometheusExpositionService` or `HealthCheckService`, by isolating other non-core services from the I/O event loops.

To achieve this, I'd like to propose adding the per-service/virtual host/server `serviceWorkerGroup` property that makes a service use a different `EventLoopGroup` than `ServerBuilder.workerGroup`, e.g.

```java
Server
  .builder()
  .workerGroup(ioEventLoopGroup, /* shutdownOnStop */ true)
  .serviceWorkerGroup(isolatedEventLoopGroup, /* shutdownOnStop */ true)
  .route()
    .path("/core-services/metrics")
    .serviceWorkerGroup(ioEventLoopGroup, /* shutdownOnStop */ true) // Use the core event loops.
    .build(new PrometheusExpositionService())
  .route()
    .path("/non-core-services/foo")
    .build(new FooService()) // Will use `isolatedEventLoopGroup`
  .build()
```

Action items:
- Add the `serviceWorkerGroup()` builder methods to `ServerBuilder` and `AbstractServiceBindingBuilder` so a user can specify the service worker groups as shown in the above example.
  - Check [this commit](https://github.com/line/armeria/commit/aa647fae9278fa54c4f303c29e1db8f058fbaf78) to get an idea on what this change will look like.
- Change how Armeria assigns an event loop to a `ServiceRequestContext`.
  - Currently, it always uses [the same event loop with the current connection](https://github.com/line/armeria/blob/armeria-1.14.0/core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java#L272-L278).
  - Modify the constructor of `DefaultServiceRequestContext` so it accepts an `EventLoop`.
  - Modify `HttpServerHandler.handleRequest()`, so it specifies an event loop from the `serviceWorkerGroup`:
    ```java
    ServiceConfig serviceCfg = ...;
    EventLoop eventLoop = serviceCfg.serviceWorkerGroup().next()
    reqCtx = new DefaultServiceRequestContext(..., eventLoop, ...);
    ```

**Comment by kezhenxu94** [comment]
Let me try this 😉

**Comment by trustin** [comment]
We had some discussion about this issue and decided the following:

- We allow specifying a `ScheduledExecutorService` and/or some type we'll define in the future (which can wrap an existing `ScheduledExecutorService` for sure), instead of letting a user specify an event loop group for a service.
- We deprecate `RequestContext.eventLoop()` in favor of a new method `RequestContext.executor()`.
- We may want to deprecate `BlockingTaskExecutor` in favor of the service-level executor, but we'll still looking for ways to streamline this.
