### ISSUE TITLE
Graphql: Return 400 instead of 500 when client sends incorrect request in json

### ISSUE THREAD

**Issue by tobias-** [line/armeria#4104]
Currently Armeria returns a 500 error when a client sends in either invalid json or invalid graphql request.

I agree with what @jrhee17 wrote in https://github.com/line/armeria/pull/4069#discussion_r801222068 , the server should return 400.

**Comment by ikhoon** [comment]
Thanks for reporting the bug. As a workaround, we can customize the response status using `ServerErrorHandler`.
