### ISSUE TITLE
Provide a way to inject an object to `Decorator`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4129]
Users can specify `@Decorator` to add a decorator to a method in an annotated service.
```java
@Get("/foo")
@Decorator(MyAuthDecorator.class)
public HttpResponse needToCheckAuthBeforeCallingThisMethod(...) {
    ...
}

static class MyAuthDecorator implements DecoratingHttpServiceFunction {
    @Override
    public HttpResponse serve(...) throws Exception {
        ...
    }
}
```
If so, Armeria server automatically creates the instance of `MyAuthDecorator` and the request is handled by the decorator before it's getting to the method.

To create the class that is specified in the `@Decorator` (i.e `MyAuthDecorator` in the example), the class should not have constructor parameters because there's no way to inject them.
We can add a dependency injector to `ServerBuilder` in order to support that:
```java
Server.builder()
      .dependencyInjector(...)
```

**Comment by heowc** [comment]
Doesn't duplicate with this issue?

- https://github.com/line/armeria/issues/4006

**Comment by ikhoon** [comment]
I think so. Let me close this.

**Comment by minwoox** [comment]
Oops, thanks for catching this. 😅
