### ISSUE TITLE
Support  for `response_body` option of gRPC-JSON transcoding

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4132]
A JSON body of a gRPC response should be extracted if `response_body` option is specified.
https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L354-L360
We can extract the content of the field specified in `response_body` before sending a response.
https://github.com/line/armeria/blob/daae15d426ffb2581fdff9f10f16ec69f90b7a36/grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java#L200-L202

**Comment by natsumehu** [comment]
@ikhoon  You can assign this to me

**Comment by ikhoon** [comment]
Thanks for volunteering for this issue!

**Comment by natsumehu** [comment]
https://github.com/line/armeria/blob/daae15d426ffb2581fdff9f10f16ec69f90b7a36/grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java#L200-L202
In the Subscriber code, the spec is not in the context. Can I change the 
https://github.com/line/armeria/blob/73cc4ae1da00f5441be94f8ad8b5f989bba0acd8/grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java#L522
convertToJson method to change the response?

**Comment by ikhoon** [comment]
>  convertToJson method to change the response?

`convertToJson` is used to create a JSON request. We can't extract a `response_body` from it.

> In the Subscriber code, the spec is not in the context

Good point. Actually, I thought we can pass a function to `frameAndServe`
such as `Function<HttpData, HttpData> responseBodyConverter`.
It is possible to implement but may hurt SRP. How about using `HttpResponse.mapData()` to convert the response body?
For example:
```java
private HttpResponse serve0(ServiceRequestContext ctx, HttpRequest req, ...) {
    ...

    final HttpResponse response = HttpResponse.from(responseFuture);
    if (responseBodyField == null) {
        return response;
    }

    response.mapData(data -> {
        // Note that the data is a reference counted object that 
        // should be released/closed after using it.  
        try (HttpData body = data) {
            byte[] array = body.array();
            // 1. Parse the array to JsonNode using Jackson
            // 2. Read the field value of `response_body`
            // 3. Serialize and convert it into `HttpData`
        }
    });
}
```

**Comment by natsumehu** [comment]
Hi, I have tried using using HttpResponse.mapData() to convert the response body. But it seems like the problem happened at 
https://github.com/netty/netty/blob/30855c71c843db6d3d0c769d2547b948f61500a2/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L165-L167

Received amount of data 23 does not match content-length header 19

I found that the netty decode the response before executing the lambda functions so I think maybe any change that will change the length of the response would not work.

https://github.com/netty/netty/blob/30855c71c843db6d3d0c769d2547b948f61500a2/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L395-L397

Thanks.

**Comment by ikhoon** [comment]
We can remove the content-length header from response headers but it does not look good.
How about passing a `Function<HttpData, HttpData> responseBodyConverter` to `frameAndServe` 
and using it in `singleSubscriber`?
