### ISSUE TITLE
gRPC server streaming, client cannot receive any response

### ISSUE THREAD

**Issue by fageiguanbing** [line/armeria#4134]
It now looks like the server will return to the client after processing all the logic. And if a server streaming request is being executed, the server does not accept any other requests.

Has anyone had a similar problem?

**Comment by ikhoon** [comment]
Could you provide more information about that?
- What Armeria version are you using?
- Which gRPC stub is used such as gRPC-Java, gRPC-Kotlin, and so on.
- Is it possible to create a reproducible example? It is super helpful to find out the cause of the issue.

**Comment by ikhoon** [comment]
Related issue: #3099

**Comment by fageiguanbing** [comment]
> Could you provide more information about that?
> 
> * What Armeria version are you using?
> * Which gRPC stub is used such as gRPC-Java, gRPC-Kotlin, and so on.
> * Is it possible to create a reproducible example? It is super helpful to find out the cause of the issue.

Armeria version: 1.14.1
gRPC stub: gRPC-Java
proto
```proto
service StreamingGreeter {
  rpc ServerStreaming (HelloRequest) returns (stream HelloReply) {}
}
message HelloRequest {
  string name = 1;
  bytes fileBody = 2;
}
message HelloReply {
  string message = 1;
  bytes fileBody = 2;
}
```
client
```java
public class MyClient {
    public static void main(String[] args) {
        Channel channel = GrpcFactory.newChannel("localhost", 8888, Integer.MAX_VALUE);
        StreamingGreeterGrpc.StreamingGreeterBlockingStub blockingStub = StreamingGreeterGrpc.newBlockingStub(channel);
        Iterator<HelloReply> helloReplyIterator = blockingStub.serverStreaming(HelloRequest.newBuilder().build());
        while (helloReplyIterator.hasNext()) {
            System.out.println(helloReplyIterator.next().getMessage());
        }
    }
}
```
server
```java
public class MyServer {
    public static void main(String[] args) {
        ThreadPoolExecutor EXECUTOR = new ThreadPoolExecutor(
                1, 1, 0, TimeUnit.SECONDS, new LinkedBlockingDeque<>(),
                new ThreadFactoryBuilder().setNameFormat("grpc-server-start-stop-%d").build());
        GrpcService grpcService = GrpcService.builder().addService(new MyServiceImpl()).build();
        Server.builder()
                .startStopExecutor(EXECUTOR)
                .http(8888)
                .service(grpcService)
                .build()
                .start();
    }
}
```

**Comment by ikhoon** [comment]
> Thread.sleep(1000L);

Armeria server executes a gRPC service on an event loop by default. Your service code blocks the event loop with `Thread.sleep()`
If you want to perform a blocking task, please turn on [`GrpcServiceBuilder.useBlockingTaskExecutor(boolean)`](
https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.14.1/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.html#useBlockingTaskExecutor(boolean)).

**Comment by fageiguanbing** [comment]
> > Thread.sleep(1000L);
> 
> Armeria server executes a gRPC service on an event loop by default. Your service code blocks the event loop with `Thread.sleep()` If you want to perform a blocking task, please turn on [`GrpcServiceBuilder.useBlockingTaskExecutor(boolean)`](https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.14.1/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.html#useBlockingTaskExecutor(boolean)).

It works! Thanks! I have a question: Whether the blocking tasks and async tasks use the same thread pool?

**Comment by ikhoon** [comment]
They use different thread pools. 
You can set a custom blocking task executor using https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.14.1/com/linecorp/armeria/server/ServerBuilder.html#blockingTaskExecutor(java.util.concurrent.ScheduledExecutorService,boolean)

**Comment by fageiguanbing** [comment]
> They use different thread pools. You can set a custom blocking task executor using https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.14.1/com/linecorp/armeria/server/ServerBuilder.html#blockingTaskExecutor(java.util.concurrent.ScheduledExecutorService,boolean)

I took a test: no streaming RPC, non-blockingTaskExecutor, 10 requests, server sleep 1s, client receive the response almost the same time.
What scenario would use `blockingExecutor`?

**Comment by jrhee17** [comment]
> I took a test: no streaming RPC, non-blockingTaskExecutor, 10 requests, server sleep 1s, client receive the response almost the same time.
What scenario would use blockingExecutor?

I think it doesn't matter whether streaming or non-streaming is used.
Rather, I think you want to use `blockingExecutor` if your API is performing any [blocking operations](https://en.wikipedia.org/wiki/Blocking_(computing)) on **armeria** threads. (So this would be `Thread.sleep()`, `CompletableFuture.join()`, etc on **armeria** threads).

So if you need to perform blocking operations, you can do it on your own threads like the following:

```
public class MyServiceImpl extends StreamingGreeterGrpc.StreamingGreeterImplBase {
    ThreadExecutor executor;
    @Override
    public void serverStreaming(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
        // in armeria thread at this point
        System.out.println(Thread.currentThread());
        executorService.submit(() -> {
            // in user defined thread at this point
            for (int i = 0; i < 1000; i++) {
                System.out.println("==================" + i);
                responseObserver.onNext(HelloReply.newBuilder().setMessage(i + "").build());
                try {
                    Thread.sleep(1000L);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
            responseObserver.onCompleted();
        });
    }
}
```

> What scenario would use blockingExecutor?

Specifying `blockingExecutor` basically lets `armeria` do the above for you (in addition to other stuff like context propagation).

**Comment by fageiguanbing** [comment]
got it. Thanks all!
