### ISSUE TITLE
Add a documentation for gPRC metrics with armeria-spring-boot

### ISSUE THREAD

**Issue by ta7uw** [line/armeria#4197]
As described in the following document, users set `MetricCollectingService` with `GrpcMeterIdPrefixFunction` as a Decorator to a server builder to collect metrics for gRPC.

https://armeria.dev/docs/advanced-metrics/#collecting-server-side-metrics

```java
import com.linecorp.armeria.common.grpc.GrpcMeterIdPrefixFunction;
import com.linecorp.armeria.server.grpc.GrpcService;

Server.builder()
      .http(new InetSocketAddress(address, port))
      .service(GrpcService.builder()
                          .addService(new MyHelloService())
                          .build())
      .decorator(MetricCollectingService.newDecorator(
              GrpcMeterIdPrefixFunction.of("grpc.service")))
      .build();
```

However, when using gRPC with armeria-spring-boot, this decorator which is set by users is ignored because Armeria Spring integrations always uses `MeterIdPrefixFunction.ofDefault`.

Users can work around this by defining a bean. (https://github.com/line/armeria/pull/3034)

```java
        @Bean
        public MeterIdPrefixFunction myMeterIdPrefixFunction() {
            return GrpcMeterIdPrefixFunction.of("custom.armeria.server");
        }
```

I think it is difficult for users to notice this and users may consider it as a bug.
Should we add a document about this?

**Comment by ikhoon** [comment]
>  Should we add a document about this?

Agreed. It would be useful for Spring users.
