### ISSUE TITLE
Support for request scoped DataLoader for GraphQL-Java

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4237]
Users can not manage the scope of `DataLoaderRegistry` because it is instantiated only when a `GraphqlService` is built.
Slack thread: https://line-armeria.slack.com/archives/C1NGPBUH2/p1651542368887699

It would be nice to give users more freedom to control the lifecycle of `DataLoaderRegistry`.
I think we can provide an API that takes `Function<ServiceRequestContext, DataLoaderRegistry>` so that users choose to return a singleton `DataLoaderRegistry`, a newly created `DataLoaderRegistry`, or whatever.
```java
class GraphqlServiceBuilder {
    public GraphqlServiceBuilder dataLoaderRegistry(Function<ServiceRequestContext, DataLoaderRegistry> dataLoaderRegistrySupplier) {
         // This method will be mutually exclusive with configureDataLoaderRegistry(...)
    }
}
```

**Comment by TheNatkat** [comment]
hey! can I work on this issue I like to contribute

**Comment by heowc** [comment]
I'm really really sorry for being late. I'm going to start slowly from today 😅
