### ISSUE TITLE
Add `StreamMessageWriter`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4253]
`StreamMessageAndWriter` is an internal API to write arbitrary objects with backpressure.
https://github.com/line/armeria/blob/0016f868b15cae6d8568004f3288ed86621a7b93/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageAndWriter.java#L23
As there is no public API for a streaming writer, we directly instantiate `DefaultStreamMessage`.
```java
StreamWriter writer = new DefaultStreamMessage();
writer.write(...);
writer.close();
```
#4186 will provide a way to write a `StreamMessage` using `OutputStream`.
To convert a `StreamMessage` to `OutputStream`, users should use directly `DefaultStreamMessage` as well.
That might be not what we want. `DefaultStreamMessage` is `@UnstableApi` and a part of implementations, so we have to hide the implementation detail.

Proposal: 
- Rename `StreamMessageAndWriter` to `StreamMessageWriter` and make it public API.
- Add `StreamMessage.streaming()` in order to create a `StreamMessageWriter` instance
```java
StreamMessageWriter writer = StreamMessage.streaming();
writer.write(...);
writer.close();
```

**Comment by tomatophobia** [comment]
```Java
StreamMessageWriter<String> writer = StreamMessage.streaming();
OutputStream os = writer.toOutputStream(...);
os.write(...);
os.close();
```
Hi 😄 @ikhoon, I have a question of above code blocks. I think `StreamMessage#fromOutputStream` or `StreamMessage#toInputStream` make sense but I am confusing about `StreamMessage#toOutputStream`. 

How can `StreamMessage` or `Publisher` be converted into `OutputStream`?

**Comment by ikhoon** [comment]
`toOutputStream` is a draft design that had been changed while developing #4186.
For what it's worth, https://github.com/line/armeria/pull/4186#issuecomment-1211699740 is the proposal for `fromOutputStream()`.

**Comment by injae-kim** [comment]
May I handle this issue? 🙇
