### ISSUE TITLE
Automatically compress gRPC response message

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4258]
A gRPC service compresses response messages if a client 1) sends `grpc-accept-encoding=XXX` and 2) a corresponding `Compressor` is set via `ServerInterceptor`.
For example:
```java
GrpcService.builder()
           .addService(new MyGrpcService())
           .intercept(new ServerInterceptor() {
               @Override
               public <ReqT, RespT> Listener<ReqT> interceptCall(
                       ServerCall<ReqT, RespT> call, Metadata headers,
                       ServerCallHandler<ReqT, RespT> next) {
                   call.setCompression("gzip"); // Enable gzip compression
                   return next.startCall(call, headers);
               }
           })
           .build();
```
It is inconvenient to add an interceptor only for compression.

For simplicity, we can provide an option that finds a suitable `Compressor` from `CompressorRegistry` using `grpc-accept-encoding` header.
```java
GrpcService.builder()
           .addService(new MyGrpcService())
           .autoCompression(true)
           .build();
```

Slack thread: https://line-armeria.slack.com/archives/C1NGPBUH2/p1652387830925109

**Comment by ikhoon** [comment]
@ta7uw(who likes to contribute to gRPC functions) Are you interested in this issue? 😉

**Comment by ta7uw** [comment]
Yes, I'd like to work on this issue!
