### ISSUE TITLE
Failed to convert an `HttpResponse` into an `InputStream`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4268]
@eisig reported a bug in `StreamMessageInputStream` converter.

> Hi,  I want to use   HttpResponse.toInputStream() to convert httpResponse to inputStream. But The following code would not work, It seems that  inputStream eos is not set.
```java
@Test
void testDownload() throws IOException {
    WebClient webClient = WebClient.builder(serverExtension.httpUri()).decorator(LoggingClient.newDecorator())
            .build();
    HttpResponse response = webClient.prepare().get("/download").queryParam("xx", "xx").execute();
    InputStream inputStream = response.toInputStream(httpObject -> {
        if (httpObject instanceof HttpData) {
            return (HttpData) httpObject;
        }
        return HttpData.empty();
    });
    // just for test. 
    // it would keep waiting here.
    byte[] bytes = ByteStreams.toByteArray(inputStream);
}
```
Slack thread: https://line-armeria.slack.com/archives/C1NGPBUH2/p1653303100545389

To fix the bug, If `httpDataConverter` returns `HttpData.empty()`, `StreamMessageInputStreamSubscriber` should request the next element to the upstream to produce bytes.
https://github.com/line/armeria/blob/e08d486816ce9beafd10b5971393667bc288a58b/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageInputStream.java#L133

**Comment by ikhoon** [comment]
Additionally, I found another bug that `StreamMessageInputStream` did not call `subscriber.request()` only if `byteBufsInputStream` is empty or has not enough data?
[https://github.com/line/armeria/blob/e08d486816ce9beafd10b5971393667bc288a58b/core[…]om/linecorp/armeria/common/stream/StreamMessageInputStream.java](https://github.com/line/armeria/blob/e08d486816ce9beafd10b5971393667bc288a58b/core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageInputStream.java#L59-L60)

@injae-kim might be interested in these bugs.

**Comment by injae-kim** [comment]
oh.. I'll fix this bug issue as soon as possible!
Sorry for making bug 🙇 cc. @ikhoon

**Comment by ikhoon** [comment]
No worries. 🙂 We should’ve checked the bug while reviewing the PR.
