### ISSUE TITLE
Find a better way to share common test classes

### ISSUE THREAD

**Issue by trustin** [line/armeria#427]
When importing Armeria into IntelliJ IDEA, it raises the following error:

```
duplicated content url: file:///.../armeria/core/src/test/java-shared
```

Also, a user cannot change the module settings at all because IDEA refuses to apply the changes because of the same issue.

**Comment by anuraaga** [comment]
As far as I know, it's never a good idea to depend on code in the test source set in random places.

I guess we would want an armeria-testing project with the shared code in the main sourceset and testCompile dependency on it. Validation to make sure it is never accidentally added to other dependency configurations is of course a plus :)
