### ISSUE TITLE
Even with useBlockingTaskExecutor enabled, gRPC's ServerInterceptor runs in a non-blocking thread

### ISSUE THREAD

**Issue by be-hase** [line/armeria#4275]
## Issue

First of all, gRPC's [ServerInterceptor](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerInterceptor.html) is a synchronous API.

Therefore, when implementing an authentication process that requires network IO on the ServerInterceptor, blocking the thread is the only way.

In the case of gRPC-java, this is not a major problem since it runs on a thread pool. ([ref](https://github.com/grpc/grpc-java/blob/9cb3c6e688541ed158433d9bf25b6dd2979b6c5a/core/src/main/java/io/grpc/internal/GrpcUtil.java#L540))
However, in Armeria, it is a problem because it runs on the event loop.
Unfortunately, even if I specify `useBlockingTaskExecutor`, the ServerInterceptor is executed on the event loop. ([ref](https://github.com/line/armeria/blob/a5be69d99f03f892abfeca017597340e2b749eea/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java))

## Suggestion

Unfortunately, the ServerInterceptor is synchronous at this time, so it would be better to allow the ServerInterceptor to run on a thread pool, as in gRPC-java.
(At least, if `useBlockingTaskExecutor` is enabled, it would be better to do so.)

For reference, in the case of gRPC-Kotlin, the ServerInterceptor runs in a thread pool and the Service runs in coroutines.

Ideally, of course, the ServerInterceptor should support async.

Or we could consider another method like this.
https://github.com/line/armeria/issues/2607#issuecomment-959966654

**Comment by be-hase** [comment]
Or we may prepare an AsyncServerInterceptor using the technique introduced here.
https://stackoverflow.com/questions/53651024/grpc-java-async-call-in-serverinterceptor

But, it would be nice if it was prepared on the gRPC-Java side...

**Comment by ikhoon** [comment]
> Unfortunately, even if I specify useBlockingTaskExecutor, the ServerInterceptor is executed on the event loop. ([ref](https://github.com/line/armeria/blob/a5be69d99f03f892abfeca017597340e2b749eea/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java))

😱 It should be a bug. Let us fix it soon.

**Comment by ikhoon** [comment]
I was working on refactoring Armeria's `ServerCall` implementations. #4192 
The change won't be difficult but it may heavily conflict with #4192. I am going to fix this problem once the refactoring PR is merged.

**Comment by be-hase** [comment]
Thank you.

In my opinion, `ServerInterceptor` should be runned at BlockingTaskExecutor when the user has specified `useBlockingTaskExecutor=true`.

By the way, I am using gRPC-Kotlin. I wrote the following code using the technique introduced in [this article](https://stackoverflow.com/questions/53651024/grpc-java-async-call-in-serverinterceptor) and it seems to work fine.
(However, it's still a rough code, and the test isn't enough)

It would be very convenient if armeria had a `ServerInterceptor` that could be written asynchronously.

```kotlin
/**
 * ref: https://stackoverflow.com/questions/53651024/grpc-java-async-call-in-serverinterceptor
 */
abstract class SuspendableServerInterceptor(
    private val context: CoroutineContext = EmptyCoroutineContext
) : ServerInterceptor {
    override fun <ReqT : Any, RespT : Any> interceptCall(
        call: ServerCall<ReqT, RespT>,
        headers: Metadata,
        next: ServerCallHandler<ReqT, RespT>
    ): ServerCall.Listener<ReqT> {
        val armeriaCtx = ServiceRequestContext.current()
        val delayedListener = DelayedListener<ReqT>()
        delayedListener.job = CoroutineScope(
            ArmeriaRequestCoroutineContext(armeriaCtx)
                    + GrpcContextElement.current()
                    + COROUTINE_CONTEXT_KEY.get()
                    + context
        ).launch {
            val listener = suspendableInterceptCall(call, headers, next)
            delayedListener.onDelegate(listener)
        }
        return delayedListener
    }

    abstract suspend fun <ReqT : Any, RespT : Any> suspendableInterceptCall(
        call: ServerCall<ReqT, RespT>,
        headers: Metadata,
        next: ServerCallHandler<ReqT, RespT>
    ): ServerCall.Listener<ReqT>

    /**
     * This code has a rough lock. It seems that it can be improved by referring to DelayedStream.
     * https://github.com/grpc/grpc-java/blob/84edc332397ed01fae2400c25196fc90d8c1a6dd/core/src/main/java/io/grpc/internal/DelayedStream.java#L445
     */
    private class DelayedListener<ReqT> : ServerCall.Listener<ReqT>() {
        private var delegate: ServerCall.Listener<ReqT>? = null
        private var pendingCallbacks: MutableList<() -> Unit> = mutableListOf()
        var job: Job? = null

        @Synchronized
        override fun onMessage(message: ReqT) {
            if (delegate == null) {
                pendingCallbacks.add {
                    log.info { "onMessage A" }
                    checkNotNull(delegate).onMessage(message)
                }
            } else {
                log.info { "onMessage B" }
                checkNotNull(delegate).onMessage(message)
            }
        }

        @Synchronized
        override fun onHalfClose() {
            if (delegate == null) {
                pendingCallbacks.add {
                    log.info { "onHalfClose A" }
                    checkNotNull(delegate).onHalfClose()
                }
            } else {
                log.info { "onHalfClose B" }
                checkNotNull(delegate).onHalfClose()
            }
        }

        @Synchronized
        override fun onCancel() {
            if (delegate == null) {
                pendingCallbacks.add {
                    log.info { "onCancel A" }
                    checkNotNull(delegate).onCancel()
                }
            } else {
                log.info { "onCancel B" }
                checkNotNull(delegate).onCancel()
            }
        }

        @Synchronized
        override fun onComplete() {
            job?.cancel()

            if (delegate == null) {
                pendingCallbacks.add {
                    log.info { "onComplete A" }
                    checkNotNull(delegate).onComplete()
                }
            } else {
                log.info { "onComplete B" }
                checkNotNull(delegate).onComplete()
            }
        }

        @Synchronized
        override fun onReady() {
            if (delegate == null) {
                pendingCallbacks.add {
                    log.info { "onReady A" }
                    checkNotNull(delegate).onReady()
                }
            } else {
                log.info { "onReady B" }
                checkNotNull(delegate).onReady()
            }
        }

        @Synchronized
        fun onDelegate(delegate: ServerCall.Listener<ReqT>) {
            log.info { "onDelegate" }
            check(this.delegate == null)
            this.delegate = delegate
            pendingCallbacks.forEach { it() }
            pendingCallbacks = mutableListOf()
        }

        companion object {
            private val log = KotlinLogging.logger {}
        }
    }

    companion object {
        @Suppress("UNCHECKED_CAST")
        
        // Get by using reflection
        internal val COROUTINE_CONTEXT_KEY: Context.Key<CoroutineContext> =
            CoroutineContextServerInterceptor::class.let { kclass ->
                val companionObject = kclass.companionObject!!
                val property = companionObject.memberProperties.single { it.name == "COROUTINE_CONTEXT_KEY" }
                checkNotNull(property.getter.call(kclass.companionObjectInstance!!)) as Context.Key<CoroutineContext>
            }
    }
}
```
