### ISSUE TITLE
Failed to download the whole file served by HttpFile by wget or curl

### ISSUE THREAD

**Issue by ngyukman** [line/armeria#4294]
When I am serving a file with size over 70MB, wget or curl gets connection closed at around 30%

```java
public class Main
{
    public static void main(String[] args)
    {
        Server server = Server.builder()
            .http(8080)
            .service("/test.txt", HttpFile.of(new File("C:\\temp\\20210727.txt")).asService())
            .build();
        CompletableFuture<Void> future = server.start();
        future.join();
    }
}
```

```
wget http://my-machine:8080/test.zip
--2022-06-09 00:01:46--  http://my-machine:8080/test.zip
Resolving ... 10.71.111.209
Connecting to ...|10.71.111.209|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 104857953 (100M) [text/plain]
Saving to: ‘test.zip.1’

test.zip.1                     31%[==============>                                   ]  31.67M  3.04MB/s    in 10s

2022-06-09 00:02:12 (3.07 MB/s) - Connection closed at byte 33210368. Retrying.
```

I have no idea why it fails but other web server (like npm serve) and does not have any issue
note that browser does not suffer from this issue

**Comment by ikhoon** [comment]
The connection seems closed after 10 seconds which is the default request timeout of an Armeria server.
https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.16.0/com/linecorp/armeria/common/Flags.html#defaultRequestTimeoutMillis()
Could you try to increase the request timeout using:
```java
Server.builder()
      .requestTimeout(Duration.ofSeconds(...))
      ...
```

**Comment by ngyukman** [comment]
Dear @ikhoon 

Thanks for your quick reply, indeed you are right
I thought timeout will only apply on response not ready within the RequestTimeout but indeed it is included in it
May I know if there is any settings that avoid timeout when serving a relatively large file for client with slow network other than simply increasing the timeout?

**Comment by ikhoon** [comment]
Armeria does not support a dynamic timeout based on the network bandwidth. 
You can either:
1. Set a specific timeout for your service using https://javadoc.io/doc/com.linecorp.armeria/armeria-javadoc/latest/com/linecorp/armeria/server/ServiceBindingBuilder.html
2. Dynamically increase a request timeout using a decorator. For example:
   ```java
   Server.builder()
         .decoratorUnder("/slow/api", (delegate, ctx, req) -> {
             ctx.setRequestTimeout(Duration.ofSeconds(...);
             return delegate.serve(ctx, req);
         });
   ```

**Comment by ngyukman** [comment]
Thanks a lot for your help

**Comment by trustin** [comment]
Created an issue: https://github.com/line/armeria/issues/4297 Please feel free to subscribe to it or consider sending out a PR. 🙇

**Comment by ikhoon** [comment]
> @ikhoon We may want to introduce a decorator that aborts the stream when there's not enough traffic for a certain period of time, e.g. Abort the connection if less than 64KiB was transferred for the last 10 seconds.

Awesome idea! With the feature, users really don't need to manipulate the timeout depending on the file size.

**Comment by ngyukman** [comment]
Thanks, that would be awesome and helps anyone that would use armeria to serve something big
