### ISSUE TITLE
Add a flag to disable HTTP/2 globally

### ISSUE THREAD

**Issue by mauhiz** [line/armeria#4300]
SessionProtocol.HTTP / HTTPS defaults (without forcing) to HTTP/2, which is usually desirable.

However, we happen to have an issue with a buggy VPN provider, which drops HTTP/2 prefaces.
Having a global (environment) toggle to disable HTTP/2 looks doable and would be very helpful

**Comment by ikhoon** [comment]
Does `globally` mean to disable HTTP/2 protocol from the client-side?
I guess support for HTTP/2 on the server-side would have no harm to it.

**Comment by ikhoon** [comment]
How about adding `-Dcom.linecorp.armeria.defaultUseHttp2UpgradeRequest=<true|false>`?
If both `-Dcom.linecorp.armeria.defaultUseHttp2Preface=false` and `-Dcom.linecorp.armeria.defaultUseHttp2UpgradeRequest=false` are set,
a cilent would not try to upgrade to HTTP/2.

**Comment by mauhiz** [comment]
Thank you, let me attempt it this way.

**Comment by ikhoon** [comment]
Sorry, `-Dcom.linecorp.armeria.defaultUseHttp2UpgradeRequest=false` is not implemented yet. It was a proposal. 
I was wondering if the problem could be fixed by disabling HTTP/2 preface and using HTTP/2 upgrade request with `-Dcom.linecorp.armeria.defaultUseHttp2Preface=false`.

**Comment by mauhiz** [comment]
I'll get confirmation from other affected people but it seems that `-Dcom.linecorp.armeria.defaultUseHttp2Preface=false` is working for me.
