### ISSUE TITLE
Add consumes and produces to HTTP method annotations

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4361]
Currently, we have separate annotations to define consume and produce media types:
```java
public class MyService {

    @Post("/foo")
    @Consumes("application/json")
    @Produces(MediaTypeNames.JSON)
    public HttpResponse foo(...) {
        ...
    }
}
```
It's a bit verbose, so it would be nice if we can specify them in one annotation:
```java
public class MyService {

    @Post(value = "/foo", consumes = "application/json", produces = MediaTypeNames.JSON)
    public HttpResponse foo(...) {
        ...
    }
}
```

**Comment by trustin** [comment]
Why is the proposed form less verbose than the current form? Define verbosity?

**Comment by minwoox** [comment]
We sometimes use a bunch of annotations in the service code. 
```java
public class MyService {

    @ExceptionHandler(...)
    @Blocking
    @Post("/foo")
    @Consumes("application/json")
    @Produces(MediaTypeNames.JSON)
    public HttpResponse foo(...) {
        ...
    }
}
```
If we can reduce the number of annotations, I thought it's simple and less verbose. 
```java
public class MyService {

    @ExceptionHandler(...)
    @Blocking
    @Post(value = "/foo", consumes = "application/json", produces = MediaTypeNames.JSON)
    public HttpResponse foo(...) {
        ...
    }
}
```
But, that's my opinion and if you think it's still the same, I'm fine with the current way. 😄

**Comment by jrhee17** [comment]
If each annotation has defined fields (`value`, `consumes`, `produces`) I think this could also have less cognitive load for users.
(As opposed to checking the documentation on which annotation is available)

**Comment by trustin** [comment]
I see. Then it's about cognitive load rather than verbosity, given the proposed form needs more keystrokes and potentially uglier indentation.

Is the intention to retain the both ways without any deprecation? The old way still is useful when a user binds a method to multiple paths and/or HTTP methods.

**Comment by minwoox** [comment]
Yes, we need both and the specified ones in the HTTP annotaion take precedence.

**Comment by jrhee17** [comment]
Oh, I was rather thinking that all defined ways are applied.

```
   @ExceptionHandler(...)
    @Blocking
    @Post(value = "/foo", consumes = "application/json", produces = MediaTypeNames.JSON)
    @Consumes("application/protobuf")
    public HttpResponse foo(...) { // accepts both json and protobuf
        ...
```

**Comment by anuraaga** [comment]
My opinion is the example shows an issue with the proposal - it seems to enable code that is harder to read. With consumes in two locations, reasoning out what is happening is not trivial - assuming overwriting precedence seems reasonable too.

Even if some annotations could be inlined, I guess not all of them can, so we can probably assume writers should know the selection of annotations. Keeping the code simple to read by reducing ambiguity probably takes priority.

**Comment by minwoox** [comment]
Thanks for the opinion. 😄 
Yeah, it probably enables code that is harder to read. However, I believe that most users don't use it that way and will choose one way to specify the media type with their tastes(in the simple way they think) and I think it's what Armeria does.
Also, I think if we can capture those specified media types at a glance, it won't be that hard to know what is happening.

**Comment by trustin** [comment]
Again, this is not less verbose. More lines doesn't necessarily mean verbose. The proposed solution does require more keystrokes (`value = `).

In the same sense, if it's for the sake of auto-completion, does this mean we will end up adding the attributes for all other annotations (e.g. `blocking = true, exceptionHandler = ...`)? I'm not sure that's a good idea.

**Comment by trustin** [comment]
Therefore, I agree with @anuraaga here and prefer not adding attributes that can be specified with an existing annotation.

**Comment by jrhee17** [comment]
> Even if some annotations could be inlined, I guess not all of them can, so we can probably assume writers should know the selection of annotations. Keeping the code simple to read by reducing ambiguity probably takes priority.

I agree with this 👍

**Comment by minwoox** [comment]
Ok then let's close this issue.
Thank you guys for the opinions. 😄
