### ISSUE TITLE
Potential deadlocks with decorator returning error with RetryingClient?

### ISSUE THREAD

**Issue by cmeiklejohn** [line/armeria#4369]
I have a decorator I'm using with GRPC (simplified example, but enough to reproduce the problem in isolation):

```
public class FaultDecoratingHttpClient extends SimpleDecoratingHttpClient {
    public boolean shouldReturnError = true;

    public FaultDecoratingHttpClient(HttpClient delegate) {
        super(delegate);
    }

    @Override
    public HttpResponse execute(ClientRequestContext ctx, HttpRequest req) throws Exception {
        if (shouldReturnError) {
            ResponseHeadersBuilder responseHeadersBuilder = ResponseHeaders.builder().status(200)
                    .add("content-type", "application/grpc+proto")
                    .add("content-length", "0".toString())
                    .add("grpc-status", "6")
                    .add("grpc-message", "my error message");
            responseHeadersBuilder.endOfStream(true);
            return HttpResponse.of(responseHeadersBuilder.build());
        } else {
            HttpResponse response = unwrap().execute(ctx, req);

            return new FilteredHttpResponse(response) {
                @Override
                protected HttpObject filter(HttpObject obj) {
                    return obj;
                }
            };
        }
    }
}
```

This decorator is used with GRPC requests and properly functions when used in isolation.  For example, when the boolean is set to `true`, and I issue a GRPC request using this decorator, it returns a response that's converted by the `GrpcClient` to a runtime exception at the call site.

However, if I happen to use the `RetryingClient` decorator, installed after -- so it executes before -- this decorator, I'm running into deadlocks.  I've traced this deadlock to L731 in the `ClientCalls.java` file in `io.grpc.stub`: `LockSupport.park(this);`.  It only appears to be a problem when the RetryingClient is combined with a `SimpleDecoratingHttpClient` that returns a HTTP response that indicates a GRPC error.

I'm wondering: when returning a `HttpResponse` from a decorator to short-circuit a request with a predefined response -- which we use widely for caching to avoid issuing RPC invocations for retrieving cached value or other types of load management -- should we be setting some sort of value on the response in order to indicate that the request is complete or similar?

**Comment by cmeiklejohn** [comment]
For what it's worth, I've also tried putting the GRPC information in the trailers; no difference, works without the `RetryingClient`, does not work with the `RetryingClient.`

```
            ResponseHeadersBuilder responseHeaders = ResponseHeaders.builder()
                    .endOfStream(true)
                    .add(HttpHeaderNames.STATUS, "200")
                    .add(HttpHeaderNames.CONTENT_TYPE, "application/grpc+proto");

            HttpHeadersBuilder responseTrailers = HttpHeaders.builder();
            responseTrailers.add("grpc-status", "6");
            responseTrailers.add("grpc-message", "error");
            return HttpResponse.of(responseHeaders.build(), HttpData.empty(), responseTrailers.build());
```

**Comment by cmeiklejohn** [comment]
Just another data point here: when I also apply the `CircuitBreakerClient` decorator, it doesn't seem to increment the counters because when it returns from our decorator that returns a `HttpResponse.of(...) the future isn't complete.`

**Comment by minwoox** [comment]
Hello, thanks for the report. 😉 

> should we be setting some sort of value on the response in order to indicate that the request is complete or similar?

So the problem happened because the request isn't complete? If we add `request.aggregate()` the problems are gone?

**Comment by cmeiklejohn** [comment]
Where would I add request.aggregate()?

**Comment by minwoox** [comment]
We can add `req.aggregate()` in the `execute` method of `FaultDecoratingHttpClient` to complete the request. But I guess completing the request might be not a problem with this issue because you've said that it's working if there's no `RetryingClient`.

How did you use `RetryingClient`? Could you give me a reproducible example so that I can investigate it?

**Comment by cmeiklejohn** [comment]
Reproducer: https://github.com/cmeiklejohn/retrying-client-bug

**Comment by cmeiklejohn** [comment]
Comment out the `RetryingClient` decorator to see it work; with `RetryingClient` enabled, it hangs.

**Comment by cmeiklejohn** [comment]
Needed to ensure that the request was completed using: `ctx.logBuilder().responseHeaders(responseHeaders);`.

Thanks @minwoox for the quick response!
