### ISSUE TITLE
CircuitBreakerClient and Decorators Not Working When Decorator Returns Error

### ISSUE THREAD

**Issue by cmeiklejohn** [line/armeria#4370]
If I have a GRPC client that uses the `CircuitBreakerClient` as a decorator as follows:

```
    val rule = CircuitBreakerRule.builder()
        .onServerErrorStatus()
        .onException()
        .thenFailure()

    var grpcClientBuilder: GrpcClientBuilder? = GrpcClients.builder(baseURI)
        .serializationFormat(GrpcSerializationFormats.PROTO)
        .decorator(CircuitBreakerClient.builder(rule).newDecorator());
```

and my server returns an error as follows:

```
        throw StatusException(Status.ALREADY_EXISTS)
```

The circuit breaker increments it's success and failure counters.

However, if I return an error from a decorator:

```
    val rule = CircuitBreakerRule.builder()
        .onServerErrorStatus()
        .onException()
        .thenFailure()

    var grpcClientBuilder: GrpcClientBuilder? = GrpcClients.builder(baseURI)
        .serializationFormat(GrpcSerializationFormats.PROTO)
        .decorator { delegate -> FaultDecoratingHttpClient(delegate) }
        .decorator(CircuitBreakerClient.builder(rule).newDecorator());
```

Where the decorator introduces the exact same failure:

```
            ResponseHeadersBuilder responseHeadersBuilder = ResponseHeaders.builder().status(200)
                    .add("content-type", "application/grpc+proto")
                    .add("content-length", "0".toString())
                    .add("grpc-status", "6")
                    .add("grpc-message", "my error message");
            responseHeadersBuilder.endOfStream(true);
            return HttpResponse.of(responseHeadersBuilder.build());
```

The circuit breaker never increments it's counters, because the `whenAvailable` function, inside of the Ameria `CircuitBreakerClient` implementation never becomes true.  

I verified that in both cases, my GRPC decorator (when returning the error) and the GRPC service (when returning the error) return identical HTTP headers.  In one case -- the server -- the Circuit Breaker's success and failure counters increment after execution when `whenAvailable` becomes true; in the other case, it never becomes true.

**Comment by cmeiklejohn** [comment]
We believe this might be somewhat related to #4369, since they were discovered together.

**Comment by minwoox** [comment]
Ah ha, now I get it.
> because the whenAvailable function, inside of the Ameria CircuitBreakerClient implementation never becomes true.

Yeah, the properties that complete the `whenAvailable` future are set inside of the client so we can't just return an `HttpResponse` in the decorator. For example the response headers that complete the `whenAvailable` future in `CircuitBreakerCliet` is set here:
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java#L266

So If we want to short-circuit a request, we should complete the request log by ourselves in the `execute` method. For example:
```java
ctx.logBuilder().responseHeaders(responseHeaders);
```

**Comment by cmeiklejohn** [comment]
The same reproducer as #4369 can be used:

* To simulate server returning the error: uncomment L14's throw statement in `ImageClassificationServiceImpl`
* Disable `RetryingClient `on L24 of `Client`, uncomment L23 of `Client` to enable the circuit breaker.

**Comment by cmeiklejohn** [comment]
I think your recommendation of:

```
ctx.logBuilder().responseHeaders(responseHeaders);
```

Might fix both this issue and #4369.  We're confirming.  Thanks for the quick feedback.

**Comment by cmeiklejohn** [comment]
Thanks so much, it seems to resolve the issue.

**Comment by minwoox** [comment]
> Might fix both this issue and https://github.com/line/armeria/issues/4369. We're confirming.

Glad to hear that. 😄 

So the problem with the issue is that `RetryingClient` and `CircuitBreakerClient` always assume that the response header is set via `HttpResponseDecoder` but it's not if we use this short-circuit decorator. Let me talk to the team if we can fix this issue. Thanks a lot! 😄

**Comment by cmeiklejohn** [comment]
We also had to set response trailers, as some of our circuit breaker rules required that trailers be completed.

```
ctx.logBuilder().responseTrailers(responseTrailers);
```
