### ISSUE TITLE
Improve confusing `AnnotatedService` behavior with `void` return type

### ISSUE THREAD

**Issue by ks-yim** [line/armeria#4390]
Currently, the behavior of `AnnotatedService` with void return type(including `Mono<Void>`) is quite confusing and users often struggles to find the right way to return `204 No Content` with `AnnotatedService`.
 
The following code demonstrates common attempts to give `204 No Content` and its actual result.

```java
@ProducesJson // It's common to add class-level @ProducesJson REST API service.
public class FooService {

    @Get("/foo") // 500 error; cause: IllegalArgumentException
    public void foo() {}

    @Get("/foo-mono") // 200 OK, Content-Type: application/json, body: "null" (4-bytes string)
    public Mono<Void> fooMono() {
        return Mono.empty();
    }

    @Get("/foo-mono-204") // 500 error; cause: IllegalArgumentException
    @StatusCode(204)
    public Mono<Void> fooMono204() {
        return Mono.empty();
    }
}

// Without @ProducesJson
public class BarService {

    @Get("/bar") // 204 No Content
    public void bar() {}

    @Get("/bar-mono") // 200 OK with empty body
    public Mono<Void> barMono() {
        return Mono.empty();
    }

    @Get("/bar-mono-204") // 204 No Content
    @StatusCode(204)
    public Mono<Void> barMono204() {
        return Mono.empty();
    }
}
```

Adding `NullToNoContentResponseConverterFunction` would be of some help but it doesn't cover `Mono<Void>` cases.

This behavior could possibly be fixed by..:
1. modifying `AnnotatedServiceFactory#defaultResponseStatus` to return `HttpStatus.NO_CONTENT` for `Mono<Void>`.
2. modifying `AnnotatedServiceFactory#routes` to ignore `producibleMediaTypes`.
   - Or by ignoring `negotiatedResponseMediaType` in `AnnotatedService` when the status code is 204.

**Comment by ikhoon** [comment]
It makes sense to return 204 No Content for the following example.
```
// Without @ProducesJson
public class BarService {

    @Get("/bar-mono") // 200 OK with empty body
    public Mono<Void> barMono() {
        return Mono.empty();
    }
}
```

As `@ProducesJson` is explicitly specified, I prefer to return `200 OK, Content-Type: application/json, body: "null"`.
Because some users might want to return "null" as their return value.
But if `@StatusCode(204)` is set, It is reasonable to return an empty body with 204.
Anyway, it should not raise 500 error for those cases.
```
@ProducesJson // It's common to add class-level @ProducesJson REST API service.
public class FooService {

    @Get("/foo") // 500 error; cause: IllegalArgumentException
    public void foo() {}

    @Get("/foo-mono") // 200 OK, Content-Type: application/json, body: "null" (4-bytes string)
    public Mono<Void> fooMono() {
        return Mono.empty();
    }

    @Get("/foo-mono-204") // 500 error; cause: IllegalArgumentException
    @StatusCode(204)
    public Mono<Void> fooMono204() {
        return Mono.empty();
    }
}
```

**Comment by ks-yim** [comment]
I will send a fix PR 😆.
