### ISSUE TITLE
WebOperationService incorrectly handling ReactiveHealthIndicator results

### ISSUE THREAD

**Issue by DasAmpharos** [line/armeria#4396]
Spring Boot WebFlux applications with reactive health indicators are incorrectly returning HTTP 200 with the following response body when requesting application health: 
```json 
{
	"scanAvailable": true
}
```

After inspecting [WebOperationService#handleResult](https://github.com/line/armeria/blob/09ab81037f5a8a9e15e4d639474e7a925b0c40f5/spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java#L202) (lines 217-225 to be exact), the method is not accounting for the possibility that `result` is `instanceof Mono<Health>`. This results in response status code of 200 with `result` as the body instead of the value emitted by `result`.

JDK: 17.0.3-tem
Armeria version: 1.17.2/1.18.0
Spring Boot version: 2.7.2

**Comment by minwoox** [comment]
Thanks for the report, @DasAmpharos!
> Spring Boot WebFlux applications with reactive health indicators

Could you let me know how did you enable this feature so that I can make a reproducible test for this, please?

**Comment by DasAmpharos** [comment]
@minwoox I created a sample project with a custom health indicator: https://github.com/DasAmpharos/armeria-reactive-health-demo

I included some additional details in the README file

**Comment by minwoox** [comment]
That is a so high-quality reproducible example. 🙇‍♂️ 
That will help us a lot. Let us take a look at it. Thank you! 😄
