### ISSUE TITLE
Provide a way to serve HttpJsonTranscoding with camelCase body/parameter field names

### ISSUE THREAD

**Issue by j-min5u** [line/armeria#4401]
There is no direct specification to field namecase in the google [Http and gRPC transcoding](https://google.aip.dev/127) documentation.

However, we were currently confirmed by googlers that we should use camelCase for Http Json transcoded apis in these issue & PR:
https://github.com/googleapis/gax-nodejs/issues/1312
https://github.com/aip-dev/google.aip.dev/pull/934

Can we add an option maybe to GrpcJsonMarshaller that when enabled creates the transcoded endpoint with camelCase field names?

**Comment by ikhoon** [comment]
Technically, `HttpJsonTranscodingService` does not rely on `GrpcJsonMarshaller` to extract field information. So it maps a query parameter into a protobuf's field.
https://github.com/line/armeria/blob/3c61331a7a14bc9b1339c91f5781cdce8bac4d2f/grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java#L307-L308
If Google API says that camelCase field names are the standard query parameters, I think we can provide an option to `GrpcServiceBuilder`.
But I'm not sure that we can change the default behavior. It could be dangerous and cause serious problems in the system running with sake_case.

Proposed to add `HttpJsonTranscodingOption` to override/customize the default behavior.
```java
enum HttpJsonTranscodingOption {
   CAMEL_CASE_QUERY_PARAMS,

   // Maybe add something later 

}
GrpcService
  .builder()
  .enableHttpJsonTranscoding(true, HttpJsonTranscodingOption.CAMEL_CASE_QUERY_PARAMS)
  ...         
```

**Comment by ikhoon** [comment]
On second thought, an enum option is difficult to expand because it can't take a parameter. A configuration class and its builder seem more reasonable.
```java
var options = 
  HttpJsonTranscodingOptions
    .buider()
    .camelCaseQueryParams(true)
    ...
    .build()
GrpcService
  .builder()
  .enableHttpJsonTranscoding(true)
  // An IllegalStateException will be raised if HttpJsonTranscoding is disabled.
  .httpJsonTranscodingOptions(options)
  .build()                                       
```

**Comment by j-min5u** [comment]
> But I'm not sure that we can change the default behavior. It could be dangerous and cause serious problems in the system running with sake_case.

I agree, this would be too big of a change to switch over to.

> On second thought, an enum option is difficult to expand because it can't take a parameter. A configuration class and its builder seem more reasonable.

builder seems ok. maybe take the option in enableHttpJsonTranscoding?
```java
GrpcService
  .builder()
  .enableHttpJsonTranscoding(true, options)
  .build()          
```
Although it might be weird that enableHttpJsonTranscoding(false, options) is possible

**Comment by ikhoon** [comment]
> Although it might be weird that enableHttpJsonTranscoding(false, options) is possible

I think we can assume that `HttpJsonTranscodingOptions` implies enabling `HttpJsonTranscoding`.
So how about dropping the boolean flag for the overload method taking `HttpJsonTranscodingOptions`?
```java
GrpcService
  .builder()
  // Use the default HttpJsonTranscodingOptions.
  .enableHttpJsonTranscoding(true)
  .build()

// Otherwise
GrpcService
  .builder()
  // Enable HttpJsonTranscoding and use the specified HttpJsonTranscodingOptions.
  .enableHttpJsonTranscoding(options)
  .build()
```

**Comment by jrhee17** [comment]
> I think we can assume that HttpJsonTranscodingOptions implies enabling HttpJsonTranscoding.

I also think this API looks cleaner 👍 

```
GrpcService
  .builder()
  // Enable HttpJsonTranscoding and use the specified HttpJsonTranscodingOptions.
  .enableHttpJsonTranscoding(options)
  .build()
```
