### ISSUE TITLE
spring aop with doc service

### ISSUE THREAD

**Issue by carl10086** [line/armeria#4417]
## Description: 

when i run official  spring-boot-minimal demo . It Usea  spring @Validated annotation .

```java
@Component
@Validated
@ExceptionHandler(ValidationExceptionHandler.class)
public class HelloAnnotatedService {
...
}
```

DocService  class Specification is something like `HelloAnnotatedService$$EnhancerBySpringCGLIB$$8b7cb243` because of aop of the spring . That may be a dynamic class name which is not friendly to partners. 

## Question

- Is there anyway to  support custom service name  in doc service ?   Thank u very much .

**Comment by ikhoon** [comment]
> Is there anyway to support custom service name in doc service ?

It is not supported at the moment.

> DocService class Specification is something like HelloAnnotatedService$$EnhancerBySpringCGLIB$$8b7cb243

I think the enclosing class created by cglib should be peeled by the following utility method for DocService. https://github.com/line/armeria/blob/49054ad7f22a7f2d64faaeb694674b0df09ad165/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java#L644-L653
