### ISSUE TITLE
Provide a way to handle GraphQL errors

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4423]
Users might want to return different responses depending on the `List<GraphQLError>`.
It would be nice if we add an interface that allows users to customize responses depending on the errors:
```java
public interface GraphQlErrorHandler {

    HttpResponse handleErros(ServiceRequestContext ctx, ExecutionInput input, List<GraphQLError> error);
    // return null to apply the next or the default handler
}

GraphQlErrorHandler errorHandler = ..
GraphqlService.builder()
              .schemaFile(...)
              .runtimeWiring(...)
              .errorHandler(errorHandler)
              .build();
```

**Comment by boggy-cs** [comment]
Hi, @minwoox . May I try this issue?

**Comment by minwoox** [comment]
@boggy-cs It's all yours. Thank you. 😄

**Comment by bog-y** [comment]
hello, @minwoox! May I ask why the ErrorHandler parameters include ServiceRequestContext and ExecutionInput?

I think it would be better to pass ExecutionResult and MediaType as parameters than ServiceRequestContext and ExecutionInput.

```java
@FunctionalInterface
public interface GraphqlErrorHandler {
    
    HttpResponse handleErrors(ExecutionResult result, MediaType produceType, List<GraphQLError> errors);
}
```
