### ISSUE TITLE
THttpService.validateRequestAndDetermineSerializationFormat on MediaType.parse(accept) failure behavior

### ISSUE THREAD

**Issue by lovepoetry** [line/armeria#443]
@trustin 

The following code will end with `HTTP 406` for accept header such as `text/plan, */*; q=0.5`.

https://github.com/line/armeria/blob/master/thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java#L465

I have two concerns.

- `MediaType.parse` maybe not capable for `accept` header parsing according to https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
- When `MediaType.parse` ends with exception, how about using `serializationFormat` as the fallback output serialization format?

**Comment by trustin** [comment]
May I know which Thrift client sends such an `accept` header?

**Comment by trustin** [comment]
> `MediaType.parse` maybe not capable for `accept` header parsing according to https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

I see. we should split the header with `,` before calling `MediaType.parse()`, right?

> When `MediaType.parse` ends with exception, how about using `serializationFormat` as the fallback output serialization format?

IIUC, `MediaType.parse()` should never fail to parse a valid mime type definition. The problem is that we did not handle the case where the client sends multiple accepted mime types. Therefore, we could:

- Handle comma-separated or multi-value `accept` headers correctly.
- When `MediaType.parse()` raises an exception (i.e. invalid mime type), ignore it.
- Respond with `406` if no mime types were accepted.
  - For `text/plain, */*`, `*/*` will match the default serialization format, so it will not cause `406`.

Sounds good?

**Comment by trustin** [comment]
Another related action item could be providing a utility for parsing the `accept` header from `HttpHeaders`:

```java
// Returns the MediaTypes in the 'accept' header in the order of preference, with 'q' parameters removed.
List<MediaType> acceptedMediaTypes = HttpHeaderGetters.accept(httpHeaders);
for (MediaType t : acceptedMediaTypes) {
    ...
}

// Additionally, we could have HttpHeaderSetters
HttpHeaderSetters.setAccept(HttpHeaders headers, Iterable<MediaType> acceptedMediaTypes);

// and probably add cookie access as well.
HttpHeaderGetters.cookie(...);
HttpHeaderSetters.setCookie(...);
```

**Comment by lovepoetry** [comment]
> May I know which Thrift client sends such an accept header?

Sorry, in fact I don't know the version of the client as it is managed by another service.

> I see. we should split the header with , before calling MediaType.parse(), right?

Yes, and should evaluate the weight if multiple content typed matched.

> IIUC, MediaType.parse() should never fail to parse a valid mime type definition. The problem is that we did not handle the case where the client sends multiple accepted mime types. Therefore, we could:
> - Handle comma-separated or multi-value accept headers correctly.
> - When MediaType.parse() raises an exception (i.e. invalid mime type), ignore it.
> - Respond with 406 if no mime types were accepted.
>   - For text/plain, */*, */* will match the default serialization format, so it will not cause 406.

Sounds good. Thanks.
However, in a production environment, event an invalid content-type is sent by request, I think using the default format instead of raising a runtime exception is better practice.
What do you think about it?

**Comment by trustin** [comment]
> However, in a production environment, even an invalid content-type is sent by request, I think using the default format instead of raising a runtime exception is better practice. What do you think about it?

Is this about `content-type` header rather than `accept`? Could you elaborate a little bit more? e.g. paste the problematic request headers here.

**Comment by trustin** [comment]
Will add a new class `HttpMediaRangeMatcher` to `com.linecorp.armeria.server.http`:

```java
public final class HttpMediaRangeMatcher {

    public HttpMediaRangeMatcher(MediaType defaultMediaType, MediaType... otherAcceptedMediaTypes) { ... }
    public HttpMediaRangeMatcher(MediaType defaultMediaType, Iterable<MediaType> otherAcceptedMediaTypes) { ... }

    public Optional<MediaType> match(HttpHeaders headers) { ... }
    public Optional<MediaType> match(String acceptHeader) { ... }
    public Optional<MediaType> match(MediaType... desiredMediaTypes) { ... }
    public Optional<MediaType> match(Iterable<MediaType> desiredMediaTypes) { ... }
}
```

**Comment by lovepoetry** [comment]
@trustin Sorry for late response.

> Is this about content-type header rather than accept? Could you elaborate a little bit more? 
> e.g. paste the problematic request headers here.

The problematic header is `accept: text/plan, */*; q=0.5`. 
About the content type range parsing failure itself (, and ; tokenization, etc.), we have already talked about it. And The `HttpMediaRangeMatcher ` looks good for the solution.

What I concerned is that when an exception occurred, the output format will be assigned as `null`, but how about assigning it with `serializationFormat`?

```java
try {
                outputSerializationFormat =
                        SerializationFormat.find(MediaType.parse(accept)).orElse(serializationFormat);
            } catch (IllegalArgumentException e) {
                logger.debug("Failed to parse the 'accept' header: {}", accept, e);
                outputSerializationFormat = null;
            }
```

**Comment by trustin** [comment]
> What I concerned is that when an exception occurred, the output format will be assigned as null, but how about assigning it with serializationFormat?

According to the RFC:

> If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response.

SHOULD means:

> SHOULD   This word, or the adjective "RECOMMENDED", mean that there   may exist valid reasons in particular circumstances to ignore a   particular item, but the full implications must be understood and   carefully weighed before choosing a different course.

Although it is not a violation of the specification to send a non-406 response, I'd like to keep the current behavior of sending a 406 when the media range specified in the `accept` header does not match (or invalid.)

The `text/plan, */*; q=0.5` is a valid `accept` header value and thus should work fine once the forementioned bug (the inability to handle media range correctly) is fixed.

**Comment by lovepoetry** [comment]
Yes, you're right.
The current behavior is better to serve various request.
Thanks!!

**Comment by anuraaga** [comment]
While thinking about HTTP encoding, I remembered this code that I copied as is from Netty

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/http/encoding/HttpEncoders.java#L60

If we have a generic Accept header parsing mechanism, we should probably replace it too :)

**Comment by trustin** [comment]
@lovepoetry #446 Should address this issue.

**Comment by trustin** [comment]
> If we have a generic Accept header parsing mechanism, we should probably replace it too :)

We currently rely on `MediaType.parse()` on this, so it can't be used for `accept-encoding` or `accept-language`, but I'd love to see this happen someday..
