### ISSUE TITLE
Add ArrayBasedEventLoopState

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4439]
We use `AbstractEventLoopState` to acquire an `EventLoop` in a client for sending requests to a host.
If only one `EventLoop` is allocated for a host, `OneEventLoopState` is used.
If more than one `EventLoop` is allocated for a host, `HeapBasedEventLoopState` is used to select an `EventLoop` depending on the `activeRequests` count.
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/AbstractEventLoopState.java#L27-L35
Using a heap is pretty efficient if the number is large. However, it's inefficient if the number is small. (e.g. 2)
So we need to:
- find the threshold to use array-based or heap-based implementation using benchmark
- add `ArrayBasedEventLoopState`

**Comment by Narayan1670** [comment]
Hi @minwoox, I would like to work on this, can you assign this me?

**Comment by minwoox** [comment]
It's all yours. Thanks! 😄

**Comment by erie0210** [comment]
Hi, :) If it's okay, can I try this one? 🙏

**Comment by minwoox** [comment]
Hi, @erie0210

We are on the internal event called Sprint which helps participants implement PRs and this is one of the issues.
@Kyurenpoto is working on it now. 😓 
Really sorry about it and could you pick another one? If you let me know which part of Ameria you are interested in, I might recommend an issue for you.

**Comment by erie0210** [comment]
Thanks for letting me know! 🙂 If you can recommend one `first-good-issue` that needs to be worked on in the project, I'd love to work on it @minwoox

**Comment by minwoox** [comment]
Hi, @erie0210!
I'm sorry that I missed your comment. 😢 
Here are a few issues that you might be interested in:
- Add missing getters #4722
- Load balancing selection strategies: #4698 #4699 #4700
- If you are interested in OAuth2: #3630

Please let me know if you have any questions. 😄
