### ISSUE TITLE
Does armeria supports compression over http/2?

### ISSUE THREAD

**Issue by xyzker** [line/armeria#444]
In my business scenario, I  usually deal with large bunches of strings, which consume a lot of bandwidth. So I'm very interested whether armeria supports compression over http/2 now. If it supports, could you show me how to use it? Or if not, do you have any plan to support it in the near future?  As far as I know, gRPC has supported compression already. And thank you very much for checking my question :)

**Comment by anuraaga** [comment]
Currently armeria has HTTP compression in the server - https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/http/encoding/HttpEncodingService.java

If the client is the browser, compression will happen automatically.

The armeria client currently doesn't support compression - I don't think it would be hard to implement it and might be nice for server/client symmetry. In my experience, internal network capacity has grown much faster than CPU and enabling compression for internal requests tends to be a loss - but maybe not for specific workloads of course.

Just wondering, is your use case for internal requests (not browser)?

**Comment by xyzker** [comment]
Yeah, my use case is for internal requests (RPC).

**Comment by xyzker** [comment]
It seems there is a bug: HttpEncodingService only encode when the content length is larger than 1kb, see in HttpEncodedResponse: 
` if (headers.contains(HttpHeaderNames.CONTENT_LENGTH)) {
            // We switch to chunked encoding and compress the response if it's reasonably
            // large as the compression savings should outweigh the chunked encoding
            // overhead.
            if (headers.getInt(HttpHeaderNames.CONTENT_LENGTH) < minBytesToForceChunkedAndEncoding) {
                return false;
            }
        }`
howerver, the new HttpDecodingClient will always decode the content. So if the httpData content is less than 1kb and it has the "content-length" parameter, the HttpDecodingClient will throw an exception when decoding.

**Comment by anuraaga** [comment]
Thanks for reporting - #466 adds a fix and test for the non-encoded case.
