### ISSUE TITLE
MultipartForm throws java.lang.IllegalStateException: subscribed by other subscriber already when used within ResponseConverterFunction 

### ISSUE THREAD

**Issue by chungonn** [line/armeria#4450]
Hi folks,

I encountered an 'Illegal State exception - subscribed by other subscriber already' when invoking a HttpRequest.aggregate() method. 

Please find the attached the source code below to reproduce the problem. The code is written in Scala 3 and tested with Armeria 1.19.0. 

In the attached code there are 3 services -  `/mp-form-agg`,`mp-form`, `mp-action`. These 3 services are implemented differently for receiving a mulitpart-form arguments i.e. a body part + a query-string . This is the request sent to the services  `curl -v  -F person=homer http://localhost:8080/`**service-name**`\?queryArg\=test`

All these 3 services have the same request signature but each has a different endpoint. The first 2 works as expected, 3rd service `mp-action` throw the above exception. 

This 3rd service is implemented as is a  `MultiiPartAction` function and it is invoked by a `ResponseConverterFunction` - **actionConverterFunction**. 

Interestingly,  if the multipart request is changed to a regular urlencoded form request, it works.
`curl -v  -F person=homer http://localhost:8080/mp-action\?queryArg\=test` this multipart request will cause the service to throw an exception
`curl -v  -d person=homer http://localhost:8080/mp-action\?queryArg\=test` this urlencoded request will work 

Please find the source below

[MulitPartForm2Main.zip](https://github.com/line/armeria/files/9650917/MulitPartForm2Main.zip)

**Comment by minwoox** [comment]
Hi, I just checked that the request is subscribed in the response converter function which means that the request cannot be aggregated.  I think this is one of the corner cases that we cannot use the cache feature of aggregation.
The possible workaround at the moment is to aggregate the request in the decorator and store it to the ctx using attr and retrieve it later.
```java
sb.decorator((delegate, ctx, req) -> {
    return HttpResponse.from(req.aggregate().thenApply(aggregatedReq -> {
        ctx.setAttr(reqKey, aggregatedReq);
        HttpRequest newReq = aggregatedReq.toHttpRequest();
        ctx.updateRequest(newReq);
        return delegate.serve(ctx, newReq);
    }));
    return delegate.serve(ctx, req);
});
```

**Comment by chungonn** [comment]
@minwoox thanks for the suggested alternative, it does not seems to work for me. As `Action` is an utility function and is an equivalent to HttpService and hence it should not be required to add a decorator to it.

I am curious as why the failing testcase does for for work for an `UrlEncoded` request given the same `Action` service and the  same aggregated request code. I will take a closer look later to study why it works for a UrlEncoded request and not  a Multipart request once I can find some free cycles.

Meanwhile, I just need to  avoid using the MultiPart that has both body params and query-string params 

Thanks for helping to look into the  issue.

**Comment by minwoox** [comment]
> As Action is an utility function and is an equivalent to HttpService and hence it should not be required to add a decorator to it.

We don't have to add the decorator to the `Action`. What I meant was adding a decorator before the annotated service so that we can store the content to the `ctx` and retrieve it later in the `Action`.

> I am curious as why the failing testcase does for for work

It's because the request is not aggregated but subscribed.
`HttpRequest` is only cached when it's aggregated via `HttpRequest.aggregate()`. But the multipart form-data is not aggregated but subscribed using `subscribe()`.
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/server/FileAggregatedMultipart.java#L62

**Comment by chungonn** [comment]
Thanks for the correcting my misunderstanding :) I have the code simplified in the testcase to allow us to zoom into the cause of problem. We actually place all the `Action` service within a `Controller`. Let me explore this later, it does seems possible when the library programmatically adds the decorator to each controller. 

We have only one use case that has a MultiPart with both body and query params in our many projects,  we  workaround the problem by dropping the use body + query params in Multipart form.

Finally, thanks for the link to FileAggregatedMultipart source.

I will close this issue.
