### ISSUE TITLE
Provide a way to set a request timeout using annotation

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4463]
The timeout of an annotated service could be set using [AnnotatedServiceBindingBuilder.requestTimeoutMillis()](https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.19.0/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.html#requestTimeoutMillis(long)).
However, it is globally applied to all methods of the service. If users want to set a custom timeout, they have to call `ServiceRequestContext.setRequestTimeout()` manually in a service or decorator.

It would be easy to set a timeout of a service or method if we introduce `@RequestTimeout`. For example:
```java
@RequestTimeout(value = 5, TimeUnit.SECONDS)
class MyService {

    // Override the service timeout and set the timeout to 10 seconds
    @RequestTimeout(value = 10, TimeUnit.SECONDS)
    @Get
    ...
    public CompletableFuture<List<Item>> getItems(...);

    // Limit timeout to 5 seconds
    @Get
    ...
    public CompletableFuture<Item> getItem(...);
}
```
If both `AnnotatedServiceBindingBuilder.requestTimeout()` and `@RequestTimeout()` is set, we can give priority to `@RequestTimeout`.

**Comment by j-min5u** [comment]
Would adding a new decorater that does ServiceRequestContext.setRequestTimeout(SET_FROM_START, ), then implementing the new @RequestTimeout with @DecoratorFactory be a viable solution for this issue? Though this would create dependency to the armeria decorator implementation, it would also allow us to use the annotation on other services (such as gRPC services) not only annotated services. If not so, I guess the annotation should be collected and acknowledged when ServiceConfig is created

**Comment by ikhoon** [comment]
The decorator approach with `setRequestTimeout` sounds good to me. 👍

By the way, I came up with this idea while having a conversation with @ks-yim. 
Meanwhile, I asked if he would like to implement this feature. So I want to know if @ks-yim is still interested in this. 😀

**Comment by j-min5u** [comment]
Nice 👏 😄 If not so, you could toss it to me 🙂

**Comment by ks-yim** [comment]
@j-min5u I haven't started working on it. It's all yours, thanks!
