### ISSUE TITLE
Build and run with JDK 19 and possible enable loom (preview required) as well

### ISSUE THREAD

**Issue by Jimexist** [line/armeria#4465]
now that JDK 19 is out we can build against JDK 19 and see if we can use the virtual thread from project loom as well.

**Comment by Jimexist** [comment]
not sure how to add the support for JDK 19 with self-hosted machines

**Comment by minwoox** [comment]
> not sure how to add the support for JDK 19 with self-hosted machines

I haven't tried that but I believe that it's just updating the GitHub Actions scripts and our Gradle build file. 😉

**Comment by ikhoon** [comment]
We are still planning how to support the virtual thread with Armeria. 

Anyway, we need to wait for gradle and other build tools to update our build version to JDK 19. https://github.com/gradle/gradle/issues/20372
