### ISSUE TITLE
`DocService`  Add collapsible grpc request / response types

### ISSUE THREAD

**Issue by Dogacel** [line/armeria#4481]
Proto response/request types are not collapsible. I think they should automatically become collapsible because those types do not contain any valuable information and most of the time they are just `{METHOD_NAME}Request` and `{METHOD_NAME}Response`.

![image](https://user-images.githubusercontent.com/7023385/195600182-2f3112e6-f759-4549-99e5-5c47091d846d.png)

Example: 
![image](https://user-images.githubusercontent.com/7023385/195600062-16f0916b-9208-4bfc-bb52-3e1c2029680a.png)

**Comment by minwoox** [comment]
So do you mean we need to make the `Parameters` and `Return Type` sections collapsible?

**Comment by Dogacel** [comment]
Yes exactly. Because each RPC method has one request and one response type, it would save everyone a click.

Also the convention is not using primitives for requests/response types. For each rpc method `XXX`, the return type would be `XXXResponse` and request type would be `XXXRequest`. [Google API Guide](https://developers.google.com/protocol-buffers/docs/style#services) [Buf Style Guide](https://docs.buf.build/lint/rules#rpc_request_standard_name-rpc_response_standard_name-rpc_request_response_unique)

**Comment by minwoox** [comment]
Now I get what you meant. 😄 
Thanks for the nice suggestion. 
It perfectly makes sense if we use this `DocService` for a gRPC service only.
However, we also use this for an annotated service or a Thrift service which might have a bunch of parameters.
In that case, the unfolded structs would make the page cumbersome.

**Comment by Dogacel** [comment]
@minwoox makes sense, can we make this appear conditionally (e.g. show it only in grpc methods) by using some sort of boolean flag?

I also realized the section `Exceptions` is always empty (maybe I have missed something) for grpc methods, we can also hide that.
