### ISSUE TITLE
`GrpcDocServicePlugin` fails when using `GrpcDecoratingService`-wrapped `GrpcService`

### ISSUE THREAD

**Issue by davin111** [line/armeria#4487]
When using `GrpcService` with decorators, `GrpcServiceBuilder` wraps it with `GrpcDecoratingService`. - [code line](https://github.com/line/armeria/blob/c888c86b288e85bb489b2938f2498095b2303e55/grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java#L1043)

However, it makes `GrpcDocServicePlugin` fail to `generateSpecification`, because when [this line](https://github.com/line/armeria/blob/755c28292c734e954bd69aebcfaeabcf7b024c16/grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePlugin.java#L127) is executed, `grpcService instanceof HttpEndpointSupport` is `false`.

As a result, `methodDefinition` can be `null` on [this line](https://github.com/line/armeria/blob/755c28292c734e954bd69aebcfaeabcf7b024c16/grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePlugin.java#L177). (Also above `assert` line fails.)

May I give a try fixing this issue?

**Comment by jrhee17** [comment]
Sorry about the bug 😅 

> May I give a try fixing this issue?

Please do so! I guess that we may want to unwrap and check if the decorated service contains an `HttpEndpointSupport`.

e.g.
```
final HttpEndpointSupport httpEndpointSupport = grpcService.as(HttpEndpointSupport.class);
if (httpEndpointSupport != null) {
...
```
