### ISSUE TITLE
Remove uncompress javascript files in `DocService`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4500]
I found that `armeria.jar` contains both compressed and uncompressed javascript files for `DocService`.
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1866157/197493724-11aeed54-53b3-4a84-98a7-dbc5c11aa93f.png">
The Documentation service is built on top of modern Javascript stacks such as React and Material UI, so the size of uncompressed javascript files is rather huge.

As `FileServiceBuilder.autoDecompress()` is able to decompress a compressed file on demand, we don't need to pack uncompressed files to `armeria.jar`.
/cc @heowc

**Comment by heowc** [comment]
I think I added [deleteOriginalAssets](https://www.npmjs.com/package/compression-webpack-plugin#user-content-deleteoriginalassets) in the first place, but it seems to be missing. 🤣

**Comment by ikhoon** [comment]
We would need some unit tests to check where an uncompressed file exists in the classpath.
