### ISSUE TITLE
`AuthFailureHandler` receives an unpeeled `Exception`

### ISSUE THREAD

**Issue by ks-yim** [line/armeria#4502]
#### Issue:
`AuthFailureHandler` functional interface accepts `Throwable` as a parameter and it is supposed to receive a so called peeled cause (peeled by Exceptions#peel or by chaining the future with `handle[Async]` callback which preserves the original exception) for this parameter.

But this behavior has changed since Armeria >= 1.6.0 after adding [`authorizeAndSupplyHandlers`](https://github.com/line/armeria/blob/94a1bf40ff41e1cfa9cd0c1a08f7bde14a7153c9/core/src/main/java/com/linecorp/armeria/server/auth/Authorizer.java#L62) which is chaining the future with `thenApply` callback, which then wraps the original cause in `CompletionException`.

If I understand it correctly, Armeria has an implicit convention of passing only the `peeled causes` to the publicly available interfaces and `AuthFailureHandler`'s current behavior is violating this convention.

**Comment by minwoox** [comment]
> If I understand it correctly, Armeria has an implicit convention of passing only the peeled causes to the publicly available interfaces

That is correct and thanks for the reporting. 👍 
Yeah, we need to fix that.
