### ISSUE TITLE
Struct `FieldInfo` is not correctly rendered in `DocService` if bean field names are overridden by `@JsonProperty`

### ISSUE THREAD

**Issue by ks-yim** [line/armeria#4506]
#### Issue:
* With the following Kotlin data class..:
   ```kotlin
   data class AccessTokenDto(
       @JsonProperty("scope")
       @Description("A space-delimited list of scopes that the bearer of the access token is allowed to access.")
       val scope: String,

       @JsonProperty("expires_in")
       @Description("After which seconds the token is expired.")
       val expiresIn: Long,

       @JsonProperty("access_token")
       @Description(
           "An opaque string that must be presented in the `Authorization` header" +
               " to access protected resources."
       )
       val accessToken: String,
    
       @JsonProperty("token_type")
       @Description(
           "Fixed to `Bearer`, which indicates the access token must be presented " +
               "in the `Authorization` with `Bearer` auth scheme."
       )
       val tokenType: String = "Bearer"
   )
   ```
   ... the `FieldInfo`s for those properties whose response field names were overridden with `@JsonProperty` is not correctly rendered in `DocService`.
   <img width="1506" alt="image" src="https://user-images.githubusercontent.com/35995647/197954910-77a0b8d4-83b3-4b10-9e42-c602dc71625b.png">

#### Cause:
* Overridden field name is used to find the right constructor parameter at [`DefaultNamedTypeInfoProvider.java:L418`](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/server/annotation/DefaultNamedTypeInfoProvider.java#L418) but it fails because there's no matching parameter name.

**Comment by ikhoon** [comment]
It sounds a bug. We need to access the original field if there is no matching field with the `@JsonPropery`
