### ISSUE TITLE
Should not return a content body for `HEAD` method in `AggregatedHttpResponseHandler`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4511]
There is a regression that a content body could be sent even if a `HEAD` method is set in a request header.
`HttpResponseSubscriber` handles the `HEAD` method correctly, but `AggregatedHttpResponseHandler` does not consider the `HEAD` method.
https://github.com/line/armeria/blob/5d1d9a5525ffe2305fcb56f32763748d1aa30168/core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java#L153-L154
https://github.com/line/armeria/blob/5d1d9a5525ffe2305fcb56f32763748d1aa30168/core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java#L129-L134

**Comment by nilanjanH** [comment]
@ikhoon - Is this issue resolved? If not, would love to get started on this.
I am new to OSS & this would be my first contribution, so any pointers[if I am assigned this issue] would also be very much appreciated.

Thanks.
