### ISSUE TITLE
Trailing dot in domain names is stripped causing search domains to be used

### ISSUE THREAD

**Issue by amirhadadi** [line/armeria#4538]
When executing requests against domain names such as `x.com.` (note the dot in the end), Armeria strips the trailing dot [here](https://github.com/line/armeria/blob/27f1d605bea0874bf0bd68962f5e405812ba55fd/core/src/main/java/com/linecorp/armeria/client/Endpoint.java#L125).
As a result search domains are being attempted.
The `.` should be preserved so that DNS resolution treats the domain name as an FQDN.

**Comment by ikhoon** [comment]
It seems a trailing dot has to be removed for SNI and preserved for Host and `:authority`.
https://lists.w3.org/Archives/Public/ietf-http-wg/2016JanMar/0430.html
