### ISSUE TITLE
RequestContextExportingAppender incompatible with ch.qos.logback.classic.net.SocketAppender

### ISSUE THREAD

**Issue by Yuri999** [line/armeria#4546]
Adding at least one `<export>` tag to `RequestContextExportingAppender` causes exception and connection loss when using `SocketAppender`.

Example `logback-spring.xml`:
```xml
    <appender name="REMOTE" class="ch.qos.logback.classic.net.SocketAppender">
        <remoteHost>localhost</remoteHost>
        <port>6810</port>
        <reconnectionDelay>10000</reconnectionDelay>
        <eventDelayLimit>1000</eventDelayLimit>
        <includeCallerData>false</includeCallerData>
    </appender>

    <appender name="REMOTE_RCEA" class="com.linecorp.armeria.common.logback.RequestContextExportingAppender">
        <appender-ref ref="REMOTE"/>
        <export>correlation.id=req.headers.correlation-id</export>
    </appender>
```

The problem is in logback's `LoggingEventPreSerializationTransformer`, which is trying to check event type and make `LoggingEventVO` of it:
```java
public Serializable transform(ILoggingEvent event) {
        if (event == null) {
            return null;
        }
        if (event instanceof LoggingEvent) {
            return LoggingEventVO.build(event);
        } else if (event instanceof LoggingEventVO) {
            return (LoggingEventVO) event;
        } else {
            throw new IllegalArgumentException("Unsupported type " + event.getClass().getName());
        }
    }
```
but `LoggingEventWrapper` only implements `ILoggingEvent` and doesn't extend `LoggingEvent`.

After fixing that issue we will get `InvalidClassException: Unauthorized deserialization attempt` in `HardenedObjectInputStream`.

Second problem is in the way `LoggingEventWrapper` is created. `RequestContextExportingAppender` passes to `LoggingEventWrapper.append(..)` its own type (exporter.export() creates `RequestContextExporter$State`) as propertiesMap, which is then can't be accepted by logback because of classes whiltelist check. 
```
        final Map<String, String> contextMap = exporter.export();
        if (!contextMap.isEmpty()) {
            final Map<String, String> originalMdcMap = eventObject.getMDCPropertyMap();
            final Map<String, String> mdcMap;

            if (!originalMdcMap.isEmpty()) {
                mdcMap = new UnionMap<>(contextMap, originalMdcMap);
            } else {
                mdcMap = contextMap;
            }
            eventObject = new LoggingEventWrapper(eventObject, mdcMap);
        }
```
So, its need to be replaced with one of java.util classes like HashMap.

**Comment by ikhoon** [comment]
`LoggingEventVO.build()` is able to take `ILoggingEvent` as its parameter.
So it sounds like a bug in `LoggingEventPreSerializationTransformer` of logback.
https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/spi/LoggingEventVO.java#L70
What do you think of reporting this issue to the logback repository?
This is because extending `LoggingEvent` might increase the size of the object layout.

**Comment by Yuri999** [comment]
> `LoggingEventVO.build()` is able to take `ILoggingEvent` as its parameter. So it sounds like a bug in `LoggingEventPreSerializationTransformer` of logback. https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/spi/LoggingEventVO.java#L70 What do you think of reporting this issue to the logback repository? This is because extending `LoggingEvent` might increase the size of the object layout.

Yeah, I'll try to report, but anyway we need to fix second problem, type of object passed as mdcMap to `LoggingEventWrapper` needs to be changed from `RequestContextExporter$State` to one of java.util classes like `java.util.HashMap`.
I'm not feeling well by deleting UnionMap, but I don't know how to do it better.

**Comment by Yuri999** [comment]
> Would you possibly point to the code where `InvalidClassException: Unauthorized deserialization attempt in HardenedObjectInputStream` is raised?
Yes.

**Comment by Yuri999** [comment]
logback PR https://github.com/qos-ch/logback/pull/614

**Comment by ikhoon** [comment]
> After fixing that issue we will get InvalidClassException: Unauthorized deserialization attempt in HardenedObjectInputStream.

It seems `HardenedObjectInputStream` is used only in socket-related appenders. It is a hacky way but How about using `HashMap` when `ch.qos.logback.core.net.AbstractSocketAppender` is set to via `addAppender()`?
https://github.com/line/armeria/blob/c34c6b54cbfaa0e911afad8d712294a93e75a17f/logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java#L231-L233
Otherwise, I prefer to use `UnionMap` so that we can avoid additional copies and object allocations if possible.

**Comment by Yuri999** [comment]
I've made some modifications in https://github.com/line/armeria/pull/4547
https://github.com/line/armeria/pull/4547/files#diff-9fa67c54d226011cc5fb45912fac54de63c87c2669e64a25c48c41a65bb75a19R229
@ikhoon, could you check please?

**Comment by ikhoon** [comment]
Thanks. I will review it today.
