### ISSUE TITLE
`SameSite=Strict` is a too strict default for `Cookie.secureBulider`

### ISSUE THREAD

**Issue by ks-yim** [line/armeria#4550]
Armeria's default cookie builder is `Cookie.secureBuilder` and it sets `SameSite` attributes to `Strict` by default.

I understand the motivation of this change was to make users explicitly opt-out cookie's security attributes as stated in  https://github.com/line/armeria/issues/3788, but I wish `SameSite=Lax` were the default because `SameSite=Strict` comes at a very serious UX tradeoff, while `SameSite=Lax` provides just enough security benefits.

Cookies with `SameSite=Strict` are not sent to the original site even when users are directed to the site with top-level navigation from off-site (by clicking `<a>` tag), and this indicates that those users will see the content as if they were not logged in to the original site even if they were logged in before.

Though `SameSite=Lax` are exposed to following attack vectors when compared to `SameSite=Strict`
* CSRF with state changing `GET`
* Guessing by timing attack as stated in [this stackoverflow thread](https://stackoverflow.com/questions/41841880/what-is-the-benefit-of-blocking-cookie-for-clicked-link-samesite-strict)

... the limited benefit of gaining protection against such attack vectors is too small to justify the UX trade-off in almost all scenarios, which makes me believe `SameSite=Lax` is a better default.

**Comment by minwoox** [comment]
Thanks for the opinion. 😄 
Yeah, I agree with you on requiring users to opt-out of the security attributes is more reasonable.
Also, the builder's name has `secure` in it. 😆

**Comment by ikhoon** [comment]
`SameSite=Lax` is the default value for modern browsers. I agree `SameSite=Lax` gives better UX  that makes webpages correctly render users information with href links.

The default of `secureBuilder` explicitly overrides some options to provide stricter security and Javadoc clearly describes what values are set. I believe there is no confusion about that. So I also prefer keeping the current behavior as is.

**Comment by ks-yim** [comment]
Thanks for taking your time to review this issue.

Yeah, it looks just good the way it is now.

The deprecation warning of `Cookie.builder()` and the fact that I was forced to ise `Cookie.secureBuilder()` felt a bit awkward at the time of the first writing because I am basically doing the following when I opt-out SameSite attribute (which is trivial😅..):
```java
new CookieBuilder(name, value)
    .secure(true)
    .httpOnly(true)
    .sameSite("Strict")
    .sameSite("Lax");
```
Anyways, no objection any more as I’ve stated above! I will close the issue.
