### ISSUE TITLE
Support `ManagementServerProperties` fully

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4560]
Users can set a port for actuator using property:
```
management.server.port=8081
```
and Armeria only support the port property:
https://github.com/line/armeria/blob/948763acc7911c951e37dbd35132edd253ea3934/spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java#L254

However, `ManagementServerProperties` has other properties such as `address`, `basePath`, and `ssl`. We also need to support that.

**Comment by kojilin** [comment]
Will make PR for this

**Comment by kojilin** [comment]
Curious about ssl setting.   
Have tried a a little with `armeria.ssl` and `management.server.ssl`. Looks like. 
1.  `ServerBuilder` can't set different ssl context for different port? So if we set `armeria.ssl`, we may need to ignore `management.server.ssl`?
2. `management.server.ssl` may become defaultSslContext if there is no `armeria.ssl` ?

**Comment by minwoox** [comment]
Thanks for taking a look into this issue. 😄 
Because we cannot set different ssl context for different port, I'm leaning toward just ignoring the SSL setting in the management property and leaving a warning log that tells users to use armeria property.

**Comment by minwoox** [comment]
>  I'm leaning toward just ignoring the SSL setting in the

I realized that we can create a virtual host with the address and port. I left my comment here:
https://github.com/line/armeria/pull/4563#discussion_r1045406194
