### ISSUE TITLE
[gRPC client question] how to compute checksum and add it to request header 

### ISSUE THREAD

**Issue by Lincong** [line/armeria#4586]
## Setup
I am using Armeria version: 1.16.0 and trying to build a feature on the gRPC client to compute a checksum and send it to the server side for validation.

## Requirement
Specifically, I am trying to make the client compute a checksum from the serialized request (Protocol Buffer object) bytes and then put the computed checksum in the request header. On the server side, before it deserializes received request bytes, it computes another checksum from received bytes, extracts the client-side-computed checksum from the header, and compares 2 checksums.

On the client side, I tried to use a decorator as shown below:

```scala
clientBuilder.decorator((delegate, ctx, req) => {
    val newReq = req.mapData(data => {
        val checksum = // Compute checksum
        ctx.addAdditionalRequestHeader(someKey, checksum) // Try to put the checksum in the request header
        return data
    })
    delegate.execute(ctx, newReq)
})
```

## Problem
In the above code example, I think the `mapData` callback is executed after the request headers have been sent so that `ctx.addAdditionalRequestHeader(...)` is actually an no-op. As a result the server side receives a request header without the `someKey, checksum` entry in it. I verified this behavior by using my (IntelliJ) debugger.

I have also tried a few other approaches (still using the decorator). For example, one other thing I tried is to use:
```scala
ctx
 .log()
 .whenAvailable(RequestLogProperty.XXX)
 .thenAccept(/* compute the checksum here */)
```
The problem here is that there is no `RequestLogProperty.XXX` that maps to serialized/binary request content. The closest I could find is `RequestLogProperty.REQUEST_CONTENT`. However, a Protocol Buffer object (instead of its serialized bytes) is passed to the `thenAccept` callback. In order to compute checksum, I need serialized bytes instead of a Protocol Buffer object. Technically I can serialize the object inside the `thenAccept` callback and then compute the checksum. But it is a waste of CPU to serialize each request twice >.<

## Question
1. Are my observations and understanding above (in the `Problem` section) correct?
2. What is the best way to implement this feature (mentioned in the `Requirement` section)?

Thanks!

**Comment by minwoox** [comment]
> Are my observations and understanding above (in the Problem section) correct?

That is correct. `mapData` is called after the `RequestHeaders` is sent.

> What is the best way to implement this feature (mentioned in the Requirement section)?

If this is only going to be used for unary calls, aggregating the request and computing the checksum is the way to go:
```java
.decorator((delegate, ctx, req) -> {
  return req.aggregate().thenAccept(aggregatedReq ->  {
      final HttpRequest newReq = aggregatedReq.toHttpRequest(checksum(aggregatedReq.content()));
      ctx.updateRequest(newReq);
      return delegate.execute(ctx, newReq);
  });
})

RequestHeaders checksum(HttpData data) {...}
```

However, as you might notice, it's now going to work for streaming because we must not aggregate the streaming request. If so we should use trailers to store the computed checksum.

We can also generalize to use trailers for both cases (unary and streaming) if we are using HTTP/2.
However, if we use HTTP/1.1 between the client and server it's not going to work because we have to use chunked encoding to send trailers: https://www.rfc-editor.org/rfc/rfc9110.html#section-6.5.1
(We can manipulate our clients to use chunked encoding when trailers are set but we need extra work for that.)

**Comment by Lincong** [comment]
Hi @minwoox , thanks for sharing the helpful information!

I tried the code example you shared and encountered below issues:

1. The required return type of the `callback 1` below is `com.linecorp.armeria.common.HttpResponse` whereas the returned type of `req.aggregate().thenAccept( ... )` is `java.util.concurrent.CompletableFuture[Void]`. So it does not compile.

```scala
(delegate, ctx, req) -> {/* callback 1 */}
```

2. I did not find a `AggregatedHttpRequest#toHttpRequest` method that takes `RequestHeaders` as an input parameter. So, I did the below instead:
```scala
        val newHeaders = oldHeaders.toBuilder
          .add(/* checksum header entry */)
          .build()
        val newReq = HttpRequest.of(newHeaders, aggregatedReq.content())
```

Let me know if I misunderstand anything. Thanks!

**Comment by minwoox** [comment]
> The required return type of the callback 1 below

Oops, sorry about it. We need to use `HttpResponse.from(...)` Let me also edit the original response.

> I did not find a AggregatedHttpRequest#toHttpRequest method 

Oops, it's added from 1.20.0. 😓  https://github.com/line/armeria/pull/4441
The snippet you pasted also works. Let's use that. 😄

**Comment by Lincong** [comment]
Thanks @minwoox for your help! I managed to get it work with your edited code example!

A follow-up questions regarding:
> We can also generalize it by using trailers for both cases (unary and streaming) if we are using HTTP/2.
We are using HTTP/2. I am sure it is possible to add trailers to a response from server to client. Is it possible to add trailers to a request sent from the client to server? If so, could you share some code examples or point me to some docs?

Merry Christmas!

**Comment by minwoox** [comment]
Merry Christmas! 😄 

> Is it possible to add trailers to a request sent from the client to server?

There's no simple and easy way before we implement this: https://github.com/line/armeria/issues/4587
Before that we can just wrap the request with the custom class:
```java
.decorator((delegate, ctx, req) -> {
    final HttpRequest newReq = new HttpRequestWithChecksum(req);
    ctx.updateRequest(newReq);
    return delegate.execute(ctx, newReq);
})


private static final class HttpRequestWithChecksum implements HttpRequest {

    private final HttpRequest delegate;

    HttpRequestWithChecksum(HttpRequest delegate) {
        this.delegate = delegate;
    }

    @Override
    public RequestHeaders headers() {
        return delegate.headers();
    }

    @Override
    public boolean isOpen() {
        return delegate.isOpen();
    }

    @Override
    public boolean isEmpty() {
        return delegate.isEmpty();
    }

    @Override
    public long demand() {
        return delegate.demand();
    }

    @Override
    public CompletableFuture<Void> whenComplete() {
        return delegate.whenComplete();
    }

    @Override
    public void subscribe(Subscriber<? super HttpObject> subscriber, EventExecutor executor,
                          SubscriptionOption... options) {
        delegate.subscribe(new ChecksumAddingSubscriber(subscriber), executor, options);
    }

    @Override
    public void abort() {
        delegate.abort();
    }

    @Override
    public void abort(Throwable cause) {
        delegate.abort(cause);
    }

    private static final class ChecksumAddingSubscriber implements Subscriber<HttpObject> {

        private final Subscriber<? super HttpObject> subscriber;

        ChecksumAddingSubscriber(Subscriber<? super HttpObject> subscriber) {
            this.subscriber = subscriber;
        }

        @Override
        public void onSubscribe(Subscription s) {
            subscriber.onSubscribe(s);
        }

        @Override
        public void onNext(HttpObject httpObject) {
            // Store the stream of httpObjects or calculate checksum in realtime.
            subscriber.onNext(httpObject);
        }

        @Override
        public void onError(Throwable t) {
            subscriber.onError(t);
        }

        @Override
        public void onComplete() {
            String checksum = ...;
            subscriber.onNext(HttpHeaders.of("X-checksum", checksum));
            subscriber.onComplete();
        }
    }
}
```

**Comment by Lincong** [comment]
Thanks @minwoox for providing the above code example! It is helpful for me to understand how I could apply the Decorator pattern with Armeria interfaces (`HttpRequest` and `Subscriber`).

Does this approach work with gRPC streaming request? I guess it should work if we append a 4-byte checksum to each streamed message in the streaming request and the server parses out the last 4 bytes of each received message as a checksum. 

Let me know if my understanding is correct. Thanks!

**Comment by minwoox** [comment]
> IIUC this new approach (appending checksum bytes at the end of each HTTP request body bytes) is more efficient than the first approach which uses req.aggregate(), right?

I didn't mean it. 😅 What I was trying to implement was calculating the checksum of an `HttpData` and sending the checksum using trailers.

> Does this approach work with gRPC streaming request?

So each streaming message has to have a checksum, right? If so, I think we have two options.
- Adding a checksum field to the message
- Framing `HttpData` with checksum and deframing the `HttpData` on the server-side.

For the first option we can do:
```
// Define message with a checksum
message SimpleRequestWithChecksum {
  SimpleRequest simple_request = 1;
  int32 checksum = 2;
}

// Java code 
SimpleRequest req = ...
int checksum = checksum(req.toByteArray());
SimpleRequestWithChecksum.newBuilder()
                         .setSimpleRequest(req)
                         .setChecksum(checksum)
                         .build();
```
With this option, we cannot use a decorator but have to check the integrity in the services.

For the second option we have to recreate the `HttpData` in the decorator with the new length that includes the original data and checksum:
----------------------+-----------------+----------------------
| new Length(4 bytes)  | original HttpData  | checksum (4 bytes) |
----------------------+-----------------+----------------------
Because newly organized `HttpData`s are sent to the services, we also have to add a decorator on the server side that deframes and restores the original `HttpData`.

**Comment by Lincong** [comment]
Got it, thanks @minwoox !

If you don't mind, I will keep this issue open for 1 more week in case I have more questions. Otherwise, I will close it in a week.

**Comment by minwoox** [comment]
Yeah, please let us know if you have more questions. 😄

**Comment by Lincong** [comment]
Hi @minwoox , I have another question.

In the example code you provided (shown below), is the `onNext` method guaranteed to be called once for each unary request? 

Could it be the case where the unary request message is very large so that its bytes are divided into multiple chunks and `onNext` is called once for each chunk? What exactly determines how many times the `onNext` method is called for a unary/streaming request?

```java
    private static final class ChecksumAddingSubscriber implements Subscriber<HttpObject> {

        private final Subscriber<? super HttpObject> subscriber;

        ChecksumAddingSubscriber(Subscriber<? super HttpObject> subscriber) {
            this.subscriber = subscriber;
        }

        @Override
        public void onSubscribe(Subscription s) {
            subscriber.onSubscribe(s);
        }

        @Override
        public void onNext(HttpObject httpObject) {
            // Store the stream of httpObjects or calculate checksum in realtime.
            subscriber.onNext(httpObject);
        }

        @Override
        public void onError(Throwable t) {
            subscriber.onError(t);
        }

        @Override
        public void onComplete() {
            String checksum = ...;
            subscriber.onNext(HttpHeaders.of("X-checksum", checksum));
            subscriber.onComplete();
        }
    }
```

**Comment by minwoox** [comment]
> so that its bytes are divided into multiple chunks and onNext is called once for each chunk?

It could be divided into multiple chunks so `onNext` can be called multiple times. 
That's why we need a new frame:
----------------------+-----------------+----------------------
| new Length(4 bytes) | original HttpData | checksum (4 bytes) |
----------------------+-----------------+----------------------

**Comment by Lincong** [comment]
Thanks @minwoox for the clarification. By `add logic for the framing`, do you mean adding logic on the server side to interpret/de-frame the new format (shown below) so that the server knows which part is checksum and which part is serialized message bytes?

```
----------------------+-----------------+----------------------
| new Length(4 bytes) | original HttpData | checksum (4 bytes) |
----------------------+-----------------+----------------------
```

**Comment by ikhoon** [comment]
> 2. IIUC this new approach (appending checksum bytes at the end of each HTTP request body bytes) is more efficient than the first approach which uses req.aggregate(), right? I think using req.aggregate() delays the sending of HTTP request headers to the server side because it has to wait for the HTTP request body as well.

It depends on `ClientRequestContext.exchangeType()`. If `ExchangeType.UNARY` or `ExchangeType.RESPONSE_STREAMING` is used or inferred, the request is aggregated always by `AggregatedHttpRequestHandler`. As a result, `req.aggregate()` in a decorator with may have a small amount of overhead with non-streaming requests. The aggregation cost just moves to the decorator.

As per https://www.ietf.org/archive/id/draft-ietf-httpbis-digest-headers-10.html#name-client-and-server-provide-f, it is compatible to send a digest field to headers so it makes more sense to compute a hash and attach it to the headers. 

> 2. Does this approach work with gRPC streaming request? I guess it should work if we append a 4-byte checksum to each streamed message in the streaming request and the server parses out the last 4 bytes of each received message as a checksum.

As you know, it is a custom protocol that could be used only with custom clients and servers that are able to interpret the format. I recommend set a digest field to the trailers for the entire data when a streaming request is used. It does not transform the original content so some arbitrary servers that do not know the format may ignore digest headers.
https://www.ietf.org/archive/id/draft-ietf-httpbis-digest-headers-10.html#name-use-with-trailer-fields-and

**Comment by minwoox** [comment]
Yeah, if there's no particular reason for adding checksums to each chunk, we can just use the trailers to send the checksum of whole messages.

**Comment by Lincong** [comment]
Thanks @ikhoon for providing the helpful information.

> set a digest field to the trailers for the entire data when a streaming request is used.

Currently gRPC wire format is `Request-Headers *Length-Prefixed-Message EOS`. In the case of streaming request, there will be multiple `Length-Prefixed-Message`. Are you suggesting appending a trailer to every `Length-Prefixed-Message` so that it becomes `Request-Headers *(Length-Prefixed-Message + Trailer) EOS` or appending one trailer to the end of the whole streaming request `Request-Headers *Length-Prefixed-Message Trailer EOS`?

The concern with the later one is that the server side does not get the checksum until all streamed messages are received. We hope to make the server validate the checksum before trying to deserializing any message. That means the server has to buffer all received streaming messages which is not practical.

**Comment by ikhoon** [comment]
>  appending one trailer to the end of the whole streaming request Request-Headers *Length-Prefixed-Message Trailer EOS

This one. I thought of adding HTTP/2 trailers to the request level.

**Comment by Lincong** [comment]
I am closing this issue since I don't have any further question at this point. Thanks a lot for the help!
