### ISSUE TITLE
any service discovery policy for armeria

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#459]
Hi guys,
is there any solution for service discovery strategy for armeria, OR can it integration with spring boot?

**Comment by trustin** [comment]
Armeria has a ZooKeeper-based service registration and discovery:

https://github.com/line/armeria/blob/master/site/src/sphinx/zookeeper.rst

It basically implements `EndpointGroup` API which is part of the core API. You can also extend it to integrate with other frameworks such as Spring for sure.
