### ISSUE TITLE
How to set timeout for `gRPC` `BindableService` for each method individually?

### ISSUE THREAD

**Issue by Dogacel** [line/armeria#4594]
We are trying to set timeout for each endpoint individually for a `BindableService`. Our use case is that some endpoints are `streaming` and some are `unary` and we want to make sure `streaming` endpoints have much higher timeout times.

I have seen [this](https://armeria.dev/docs/server-sse/#adjusting-the-request-timeout) example for SSE but I am not sure how we can do the same thing for `gRPC` bindable service.

**Comment by minwoox** [comment]
Hi! With 1.21.0, we can add `@RequestTimeout` annotation to the class or method.
With the earlier versions of 1.21.0, we can add a decorator that sets timeout for the service. 
https://github.com/line/armeria/blob/c888c86b288e85bb489b2938f2498095b2303e55/grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java#L237

**Comment by Dogacel** [comment]
@minwoox Thanks for the explanation. I have seen that `@RequestTimeout` decorator but I thought it was only for annotated services because of how the tests were constructed. Should we add this to the documentation for other users?

**Comment by ikhoon** [comment]
> Should we add this to the documentation for other users?

It is a good idea. We could add similar documentation like https://armeria.dev/docs/client-timeouts for the server side.
