### ISSUE TITLE
(Feature Request) Support `ExceptionHandler` decorator

### ISSUE THREAD

**Issue by Dogacel** [line/armeria#4604]
# Description
The current implementation of the `ExceptionHandler` for annotated HTTP services looks pretty good. I have found the following issue for rpc-based services:
- #2044

The answer [here](https://github.com/line/armeria/issues/2044#issuecomment-740466828) is more than enough but I think we can still add a decorator for
1. Specialized exception handling per method/service.
2. Separation of concern and consistency.

This topic is similar to rate limiting, timeouts, or logging. Each has a default setting and can be changed from `ServerBuilder` or `GrpcService`. But I think it makes more sense to see them in the actual controller implementations using decorators.

For specialized exception handling, I think the following cases make sense:
- The same exception can mean different things for different endpoints. (E.g. `IOException` can mean both an invalid parameter, internal error, or not found).
- We might want to hide some important endpoints by returning `Not found` instead of `Unauthorized`. (E.g. if there are path parameters)

# Example use cases

```kotlin
@ExceptionHandlerDecorator(ExceptionHandlerFunction::class)
```

or 

```kotlin
@ExceptionMappingDecorator(IllegalArgumentException::class, Status.UNAUTHENTICATED)
```

It could be nice to add some specialized information from `exception.message` if possible too.

**Comment by jrhee17** [comment]
> I think it makes more sense to see them in the actual controller implementations using decorators.

I think this makes sense 👍 

Although annotated services already utilize an `@ExceptionHandler` decorator which serves a similar purpose, I guess it is difficult to unify since:
1) the method signature is different from `GrpcStatusFunction`.
2) the timing at which each exception handler is called is different anyways.

I suppose it makes sense that a new annotation is created specifically for grpc services e.g. `@GrpcExceptionHandler`.

```java
@Repeatable(GrpcExceptionHandlers.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE, ElementType.METHOD })
public @interface GrpcExceptionHandler {

    Class<? extends GrpcStatusFunction> value();
}
```

Having said this, I would like to also get an opinion from the other maintainers before anyone starts working on this.

**Comment by ta7uw** [comment]
I'm interested in this feature.
May I work on developing `GrpcExceptionHandler`?

**Comment by jrhee17** [comment]
> Having said this, I would like to also get an opinion from the other maintainers before anyone starts working on this.

Sorry about the late reply 😄   Let me bring up the API design with the other maintainers before you start working on it

**Comment by jrhee17** [comment]
Sorry about the wait 😅    I think the general direction will be in the following format.

```java
@GrpcExceptionHandler(GrpcExceptionHandlerFunction.class)
```

**Comment by ta7uw** [comment]
Thanks for checking.
Let me work on this.
