### ISSUE TITLE
Remove `[]` from allowed path chars

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4607]
`[` and `]` are added as allowed path chars.
https://github.com/line/armeria/blob/55504bdf4f09b05adf07a16a076ec28e3fbfccf4/core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java#L68-L69
According to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) the valid characters for the path component are:
```
a-z A-Z 0-9 . - _ ~ ! $ & ' ( ) * + , ; = : @
```

**Comment by minwoox** [comment]
😱
