### ISSUE TITLE
Return "431 Request Header Fields Too Large" when the header value exceeds

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4609]
Netty HTTP/1 codec raises `TooLongHttpHeaderException` if headers exceed the max length limit.
However, `Http1RequestDecoder` only checks `TooLongHttpLineException` and returns "414 Request-URI Too Long". Otherwise, "400 Bad Request" is returned.
https://github.com/line/armeria/blob/d9d9d3ea16efb17d24b9935885fd2a2b4da25aa9/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L179-L183

It would make sense to return `431 Request Header Fields Too Large` when `TooLongHttpHeaderException` is raised.

**Comment by daniel-itunu** [comment]
> Request Header Fields Too Large

would this be a good fix? @ikhoon 
`if (cause instanceof TooLongHttpLineException) {
                            fail(id, null, HttpStatus.REQUEST_URI_TOO_LONG, "Too Long URI", cause);
                        } else if (cause instanceof TooLongHttpHeaderException) {
                            fail(id, null, HttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE, "Request Header Fields Too Large", cause);
                        } else {
                            fail(id, null, HttpStatus.BAD_REQUEST, "Decoder failure", cause);
                        }`

**Comment by ikhoon** [comment]
Right, it was what I thought.
