### ISSUE TITLE
Provide easier way to include google error details to response in GrpcStatusFunction

### ISSUE THREAD

**Issue by mscheong01** [line/armeria#4614]
Motivation:
currently, Users define method `io.grpc.Status apply(RequestContext ctx, Throwable throwable, Metadata metadata);` of `GrpcStatusFunction` to customize gRPC error responses.
Also, armeria supports google error formats by checking the grpc-status-details-bin trailer.
While this trailer is automatically set when throwing a `io.grpc.StatusException` created from `com.google.rpc.Status`,
i.e)
```java
throw StatusProto.toStatusException(
    Status.newBuilder()
        .setCode(1)
        .setMessage("some_message")
        .addDetails(
            Any.pack(
                BadRequest.newBuilder()
                    .addFieldViolations(
                        BadRequest.FieldViolation.newBuilder()
                            .setDescription("some_description")
                            .build()
                    )
                    .build()
            )
        )
);
```
It is not easy to include details from `GrpcStatusFunction` because io.grpc.Status does not know of grpc-status-details.
there is a workaround that I am currently using:
```java
class CustomExceptionHandler implements GrpcStatusFunction {
    @Override
    Status apply(RequestContext ctx, Throwable throwable, Metadata metadata) {
        StatusException statusException = StatusProto
                                            .toStatusException(
                                                Status.newBuilder()
                                                    .setCode(1)
                                                    .setMessage("some_message")
                                                    .addDetails(
                                                        Any.pack(
                                                            BadRequest.newBuilder()
                                                                .addFieldViolations(
                                                                    BadRequest.FieldViolation.newBuilder()
                                                                        .setDescription("some_description")
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                    )
                                            );
        metadata.merge(statusException.trailers);
        return Status.fromThrowable(statusException);
    }
}
```
which explicitly sets the grpc-status-details-bin trailer to the metadata, but this requires prior knowledge of how grpc status details work.
Can we make some changes to make this easier?

Suggestions:
1. make GrpcStatusFunction return a armeria-native Status, which contains a field about grpc status details and could be converted to io.grpc.Status
2. create a GoogleGrpcStatusFunction that instead of io.grpc.Status, returns a com.google.rpc.Status for its apply method. then, add a convert method to GrpcStatusFunction which sets the required trailers to metadata while converting.

etc

**Comment by ikhoon** [comment]
I prefer `GoogleGrpcStatusFunction`. As you imagined, it would be not only the simplest idea but also customizable.
```java
public interface GoogleGrpcStatusFunction extends GrpcStatusFunction {
    @Override
    @Nullable
    default Status apply(RequestContext ctx, Throwable throwable, Metadata metadata) {
        final com.google.rpc.Status statusProto = applyStatusProto(ctx, throwable, metadata);
		if (statusProto == null) {
            return null;
        }

        final Status status = Status.fromCodeValue(statusProto.getCode())
                                    .withDescription(statusProto.getMessage());
        metadata.put(STATUS_DETAILS_KEY, statusProto);
        return status;
    }

    com.google.rpc.Status applyStatusProto(RequestContext ctx, Throwable throwable, Metadata metadata);
}
```
It might be worth adding to the grpc module.

**Comment by minwoox** [comment]
`GoogleGrpcStatusFunction` looks awesome. 👍

**Comment by trustin** [comment]
We also need to make sure it's allowed to throw `StatusRuntimeException` created from `StatusProto.toStatusRuntimeException()` to add error details, as shown in [this SO answer](https://stackoverflow.com/a/67763163).

**Comment by ta7uw** [comment]
I'm interested in this feature.
May I start working on it?

**Comment by ikhoon** [comment]
Sure 🥰
