### ISSUE TITLE
Add support for Micrometer Observation

### ISSUE THREAD

**Issue by marcingrzejszczak** [line/armeria#4659]
I'm a co-maintainer of Spring Cloud Sleuth and Micrometer projects (together with @shakuzen and @jonatan-ivanov).

[Micrometer Observation](https://micrometer.io/docs/observation) is coming as part of the Micrometer 1.10 release and [Micrometer Tracing](https://micrometer.io/docs/tracing) is a new project. The idea of Micrometer Observation is that you instrument code once but you get multiple benefits out of it - e.g. you can get tracing, metrics, logging or whatever you see fit).

Since this project already supports Micrometer I was curious if there's interest in adding Micrometer Observation support so that except for metrics, spans could be created and tracing context propagation could happen too. 

If there's such interest we could provide a PR to add support for that.

**Comment by jrhee17** [comment]
> I was curious if there's interest in adding Micrometer Observation support so that except for metrics, spans could be created and tracing context propagation could happen too

Thanks!  I'll have to take a closer look into [Micrometer Observation](https://micrometer.io/docs/observation), [Micrometer Tracing](https://micrometer.io/docs/tracing) to see how this can be integrated, but I think we're definitely open to adding Micrometer Observation support 👍
