### ISSUE TITLE
HttpServerTest.testTimeout flaky

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#467]
Had this failure happen on a build, rebuild with no code change fixed.

```
:shaded-test:shadedCoreTest[jetty-alpn-agent] Using: alpn-boot-8.1.10.v20161026.jar
com.linecorp.armeria.server.http.HttpServerTest > testTimeout[1: h1] FAILED
    java.lang.AssertionError: 
    Expected: is <503>
         but: was <200>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.linecorp.armeria.server.http.HttpServerTest.testTimeout(HttpServerTest.java:407)
```

**Comment by trustin** [comment]
This is interesting. The client received '503 Service Unavailable` but `requestLog` (server) reported 200. Any chance to reproduce it?

**Comment by anuraaga** [comment]
Unfortunately haven't reproduced, have only seen it that one time so far. But wanted to record it for tracking

**Comment by anuraaga** [comment]
Ran into this again on Travis

https://travis-ci.org/line/armeria/builds/220914363

**Comment by trustin** [comment]
This is now the most frequent cause of failure. Will investigate soon.
