### ISSUE TITLE
Add documentation for Spring Boot integration

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4670]
We don't have detailed documenations how Spring Boot integration works and how to customize services and settings.
Here are some of them we need to explain:
- [ArmeriaSettings](https://github.com/line/armeria/blob/76c50fe8238525fab7180b51c0de8422e6526e13/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java#L77)
- [Beans](https://github.com/line/armeria/blob/39efeb240b95c8969c81e94eca8ed07f1f4026df/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java#L70-L75) that users can provide.
- [InternalServices](https://github.com/line/armeria/blob/7626562204bd4311a1205df9d733203324355a96/spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/InternalServices.java#L48)

**Comment by ikhoon** [comment]
> Is this documentation intended for developers looking to migrate from existing Spring applications to Armeria or for developers interested in utilizing Armeria and Spring together from scratch?

As a rule of thumb, I think, most Armeria users who use Spring integration already know Spring technology. They may want to migrate or integrate their legacy code with Armeria.
