### ISSUE TITLE
Add metrics about `EventLoop`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4675]
Micrometer does not support metrics for Netty's `EventLoop`. https://github.com/micrometer-metrics/micrometer/issues/522
We may add our custom metrics for `EventLoop`.
- Number of `EventLoop`s
- Number of pending tasks.
- ...

**Comment by seonwoo960000** [comment]
This looks interesting. May I try on this issue ?

**Comment by seonwoo960000** [comment]
Looks interesting. If no one's assigned, may I look into the issues ?

**Comment by ikhoon** [comment]
For sure. Thanks for your interest. 😀

**Comment by vkostyukov** [comment]
Checking to see if I missed a PR addressing this ticket? We need something like this internally so I wanted to build something ad-hoc. @seonwoo960000 are you actively working on it?

**Comment by seonwoo960000** [comment]
Hi @vkostyukov ! I'm not currently working on this and I think you can first work on this issue.

**Comment by vkostyukov** [comment]
Thanks! I will grab this!

**Comment by vkostyukov** [comment]
Got a PR here: #4750 4750
