### ISSUE TITLE
Add StreamMessage.flatMapSequential() 

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4678]
that is similar to [`StreamMessage.flatMap`](https://github.com/line/armeria/pull/4227) but produces the elements sequentially.

**Comment by sleeplesslord** [comment]
I'm interested in doing this one once I finish up flatMap 🙂

**Comment by minwoox** [comment]
Thanks, @sleeplesslord! 😄

**Comment by minwoox** [comment]
I see. Let me finish reviewing #4227 if there're any optimization points.

**Comment by minwoox** [comment]
Yes, it turned out to be that we can just use the flatMap. 😓 
There are not so many optimization points. The `buffer` isn't going to be used anyway when `maxConcurrency == 1`. 
So let's just close this issue. 😄
