### ISSUE TITLE
Support web proxy

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4681]
A user might want to use an Armeria server as a web proxy that forwards a request to the server whose URL is specified in the path.
For example, if a request is
```
GET https://en.wikipedia.org/wiki/Proxy_server HTTP/1.1
```
, then the Armeria server forwards the request to `https://en.wikipedia.org/`.

In order to support this, we might need to
- Allow a full path in the path
- Add a special HTTP service that handles those proxy requests

https://en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers

**Comment by wu-sheng** [comment]
Thanks for opening this. I am going to follow this to see whether this is accepted by Armeria team.

**Comment by trustin** [comment]
Looks like HTTP/2 `:path` header represents only an absolute path. Given that our API model always normalizes the request into HTTP/2, `RequestHeaders.path()` is not able to have a full URI.

What do you think about adding a configuration option that replaces the given request URI string before we start any validation? We could allow a user to perform a string transformation that turns an absolute URI into a path:

```java
Server
  .builder()
  .absoluteUriTransformer(absoluteUri -> "/web_proxy?uri=" + encodeURI(absoluteUri))
  ...
```

Then, a user could bind a service at `exact:/web_proxy` to handle it properly. If unspecified, the server will simply respond with 400 Bad Request.

What do you think, @wu-sheng and @minwoox ?

**Comment by wu-sheng** [comment]
This should be good enough. We could ask users to provide domain name(path prefix) to replace.

cc @pg-yang

**Comment by wu-sheng** [comment]
Created https://github.com/apache/skywalking/issues/10520 to track this. Will update accordingly after your release.

**Comment by wu-sheng** [comment]
Final update. We have upgrade to 1.23.1 for this.
SkyWalking 9.5 would include this to support AWS firehose channel in no-proxy mode. Thanks so much for the support.
