### ISSUE TITLE
I must use thrift?

### ISSUE THREAD

**Issue by VicBing** [line/armeria#469]
I must use thrift if i want to use armeria in my production? Is there any example shows how to use armeria for dev microservices?

**Comment by trustin** [comment]
You don't have to use Thrift when writing your service with Armeria. Thrift is an optional component. You can build a plain HTTP clients and services as easily as building Thrift clients and services.

For client-side, see: 
- http://line.github.io/armeria/client-http.html
- http://line.github.io/armeria/client-http-retrofit.html (Retrofit2 integration)

For server-side, see:

- http://line.github.io/armeria/server-http-file.html (serving static files)
- The API documentation of DynamicHttpService: https://line.github.io/armeria/apidocs/com/linecorp/armeria/server/http/dynamic/package-summary.html
  - and HttpServiceTest https://github.com/line/armeria/blob/master/core/src/test/java/com/linecorp/armeria/server/http/HttpServiceTest.java (Sorry that it's not well documented.)

Please let me know what you think. What more is needed, what's lacking, etc.

**Comment by VicBing** [comment]
I want use armeria to：
1.Integration with archaius2 for configuration management
2.Integration with zipkin for tracing
３．Integration with etcd for Service registration and discovery
Any suggestions for how to do this?

**Comment by trustin** [comment]
- Archaius integration - I'm not sure what configuration properties you are going to store but you could just use a well known Archaius client in the market. Armeria itself doesn't provide the integration with it.
- Zipkin integration - Yes, Armeria integrates with Zipkin. Please see `HttpTracingClient` and `HttpTracingService`.
- Etcd integration for service registration and discovery - Armeria provides the integration with ZooKeeper for service registration and discovery. You can implement `EndpointGroup` to implement Etcd integration. i.e. There's no out-of-the-box integration, but it should be trivial to write one. (Interested in sending a PR?)

**Comment by VicBing** [comment]
I am newly to microservices, it a little diffcult for me @_@. 

thanks for you suggestions.

**Comment by trustin** [comment]
@VicBing My pleasure. Thanks for asking questions. Please feel free to let us know about your decisions. We'd be happy to hear that you ended up using Armeria, but it's fine even if that was not the case. Please just let us know what was missing in Armeria or what you did not like about it, so we can fix them. ❤️
