### ISSUE TITLE
Provide a way to set the number of attempts to decide whether to warn or not when DNS query failed

### ISSUE THREAD

**Issue by ta7uw** [line/armeria#4690]
I occasionally see the following warning
`DNS query failed; retrying in {} ms (attempts so far: 1)`

This warning is important when we make DNS query for the first time.
However, considering retrying,  I guess that it is not so important when making DNS query due to TTL expiration.

How about setting the number of attempts to decide whether outputting the warning for queries due to TTL expiration?

**Comment by ikhoon** [comment]
It is a good suggestion. Many people may not be interested in warning messages for retrying expired records.

However, I'm not sure it is a general solution for various cases. Some users may want to warn about certain exceptions for the first time.
What do you think of adding an event listener for DNS records?
```java
interface DnsQuestionListener {
    void onSuccess(@Nullable List<DnsRecord> oldRecords, List<DnsRecord> newRecords);

    // Default implementation of this would warn for all failures.
    void onFailure(@Nullable List<DnsRecord> oldRecords, Throwable cause, int attemptsSoFar);
}
```

**Comment by ta7uw** [comment]
It seems better.

**Comment by ta7uw** [comment]
I'm going to work on this feature.
