### ISSUE TITLE
Unencoded square brackets are not correctly handled at server-side

### ISSUE THREAD

**Issue by jrhee17** [line/armeria#4694]
Armeria clients correctly encode square brackets when sending requests.
However, some browsers and `curl` seem to send requests without encoding square brackets which is a violation of the [rfc](https://www.ietf.org/rfc/rfc3986.txt))

When an armeria server receives a request where the URI contains unencoded square brackets, the request is processed normally.
However, when `request.uri()` is invoked, Java's `java.net.URI()` is invoked.
Because square brackets are not allowed in `java.net.URI`'s implementation, an exception occurs.

```
java.lang.IllegalStateException: not a valid URI: http://localhost:57893/uri-valid/[...foobar]
    at com.linecorp.armeria.common.HttpHeadersBase.uri(HttpHeadersBase.java:214)
    at com.linecorp.armeria.common.DefaultRequestHeaders.uri(DefaultRequestHeaders.java:46)
    at com.linecorp.armeria.common.HttpRequest.uri(HttpRequest.java:299)
    at com.linecorp.armeria.client.BlockingWebClientTest$1.lambda$configure$4(BlockingWebClientTest.java:62)
```

This is a surprise since a user would assume a request is valid if the service was invoked.
We may either:
1. Check for unencoded characters when `HttpRequest#uri` is invoked
2. Just reject requests with invalid paths/headers to begin with

ref: https://line-armeria.slack.com/archives/C1NGPBUH2/p1676961228194539
reproducer: https://github.com/tobias-/armeria/tree/bracket_test

Credit to @tobias- 🙇 👍 🙇

**Comment by tobias-** [comment]
Solution 2 may be correct, but it would be disastrous for us. I've gone through the following browser which would *not* work with Armeria after solution 2:
* chrome 110.0.5481.100 (Official Build) (arm64)
* Safari 16.3 (18614.4.6.1.6)
* Brave v1.48.164 (Feb 15, 2023)
* HttpURLConnection (java 17)
* curl 7.85.0
* wget 1.21.3

**Comment by trustin** [comment]
Another option is to automatically percent-encode `[` and other harmless yet prohibited characters before putting it into `RequestHeader`.

**Comment by ikhoon** [comment]
I didn't know that it is escaped and not rejected.
Initially, I filed the original issue #4607 to make Armeria return 400 Bad Request so that the default response for `[]` is similar to other web servers.
https://github.com/playframework/playframework/blob/main/core/play-integration-test/src/it/scala/play/it/http/BadClientHandlingSpec.scala#L58-L65

I'm not strong here. I'm also fine with percent-encode option.

**Comment by tobias-** [comment]
I managed to dig up an old (2015) stackoverflow post that implies that IE and Chrome USED to escape the characters, but Chrome has since switched to NOT encoding them.

https://stackoverflow.com/questions/12628717/encoded-url-with-square-brackets-different-behaviour-in-chrome-firefox-ie
