### ISSUE TITLE
Option to force HTTP/2 connection over TLS without negotiation

### ISSUE THREAD

**Issue by 0lejk4** [line/armeria#4702]
Hello, is it possible to force the Armeria HTTP Client to use HTTP/2 over TLS and skip negotiation, or even if negotiation fails? I mean if I for sure know that the server support HTTP/2.
Is it possible to send a preface in such a case?
https://httpwg.org/specs/rfc7540.html#known-http

**Comment by 0lejk4** [comment]
When I try to send requests In my case happens this: https://github.com/line/armeria/blob/fee87f8da942d0e6343e814489524b73db60ef3b/core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java#L238

**Comment by ikhoon** [comment]
As per rfc7540 3.4, Connection preface can be used for HTTP/2 over cleartext.
> This only affects the establishment of HTTP/2 connections over cleartext TCP; implementations that support HTTP/2 over TLS MUST use [protocol negotiation in TLS](https://httpwg.org/specs/rfc7540.html#TLS-ALPN) [TLS-ALPN].

Do you want to use connection preface for HTTP/2 over TLS?

**Comment by 0lejk4** [comment]
Exactly, it seems that some clients support them and some don't and I wanted to achieve this with Armeria. If it is not available now could I contribute such feature?

**Comment by 0lejk4** [comment]
I created a draft PR for this feature. Published locally and this seems to be working for me, although I do not know if maybe something is wrong with these changes. Waiting for your reply.
