### ISSUE TITLE
Support custom JSON marshaller for error details in unframed grpc error

### ISSUE THREAD

**Issue by cormoran** [line/armeria#4723]
In short, implements this [TODO comment](https://github.com/line/armeria/blob/ff25d6f1e79c9fcfbbe632052a3102411554458f/grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlers.java#L71).

When using grpc richer error response, we sometimes want to pass custom type in [`Status.details`](https://github.com/googleapis/googleapis/blob/00179492fb1d3ceedd9c65b803c6230d59a15d94/google/rpc/status.proto#L48) instead of well-known details.
Now it fails for unframed http transcoding requests since the error marshaller doesn't know custom types  and there is no way to register custom types.

**Comment by ikhoon** [comment]
It is time to add a builder class to create `UnframedGrpcErrorHandler` with various options.
For example:
```java
UnframedGrpcErrorHandler.builder()
                        .responseType(UnframedGrpcErrorResponseType.JSON,
                                      UnframedGrpcErrorResponseType.PLAINTEXT)
                        .statusFunction(UnframedGrpcStatusMappingFunction)
                        .jsonMarshaller(MessageMarshaller)
                        .build()
```
