### ISSUE TITLE
Always remove a URI fragment from an outgoing request

### ISSUE THREAD

**Issue by trustin** [line/armeria#4766]
We have inconsistent behavior between two following examples:

```java
WebClient.of()
         .get("https://example.com/foo#bar")

WebClient.of("https://example.com/")
         .get("/foo#bar")
```

The first example sends `/foo` as the request path but the second one sends `/foo#bar` (or `/foo%23bar` once #4765 is merged).

For the consistency, we should change the behavior of the latter by removing a URI fragment from the request path. The fragment could be stored in `ctx.fragment()` so it can be used as a hint for decorators, like we already do so in Thrift clients.

We also evaluated the alternative option that changes the behavior of the former by always treating `#bar` as a part of request path. However, we decided to go with the first option because we expect no Armeria users send a request whose request path contains `#` yet thanks to #4765 (although we did't intend this 😅), making it a much less breaking change.

**Comment by minwoox** [comment]
Closed by #4789
