### ISSUE TITLE
Introduce GrpcCallOptions to query saved CallOptions from ClientRequestContext

### ISSUE THREAD

**Issue by vkostyukov** [line/armeria#4776]
I'm proposing a feature where gRPC `CallOptions` are saved within a `ClientRequestContext` somewhere in the [ArmeriaClientCall ctor](https://github.com/line/armeria/blob/main/grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java#L161) so users can retrieve it later, within client decorators should they need it. An API to access saved `CallOptions` object may look like this:

```
val ctx: ClientRequestContext = ???
val options: CallOptions = GrpcCallOptions.get(ctx)
```

/cc @ikhoon

**Comment by ikhoon** [comment]
We are preparing for the release of 1.23.0.
If it is not urgent, let us schedule it to 1.24.0

**Comment by vkostyukov** [comment]
I think we'd love to have it in 1.23, but I surely don't want it to delay the release. I'm willing to volunteer my time and contribute it but I'm unsure if it can go through the review quick enough.
