### ISSUE TITLE
Provide a way to set DistributionSummary config via builder

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4781]
Users need to use `MoreMeters.setDistributionStatisticConfig(config)` to specify the distribution config.
That means users cannot configure different configs depending on the client. Using the static class is also not intuitive and not the Armeria style which uses a builder for setting configuration.
We can probably do:
```java
MetricCollectingClient.builder(meterIdPrefixFunction)
  .distributionStatisticConfig(config)
  ...
```

We can also add the getter to `FlagsProvider`:
```java
public interface FlagsProvider {
  default DistributionStatisticConfig distributionStatisticConfig() { return null;}
}
```

**Comment by echo304** [comment]
I will take this issue :) ✋
