### ISSUE TITLE
Provide a way to easily create `CircuitBreakerRule` with `RequestLog`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4782]
`ResponseHeaders`, `HttpStatus` and an exception is used to decide if a request fails and the result is reported to `CircuitBreaker`.
https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleBuilder.java#L127-L143
That would be sufficient if users may want to build a fine-grained rule based on the information in `RequestLog` such as response duration.
I proposed to add new builder methods to create a rule with `RequestLog`
```java
class CircuitBreakerRuleBuilder {

    @Override
    public CircuitBreakerRuleBuilder onRequestLog(
            Predicate<RequestLog> requestLogFilter) {
        ...
    }
}
```

**Comment by babjo** [comment]
I'll handle this issue soon. @ikhoon nim, would you please assign this to me?

**Comment by ikhoon** [comment]
> it would be consistent to have the new method receiving both ClientRequestContext and RequestLog. Should I do that like below?

Right, my example was a draft. We need to add the both version.

>  should add BiPredicate<ClientRequestContext, RequestLog> requestLogFilter to AbstractRuleBuilder as a member field and implement the onRequestLog method in all the subclasses, right?

It sounds good.

**Comment by babjo** [comment]
@ikhoon nim, I'm writing some unittests after `onRequestLog` implementation. Would you please take a look at below?
 
```java
@Test
    void openCircuitWithRequestLog() {
        final CircuitBreakerRuleWithContent<HttpResponse> rule =
                CircuitBreakerRuleWithContent
                        .<HttpResponse>builder()
                        .onRequestLog((ctx, requestLog) -> requestLog.responseDurationNanos() > 100) // (2) RequestLogProperty#RESPONSE_END_TIME is unavailable and it throws RequestLogAvailabilityException.
                        .thenFailure();
        final BlockingWebClient client =
                WebClient.builder(server.httpUri())
                         .decorator(CircuitBreakerClient.newDecorator(CircuitBreaker.ofDefaultName(), rule))
                         .build()
                         .blocking();

        assertThat(client.get("/delayed").contentUtf8()).isEqualTo("Hello, Armeria!"); // (1) "/delayed" endpoint responds 1 second late.
        await().untilAsserted(() -> {
            assertThatThrownBy(() -> client.get("/")).isInstanceOf(FailFastException.class);
        });
    }
```

I want to write a unittest that circuit becomes OPEN due to delayed response, and verify that the failfastexception is returned as the response of the next request. However, in `onRequestLog`, I'm facing an issue where the responseDurationNanos isn't available because the response hasn't been aggregated yet. How could I make the `RequestLogProperty#RESPONSE_END_TIME` value available in `onRequestLog`?

**Comment by ikhoon** [comment]
Good question. `CircuitBreaker` waits until the response headers are available by default so `RequestLogProperty#RESPONSE_END_TIME` isn't recorded when the predicates are called.
https://github.com/line/armeria/blob/ab7488bafc2912445f026fb6d02420f134937073/core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java#L321-L335
We may change 1) `CircuitBreakerRule.requiresResponseTrailers()` to return `true` when `onRequestLog` is configured and then 2) make `CircuitBrekear` use `ctx.log().whenComplete()` if `requiresResponseTrailers` is true.

For example:
```java
final RequestLogProperty property =
        rule.requiresResponseTrailers() ? null
                                        : RequestLogProperty.RESPONSE_HEADERS;

...

private void reportResult(ClientRequestContext ctx, CircuitBreakerCallback callback,
                          @Nullable RequestLogProperty logProperty) {
    final CompletableFuture<RequestLog> logFuture;
    if (logProperty == null) {
        logFuture = ctx.log().whenComplete();
    } else {
        logFuture = ctx.log().whenAvailable(logProperty);
    }
    logFuture.thenAccept(log -> { ... });
}
```

**Comment by babjo** [comment]
I got it. I'll try that then. Thank you for your explanation in detail.
