### ISSUE TITLE
Migrate JUnit 4 tests in Spring Boot integration modules to JUnit 5

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4788]
Spring integration modules have to use JUnit 4 to share the test suites with the legacy Spring Boot 1.
https://github.com/line/armeria/blob/5bd1c7b08d783a8ea39fa2dd9259cec899ecb606/spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java#L25-L42
Spring Boot 1 integration modules are going to be removed from Armeria. #4787

That means there is no reason we have to use JUnit 4 after #4787 is merged. It would be nice to use JUnit 5 like any other test code.

**Comment by mitrofmep** [comment]
Can I deal with this?

**Comment by ikhoon** [comment]
Of course. Thanks for your interest.

**Comment by ikhoon** [comment]
You may want to start after https://github.com/line/armeria/pull/4787 is merged.

**Comment by heowc** [comment]
Can I deal with this? 🤔
