### ISSUE TITLE
Internal services are bound twice to the server

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4796]
When `internalServicePort` and `managementServerPort` are the same,
https://github.com/line/armeria/blob/57295d3ed82748dc6949f825910705a6c17d098f/spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java#L119-L129

internal services are bound twice:
https://github.com/line/armeria/blob/57295d3ed82748dc6949f825910705a6c17d098f/spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java#L155-L161

We should dedup the ports.

**Comment by ikhoon** [comment]
> We should dedup the ports.

If that happens, users may have set that value by mistake. What do you think of raising an `IllegalStateException` rather than deduplication for that case?
