### ISSUE TITLE
Add fallback strategy to `CircuitBreakerClient`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4800]
If a circuit for `CircuitBreakerClient` becomes open, requests are rejected with:
- `FailFastException`
https://github.com/line/armeria/blob/ab7488bafc2912445f026fb6d02420f134937073/core/src/main/java/com/linecorp/armeria/client/circuitbreaker/DefaultCircuitBreakerClientHandler.java#L47-L49
- `UnprocessedRequestException(CallNotPermittedException)`
https://github.com/line/armeria/blob/ab7488bafc2912445f026fb6d02420f134937073/resilience4j2/src/main/java/com/linecorp/armeria/resilience4j/circuitbreaker/client/Resilience4JCircuitBreakerClientHandler.java#L114-L118

If users want to add a fallback logic when the request is failed by `CircuitBreakerClient`, it is possible to add a custom decorator that wraps `CircuitBreakerClient` to recover.
```java
WebClient
  .builder(...)
  .decorator(CircuitBreakerClient.newDecorator(...))
  .decorator((delegate, ctx, req) -> {
   try {
        delegate.execute(ctx, req);
    // If resilent4j's `CircuitBreaker` is used.
    } catch(UnprocessedRequestException ex) {
        if (ex.getCause() instanceof CallNotPermittedException) {
            // Recover the request.
        }
    }
  });
```

That said, it would be more convenient for users to set a fallback logic via a builder method `CircuitBreakerClient`.
```java
CircuitBreakerClient
  .builder(...)
  .recover((ctx, req) -> {
     /* fallback */ 
     return HttpResponse.of(...);
  });
```

We may add a new API to `CircuitBreakerClientHandler` to check which exception is a circuit breaker exception.
```java
interface CircuitBreakerClientHandler {
   default boolean isCircuitBreakerException(Exception ex) {
       return ex instanceof FailFastException;
   }
}

class Resilience4JCircuitBreakerClientHandler implements CircuitBreakerClientHandler {
    @Override
    public boolean isCircuitBreakerException(Exception ex) {
        return ex instanceof UnprocessedRequestException && 
               ex.getCause() instanceof CallNotPermittedException;
    }
}
```

**Comment by echo304** [comment]
Can I take this task? ✋

**Comment by ikhoon** [comment]
👍 Sure!

**Comment by my4-dev** [comment]
@echo304 
I have been working on this issue since the other day and have almost completed it. Therefore, I decided to finish it and submit a Pull Request. I'm sorry for any inconvenience this may have caused you, as you were enthusiastic about this task🙇‍♂️
