### ISSUE TITLE
ArmeriaServerHttpResponse doesn't inherit 'getStatusCode()' of interface ServerHttpResponse

### ISSUE THREAD

**Issue by davin111** [line/armeria#4819]
I use spring boot 3.0.5 with recently released armeria 1.23.1.

When I call some apis of my server with some cases, I got errors saying `Receiver class com.linecorp.armeria.spring.web.reactive.ArmeriaServerHttpResponse does not define or inherit an implementation of the resolved method 'abstract org.springframework.http.HttpStatusCode getStatusCode()' of interface org.springframework.http.server.reactive.ServerHttpResponse.`

I think this is because of newly added `getStatusCode()` (and maybe `setStatusCode()`) method of spring `org.springframework.http.server.reactive.ServerHttpResponse`.

If I guess correctly and this is yet handled, can I try to fix it?

**Comment by jrhee17** [comment]
I thought the following file would handle the issue you mentioned (which was included in this release)
https://github.com/line/armeria/blob/main/spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/AbstractServerHttpResponseVersionSpecific.java

I'm wondering if there are any `spring-boot2` related dependencies in your project setup which may cause conflicts.

Having said this, if there are any issues we would be grateful if you can try to fix it 🙇

**Comment by davin111** [comment]
@jrhee17 Oh... sorry for bothering you. You're correct. I didn't modify the `"com.linecorp.armeria:armeria-spring-boot2-webflux-starter"` dependency. After I correct it, the issue is resolved.

I had checked only `ArmeriaServerHttpResponse` file and had misunderstood. Sorry again.
