### ISSUE TITLE
`ServerErrorHandler` behavior is not well defined when `maxRequestLength` is exceeded

### ISSUE THREAD

**Issue by jrhee17** [line/armeria#4821]
When `maxRequestLength` is exceeded from server-side,

1. An error response is returned
https://github.com/line/armeria/blob/62349aba927cde2a8bf8936051b7346e7002a2d9/core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java#L315-L322
2. `onProtocolViolation` is invoked returned response is written
https://github.com/line/armeria/blob/62349aba927cde2a8bf8936051b7346e7002a2d9/core/src/main/java/com/linecorp/armeria/server/ServerHttpObjectEncoder.java#L79-L81
3. Afterwards, the request is cancelled
https://github.com/line/armeria/blob/62349aba927cde2a8bf8936051b7346e7002a2d9/core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java#L323-L324
4. And the `onServiceException` callback is invoked after calling the `HttpService`
https://github.com/line/armeria/blob/62349aba927cde2a8bf8936051b7346e7002a2d9/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L376

Although `ServerErrorHandler#onServiceException` is invoked at step 4, the returned value is ignored since the response has already been written at step 2.

We may need to rethink what exactly `ServerErrorHandler#onProtocolViolation` means. (is it really for protocol violations? or just exceptions that occur before reaching the service level?)

At the very least the returned value from `ServerErrorHandler#onServiceException` shouldn't be ignored.

Additionally, @vkostyukov suggested that we may reject requests based on the `Content-Length` header when it is available.

slack ref: https://line-armeria.slack.com/archives/C1NGPBUH2/p1681147580747319
reproducer: https://gist.github.com/vkostyukov/c1e75b5eceb14bbd2538733d0def436f

**Comment by minwoox** [comment]
I believe this can be resolved by #5227.

**Comment by minwoox** [comment]
Closed by #5227
