### ISSUE TITLE
Can't config costume ProtobufResponseConverterFunction for annotated http service

### ISSUE THREAD

**Issue by wenge-aft** [line/armeria#4839]
I am try to config a ProtobufResponseConverterFunction that will convert protobuf Message object to json. The default ProtobufResponseConverterFunction is using **JsonFormat.printer()**, which will convert the field name to **lowerCamelCase**, but I want to preserve the field name in proto file. When I trying to set the the printer like bellow:
```
.annotatedService().useBlockingTaskExecutor(true).responseConverters(
    ProtobufResponseConverterFunction(JsonFormat.printer().preservingProtoFieldNames())
).build(adminOfferService)
```
But I found the setting is not working, the reason is that [AnnotatedService's](https://github.com/line/armeria/blob/main/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java) constructor is not doing the right thing
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/76029783/233548547-67006037-5806-4f2d-91e9-4a7a012c65a4.png">

In [newResponseConverter](https://github.com/line/armeria/blob/62349aba927cde2a8bf8936051b7346e7002a2d9/core/src/main/java/com/linecorp/armeria/internal/server/annotation/ResponseConverterFunctionUtil.java#L70) func:
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/76029783/233548896-0378a566-435b-4659-822c-1ae91befe3c2.png">
It returns at above, because delegatingResponseConverterProviders has include ProtobufResponseConverterFunctionProvider
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/76029783/233549346-c5f38153-bfe5-40c3-adcc-fb91c39af844.png">

A default ProtobufResponseConverterFunction will return here
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/76029783/233550095-733e07a5-52ae-4d60-a317-cd5897f760a0.png">

Which will **dismiss** my origin ProtobufResponseConverterFunction

**Comment by minwoox** [comment]
Which Armeria version are you using?
I think `delegatingResponseConverterProviders` do not include `ProtobufResponseConverterFunctionProvider`. 
https://github.com/line/armeria/blob/529738c836c78bf94d032f1328ec4241d662d19c/protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java#L41 is called from https://github.com/line/armeria/blob/e81c37cda086fe38198aa6415af202bd453a2e32/core/src/main/java/com/linecorp/armeria/internal/server/annotation/ResponseConverterFunctionUtil.java#L74
which means that the converter isn't applied before the converter you specified.
Could you give us a simple reproducing repository so that I can investigate on it?

**Comment by wenge-aft** [comment]
@minwoox I am using 1.15.0.
This is the repo: https://github.com/wenge-aft/armeria-test
when you start the application and run
```
curl --location 'http://localhost:8080/v1/management/offer' \
--header 'Content-Type: application/json' \
--data '{
    "name": "test offer",
    "test_description": "adidas"
}'
```
I got response
```
{
    "name": "test offer",
    "testDescription": "adidas"
}
```
and I expect to get
```
{
    "name": "test offer",
    "test_description": "adidas"
}
```

And after test newest version 1.23.1, I have found you have fix it. 

Sorry to confuse you, and thank you for your great work and quick reply

**Comment by wenge-aft** [comment]
@minwoox just found you have fixed this last year. https://github.com/line/armeria/issues/4301 And also found that was raised by another engineer from our company. I think it's ok to close

**Comment by minwoox** [comment]
Yes, it's fixed. 😆 
Let me close this issue, then.
