### ISSUE TITLE
how can I integration Armeria with spring-boot

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#485]
Is there any boilerplate for integrating spring-boot with Armeria.

**Comment by trustin** [comment]
What sort of integration would you need? I'd like to gather some requirements before working on this.

**Comment by eonezhang** [comment]
there maybe two points from my perspective,
* programming model,
eg
```java
@ArmeriaService(protocol=Protocol.THRIFT, path="/user")
public class UserService extends TUserService.AsyncIface {
}
```

* integration with spring-boot and spring-cloud stack, such as the api gateway zuul

**Comment by trustin** [comment]
Sweet. At LINE, we have some internal classes written by @anuraaga and @imasahiro that integrates with Spring boot and we'd like to include it into `armeria-spring` eventually. @imasahiro, you interested?

**Comment by eonezhang** [comment]
@imasahiro how about your thoughts, I would like to heart about that.

**Comment by imasahiro** [comment]
@trustin @eonezhang sounds good. Let me make a PR about spring-boot integration as first step.

**Comment by eonezhang** [comment]
@imasahiro looking forward to your PR ;-)
