### ISSUE TITLE
Provide a way to customize GraphQL `ExecutionId`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4867]
In GraphQL-Java, an `ExecutionId` can be assigned to each query (`ExecutionInput`). If `ExecutionId` is not set, `UUID.randomUUID()` is allocated as the default `ExecutionId`.
https://github.com/graphql-java/graphql-java/blob/e1555f8af7111bca7a276a63d4df3a0419630e9c/src/main/java/graphql/execution/ExecutionIdProvider.java#L11
https://github.com/graphql-java/graphql-java/blob/e1555f8af7111bca7a276a63d4df3a0419630e9c/src/main/java/graphql/execution/ExecutionId.java#L20

The default `ExectionId` has two drawbacks.
- `UUID.randomUUID()` uses `SecureRandom` which has a [performance issue](https://www.synopsys.com/blogs/software-security/issues-when-using-java-securerandom/) if sufficient entropy is not available.
- It is impossible for the user to set an `ExecutionId` based on the request.
 
We may reuse the `RequestId` of `ServiceRequestContext` for the default `ExecutionId` so that users easily associate an HTTP request with a GraphQL query. It would be nice to provide a factory for `ExecutionId` so that users can customize this part.

```java
interface ExecutionIdGenerator {
    static ExecutionIdGenerator of() {
	    return (ctx, query, operationName) -> ExecutionId.from(ctx.id().text());
    }

    ExecutionId generate(ServiceRequestContext ctx, String query, String operationName);

    default asExecutionProvider() { ... }
}

class GraphqlServiceBuilder {

    public GraphqlService build() {
        GraphQL.Builder builder = ...;
        builder.executionIdProvider(excutionIdGenerator.asExecutionProvider());
        ...
    }
```

**Comment by tomatophobia** [comment]
Hi, @ikhoon May I handle this issue?

**Comment by ikhoon** [comment]
Yes, please. ❤️
