### ISSUE TITLE
support latest protoc.

### ISSUE THREAD

**Issue by KatsumiYokomichi** [line/armeria#4869]
Armeria gRPC componet is not compatible with stub that generated by latest protoc.
I know to upgrade gRPC library Armeria uses, JDK 8 support has to be dropped.
But keep using old protoc is not good at all.
Isn't time to drop JDK 8 support?

Quarkus had the same problem and they decided to drop JDK 8 support.

**Comment by jrhee17** [comment]
Hi, I didn't know there was a minimum java requirement for protoc 😅   Do you have any references that announces this behavior?

And I wasn't able to find any notes that where protobuf is dropping support for java 8.
https://github.com/protocolbuffers/protobuf/releases

jfyi. I think we're using `3.21.1` at the moment.

https://github.com/line/armeria/blob/92e70170b560470a68ae18895d60b3689c8d98bb/dependencies.toml#L789
https://github.com/line/armeria/blob/92e70170b560470a68ae18895d60b3689c8d98bb/dependencies.toml#L789-L791
https://github.com/line/armeria/blob/92e70170b560470a68ae18895d60b3689c8d98bb/gradle/scripts/lib/java-rpc-proto.gradle#L37

**Comment by jrhee17** [comment]
> Armeria gRPC componet is not compatible with stub that generated by latest protoc.

If you can share the error message you encountered, it would also help 🙇

**Comment by ikhoon** [comment]
>  Isn't time to drop JDK 8 support?

We don't a specific plan to drop JDK 8. As far as I know, many of our community users and LINE internally use Java 8.

**Comment by trustin** [comment]
> the error message

More specifically, the full stack trace. Meanwhile, we might want to add a test module under `:it` to ensure the forward compatibility.

**Comment by KatsumiYokomichi** [comment]
I've got this build error.
```
C:\work\grpctest\build\generated\source\proto\main\java\com\example\grpc\hello\Helloworld.java:386: error: cannot find symbol
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                          ^
  symbol: method parseUnknownField(CodedInputStream,ExtensionRegistryLite,int)
```
protoc setting in build.gradle is this.
```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.23.0"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.55.1'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}
```
Please see this issue.
https://github.com/protocolbuffers/protobuf/issues/10695#issuecomment-1267493171

**Comment by jrhee17** [comment]
> We might need two versions for armeria-grpc to keep JDK 8 compatiblity and have security issue fix.

Note that the upgrade PR from our side will be included in the next release.
https://github.com/line/armeria/pull/4820

This version includes a fix for the following issue which was a blocker for upgrading protobuf (which may be why you are mentioning jdk8 compatibility)
https://github.com/protocolbuffers/protobuf/issues/11393

**Comment by KatsumiYokomichi** [comment]
Thanks!. That should solve the issue we see. 
And keep having JDK 8 compatibility is also good.
