### ISSUE TITLE
It seems that the `management.endpoints.web.exposure` setting in spring boot is not supported by `armeria-spring-boot3-actuator-starter`.

### ISSUE THREAD

**Issue by be-hase** [line/armeria#4874]
## Overview

I am aware that the `armeria-spring-boot3-actuator-starter` (also `armeria-spring-boot2-actuator-starter`) can be used to run the spring boot actuator endpoint using the armeria server.

The spring boot actuator endpoint has several dangerous endpoints.
For example, there are endpoints that can get `heapdumps`.

In general, we(spring boot users) can avoid exposing some endpoints by setting `management.endpoints.web.exposure`.
https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.actuator.management.endpoints.web.exposure.exclude

But, it seems that the `management.endpoints.web.exposure` is not supported by `armeria-spring-boot3-actuator-starter`.

## Why

The original Spring Boot Actuator has the following code.
https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/endpoint/web/WebEndpointAutoConfiguration.java#L112-L116

However, there is no such code in `armeria-spring-boot3-actuator-starter`.
https://github.com/line/armeria/blob/e15c7b7809db6d77c6798c237707e942fceb51bb/spring/boot3-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java

Of course, if all settings of spring boot are supported, the cost on the armeria side will be large.
However, `management.endpoints.web.exposure` is an important and frequently used setting that is worth supporting.

## Simple Reproduction Code

https://github.com/be-hase/armeria-issues-202305/tree/main/example/actuator-issue

Adding a bean like this would work well.
(remove comment out)
https://github.com/be-hase/armeria-issues-202305/blob/main/example/actuator-issue/src/main/java/example/actuator_issue/Application.java#L31-L36

**Comment by ikhoon** [comment]
> Of course, if all settings of spring boot are supported, the cost on the armeria side will be large.
However, management.endpoints.web.exposure is an important and frequently used setting that is worth supporting.

Agreed. It would be a good idea to support `management.endpoints.web.exposure` in `armeria-spring-boot{2,3}-actuator-starter`

**Comment by minwoox** [comment]
I thought we were already handling it.
This is a relevant test:
https://github.com/line/armeria/blob/57295d3ed82748dc6949f825910705a6c17d098f/spring/boot3-actuator-autoconfigure/src/test/resources/application-secureTest.yml#L17
https://github.com/line/armeria/blob/57295d3ed82748dc6949f825910705a6c17d098f/spring/boot3-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationSecureTest.java#L72-L75

So if it doesn't work, that's a bug. 😅  Let me investigate it.

**Comment by minwoox** [comment]
> The armeria default setting seems to expose all endpoints.

No, it isn't. 😅  If you remove one of those ID in the configuration, the test wouldn't work.

And the reproducible code you gave actually works.
I sent the request http://127.0.0.1:8081/actuator/beans and I got the response.
Could you check it again, please? 🤔

**Comment by minwoox** [comment]
It seems like we have a bug in there. Let me investigate it more. 😅 Sorry for making you get confused.

**Comment by be-hase** [comment]
OK, I'll send a PR later. :)
