### ISSUE TITLE
Do you use any gradle plugin to generate source code from thrift IDL

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#488]
As title said, how do you generate java code from thrift IDL, manually or other automation tips while you use gradle to as the build tool?

**Comment by trustin** [comment]
We do not use a plugin but just define a task. See [here](https://github.com/line/armeria/blob/9417d58c9d2213a4072dd621631435cee6ee4296/build.gradle#L393). You can also consider using one of the plugins listed [here](https://plugins.gradle.org/search?term=thrift)

**Comment by eonezhang** [comment]
thanks @trustin , you are so active, I really want to apply the armeria to my product in the near future. more questions will be raised in future,  thanks for you patience.

**Comment by trustin** [comment]
@eonezhang I appreciate your interest. Let me look forward to your further questions. Also, please consider promoting Armeria to your colleagues and friends! ;-)

**Comment by eonezhang** [comment]
@trustin sure, now team is comparing gRPC with Armeria, and I saw Armeria is easy to integrate with  gRPC, and other team members find some spring-boot-grpc-starter for gRPC, I'm trying to find out the way Armeria work with. 
and the api gateway is also a trouble, for old browsers only json is supported, thrift and protobuf were limited, we need to move on.

**Comment by anuraaga** [comment]
I'm not familiar with the Zuul gateway, but I'm finishing up work on a protobuf-json compat library that is many times faster than the official one, so I can use it to give proper grpc+json support to armeria. Hopefully that will help :)

**Comment by trustin** [comment]
@anuraaga Way to go!

**Comment by eonezhang** [comment]
@anuraaga sound very cool, @trustin  I hope in near future, I could contribute to Armeria ;-)
