### ISSUE TITLE
[Question] - Any reason to force 200 status code for "application/json-seq"  response in JsonTextSequences

### ISSUE THREAD

**Issue by ryukato** [line/armeria#4901]
I found codes to force http status code in response to `200` from [JsonTextSequences.java#L339] (https://github.com/line/armeria/blob/323fb45164c83f68e6efa2f0885efc728b62539a/core/src/main/java/com/linecorp/armeria/server/streaming/JsonTextSequences.java#L339), and the [rfc7464](https://datatracker.ietf.org/doc/rfc7464/) is mentioned in the comments. sorry but I can't find any words about we have to use only `200` status code for an "application/json-seq"  response. 
if allowing other status code does not break anything, then would you consider that?
and I appreciate if you let me know there is anything I missed.

Thanks in advance. 👍

**Comment by minwoox** [comment]
@ryukato Apologize for making you wait for a long time. 😓 
I totally missed this issue.
Like you said rfc7646 doesn't say anything about the status and I couldn't find any relevant documentation.
I also don't remember why we have decided to use only the 200 status. So, probably okay to remove the warning log.
What's the status that you want to use instead by the way?

**Comment by ryukato** [comment]
@minwoox I appreciate your answer. I think that's enough. :)
