### ISSUE TITLE
Consider using the same Java version as the build JDK by default

### ISSUE THREAD

**Issue by trustin** [line/armeria#4904]
I realized our tests are always run by default with Java 8. I agree that we should make sure our project runs on JRE 8 without a problem, but I feel like we should use the same Java version as the build JDK in our daily dev loop, so we spot any future incompatibilities early. We already make sure our tests pass on all major JRE versions including 8 in our CI, so this shouldn't lead us to any problem in my opinion.

**Comment by ikhoon** [comment]
Sounds like a good idea. Let me handle this after #4812 is merged to avoid conflicts. #4812 has some changes to `targetJavaVersion` in `java.gradle`

**Comment by minwoox** [comment]
Oops, I sent a PR for it without recognizing this issue. 😓 
https://github.com/line/gradle-scripts/pull/162
PTAL.

**Comment by ikhoon** [comment]
The PR has been merged. 😉
