### ISSUE TITLE
Support `ResponseEntity` in annotated services.

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4910]
`ResponseEntity<T>` was introduced to support automatic JSON deserialization for REST API on the client side.

At that time, we already had `HttpResult` which is almost the same as `ResponseEntity`. However, we can't use it for clients because `HttpResult` is located in `com.linecorp.armeria.server.annotation`.

We don't have maintain two similar APIs that may confuse users about their usage. I think `HttpResult` can be deprecated in favor of `ResponseEntity` which will be a drop-in replacement API when users want to return a response object with HTTP status.

**Comment by trustin** [comment]
@moromin is working on this.
