### ISSUE TITLE
Add Armeria `HttpClientAdapter` for better support Spring 6 HTTP interface

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4912]
If we provide an Armeria [`HttpClientAdapter`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/service/invoker/HttpClientAdapter.html) implemented on top of Armeria `WebClient` for Spring 6 HTTP interface, users can directly create Spring 6 HTTP interface without depending on WebFlux modules. 

```java
WebClient webClient = ... // Armeria WebClient
HttpServiceProxyFactory httpServiceProxyFactory = 
  HttpServiceProxyFactory
    .builder(ArmeriaHttpClientAdapter.of(webClient))
    .build();
booksService = httpServiceProxyFactory.createClient(BooksService.class);
```

In addition to the convenience of creation, as the HTTP interface can directly communicate with remote peers without WebFlux's WebClient layer, it will have better performance.

**Comment by heowc** [comment]
Isn't this a duplicate issue? :thinking: 

- https://github.com/line/armeria/issues/4838

**Comment by ikhoon** [comment]
Indeed. The detail is different but the purpose is the same. Let me close this in favor of #4838
