### ISSUE TITLE
[Question] how to check if a request is the last retry attempt in gRPC client

### ISSUE THREAD

**Issue by Lincong** [line/armeria#4915]
## Context
I am on Armeria `1.16.2` and using gRPC client decorated with `RetryingClient`. We rely on the `ctx.log.whenComplete` callback to collect metrics for a request. 

In order to record some custom retry metric (a histogram of the number of attempts took to complete a request within a time window), we need the information on whether a request is the last attempt. For example, if the max total retry attempt is 3 and the current request is the 2nd attempt (and the 1st attempt is the original request), we know that this request is not the last attempt.

## What I considered
- I checked `ClientRequestContext` interface/APIs but did not find anything we can leverage there.
- I checked HTTP headers and realized that every retry request has a header with key `"armeria-retry-count"` and its value tells us the current retry attempt number. In order to know whether a retry is the last attempt, we still need to know the max total retry attempts.
- There is a way to retrieve retry state in `AbstractRetryingClient` as shown below and the retry state contains sufficient information. However, `STATE` is private to `AbstractRetryingClient`. 

```java
State retryState = ctx.attr(STATE); // `ctx` is `ClientRequestContext`
```

Let me know if this is possible given APIs in `1.16.2`. Thanks!

**Comment by ikhoon** [comment]
> the number of attempts took to complete a request

We recently added a new metric for `RetryingClient` that uses `RequestLog.children.size()` to know the number of actual requests made. Was the information helpful to measure your metrics?
https://github.com/line/armeria/pull/4707/files#diff-bc19bd339166e0240aad34cc1d72a4cffa1b55140064f9da31381db924cb19f3R166

**Comment by Lincong** [comment]
Thanks @ikhoon for providing this information! This metrics is definitely useful. However, I am afraid it does not quite fit into my use case.

IIUC this metrics track the total number of requests including retries. However, my use case interests in for each request, how many retries occurred because we want to record a histogram, for example:

```
1st request (failed), retry 1 (failed), retry 2 (succeeded) --> record 3 to the histogram.

2nd request (succeeded) --> record 1 to the histogram 

3rd request (failed), retry 1 (failed), retry 2 (failed), retry 3 (failed) --> record 4 to the histogram.
```

This [metric](https://github.com/line/armeria/pull/4707) increments by 8 (= 3 + 1 + 4) given the above 3 requests and their retries and this information is not required by my use case.

Let me know if I misunderstood anything.

**Comment by ikhoon** [comment]
> This https://github.com/line/armeria/pull/4707 increments by 8 (= 3 + 1 + 4) given the above 3 requests and their retries and this information is not required by my use case.

`MetricCollecingClient` has been providing two kinds of metrics for retries since #4707 was merged. 
- `actual.requests` is a counter that increases the actual executed requests.
https://github.com/line/armeria/blob/4c9dccf996dc062f8f77d7013de504141d9c8306/core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java#L324-L324
- `actual.requests.attempts` is a histogram that records request attempts to a bucket.  
https://github.com/line/armeria/blob/4c9dccf996dc062f8f77d7013de504141d9c8306/core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java#L357-L375

`actual.requests.attempts` seems similar to your requirement. Please correct me if I misunderstood.

**Comment by Lincong** [comment]
Thanks @ikhoon for pointing it out and sorry for missing it completely!

Yes, `actual.requests.attempts` mostly fits my use case. Some follow-up questions:

1. Will this [PR](https://github.com/line/armeria/pull/4707) be part of [1.24.0 release](https://github.com/line/armeria/milestone/211?closed=1)?
2. My only concern with this `actual.requests.attempts` metrics is that tags are limited. According to tests in the PRs, there are 4 tags, for example: `http.status=200, method=POST, result=success, service=none`. Ideally, we'd like to have (at least) another 2 tags, namely `client_name` and `RPC request type`. `client_name` is our notion of identifying a gRPC client stub and `RPC request type` is basically the `requst.getClassName`. With these 2 tags, this metric becomes much more useful because we will know the request attempt number distribution on which gRPC client stub and which RPC request. (Hey @vkostyukov, could you chime in a bit here regarding how necessary additional tags are for our use case). I am not sure if I can leverage `MeterFilter` to inject/add these tags to this `actual.requests.attempts` histogram metric.

**Comment by ikhoon** [comment]
> Will this https://github.com/line/armeria/pull/4707 be part of [1.24.0 release](https://github.com/line/armeria/milestone/211?closed=1)?

Yes it is.

> Ideally, we'd like to have (at least) another 2 tags, namely client_name and RPC request type. client_name is our notion of identifying a gRPC client stub and RPC request type is basically the requst.getClassName.

You can dynamically add additional tags with `MeterIdPrefixFunction.andThen(...)` depending on the current request context. For example,

```java
var prefixFunction =
  GrpcMeterIdPrefixFunction.of("grpc").andThen((registry, log, meterIdPrefix) -> {
    final RpcRequest requestContent = (RpcRequest) log.requestContent();
    final String requestType = requestContent.params().get(0)
                                             .getClass()
                                             .getSimpleName();
    return meterIdPrefix.withTags(ImmutableList.of(
            Tag.of("client.name", "your-client-name"), Tag.of("request.type", requestType)));
 });

```
