### ISSUE TITLE
Return 404 when request has invalid queryParams

### ISSUE THREAD

**Issue by yunjoopark** [line/armeria#4927]
If there is a request to a unregistered path, armeria returns 404 by FallbackService.

However, when there is a service method with `@MatchesParam` in a annotated service and request has no such a query param, it returns 500 by java.lang.IllegalArgumentException: routingResult: RoutingResult{<empty>} (must be present) at Routed:51 --> Http1RequestDecoder:223

```
@PathPrefix("/objects")
class ServiceHandler(
) {

    @Get
    @MatchesParam("id")
    suspend fun getById(
        @Param id: Int
    ) = mapOf()
}
```
```
curl --location 'http://localhost:8080/objects' \
```

```
java.lang.IllegalArgumentException: routingResult: RoutingResult{<empty>} (must be present)
	at com.linecorp.armeria.server.Routed.of(Routed.java:51)
	at com.linecorp.armeria.server.RouteCache$CachingRouter.find(RouteCache.java:126)
	at com.linecorp.armeria.server.VirtualHost.findServiceConfig(VirtualHost.java:392)
	at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:216)
```

**Comment by jrhee17** [comment]
I don't think this is a trivial fix 😅    Let me reschedule for the next milestone since we're releasing the next version soon
