### ISSUE TITLE
`AggregatedHttpObject.content(Charset)` should respect the `charset` attribute in the `content-type` header

### ISSUE THREAD

**Issue by trustin** [line/armeria#4931]
Currently, `AggregatedHttp{Object,Request,Response}.content(Charset)` always uses the given `Charset` to convert its content into a `String`. This can lead to incorrectly decoded content when the content is actually encoded in a different character set and its `content-type` header has the `charset` attribute, e.g.

- `content-type: application/json; charset=EUC-KR`

The above content should be decoded using `EUC-KR` character set even if a user specified `StandardCharset.UTF_8` with `content(Charset)`.

Specifically, this method should check the `content-type` header and its `charset` rather than blindly using the specified `Charset`: https://github.com/line/armeria/blob/armeria-1.23.1/core/src/main/java/com/linecorp/armeria/common/AggregatedHttpObject.java#L41-L43

**Comment by CNJingo** [comment]
@trustin So should content methods that take a CharSet as a parameter be deprecated, or just the logic inside the method be modified?

**Comment by trustin** [comment]
The latter :-)

**Comment by CNJingo** [comment]
Is it okay to replace a parameter with a charset of content type without any notification?

**Comment by trustin** [comment]
I think so, because the currwnt behavior leads to incorrectly decoded
content. Do you have any concerns on your mind?

**Comment by CNJingo** [comment]
I just wanted to get some advice before contributing. Can I take this one?

**Comment by jrhee17** [comment]
Resolved by #4948
