### ISSUE TITLE
A `DnsTimeoutException` should also set `true` to `ctx.isTimedOut()`.

### ISSUE THREAD

**Issue by trustin** [line/armeria#4935]
Related:
- https://github.com/line/armeria/issues/4876#issuecomment-1562255976
- https://github.com/line/armeria/pull/4882

We need to make sure `CancellationScheduler.finishNow(TimeoutException)` is invoked on more timeout types such as session/connection/DNS timeout so that `true` is set to `ctx.isTimedOut()`.

/cc @injae-kim

**Comment by injae-kim** [comment]
Please assign this issue to me~! I'll make PR soon 🙇 thanks!

**Comment by injae-kim** [comment]
(Sorry for late, I'll make PR until 8/31 🙇)
