### ISSUE TITLE
Add `RequestLogAccess.getIfAvailable(RequestLogProperty)`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4956]
Both `RequestLogAccess.isAvailable()` and `RequestLogAccess.ensureAvailable()` should be used to safely get a `RequestLog` when the given `RequestLogProperty`. 

https://github.com/line/armeria/blob/0ce077ee0dab4192b709b6fe824d89768209aaf1/core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java#L116-L118

The code style looks verbose and is not efficient because each operation accesses a volatile variable and computes the available flags.

If we provide an API that returns `RequestLog` only when the given flags are available, it is performant and Kotlin users may take advantage of null [safe calls](https://kotlinlang.org/docs/null-safety.html#safe-calls).
```java
interface RequestLogAccess {
  @Nullable
  RequestLog getIfAvailable(RequestLogProperty... properties);

  @Nullable
  RequestLog getIfAvailable(Iterable<RequestLogProperty> properties);
}

val cause: Throwable? = 
 ctx.log()
    .getIfAvailable(RequestLogProperty.RESPONSE_CAUSE)?.responseCause()
```

**Comment by Kyoungwoong** [comment]
Can i take this one?

**Comment by ikhoon** [comment]
For sure. Thanks in advance. 🙇‍♂️
