### ISSUE TITLE
Add an example for krotoDC

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4990]
https://github.com/mscheong01/krotoDC is yet another a protoc plugin that generates Kotlin data classes and gRPC service/stub.
It would be nice to add an example to check compatibility with Armeria gRPC services and clients.

**Comment by ikhoon** [comment]
@mscheong01 Have you tried krotoDC with Armeria?

**Comment by mscheong01** [comment]
@ikhoon Yes I have 😆 We actually have production apis that are served using krotoDC on Armeria +Springboot servers.

**Comment by ikhoon** [comment]
That sounds nice. Are you interested in sending a PR? We can add krotoDC example to `examples/grpc-krotodc`. If you are busy, I will be excited to try krotoDC for myself. 😉

**Comment by ikhoon** [comment]
Many gRPC-Kotlin users who want to use gRPC with Kotlin data class such as @Dogacel might be interested in https://github.com/mscheong01/krotoDC

**Comment by Dogacel** [comment]
Yep, that sounds amazing, Previously I have looked into [pbandk](https://github.com/streem/pbandk). One of the issue was the client/server stubbing. There isn't a default solution to create custom client/server code, so we did not use it. Also, some things I would consider in examples:
- Client/server stubs that use `Kroto` data classes
- Use of interceptors such as [Protoc-Gen-Validate](https://github.com/bufbuild/protovalidate)

**Comment by mscheong01** [comment]
> That sounds nice. Are you interested in sending a PR? We can add krotoDC example to examples/grpc-krotodc. If you are busy, I will be excited to try krotoDC for myself. 😉

I'm a bit busy at the current moment 😓 I could give it a go when I get the chance, but you don't have to wait for me to add the examples 🙇‍♂️ 
Also, thanks for adding this. It means a lot to me 😆

**Comment by mscheong01** [comment]
I'm currently working on this, and I ran into a problem where Armeria requires the `StubFor`annotation on kotlin stubs. I quickly filed a [PR](https://github.com/mscheong01/krotoDC/pull/17) that adds the annotation to all krotoDC generated stubs. After I deploy the new version and check that the example I wrote works, I'll file the completed PR for it 😄
