### ISSUE TITLE
Make `RequestContextExtension.hook()` public API 

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4991]
`RequestContextExtension.hook()` is an API that is invoked whenever a `RequestContext` is pushed to the current context. https://github.com/line/armeria/blob/145bc0c5a9f28d8e88f5df492ba4f05f541d3548/core/src/main/java/com/linecorp/armeria/internal/common/RequestContextExtension.java#L36-L45
This is especially useful when propagating a specific context with `RequestContext`.
https://github.com/line/armeria/blob/145bc0c5a9f28d8e88f5df492ba4f05f541d3548/brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java#L126-L127
If we expose it to the public API, third-party libraries or users may use it to implement custom instrumentation for Armeria servers or clients

**Comment by my4-dev** [comment]
Hi, @ikhoon !
In this Issue, I think it would be good to add new API and decorator which receives `Supplier<? extends AutoCloseable> contextHook` as an argument like this.
In decorator, we invoke NonWrappingRequestContext#hook and set it to Client which is returned.

```java
WebClient.builder()
    .decorator(newAPI.newDecorator(contextHook))
    ...
    .build();
```

Does it make sense?
Do you have any other ideas in mind?

**Comment by ikhoon** [comment]
Good point. It would be useful to add a builder method for `contextHook`. That said, it is possible to implement this with a decorator but I don't see that the API design is convenient.

What do you think of this style?
```java
WebClient
  .builder()
  // `contextHook` should be attached when a new ClientRequestContext is created.
  .contextHook(contextHook)
  ...
  .build();

Server
  .builder()
  // `contextHook` should be attached when a new ClientRequestContext is created.
  .contextHook(contextHook)
  ...
  .route().contextHook(serviceContextHook)
          .build(service)
  .build();
```

In addition to client builder API, the purpose of this issue is to move `RequestContextExtension.hook()` to `RequestContext.hook()` and stabilize it.

**Comment by my4-dev** [comment]
@ikhoon : There is an `hook()` method at [NonWrappingRequestContext.java#L272](https://github.com/my4-dev/armeria/blob/40dd139a531a7c6c59438ff772859e0f24df6476/core/src/main/java/com/linecorp/armeria/internal/common/NonWrappingRequestContext.java#L272) and `NonWrappingRequestContext` is inherited by `DefaultClientRequestContext` and `DefaultServiceRequestContext`.

I think it would be good to use this method like the following.
```java
final DefaultServiceRequestContext reqCtx = ...
reqCtx.hook(config.contextHook());
```

Is it needed to implement `hook()` method in `RequestContext`?

**Comment by ikhoon** [comment]
No, we don’t reimplement it. We just move up the method from RequestContextExtension to RequestContext so that every user could use the API.
