### ISSUE TITLE
Expose the server-side metrics programmatically

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4992]
Metrics related to the server, especially connection and request, are not exposed as API. If these values are exposed, users will be able to implement more sophisticated graceful shutdowns such as stopping the server when there are no pending requests.
```java
public class ServerMetrics {

    public int pendingRequests();
 
    public int activeRequests();

    public int activeConnections();
    ....
}

Server server = ...;
ServerMetrics metrics = server.serverMetrics();
```

Pending requests can increment the headers when they are received.
https://github.com/line/armeria/blob/145bc0c5a9f28d8e88f5df492ba4f05f541d3548/core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java#L102-L103
The value will be decreased when they are handed over to the service.
https://github.com/line/armeria/blob/145bc0c5a9f28d8e88f5df492ba4f05f541d3548/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L362-L363
In the case of `ExchangeType.UNARY` or `ExchangeType.RESPONSE_STREAMING`, buffering is performed until the entire body is received, so it will be counted as pending requests until `END_OF_STREAM` is received.

**Comment by seonwoo960000** [comment]
Please assign it to me ~ 🥺

**Comment by seonwoo960000** [comment]
Hi @ikhoon, thank you for the detailed explanation. 
I wonder if this feature should consider `Http1RequestDecorder` as well 🤔 . To my understanding, armeria collects all the request related objects if the request is an aggregating request(referenced the code below) 

`Http1RequestDocoder.java` 
```
// An aggregating request will be fired after all objects are collected.
if (!req.needsAggregation()) {
    ctx.fireChannelRead(req);
}
```

So if http1 request is a request that requires aggregation, then is the state of the request is a `pending` ? And if it is, should we consider http1 while implementing this feature ?

**Comment by ikhoon** [comment]
Right. The link to `Http2RequestDecoder` was an example. We should consider both HTTP/1 and HTTP/2.

**Comment by seonwoo960000** [comment]
@ikhoon ! Thank you for the confirmation. May I work on this issue ?

**Comment by minwoox** [comment]
`activeConnections`: https://github.com/line/armeria/blob/9061e241961c806951dd855be65fd871131a1835/core/src/main/java/com/linecorp/armeria/server/ConnectionLimitingHandler.java#L50

**Comment by minwoox** [comment]
Sorry @seonwoo960000, this issue has been assigned to a participant for the internal sprint that you've experienced. 😆

**Comment by seonwoo960000** [comment]
@minwoox that's a great news. Hope a new contributor is added to Armeria 😄
