### ISSUE TITLE
Programmatically configured options on `ServerBuilder` are overridden by `ArmeriaSettings`

### ISSUE THREAD

**Issue by KarboniteKream** [line/armeria#5009]
When using the `spring-boot{2,3}-autoconfigure` library, the provided `ArmeriaSettings` autoconfiguration is overridding any user-supplied configuration in code.

For example, when using `builder.gracefulShutdownTimeout(x, y)`, the provided values are applied to`ServerBuilder`, but before the server is built, they're overwritten by the autoconfiguration classes.

This can be reproduced by setting a breakpoint here:
https://github.com/line/armeria/blob/2e506361b64356d04dcae0eebce155dc8adf3743/core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java#L824-L825

Then, you should set a custom value here:
https://github.com/line/armeria/blob/2e506361b64356d04dcae0eebce155dc8adf3743/examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/HelloConfiguration.java#L21-L24

Once the application is started, you can observe the provided value being overriden by `ArmeriaSettings`.

As a temporary workaround, you can inject `ArmeriaSettings` and use `setGracefulShutdownQuietPeriodMillis()`

**Comment by ikhoon** [comment]
Some users may not want to override the values provided by `ArmeriaSettings`.
How about adding a flag that determines whether the value of Armeriasettings can be overridden?

If `overridable` is set to `true`, `ArmeriaSettings` will be applied before `ArmeriaServerConfigurator` is applied. 
```yaml
armeria:
  overridable: true 
```

@KarboniteKream Can this approach meet your requirements?

**Comment by jrhee17** [comment]
> If overridable is set to true, ArmeriaSettings will be applied before ArmeriaServerConfigurator is applied.

So if `overridable: true`, then which settings will be overridable? I think we should clearly define which settings are overridable if we choose to go with this option.

> Some users may not want to override the values provided by ArmeriaSettings.

Overall I thought it is reasonable that configuration properties are overridden programmatically. I'm curious what kind of scenario/properties users may not want to override  😄

**Comment by ikhoon** [comment]
If I wrote a novel... Let's say an `ArmeriaServerConfigurator` bean is injected by other modules or libraries. The code owner may not want `ArmeriaServerConfigurator` to change. But it would not be the normal case.

> I think we should clearly define which settings are overridable if we choose to go with this option.

Good point. `ArmeriaServerConfigurator` couldn't override some settings, such as decorators or internal services.

Thinking about it again, it seems that it is sufficient to modify to apply `ArmeriaSettings` first and then apply `ArmeriaServerConfigurator` later.

**Comment by jrhee17** [comment]
> If I wrote a novel... Let's say an ArmeriaServerConfigurator bean is injected by other modules or libraries. The code owner may not want ArmeriaServerConfigurator to change. But it would not be the normal case.

I agree this may be a case.
Having said this, I think spring provides enough customization (e.g. disabling beans, turning off autoconfiguration, etc.) so that we don't have to worry about this too much

**Comment by KarboniteKream** [comment]
> Can this approach meet your requirements?

That would work, but I agree with @jrhee17. I would expect `ArmeriaSettings` be the global defaults (which I can modify on a per-application basis), but be able to programmatically override it for specific services.

About `ArmeriaServerConfigurator` beans, hopefully the module/library would provide the configuration classes that can either be disabled or imported on demand, and not have major impact.

That's just my two cents. I'll trust your final decision, since you have more experience in this area.

**Comment by minwoox** [comment]
@KarboniteKream My apologies for the delay in addressing this. I have created a PR to resolve this issue. PTAL. 🙇
