### ISSUE TITLE
Add a builder for `ServerListener`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5031]
Discord thread: https://discord.com/channels/1087271586832318494/1087272728177942629/1129037723643166792

It would be nice to add builder methods for `ServerListener`.
```java
final var executor = Executors.newSingleThreadExecutor();
var listener = 
  ServerListener
    .builder()
   .whenStopping((s) -> {
     executor.shutdown();
   })
  .build();

Server
  .builder()
  .serverListener(listener);
```

In addition to the builder methods, we can add some useful factory methods that perform a specific actions when a server is started or stopped.
```java
public interface ServerListener {

  static ServerListener wrap(Executor executor) { ... }

}
```

@jmadureira suggested all ideas and I just rewrote them.

**Comment by ikhoon** [comment]
I realized that we already have `ShutdownSupport` that stops an executor when a server stops.
https://github.com/line/armeria/blob/669f525ec1e05d8e3b3b0aa724b070fc6350bb1f/core/src/main/java/com/linecorp/armeria/server/ShutdownSupport.java#L38-L38
It may be better to sharpen `ShutdownSupport` API and make it a public API.

**Comment by trustin** [comment]
```java
public interface EventListener {
  EventListener withExecutor(Executor executor);
}

public interface ServerListener extends EventListener { ... }

public interface SomeOtherListener extends EventListener { ... }
```

**Comment by tomatophobia** [comment]
@ikhoon 
Hi! If I understand the issue and Discord conversation correctly, It seems to be suggesting creating a `ServerListener` to gracefully stop the `ExecutorService` running in the background in response to the shutdown of the Armeria server.

However, it seems that we can handle this using the `whenStopping` method, as written in the issue. Could you explain what the required "builder method" is?

I understand the need for the factory method (ShutdownSupport#of). So, is it just a matter of creating an appropriate factory method?

**Comment by ikhoon** [comment]
> Could you explain what the required "builder method" is?

Good question. Sometimes, builder methods with fluent chaining might be convinient to implement users’ business logic. Additionally, builder pattern could avoid breaking changes when a new method is added the interface. It could happen in an unstable API or major upgrade. 

> So, is it just a matter of creating an appropriate factory method? Or, are there any missing features in the whenStopping method?

No, we won’t fix or add a new feature to whenStopping. The aim of this issue is to add some utility class and builder method to easily close some tasks or objects when a server stops.

**Comment by tomatophobia** [comment]
Thank you! May I handle this issue?

**Comment by ikhoon** [comment]
Yes, please!

**Comment by tomatophobia** [comment]
@ikhoon Thanks! I'm trying to sharpen `ShutdownSupport` API now. Below is the current code of method.
```
static ShutdownSupport of(ScheduledExecutorService executor) {
    requireNonNull(executor, "executor");
    return () -> {
        // omitted some parts
        e.shutdown();

        // omitted some parts
        while (!e.isTerminated()) {
            try {
                e.awaitTermination(1, TimeUnit.HOURS);
            } catch (InterruptedException ignore) {
                interrupted = true;
            }
        }
        // omitted some parts
        return UnmodifiableFuture.completedFuture(null);
    };
}
```
I have omitted some parts of the code. The method returns `() -> CompletableFuture<void>`. The returned function appears to execute asynchronously, but in reality, it synchronously waits for the executor to finish and then returns the final effect. Therefore, when implementing `ServerListener` using this approach, the server synchronously waits for the executor to complete.

Depending on the user's requirements, there may be a need to adjust this behavior. Is it appropriate for the Armeria server to synchronously wait for the external executor's termination? Or, should we provide users the both synchronous and asynchronous methods for waiting?

**Comment by ikhoon** [comment]
> The returned function appears to execute asynchronously, but in reality, it synchronously waits for the executor to finish and then returns the final effect.

It is a good question. `CompletableFuture` may provide parallel execution for closing tasks. It would make a server stop quickly. But that said, I am also unsure it is pratically useful in the real world.

I think it would not be difficult to convert from synchronous to asynchronous. Let's implement a synchronous version and listen to other fork's opinions in the review process.
