### ISSUE TITLE
Specify a client TLS key pair without `ClientFactory`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5033]
A TLS key pair is used to authenticate a client's access. If a client needs several endpoints that use different client certificate authentications, `ClientFactory` should be created as many as the number of certificates.

`ClientFactory` has its own connection pool. If many `ClientFactory`s are made, it would be connection leaks. It's not a scalable implementation pattern.

I proposed to specify a TLS key pair on the client side with `ClientOption` so that users can set a new certification when creating a new `WebClient` without a new `ClientFactory`.

**Comment by my4-dev** [comment]
Hi, @ikhoon . I have a question about this Issue.
I consider implementing new APIs to specify a client TLS key pair in ClientOption for several endpoints.
What should we use to distinguish which client TLS key pair corresponds to which endpoint, URI or anything else?

**Comment by ikhoon** [comment]
Good question. I realized that this issue is more complex than I thought at first. The two main changes for this issue will be:
- Design a new API for TLS key pair and their provider.
	```java
	public interface TlsProvider {
	  TlsKeyPair provide(String hostname);
	
	  default TlsKeyPair orElse(TlsProvider other) { 
	    /* compose two TlsKeyPairs */ 
	  }
	}
	
	public class TlsKeyPair {
	  private PrivateKey privateKey;
	  private List<X509Certificate> keyCertChain;
	}
	
	public class ClientOptions {
	  public static final ClientOption<TlsProvider> TLS_PROVIDER =
	    ClientOption.define("TLS_PROVIDER", ..TlsProvider.empty());
	}
	```
- Refactor `HttpChannelPool` and related low-level classes to dynamically choose a TLS key pair when establishing a connection. Currently a `SslContext` is statically bound when a `ClientFactory` is created.
https://github.com/line/armeria/blob/7375dda034934eb5e3b937db18770caccb858b6b/core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java#L95-L99
