### ISSUE TITLE
Revive the legacy debug form

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5059]
I got a report from a LINE internal user:

> Hello, I noticed there is a UI change for the armeria internal docs page, where we can no longer send a request by scrolling down on the endpoint information view, and need to click "Debug" to open a pop-up view. I was wondering, what is the main reason for this change?
> 
> I think the main issue is when I need to copy and paste / reference endpoint definitions while writing the request. In the old view, we had the option to use the "Debug" pop up if we wanted a larger view, but now that is the only way to send a request.

I think we don't have to provide only one of the two debug forms. We may render the legacy debug from on the bottom of the method page while keeping the `Debug` button to show a debug modal.

**Comment by Dogacel** [comment]
Yes it makes sense to have both forms 👍 

I wonder what is `reference endpoint definitions `?

I was expecting autocomplete functionality to help a lot while writing the request as you will see documentation and field names while you type. I know auto complete is limited to gRPC, Thrift and GraphQL maybe we can autocomplete more stuff like endpoint paths, headers etc 😆 WDY think?

**Comment by ikhoon** [comment]
> I wonder what is reference endpoint definitions ?

I guess some users want to see the method and request object definitions/specifications while writing the requests.

> I was expecting autocomplete functionality to help a lot while writing the request as you will see documentation and field names while you type. I

Totally agreed. Autocomplete itself could be documentation that will make users write requests without references.

**Comment by jrhee17** [comment]
Resolved by #5072
