### ISSUE TITLE
Allow a user to specify alternate success/failure logic when building HttpAuthService with HttpAuthServiceBuilder

### ISSUE THREAD

**Issue by trustin** [line/armeria#506]
`HttpAuthService` has two protected methods that allows a user to override the default behavior of when authentication succeeds or fails: `HttpAuthService.onSuccess()` and `HttpAuthService.onFailure()`.

However, it is impossible for a user to override the default behavior when building it using `HttpAuthServiceBuilder`. A user has to extend it which is less convenient.

We could define a callback interface like the following so that a user can specify it when building with `HttpAuthServiceBuilder`:

```java
public interface HttpAuthHandler { // better name?
    static HttpAuthHandler DEFAULT = new HttpAuthHandler() {
        @Override
        public HttpResponse onSuccess(ServiceRequestContext ctx, HttpRequest req) throws Exception {
            return delegate().serve(ctx, req);
        }

        @Override
        public HttpResponse onFailure(ServiceRequestContext ctx, HttpRequest req, @Nullable Throwable cause)
            throws Exception {
            // Log the cause if necessary.
            final DefaultHttpResponse res = new DefaultHttpResponse();
            res.respond(HttpStatus.UNAUTHORIZED);
            return res;
        }
    };

    HttpResponse onSuccess(ServiceRequestContext ctx, HttpRequest req) throws Exception;
    HttpResponse onFailure(ServiceRequestContext ctx, HttpRequest req, @Nullable Throwable cause)
            throws Exception;
}
```

**Comment by anuraaga** [comment]
I was looking into this, and another isssue is that extending `HttpAuthService` means losing out on the default authorization logic. What do you think about merging `HttpAuthServiceImpl` into `HttpAuthService`? Would anyone ever need a different implementation of `authorize`, considering it supports the very general `Authorizer<HttpRequest>`?
