### ISSUE TITLE
Provide an easy way to redirect a path with no trailing slash

### ISSUE THREAD

**Issue by trustin** [line/armeria#51]
For example, when a user adds a service under `/mypath`, the server will only dispatch the request whose path starts with `/mypath/` and not `/mypath`.

A user is expected to write a simple redirection service that redirects `/mypath` to `/mypath/` but it's not very user-friendly. We could provide a service implementation for this, but it's still not user-friendly enough in my opinion.

We could perhaps modify `HttpServerHandler` so that:

- if the path does not end with '/' and there's no matching service entry,
  - it checks if there's any matching service entry with `path + ''/'`
    - if there's a match, respond with a redirect

This is related with #45

**Comment by anuraaga** [comment]
+a million!
