### ISSUE TITLE
Implement POST method for HttpHealthCheckService that overrides the healthiness

### ISSUE THREAD

**Issue by trustin** [line/armeria#511]
A user sometimes want to override the healthiness reported by `HttpHealthCheckService` when the healthiness determined by `HttpHealthCheckService` automatically is not something expected.

It would be useful to have the three operations:

- override to 'healthy'
- override to 'unhealthy'
- do not override

/cc @yuinacor

**Comment by yuinacor** [comment]
Do not override should returns 200 and that's status?
`HttpHealthCheckService` already has that operation.

I don't understand why `do not override` is requires for this service.

**Comment by trustin** [comment]
Let's say you want to exclude your Armeria server instance from the cluster by overriding the healthiness to 'off' (or false). Once you are done with some runtime maintenance, you'll want to turn the override off (back to automatic mode.) Note that you can't override the healthiness to 'on' (or true) in this case because you cannot take advantage of the graceful shutdown feature Armeria provides.

**Comment by yuinacor** [comment]
My implementation not updates all heathiness. It changes `HttpHealthCheckService`'s own health cheker only.
I think, each health checker should check some specific status, so overriding all status is hard to check that.

So, we don't have to `do not override` for this scope.

**Comment by trustin** [comment]
I missed that it only updates its own `SettableHealthChecker`. i.e. there's no need for 'do not override'

**Comment by minwoox** [comment]
Can we close this? @trustin @yuinacor

**Comment by trustin** [comment]
Yes.

**Comment by trustin** [comment]
Thanks again, @yuinacor !
