### ISSUE TITLE
Add support for Snappy and Zstd content compression

### ISSUE THREAD

**Issue by trustin** [line/armeria#5125]
We currently support gzip, deflate and brotli content compression, and we could add more for even more interoperability with the servers that use other compression algorithms.

We could add support for Snappy and Zstd by updating `StreamDecoderFactory`, `HttpEncoders` and `FileService.ContentEncoding`.

**Comment by sindhunaydu** [comment]
hi @trustin, I would like to work on this issue, can you assign it to me?

**Comment by trustin** [comment]
@sindhunaydu For sure! Please go ahead :bow:

**Comment by sindhunaydu** [comment]
Hi @trustin I'm new to this and would appreciate some guidance. I started looking into the 3 classes that you mentioned above. Apart from updating those classes, do I also need add the following, 
- SnappyOutputStream (similar to BrotliOutputStream)
- SnappyStreamDecoder (similar to BrotliStreamDecoder)
Before I start implementing the OutputStream and StreamDecoder classes, I want to make sure if there needs to be a separate implementation for Snappy and Zstd or if I should reuse Brotli. Thanks!

**Comment by trustin** [comment]
@sindhunaydu I feel like separate implementations will be fine. If you find that there are quite some common code among them, you might want to introduce some abstract class that those classes will extend from. What do you think?

**Comment by trustin** [comment]
By the way, are you planning to add some dependencies to support the compression algorithms? If so, what would they be?

**Comment by sindhunaydu** [comment]
Thanks @trustin, I will look into implementing an abstract class if there is redundant code. Will think about it some more.

How about these dependencies? 
1. Snappy - https://mvnrepository.com/artifact/org.xerial.snappy/snappy-java (github link -  https://github.com/xerial/snappy-java)
2. Zstd - https://mvnrepository.com/artifact/com.github.luben/zstd-jni (github link - https://github.com/luben/zstd-jni)

**Comment by trustin** [comment]
Sounds good to me. Looking forward to your PR!

**Comment by sindhunaydu** [comment]
Hi @trustin, I'm running into an issue that I dont know how to fix and would like get some guidance. I was able to implement the Snappy compression. With ZSTD, I was unable to find any `ChannelHandler` (ZstdFrameDecoder) type class in the dependencies. 

This is where I'm trying to use the `ZstdFrameDecoder` (of type ChannelHandler) but there is no such or similar implementation -
https://github.com/sindhunaydu/armeria/blob/c652ad18890d687d22b323219ecb77e127d54a3b/core/src/main/java/com/linecorp/armeria/common/encoding/StreamDecoderFactories.java#L78C51-L78C51

**Comment by trustin** [comment]
Ah, I see. Then how about focusing on Snappy compression for now, until Netty adds one for zstd?

**Comment by sindhunaydu** [comment]
@trustin sounds good!

**Comment by sindhunaydu** [comment]
@trustin I'm close to being done, following tests are failing because for SNAPPY the decode0 is coming up as empty (0B), 

1. DecoderLengthLimitTest > decodedDataShouldNotExceedLengthLimit(HttpEncodingType) > [4] encodingType=SNAPPY FAILED

Error: Expected :"1111111 ..."
Actual   :""

2. DecoderLengthLimitTest > chunkedDataShouldNotExceedLengthLimit encodingType=SNAPPY FAILED

Error: Expected :"01234567891011121314151617181 ..."
Actual   :""

I'm currently debugging these issues, my guess is `toStringUtf8()` is not implemented for SNAPPY.

**Comment by trustin** [comment]
@sindhunaydu Do you need help troubleshooting it? Let me take a look once you share your branch! :bow:

**Comment by sindhunaydu** [comment]
@trustin sorry couldnt get back to you sooner. This is my working branch. I know that there are some formatting changes and license info that needs to be added. The two tests that are failing are, `chunkedDataShouldNotExceedLengthLimit` and  `decodedDataShouldNotExceedLengthLimit` in `DecoderLengthLimitTest.java`. 

https://github.com/line/armeria/compare/main...sindhunaydu:armeria:main
