### ISSUE TITLE
Refactor Bootstrap retrieval in `HttpChannelPool`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#5129]
We now have fairly complex logic for creating and getting `Bootstrap`s in `HttpChannelPool`.
It's 3-dimensional access that depend on:
- inet or unix
- session protocol; and
- WebSocket or not

We need to extract this data structure and lookup logic into its own class to simplify it.
```
final class Bootstraps {

  Bootstraps() {...} // Initialize data structure whose key is composed of the above 3 dimensions.

  Bootstrap get(SocketAddress remoteAddress, SessionProtocol desiredProtocol,
          SerializationFormat serializationFormat) {...}
}
```

**Comment by russell-yoo** [comment]
hi @minwoox. I want to work on the issue, can you assign this issue to me?

**Comment by minwoox** [comment]
Of course, @russell-yoo! 😉 
We have to merge #4972 first by the way. I will tell you after I merge the PR. Please stay tuned. 😄

**Comment by minwoox** [comment]
@russell-yoo, #4972 is merged. This is all yours. 😆

**Comment by russell-yoo** [comment]
@minwoox. Thank you. I'll try to refactor bootstrap retrieval.
