### ISSUE TITLE
Support micrometer-context-propagation

### ISSUE THREAD

**Issue by be-hase** [line/armeria#5145]
micrometer-context-propagation is now available.
https://github.com/micrometer-metrics/context-propagation

And the reactor supports micrometer-context-propagation.
https://spring.io/blog/2023/03/30/context-propagation-with-project-reactor-3-unified-bridging-between-reactive

Currently, Armeria provides [RequestContextHooks](https://github.com/line/armeria/blob/5f9c1b679d1581a34dcd13fa56a5a22290e3d916/reactor3/src/main/java/com/linecorp/armeria/common/reactor3/RequestContextHooks.java), which could be replaced by providing an extension to micrometer-context-propagation.

like this:

```kotlin
// Sorry, I wrote it in kotlin.

class ArmeriaRequestContextAccessor : ThreadLocalAccessor<RequestContext> {
    override fun key(): Any {
        return KEY
    }

    override fun getValue(): RequestContext? {
        return RequestContextUtil.get()
    }

    override fun setValue(value: RequestContext) {
        RequestContextUtil.getAndSet<RequestContext>(value)
    }

    override fun setValue() {
        // NOOP
    }

    override fun restore(previousValue: RequestContext) {
        RequestContextUtil.getAndSet<RequestContext>(previousValue)
    }

    override fun restore() {
        RequestContextUtil.pop()
    }

    companion object {
        val KEY = ArmeriaRequestContextAccessor::class.java
    }
}
```

Then, users can execute the following code.

```kotlin
fun main(args: Array<String>) {
    ContextRegistry.getInstance().registerThreadLocalAccessor(ArmeriaRequestContextAccessor())
    Hooks.enableAutomaticContextPropagation()
    
    // run application
}
```

From the above article, it seems to me that the performance aspect has been devised. ( I haven't measured it but...

**Comment by jrhee17** [comment]
Took a quick look through the API/source and looks promising! 👍

**Comment by trustin** [comment]
@chickenchickenlove will work on it :smile:

**Comment by be-hase** [comment]
wow, sounds good.
I think it will probably improve performance.

( Sorry I didn't contribute with a pull request. haha
