### ISSUE TITLE
Firefox fails to establish a websocket connection to Armeria Websocket Server

### ISSUE THREAD

**Issue by thomasbruggink** [line/armeria#5165]
The following code in Firefox fails with a `BAD_REQUEST` when connecting to an Armeria Websocket Server:
```
const socket = new WebSocket("ws://localhost:8080/chat")
socket.addEventListener("open", (event) => {
    console.log(event)
})
```
The reason for the rejection is that Armeria checks for the presence of the `Connection` header which must contain the value `Upgrade`. However Firefox sends the `Connection` header with the `keep-alive, Upgrade` value.
The websocket specification ([section 4.1 page 18](https://datatracker.ietf.org/doc/html/rfc6455#section-4.1) says `The request MUST contain a |Connection| header field whose value MUST include the "Upgrade" token.` So I believe it's allowed to have multiple values in here.

Removal of the `Connection` header happens here: https://github.com/line/armeria/blob/main/core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java#L732
Rejection of the request happens here: https://github.com/line/armeria/blob/main/core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketUtil.java#L42

**Comment by yeomiji** [comment]
> The reason for the rejection is that Armeria checks for the presence of the Connection header which must contain the value Upgrade. However Firefox sends the Connection header with the keep-alive, Upgrade value.
The websocket specification ([section 4.1 page 18](https://datatracker.ietf.org/doc/html/rfc6455#section-4.1) says The request MUST contain a |Connection| header field whose value MUST include the "Upgrade" token. So I believe it's allowed to have multiple values in here.

Thanks for the analysis! I believe this was pointed out in the review, but we thought we could handle it later.
However, if firefox is sending multiple values by default, I guess we have a good reason to prioritise this 👍

**Comment by jrhee17** [comment]
> The reason for the rejection is that Armeria checks for the presence of the Connection header which must contain the value Upgrade. However Firefox sends the Connection header with the keep-alive, Upgrade value.
The websocket specification ([section 4.1 page 18](https://datatracker.ietf.org/doc/html/rfc6455#section-4.1) says The request MUST contain a |Connection| header field whose value MUST include the "Upgrade" token. So I believe it's allowed to have multiple values in here.

I think we were aware of this issue, but we didn't think clients would be sending multiple connection header values by default. Thanks for the analysis 👍   We should get this fixed
