### ISSUE TITLE
Easily mask sensitive headers from request logs

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5175]
The default `LogFormatter` produces all headers by default. Users may not want to log sensitive information `Authorization` or session information in cookies.

Headers can be filtered by `requestHeadersSanitizer((ctx, headers) -> ...)`. But that said, it is inconvenient to implement a sanitizer. It should be useful if users can set a blacklist of headers that should be masked.
```java
LoFormatter
  .builderForText()
  // Mask the specified headers.
  .maskHeaders(Authorization, Cookie...)
```

We can also provide the default blacklist to mask request and response headers.

**Comment by seonwoo960000** [comment]
I've questions regarding this issue. 
- Should we mask request and response headers ? 
- How should we mask headers? Can we simply replace the header values to `*****` ?

**Comment by ikhoon** [comment]
> Should we mask request and response headers ?

Right. We need to mask both headers. `.maskHeaders()`, `.maskRequestHeaders()`, `.maskResponseHeaders()` could be added for convinience. 

> How should we mask headers? Can we simply replace the header values to ***** ?

`****` sounds good to me.

> Should we apply masking even when requestHeadersSanitizer is present already?

I don't think so. They are mutually exclusive. An `IllegalStateException` could be raised if both `maskHeaders` and `requestHeadersSanitizer` are set.

**Comment by trustin** [comment]
Related: #5286

**Comment by seonwoo960000** [comment]
Sorry for the late work. I've applied the comments, thank you 🙇

**Comment by codefromthecrypt** [comment]
I think this should help cleanup zipkin. thanks! https://github.com/openzipkin/zipkin/blob/4f263def864b2117bcfbb9f8cfbc73e8c5f077be/zipkin-server/src/main/java/zipkin2/server/internal/elasticsearch/HttpClientFactory.java#L67-L73
