### ISSUE TITLE
The @Description annotation in super class/interface does not work

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5195]
### Discussed in https://github.com/line/armeria/discussions/5192

<div type='discussions-op-text'>

<sup>Originally posted by **evgeny-mordyasov** September 20, 2023</sup>
The `@Description` annotation does not work when it is specified in the service interface. When I specify the annotation in the class, then everything is ok. I want to document my services in the interface so as not to clutter the code in the implementation with unnecessary annotations.

My interface:

```
public interface RestClientService {

    HttpResponse findByEntityId(@Description("client id") Long entityId);
}

```

My class:

```
public class RestClientServiceImpl implements RestClientService {

    private final ClientService service;

    public RestClientServiceImpl(ClientService service) {
        this.service = service;
    }

    @Get("/{entityId}")
    @Override
    public HttpResponse findByEntityId(@Param Long entityId) {
       ...
    }
}
```

My Config:

```
@Configuration
public class ArmeriaConfig {

    @Bean
    public ArmeriaServerConfigurator armeriaConfigurator(RestClientService restClientService) {
        return serverBuilder ->
                serverBuilder
                        .serviceUnder("/docs", docService());
    }

    private DocService docService() {
        return DocService.builder().build();
    }
}
```

Dependency maven:

```
<dependency>
    <groupId>com.linecorp.armeria</groupId>
    <artifactId>armeria-spring-boot3-starter</artifactId>
    <version>1.25.2</version>
</dependency>
```</div>

**Comment by minwoox** [comment]
Reference:
https://github.com/line/armeria/blob/d30db0c88d178468c3bb03a4e1d920b4c7a897b9/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java#L594
https://github.com/line/armeria/blob/d30db0c88d178468c3bb03a4e1d920b4c7a897b9/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java#L156-L158
