### ISSUE TITLE
Allow customizing server-side timeout response

### ISSUE THREAD

**Issue by trustin** [line/armeria#521]
A service may want to provide its own timeout reponse instead of the default '503 Service Unavailable'.

/cc @anuraaga

**Comment by abdulazizali77** [comment]
Hi @trustin , can i have a shot at this?

**Comment by trustin** [comment]
Sure, you can. :-)

**Comment by trustin** [comment]
I was thinking of adding a default method to `Service` whose implementation merely throws `ServiceUnavailableException`. e.g.

```java
public interface Service<I extends Request, O extends Response> {
    ...
    default O handleTimeout(ServiceRequestContext ctx, I request) throws Exception {
        return ServiceUnavailableException.get();
    }
}
```

**Comment by abdulazizali77** [comment]
thanks for the hint @trustin , i still havent poked through the code yet! :)

**Comment by abdulazizali77** [comment]
hi @trustin i understand the code a little better now,
-do you think we should default implementations for some of the concrete services? some of the inetresting ones...
`DocService`
`SimpleCompositeService`
`HttpFileService`
`HttpHealthCheckService`
`DynamicHttpService`
`MappedDynamicFunction`

-do you think we should provide other default handlers for other response codes (eg 500, 504 )?
-do you think we should have an abstract server error handler ? or a server handler map?

**Comment by trustin** [comment]
Thanks for looking into, @abdulazizali77. Great questions.

> Do you think we should have default implementations for the concrete services?

This question makes me think it may not be a good idea to add a new method to `Service` as I suggested above. It would be great if we can write this as a decorator, but request timeout is handled in a lower layer unfortunately.

So, what do you think about defining a configuration property that translates an exception into a response? e.g. `ServiceUnavailableException` or `RequestTimeoutException` could be translated into 503 by default.

> Do you think we should provide other default handlers for other response codes?

We don't need to alter the HTTP response produced by a `Service`. If that's the case, a user could do that using a decorator. What we are trying to achieve is to provide an extension point where a decorator cannot manipulate.

> Do you think we should have an abstract server error handler or a server handler map?

Yeah, I think so, as I answered in the first question. Please feel free to let me know if you have a better idea. :-)

**Comment by anuraaga** [comment]
Was thinking about this and wonder - should the ability to set a timeout handler be on RequestContext itself? There might be additional logic like releasing resources done on timeout that would be difficult in a service-level configuration.

**Comment by anuraaga** [comment]
Hello @trustin @abdulazizali77 any thoughts or plan on this? Without it I can't handle timeouts correctly in gRPC and it's the last significant point to finish up armeria-grpc :)

**Comment by trustin** [comment]
I can take over if @abdulazizali77 doesn't have time for this. Or you can. :-)

**Comment by abdulazizali77** [comment]
apologies didnt have time to think this over (since 23 days ago!) If there is time before the release/milestone, im still interested, but still unsure of the best approach
@trustin
-If we were to create a map from Exception to handler, would we add this into /through `ServerConfig`?
-would we do most of the handling in `Server.start` and potentially specifically in any `Service.serve` eg `AbstractHttpService` ?

@anuraaga do you think something `DefaultServiceRequestContext.setRequestTimeoutChangeListener` should be defined higher up the chain? What is your basic idea?

**Comment by anuraaga** [comment]
@abdulazizali77 Yep, that's basically my idea. I think there is a need to allow per-request handling of deadlines. Some approaches I've thought of are

- `DefaultServiceRequestContext.setRequestTimeoutChangeListener`
- `Service.withDeadlineHandler((..., ctx, ...) -> ...)` - in this case I'd make sure per-request state is stored into `ctx` via `RequestContext#attr` at the beginning of a request.

No strong opinion on either approach. I think a map from Exception to handler is closer to the second, and would be more generic than something deadline-specific, but it is important to allow the handler to access the `ctx` to take care of any request-specific state as needed (e.g., to clear up non-GC'd memory buffers).

**Comment by anuraaga** [comment]
@abdulazizali77 Just wondering, do you think you'll get to take a look at this? If not, I'd like to take over and crank it out next week

**Comment by abdulazizali77** [comment]
@anuraaga @trustin apologies, havent had enough time to spend on this.
The direction is clearer to me now, would `ServiceConfig` have sort of `ResponseMapping` like `PathMapping`
@anuraaga since this seems to be high priority, i think you would have to take it back

**Comment by trustin** [comment]
Fixed by @anuraaga in a rather interesting yet more powerful way. :-)
