### ISSUE TITLE
Mask well known HTTP headers that contain sensitive information by default

### ISSUE THREAD

**Issue by trustin** [line/armeria#5286]
Our log formatter and `DefaultRequestLog.toString*()` by default logs all the HTTP headers without masking anything. I'd be more sensible behavior to mask some well known HTTP headers such as `Authorization` and `(Set-)Cookie`.

**Comment by trustin** [comment]
Related: #5175

**Comment by Pooja1672** [comment]
Hello @trustin , I would like to work on this issue ? Can you assign this to me.

**Comment by seonwoo960000** [comment]
I've applied the comments! Sorry for late work 
https://github.com/line/armeria/pull/5188

**Comment by ikhoon** [comment]
Fixed by #5188
