### ISSUE TITLE
Show/Throw Error if register Service to the same path

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#529]
When a user register multiple service to the same path through `ServerBuilder#serviceAt`, armeria creates a `Server` with services but PathMappings only map a request to a service that is registered first.
```java
    @ClassRule
    public static final ServerRule server = new ServerRule() {
        @Override
        protected void configure(ServerBuilder sb) throws Exception {
            sb.serviceAt("/api", new EchoService("1"))
              .serviceAt("/api", new EchoService("2"))
              .serviceAt("/api", new EchoService("3"));
        }
    };
    @Test
    public void test1() throws Exception {
        try (CloseableHttpClient hc = HttpClients.createMinimal()) {
            final HttpGet req = new HttpGet(server.uri("/api"));
            try (CloseableHttpResponse res = hc.execute(req)) {
                assertThat(EntityUtils.toString(res.getEntity()), is("1"));
            }
        }
    }
    private static class EchoService extends AbstractHttpService {
        private final String s;

        public EchoService(String s) {
            this.s = s;
        }

        @Override
        protected final void doGet(ServiceRequestContext ctx, HttpRequest req, HttpResponseWriter res) {
            res.write(HttpHeaders.of(HttpStatus.OK));
            res.write(HttpData.of(s.getBytes()));
            res.close();
        }
    }
```

It would be better to show message (or throw Exception) when ServerBuilder detects same path.

**Comment by anuraaga** [comment]
I realized I was enjoying the previous behavior by having a framework that registers a default service for a path, but providing a customization point to allow code to customize `ServerBuilder` before it runs, so they could provide a different implementation if needed. The only way to support that now I think is to have an explicit way to disable the default service, which adds some extra noise.

Would it make sense to add a flag to `ServerBuilder` to disable this check, for framework authors?
