### ISSUE TITLE
Build `RequestContext` with `EndpointGroup`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5292]
`ClientRequestContextBuilder` provides a builder method for an `Endpoint`, but no methods for `EndpointGroup`.

The builder method would be useful to test an `EndpointSelector` and `EventLoop` allocation.
```java
ClientRequestContext
  .builder()
  .endpointGroup(group)
  ...
  build()
```

**Comment by ikhoon** [comment]
Sorry, I got confused. We don't need `EndpointGroup` builder method for `ServiceRequestContext`. Let me update the issue description.

**Comment by Leewongi0731** [comment]
Hi, @ikhoon nim! could I take this issue??

**Comment by ikhoon** [comment]
There is a PR in progress. #5298
Could you pick up other issues? 😉

**Comment by Leewongi0731** [comment]
Oh, I didn't see this PR!! I'll look around other issues!
