### ISSUE TITLE
Default native-image config files is not enough for some project.

### ISSUE THREAD

**Issue by yswdqz** [line/armeria#5296]
Starting from version 1.25.0, Armeria has begun to support GraalVM, but there are still some default configurations that are not adequately addressed.

<img width="1511" alt="image" src="https://github.com/line/armeria/assets/74546965/c5d50655-0e18-4ce3-af73-563fcbe58cc9">
<img width="1499" alt="image" src="https://github.com/line/armeria/assets/74546965/48ef8ee9-d32a-4b12-b3f4-7400cc4495bc">

I am trying to compile SkyWalking (which uses Armeria) into a native image and have encountered some issues (the above picture is not all of problems I have found). After running with the native tracing agent, I obtained the following configuration, which successfully compiled and resolved the aforementioned issues.

[native-image.json](https://github.com/line/armeria/files/13328475/native-image.json)

These configurations may not be the simplest, but they do solve the problem. Could you consider incorporating them into the main repository?

**Comment by jrhee17** [comment]
Hi! Sorry about the late comment.

I think it's probably fine to add this to the base configuration, but let me also talk to the other devs tomorrow morning cc. @trustin

**Comment by trustin** [comment]
Thanks a lot for reporting this issue, @yswdqz! At the moment, our native-image configuration is not updated automatically because the configuration generated by the tracing agent is not clean enough, although we hope to automate it in the future. I'll take a look and merge your configuration in the next release. :bow:

**Comment by jrhee17** [comment]
Let me just release a new version with the re-run of the config for now. We can follow up if there are other configs we missed.

**Comment by yswdqz** [comment]
Thank you ! I'm sorry that I don't have time to test it recently. I will test it later.

**Comment by trustin** [comment]
No problem. Please feel free to reopen this issue or open a new one if you find the new version still has a problem. :bow:
