### ISSUE TITLE
Appveyor build flaky

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#530]
I often notice Appveyor build takes forever, and has random failures due to timeouts (e.g., ClosedSessionException). I guess the containers aren't very powerful. If I remember correctly, we requested strong machines from Travis, maybe that'd be a possibility here. Otherwise, how about removing shaded tests from the windows build? I think it's very unlikely that there'd be a windows-only issue with shaded jars, and they add a lot of time / load to the build. I dunno why, but I feel like most flakes on both Travis and Appveyor happen during shaded tests (perhaps time-based throttling).

**Comment by trustin** [comment]
We didn't request a powerful machine to Travis :-) I agree it's annoying to see the failure in Appveyor. Will try to figure out what the actual cause of this once I have time..

**Comment by trustin** [comment]
See #548
