### ISSUE TITLE
[Docs] Omit "$" character when copying code 

### ISSUE THREAD

**Issue by seonWKim** [line/armeria#5322]
Nit, when copying the command by clicking copy button, "$" is included in the clipboard. 
![image](https://github.com/line/armeria/assets/69591622/12662d1b-d4bc-4334-9c7e-e30476f8dedc)

### Result: `$ ./gradlew --parallel build` 

I copied the code to run './gradlew --parallel build', but it was a little bit bothersome because of the inclusion of the '$' symbol. What do you think about copying only the text part without the '$'?

**Comment by ikhoon** [comment]
> What do you think about copying only the text part without the '$'?

It sounds nice.
