### ISSUE TITLE
`RequestContextExportingAppender` has a dependency on `Flags` which partially breaks logging

### ISSUE THREAD

**Issue by KarboniteKream** [line/armeria#5327]
When Armeria is configured with Logback and `RequestContextExportingAppender` with custom headers, and when multiple Netty versions are present in the classpath, logs for `Flags` will be missing.

When the following appender with a custom header is configured in Logback:
```xml
<appender name="ARMERIA_KAFKA" class="com.linecorp.armeria.common.logback.RequestContextExportingAppender">
  <appender-ref ref="KAFKA" />
  <export>req.headers.x-real-ip</export>
</appender>
```

The Logback setup flow will behave as follows:
1. [`setExport()`](https://github.com/line/armeria/blob/a8a9ca2f3baf3f001b73a2decbcc9c38e3da2e23/logback/logback12/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java#L148) is called for `req.headers.x-real-ip`
2. Eventually, we call [`ExportGroupBuilder.requestHeader()`](https://github.com/line/armeria/blob/a8a9ca2f3baf3f001b73a2decbcc9c38e3da2e23/core/src/main/java/com/linecorp/armeria/common/logging/ExportGroupBuilder.java#L127-L132)
3. Following `toHeaderName()`, we reach [this call to `Flags.validateHeaders()`](https://github.com/line/armeria/blob/a8a9ca2f3baf3f001b73a2decbcc9c38e3da2e23/core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java#L991-L993)
4. This initializes the `Flags` class, which initializes `TransportType`, which initializes `TransportTypeProvider`
5. `Flags` will log the values of all flags, and `TransportTypeProvider` will [validate Netty versions](https://github.com/line/armeria/blob/a8a9ca2f3baf3f001b73a2decbcc9c38e3da2e23/core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java#L60-L94) and log a warning in case of inconsistencies

However, since we're still setting up Logback, no appenders are configured on `ROOT` level, so this information will never be logged.

By removing `<export>req.headers.x-real-ip</export>` or using `req.headers.user-agent` (a known and pre-cached header), the call to `Flags.validateHeaders()` never happens, and the `Flags` class is initialized after Logback setup is done. In that case, the logs will appear as expected.

We can probably fix this by breaking the dependency between `RequestContextExportingAppender` and `Flags.

**Comment by jrhee17** [comment]
I haven't been able to analyze the issue in detail, but perhaps we can consider a lazy loading mechanism for each flag value. We have already had multiple issues stemming from cyclic dependency when the `Flags` class is loaded, so I feel like we may want to take a more general approach

```java
boolean VERBOSE_SOCKET_EXCEPTIONS
```
to
```
Supplier<Boolean> VERBOSE_SOCKET_EXCEPTIONS
```

The downside would be we won't be able to print flag values on initialization

**Comment by KarboniteKream** [comment]
I've created a branch for `armeria-examples/spring-boot-webflux` with `logback-spring.xml` that reproduces the issue:
https://github.com/KarboniteKream/armeria-examples/commit/18c834ca00bf78269f9ba9c2284f9897e1901d1f

If you run it as is, you'll only see 3 logs from `Flags`:
```
com.linecorp.armeria.common.Flags        : useOpenSsl: true (default)
com.linecorp.armeria.common.Flags        : Using OpenSSL: BoringSSL, 0x1010107f
com.linecorp.armeria.common.Flags        : dumpOpenSslInfo: false (default)
```

If the line `<export>req.headers.fake-header</export>` is removed or replaced with a well-known header, you'll see all logs for `Flags`:
```
com.linecorp.armeria.common.Flags        : verboseExceptionSampler: ExceptionSampler{rate-limit=10} (default)
com.linecorp.armeria.common.Flags        : verboseExceptions: rate-limit=10 (default)
com.linecorp.armeria.common.Flags        : preferredIpV4Addresses: * (default)
com.linecorp.armeria.common.Flags        : verboseSocketExceptions: false (default)
...
```

**Comment by ikhoon** [comment]
Many thanks for the reproducer. 🙇‍♂️

**Comment by ikhoon** [comment]
The problem was produced with Spring WebFlux module. But Spring MVC didn't have the same issue.
Let me send a patch for that soon.
