### ISSUE TITLE
Convert `RequestTimeoutException` to gRPC `Status` using `GrpcExceptionHandlerFunction`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5329]
The logic converting `RequestTimeoutException` to gRPC `Status` is hard-coded so users can't override the message or customize the `Status`.

https://github.com/line/armeria/blob/d30db0c88d178468c3bb03a4e1d920b4c7a897b9/grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java#L323-L325

Before applying the default logic, we may first apply a user-defined `GrpcExceptionHandlerFunction`.

**Comment by seonwoo960000** [comment]
May I look into the issue? 😄
