### ISSUE TITLE
Make `AnnotatedService` public

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5382]
`AnnotatedService` provides specialized information for annotated services such as `Method`, service instance, the default status, and so on.
However, `AnnotatedService` is an internal API so users should access it unsafely via `ctx.config().service().as(AnnotatedService.class)`

I propose to add `AnnotatedServiceConfig` to provide annotated service-specific information.

```java
public final class AnnotatedServiceConfig extends ServiceConfig {
    ...

    Object serviceObject() {
        return object;
    }

    Method method() {
        return method;
    }

    HttpStatus defaultStatus() {
        ...
    }
    ...
}
```

**Comment by chickenchickenlove** [comment]
Hello, @ikhoon nim. 

I've come up with an idea for a scalable API, although it might be a bit rough. 
By using `enums` and `Maps` together, I expect that it can be extended in various `ServiceConfig`'s Children Classes.

How about this way?

```java
public abstract class ServiceConfig { 
     // Add this abstract method. 
    public <E, T> T getSpecificValue(E field, Class<T> type);
     ...
}
```
- Add abstract method to `ServiceConfig`. all children classes of `ServiceConfig` should implement this method. 
- This method is to produce common interface to get their specific values. (For example, `AnnotatedService`'s `method`)
- `E` means kind of `enum`. `T` means type of values. 


```java
// Add this enum
public enum AnnotedServiceField {
  Method, 
  ServiceObject, 
  DefaultStatus,
  ...
}
```
- Add `enum` for each concrete class of `ServiceConfig` to prevent to forget some fields. 

```java
public class AnnotatedService { 
  
  ...
  // Add this method.
  public Map<AnnotatedServiceField, Object> fieldsToMap(){ 
    final Map<AnnotatedServiceField, Object> maps = Arrays.stream(AnnotatedServiceField.values())
              .collect(Collectors.toMap(v -> v, v -> null));
    
    ...
    maps.put(AnnotatedServiceField.HttpStatus, this.httpStatus);
    maps.put(AnnotatedServiceField.Method, this.method);
    ...

   return maps;
  } 
...
}
```
- In case of `AnnotatedService`, i propose that add `fieldsToMap()` method to return `Map` their specific fields. 

```java
public class AnnotatedServiceConfig extends ServiceConfig {

  ...
  // add this methods.
  private final Map<AnnotatedServiceField, Object> specificConfig;
  public T getSpecificValue(AnnotatedServiceField field, Class<T> type){
      Object field = specifigConfig.get(field);
      return (type) field;
  }
  ...

}
```
- `AnnotatedServiceConfig` should implement abstract method `T getSpecificValue(AnnotatedServiceField field, Class<T> type)`. 


```java
public class ServiceConfigBuilder implements ServiceConfigSetters {
    ServiceConfig build(...) {
        final Map<AnnotatedServiceField, Object> specificFields = service.fieldsToMap()   // Add this code.
        ServiceErrorHandler errorHandler =
                serviceErrorHandler != null ? serviceErrorHandler.orElse(defaultServiceErrorHandler)
                                            : defaultServiceErrorHandler;
        ...
    }
}
```
- In case of `AnnotatedServiceConfig`, `service.fieldsToMap()` can be added to `ServiceConfigBuilder#build(...)` for `specificFields` to be included `AnnotatedServiceConfig`. 


IMHO, The key aspects are as follows:

1. Declare an enum for each Concrete ServiceConfig class to specify certain values.
2. Create a Map that uses the enum as a Key and stores values.
3. The ServiceConfig interface provides a Generic method to retrieve values from the map.

Through this approach, I expect to `ServiceConfig` can produce API that can be extended to multiple concrete class of `ServiceConfig`.

What do you think? 
When you have some free time, please take a look 🙇‍♂️

**Comment by ikhoon** [comment]
I forgot to leave the original motivation for this issue. https://discord.com/channels/1087271586832318494/1087272728177942629/1195732884544299139

**Comment by ikhoon** [comment]
On second thought, it may be simpler just to make `AnnotatedService` `interface` like `GrpcService` and expose it as a public API.
```java
public interface AnnotatedService {

    Object object();

    Method method();

    HttpStatus defaultStatus();

    Route route();
    ...
}
```

**Comment by chickenchickenlove** [comment]
@ikhoon nim, thanks for your comments.
Sound like refactoring, is it right?
