### ISSUE TITLE
`Http2Exception: Frame length: <some large number> exceeds maximum: 16384` when the request/response header size exceeds ~42KB

### ISSUE THREAD

**Issue by Lincong** [line/armeria#5385]
[This PR](https://github.com/line/armeria/pull/5384) contains the repro. Please see its description for how to run it.

### What we know about this issue:

- As subject. The failure is `Http2Exception: Frame length: <some large number> exceeds maximum: 16384` when the request/response header size exceeds ~42KB (whereas the max HTTP/2 header size is set as 96KB).
- It is limited to HTTP/2.
- The failure only happens when TLS is enabled.
- It affects both the request path (`client -> server`) and the response path (`server -> client`). The repro demonstrates this issue in the response path.
- The issue/bug is very likely to be on the sender side. We did an experiment in which we used `curl` to send a simple `GET` request to the server which sends back a response with a large header. The `curl` command fails when the response header size exceeded some threshold (~46KB).
- From my debugging, the frame-length-exceeded exception happens when there are 3 or more frames to transmit response header bytes (> ~46KB). In other words, there must be 1 HEADERS frame and at least 2 CONTINUATION frames. The frame header of the second CONTINUATION frame is missing. The client-side frame reader assumed the first 9 bytes are frame header and tried to decode frame length information from these 9 bytes. However, it ended up interpreting some frame payload bytes as frame length and got a number larger than max frame size (16384 bytes).

### Appendix:
1. A brief context of how HTTP/2 works (in case it is useful): the response header is divided into one or multiple HTTP/2 frames which are transmitted to the client. Each frame has a [9-byte frame header](https://httpwg.org/specs/rfc7540.html#FrameHeader) and a [frame payload](https://httpwg.org/specs/rfc7540.html#FrameSize) (<= 2^14 == 16384 bytes). If response header bytes cannot fit in one frame, multiple frames are used for transmission and the first frame is called [HEADERS frame](https://httpwg.org/specs/rfc7540.html#HEADERS) and the following frame(s) are called [CONTINUATION frame(s)](https://httpwg.org/specs/rfc7540.html#CONTINUATION). Otherwise, only one HEADERS frame is transmitted. [Here](https://docs.google.com/document/d/1coI9xLnMCIgSio2pYPpED1PKiawdB9Eob-Yqh_76dMw/edit#bookmark=id.6wbiizood0ne) is this process in Netty code.

**Comment by Lincong** [comment]
Here is the more detailed reason why I suspect the issue/bug is on the sender side:

I used curl to send a HTTP/2 `GET` request to a server and expect the server to send a response with a large header. In my IntelliJ debugger, I can see that 3 `CONTINUATION` frames were sent because [this code](https://github.com/netty/netty/blob/b1947417b7444326965086b951b75f0128cf7085/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java#L569-L578) was executed 3 times in the do-while loop. However, HTTP/2 traffic captured by my Wireshark setup told a different story: only one `CONTINUATION` frame and the following data cannot be interpreted as HTTP/2 data (as shown below). This is exactly what the Armeria client from this [repro](https://github.com/line/armeria/pull/5384) complained: cannot interpret HTTP/2 frame data due to `Http2Exception: Frame length: <a large number> exceeds maximum: 16384`.

<img width="1505" alt="image" src="https://github.com/line/armeria/assets/9780681/9ce9049f-8e1e-40c1-ab22-61ed53e7f6b2">

**Comment by Lincong** [comment]
Thanks to @minwoox , we found the culprit in Netty and are working on a [fix](https://github.com/netty/netty/pull/13786).

**Comment by minwoox** [comment]
Fixed by https://github.com/netty/netty/pull/13786
Thanks a lot for reporting, @Lincong!
