### ISSUE TITLE
Add RetryingHttpClient

### ISSUE THREAD

**Issue by trustin** [line/armeria#540]
.. which is similar to `RetryingRpcClient`. /cc @taicki @imasahiro

**Comment by minwoox** [comment]
Hi @trustin, can I try this?

**Comment by trustin** [comment]
Sure. Please feel free to take a stab.

**Comment by minwoox** [comment]
Alright! Thanks @trustin.

I went through the streams in #364, and I have a couple of questions before I get started.

It seems that there’s no default limit value for retrying attempt when a client forgets to invoke
<pre><code>withMaxAttempts(int maxAttempts)</code></pre>
Don’t we need to provide a default limit for that? 

Secondly, do I need to take account of Retry-After header?
What if a client who sets Backoff  as NO_DELAY gets the response 503 with 
<pre><code>Retry-After: 120</code></pre>
then the client should ignore its own strategy and follow the response?

**Comment by trustin** [comment]
> Don’t we need to provide a default limit for that?

I agree it's probably a good idea to have a sane default value for this, but it's not part of this issue. Could you file a new issue for this?

> Do I need to take account of Retry-After header?

That's a great question. How about making this configurable? By default, the retrying HTTP client could respect the `Retry-After` header, but a user may want to enforce his/her policy. For example:

    long interval = backoff.nextInterval(numAttemptsSoFar);
    if (respectRetryAfter) {
        interval = Math.max(retryAfterMillis, interval);
    }

**Comment by minwoox** [comment]
SGTM. I will do it in that way :-)
