### ISSUE TITLE
Use 'new DisableOnDebug(new Timeout(..))' in our tests.

### ISSUE THREAD

**Issue by trustin** [line/armeria#542]
By @anuraaga in #541:

> DisableOnDebug to test timeout. My previous attempt at this, if you remember it, failed since it doesn't
> affect Test(timeout = pattern, but for this test I'm only using a global timeout. This is probably a good 
> pattern to use generally in armeria since it makes debugging much easier and removes some of the
> noise on timeouts.

**Comment by KarboniteKream** [comment]
Can this issue be closed?

We already apply a global timeout for JUnit 5 here: https://github.com/line/armeria/blob/master/testing-internal/src/main/resources/junit-platform.properties

Additionally, all JUnit 4 tests already seem to be using `new DisableOnDebug(new Timeout(...))`

**Comment by minwoox** [comment]
Thanks, @KarboniteKream! Yes, we can close this issue. 😄
