### ISSUE TITLE
Is there any way to provide global ExceptionHandler?

### ISSUE THREAD

**Issue by Mina-1316** [line/armeria#5440]
I'm currently trying to create application based on annotation services, and I know there are already a way to provide the Exception handler by [this documentation](https://armeria.dev/docs/server-annotated-service/#handling-exceptions).

Since this configuration is appliable per service, is there any way to provide(or override) default exception handler, like spring boot's `ControllerAdvisor` bean?

in Document linked above:
>If there is no exception handler which is able to handle an exception, the exception would be passed to the default exception handler.

**Comment by ikhoon** [comment]
You can set a custom `ServerErrorHandler` to `ServerBuilder`.
```java
@Bean
public ArmeriaServerConfigurator serverConfigurator() {
    return sb -> sb.errorHandler(myServerErrorHandler);
}
```
- https://javadoc.io/doc/com.linecorp.armeria/armeria-javadoc/latest/com/linecorp/armeria/server/ServerErrorHandler.html
- https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.27.0/com/linecorp/armeria/server/ServerBuilder.html#errorHandler(com.linecorp.armeria.server.ServerErrorHandler)


By the way, it seems good to directly inject `ServerErrorHandler` via a bean.
Suggestion:
```java
@Bean
public ServerErrorHandler serverErrorHandler() {
    return myServerErrorHandler;
}
```

**Comment by ikhoon** [comment]
Created #5443 to support the `ServerErrorHandler` bean.
Contribution is welcome if you are interested in sending a PR.

**Comment by Mina-1316** [comment]
Thanks for the fast response! I'll check and contribute later if I can.
