### ISSUE TITLE
Add homePageUrlPath, statusPageUrlPath to EurekaUpdatingListenerBuilder

### ISSUE THREAD

**Issue by codefromthecrypt** [line/armeria#5464]
#5369 added healthCheckUrlPath to `EurekaUpdatingListenerBuilder.healthCheckUrlPath`

There are a couple other properties that should have the same treatment for the same reasons: `homePageUrlPath` and `statusPageUrlPath`.

While these attributes of InstanceInfo are not critical to the functionality of the server, @SankM1 noticed that the Eureka UI greys out instances missing a `statusPageUrl`
![image](https://github.com/line/armeria/assets/64215/8c2c66a5-1a12-49e5-8551-13636892fa70)

This is typically served by spring boot under an actuator path, but in the case of zipkin, it is literally the path "/status". Adding it manually makes the link show up like others
![image](https://github.com/line/armeria/assets/64215/4a146979-f54b-4ef0-8bae-b948888d0a51)

Eureka has secure and non-secure path for health check but it only uses non-secure path for homePageUrl and statusPageUrl:
https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java#L673-L681
https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java#L587
https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java#L628
Let's just use the plain text now and revisit this later if it becomes a problem. 

Thanks @minwoox for the investigation!

**Comment by codefromthecrypt** [comment]
cc @spencergibb just as an FYI (unless you want an excuse to do some armeria ;))

**Comment by minwoox** [comment]
Will send a patch today. 😉

**Comment by codefromthecrypt** [comment]
thanks! we'll cut zipkin as soon as this is released!
