### ISSUE TITLE
Introduce Connection Drain Duration for ClientFactory Closure

### ISSUE THREAD

**Issue by minwoox** [line/armeria#5470]
Problem:
Currently, when a `ClientFactory` is closed in Armeria, all connections associated with it are immediately closed as well. While this behavior is expected, it can pose a minor issue if a user needs to wait for ongoing requests to complete, especially in scenarios where the server is shutting down.

Proposed Solution:
To address this issue, I suggest introducing a connection drain duration similar to what is implemented for the server side in Armeria. By allowing a grace period for ongoing requests to finish before closing connections, users can ensure that their requests complete

Relevant Code:
[HttpClientFactory.java](https://github.com/line/armeria/blob/71373dbc5c61d2bf209c1634cfdc9b8bd2191cd1/core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java#L430)
[HttpChannelPool.java](https://github.com/line/armeria/blob/d2afcd905f760bb02fe66f421628a92da75a227c/core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java#L553-L582)
[Http2ServerConnectionHandler.java](https://github.com/line/armeria/blob/6e485eb4c578271818e5631335d33f0ed96e2859/core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java#L165-L190)
[Flags.java](https://github.com/line/armeria/blob/7287ba506c64d909957019d63474da2d7ea0e90c/core/src/main/java/com/linecorp/armeria/common/Flags.java#L979)

**Comment by Lincong** [comment]
Thanks Minwoox, here is our Discord [discussion context](https://discord.com/channels/1087271586832318494/1208472085710774312/1209419545777803275)

**Comment by seonwoo960000** [comment]
Hi @minwoox , I've added a PR to add graceful shutdown for the `ClientFactory`

**Comment by minwoox** [comment]
Closed by #5489
