### ISSUE TITLE
Method is not found `decoderEnforceMaxRstFramesPerWindow`

### ISSUE THREAD

**Issue by hmhuan** [line/armeria#5475]
https://github.com/line/armeria/blob/2e99b180518f2543c9189a1fe00d5a711a4a7a49/core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandlerBuilder.java#L38

https://github.com/line/armeria/blob/2e99b180518f2543c9189a1fe00d5a711a4a7a49/core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandlerBuilder.java#L46-L47

**Comment by ikhoon** [comment]
`decoderEnforceMaxRstFramesPerWindow` is introduced in the Netty 4.1.107.Final.
https://github.com/netty/netty/commit/58f75f665aa81a8cbcf6ffa74820042a285c5e61#diff-82f568a075ff63e9727ce8622f3a2b1553099182edf1fd0b4f857226252b05adR47
The problem will be fixed if you upgrade the netty version in your project.
