### ISSUE TITLE
Support for `@Attribute` in annotated services

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5514]
It would be good to support `@Attribute` annotation to declaratively inject the attributes in `ServiceRequestContext.attr(key)` into annotated services.

```java
class MyService {

  @Get("/")
  public String hello(@Attribute("myAttribute") String myAttribute, ...) {
     ...
  }

}
```

**Comment by chickenchickenlove** [comment]
Hi, @ikhoon nim. 
I'm new and interested in `armeria`. 

After reading the code of Armeria and your explanation, it seems like I can do this work.
May i work for this issue?

**Comment by ikhoon** [comment]
One of our internal employees is interested and is preparing to develop the issue. We appreciate your interest, but why not consider another issue? 🙏

**Comment by chickenchickenlove** [comment]
Thanks for your comment. 🙇‍♂️ 
I see, i didn't realize that it's listed on sprint.
I vote this issue. i would be grateful for the opportunity to address this issue as one of the participants. 
Have a good day!

**Comment by ikhoon** [comment]
I didn't know you were a member of Armeria Sprint. 😄
It's all yours.
