### ISSUE TITLE
Make `GrpcStatus` implement `GrpcExceptionHandlerFunction`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5550]
Although we use `GrpcStatus` as the default implementation of `GrpcExceptionHandlerFunction`, it does not implement `GrpcExceptionHandlerFunction`.
https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java#L79-L80

It would be good to refactor `GrpcStatus` and rename it to `DefaultGrpcExceptionHandlerFunction`. Afterward, `DefaultGrpcExceptionHandlerFunction` can be set to `GrpcServiceBuilder` and `GrpcClientBuilder` as default values.
https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java#L118-L118
https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientBuilder.java#L104-L104

**Comment by trustin** [comment]
Maybe instead add `asExceptionHandler()`?

**Comment by trustin** [comment]
Actually, never mind. I should have read the details of this issue before writing a comment 😓
