### ISSUE TITLE
Consider making `ContentTooLargeException` extend `HttpStatusException`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5578]
Suggested by @dlvenable (https://github.com/line/armeria/discussions/5565)
> The ContentTooLargeException does not inherit from HttpStatusException. We currently have a block of code that handles HttpStatusException exceptions by looking to see if it is a client or server error. Can we make ContentTooLargeException inherit from HttpStatusException?

`ContentTooLargeException` represents 413 status so, I think, we can make `ContentTooLargeException` extend `HttpStatusException` to streamline exception handling logic.

**Comment by ikhoon** [comment]
I realized that `ContentTooLargeException` can't simply extend `HttpStatusException` because `HttpStatusException` is in `server` package but `ContentTooLargeException` is in `common`.

It seems like this issue should be considered in Armeria 2.0.

**Comment by minwoox** [comment]
I believe that we don't want to make `ContentTooLargeException` extend `HttpStatusException`. 
See this comment: https://github.com/line/armeria/discussions/5565#discussioncomment-9056979
