### ISSUE TITLE
Convert HTTP body to Java object or vice versa for DynamicHttpFunction

### ISSUE THREAD

**Issue by hyangtack** [line/armeria#563]
.. like spring message converter.

**Comment by imasahiro** [comment]
Looks same as this issue? https://github.com/line/armeria/issues/400

**Comment by hyangtack** [comment]
Thanks, @imasahiro. I closed #400 because this issue is more general. 😃

**Comment by imasahiro** [comment]
Hi, just write simple object -> json serialized HttpData. https://gist.github.com/imasahiro/16cfaaceb85823414d06cb96be6bab4b
Does this issue focus on "Convert Java object to HTTP body", right?

**Comment by hyangtack** [comment]
@imasahiro Actually we are focusing on the both way of the conversion. But I have not thought about that enough yet, especially the way converting HTTP body to Java object. 

Anyway, your implementation is good for "converting Java object to HTTP JSON body". 👍  At the moment when I filed this issue there was no way to register a converter with Object class, but now it is available. 😄

**Comment by trustin** [comment]
Resolved long time ago. :+1:
