### ISSUE TITLE
RoutingContext.withPath() doesn't respect Flags.allowSemicolonInPathComponent()

### ISSUE THREAD

**Issue by minwoox** [line/armeria#5726]
`RoutingContext.withPath()` should respect the value `Flags.allowSemicolonInPathComponent()`. If `Flags.allowSemicolonInPathComponent()` returns true, it shouldn't raise an exception here:
https://github.com/line/armeria/blob/db3973d74e70e177b0849f201fdd96615f2f6292/core/src/main/java/com/linecorp/armeria/server/RoutingContext.java#L152

**Comment by ikhoon** [comment]
Fixed by #5727
