### ISSUE TITLE
AnnotatedHttpService: Inject a query string parameter as a method argument

### ISSUE THREAD

**Issue by hyangtack** [line/armeria#580]
.. like `@RequestParam` of Spring framework. Also, we need to figure out how to handle `POST` method parameters. (only support for `content-type:application/x-www-form-urlencoded` and automatically aggregation?)

**Comment by trustin** [comment]
What media types do Spring framework support? Eventually we will need to support multipart as well.

**Comment by hyangtack** [comment]
I couldn't understand their codes all, but found that they support `@RequestParam` for the following media types in a HTTP `POST` request:
- application/x-www-form-urlencoded
- multipart/form-data

Multipart form data is also supported by [`@RequestPart` annotation](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestPart.html).

IMHO, we need to support query string for `GET` request and `x-www-form-urlencoded` for `POST` request  first because it's more often used than multipart form data. 

@trustin May I take this issue to try to resolve the first goal?

**Comment by trustin** [comment]
SGTM

**Comment by trustin** [comment]
Closed by #589
