### ISSUE TITLE
Soft-fail on error "Only unary methods can be configured with an HTTP/JSON endpoint"

### ISSUE THREAD

**Issue by Dogacel** [line/armeria#5828]
https://github.com/line/armeria/blob/104855af85783b40aba4750a15b5b79159f65e3a/grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java#L162-L165

I am using gRPC definitions of another service to create a proxy service that authorizes requests & logs access. However, the server throws ISE during startup due to this error.

In my mind, we should fail softly and just warn the user about transcoding options are skipped for this endpoint. I am not sure what the intention of original authors are but maybe the proxy server they are using supports transcoding for non-unary.

**Comment by Dogacel** [comment]
@trustin @ikhoon @minwoox @jrhee17 I know it is not ideal to ask prioritization of issues, but I have already opened a PR and this is a blocker for a new service I am trying to proxy 🙏 I would be glad if you can take a look 😊

**Comment by ikhoon** [comment]
The PR is added in 1.29.3 which we will release today. 😉
