### ISSUE TITLE
HTTP 200 is UNKNOWN in actuator metrics

### ISSUE THREAD

**Issue by bytestreme** [line/armeria#5882]
Spring Boot 3.3.3
Armeria 1.29.0

Looks like there is an issue with setting http status code because when `org.springframework.http.server.reactive.observation.DefaultServerRequestObservationConvention` calls `context.getResponse().getStatusCode()`, `ArmeriaServerHttpResponse` returns `null`

**Comment by bytestreme** [comment]
Using also com.linecorp.armeria:armeria-spring-boot3-webflux-starter:1.29.0

**Comment by jrhee17** [comment]
Hi, there's actually a `ObservationConvention` defined for Armeria [DefaultServiceObservationConvention](https://github.com/line/armeria/blob/main/core/src/main/java/com/linecorp/armeria/server/observation/DefaultServiceObservationConvention.java) which can be enabled via `ObservationService`.

Having said this, let me look into why Spring's integration doesn't work for Armeria in the next working days

**Comment by jrhee17** [comment]
I found a bug in armeria's implementation which doesn't return the correct status code - I'll try to get this merged in the next milestone 🙏
