### ISSUE TITLE
gRPC AsyncServerInterceptor throws an exception when opentelemetry-javaagent is enabled

### ISSUE THREAD

**Issue by kabigon-sung** [line/armeria#5937]
Hi team,
I found that the `AsyncServerInterceptor` throws an exception when `opentelemetry-javaagent` is enabled.
Here is the exception and stacktrace:
<img width="1728" alt="截圖 2024-10-14 下午2 44 41" src="https://github.com/user-attachments/assets/ce6a6ab1-ffe4-48c0-b693-e0acb1e17ab0">

Armeria Version - 1.30.1

Possible root cause:
The default method `interceptCall` in `AsyncServerInterceptor` creates an instance of `DeferredListener`. The constructor of  `DeferredListener` performs checking on the `ServerCall<I, O> call` parameter. The checking requires that the passed `call` should be a subclass  of `com.linecorp.armeria.internal.server.grpc.AbstractServerCall`.
When `opentelemetry-javagent` is enabled, the original `com.linecorp.armeria.server.grpc.UnaryServerCall` object is replaced by `io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.TracingServerInterceptor$TracingServerCall`. Since `TracingServerCall` is not a subclass of `AbstractServerCall `, the constructor of `DeferredListener` throws an exception.

How to reproduce the problem
1. Implement a `AsyncServerInterceptor`
```java
public static class MyInterceptor implements AsyncServerInterceptor {
        @Override
        public <I, O> CompletableFuture<Listener<I>> asyncInterceptCall(ServerCall<I, O> call,
                                                                        Metadata headers,
                                                                        ServerCallHandler<I, O> next) {
            final Context context = Context.current();
            return CompletableFuture.supplyAsync(() -> {
                try {
                    return context.call(() -> next.startCall(call, headers));
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            });
        }
    }
```
2. Add the interceptor to the `GrpcService`
```java
sb.service(GrpcService.builder()
                                        .intercept(new MyInterceptor()) // add the interceptor
                                        .addService(new MyHelloService())
                                        .build());
```
4. Download the `opentelemetry-javaagent` from https://github.com/open-telemetry/opentelemetry-java-instrumentation.
5. Run the server with `opentelemetry-javaagent`.
6. Sending a gRCP request causes the error.

**Comment by jrhee17** [comment]
I realized `delegateMH` doesn't work as expected 😅  We'll fix this from armeria-side in the next version 🙏
