### ISSUE TITLE
Armeria grpc authentication SSL/TLS

### ISSUE THREAD

**Issue by demongaorui** [line/armeria#598]
Is there a way to make enable authentication SSL/TLS for Armeria grpc service or server like:
http://www.grpc.io/docs/guides/auth.html#with-server-authentication-ssltls-4

Or, authentication SSL/TLS could work between Armeria server and upstream gprc clients?

**Comment by anuraaga** [comment]
TLS is a part of armeria and its HTTP-handling itself and not really related to gRPC - the normal documentation for armeria and TLS applies to gRPC too.

http://line.github.io/armeria/server-basics.html#ssl-tls

As TLS happens at HTTP level, upstream gRPC clients should work fine too. It's actually been verified before in the interop test, which enables TLS with a custom CA.

https://github.com/line/armeria/blob/master/it/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java#L107
