### ISSUE TITLE
New armeria release 1.31.0 contains dependency on protobuf-java 4.28.2

### ISSUE THREAD

**Issue by smax48** [line/armeria#5990]
Looks like this  4.28.2 comes from the updated protobuf-jackson.

Basically this new version breaks everything protobuf-related - as 4.x is not compatible with 3.x

**Comment by jrhee17** [comment]
If protobuf4 was included, it's unintentional 😅   Let me check and release a patch version. Thanks for the report!

**Comment by trask** [comment]
we ran into this also: https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1550#issuecomment-2487393565

**Comment by anuraaga** [comment]
For context, protobuf-jackson supports both v3 and v4 while declaring a dependency on the latest version of protobuf when releasing as I think is standard for Java libraries. Perhaps protobuf is too weird to apply standard norms too... One note is that my understanding was the complete breakage in v4 was resolved 

https://github.com/protocolbuffers/protobuf/issues/17247

I wonder if that just leaves potentially small parts of Armeria left that may need fixing for compatibility. That being said, grpc-java hasn't updated yet which is a good sign. Let me know if it seems the practical approach is to sticking to a v3 dependency in protobuf-jackson for now (some work to wire v4 into the CI in that case, Google loves to cause us extra work :P).

**Comment by smax48** [comment]
I quickly tested our project with the latest v4 and it just breaks everything... Even though code changes are not very complex (to fix compilation errors), runtime behaviour was broken. In our projects we use other components that are dependent on protobuf serialization (Temporal) - and that simply didn't work with mixed v3/v4.

So it would be very good to keep using protobuf-java v3 as long as grpc-java itself doing the same :-)
