### ISSUE TITLE
maven archive armeria-tomcat8.0-source.jar   does not include completed classes

### ISSUE THREAD

**Issue by jonefeewang** [line/armeria#604]
maven archive armeria-tomcat8.0-source.jar does not include completed classes, in a project using armeria-tomcat8.0, when navigated to class "TomcatServiceBuilder" for example,  IntelliJ Idea is showing the decompiled class file, not the source file

**Comment by trustin** [comment]
The binary JAR contains all the necessary classes and it's the sources JAR that has missing files, right?

**Comment by jonefeewang** [comment]
@trustin yes.
