### ISSUE TITLE
SessionOption should include a way to set keyManager for clients.

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#610]
Currently, there doesn't seem to be a way to set the identifying SSL certificate for a client, for using SSL client auth.

**Comment by anuraaga** [comment]
Also it might be useful to make it more generic, something like `Consumer<SslContextBuilder>` since SSLContextBuilder already has many convenience methods that would be annoying to try to reproduce as session options.

**Comment by trustin** [comment]
+1 for adding a generic way to configure an `SslContext`. Interested in sending a PR?

**Comment by anuraaga** [comment]
Yup - will probably send around end-of-week

**Comment by trustin** [comment]
Great! Let me stay tuned.
