### ISSUE TITLE
How to cancel a request if armeria event loop is blocked by blocking futures?

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#614]
When run a business logic that has blocking task (e.g. sync mysql access) on armeria event loop (e.g. below snipet), it blocks the event loop and does not return any response includes response time out error.

```java
@SpringBootApplication
public class SampleApplication {
    @Bean
    HttpServiceRegistrationBean httpService(final EmbeddedWebApplicationContext applicationContext) {
        CompletableFuture<Object> blockedFuture = new CompletableFuture<>();
        return new HttpServiceRegistrationBean()
                .setServiceName("buggy-service")
                .setService(new AbstractHttpService() {
                    @Override
                    protected void doGet(ServiceRequestContext ctx, HttpRequest req, HttpResponseWriter res)
                            throws Exception {
                        blockedFuture.get(); // This is bug!!! This blocking should be executed on other executor.
                        res.respond(HttpStatus.OK, MediaType.ANY_TEXT_TYPE, "OK");
                    }
                }.decorate(LoggingService.newDecorator()))
                .setPathMapping(PathMapping.ofPrefix("/my-buggy-service"));
    }

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }
}
```

As a result, requests are failed by client side timeout but still remaining on event loop.  At this memoent, because not all event loop threads are blocked, other service (e.g. HealthCheckService) returns correctly if a request is served by not blocked event loop thread.

And if a client uses HealthCheckedEndpointGroup to connect the service, and if a health check client hits not blocked event loop thread, an endpoint is treated as healthy clients send a request continuously but requests are sometimes failed since it hits blocked event loop thread by timeout error, for example,
```java
com.linecorp.armeria.client.SessionProtocolNegotiationException:
  expected: http, reason: connection established, but session creation timed out:
  [id: 0x7fb2c0bb, L:/127.0.0.1:61632 - R:localhost/127.0.0.1:8080]
```

The solution for this is "do not run any blockings on event loop. Instead, wait them at executors for blocking tasks".
But want to know what is the best way to detect/handle this kind of error(?) on armeria side.

Here is minimal example to reproduce this issue.
https://github.com/imasahiro/armeria-issue614

**Comment by mauhiz** [comment]
> "do not run any blockings on event loop"

Same advice there: https://www.playframework.com/documentation/2.5.x/ThreadPools

I don't think there is any easy way to prevent this...

**Comment by anuraaga** [comment]
I think I've seen frameworks which report suspicious blocking of the event loop threads - I don't know the implementation but assume they use JMX to monitor the threads for blocking. As @mauhiz says, I agree there doesn't seem to be anything to do if the code makes it to production, but it might be able to flag issues during e.g., alpha testing.

**Comment by trustin** [comment]
I think you can write a JVM agent which manipulates the byte code of the blocking operations you are interested so that the blocking operation fails with a `RuntimeException` when it is invoked from an I/O thread. In this case, you could manipulate the byte code of `CompletableFuture` like this:

```java
    private Object waitingGet(boolean interruptible) {
        EventLoop eventLoop = RequestContext.mapCurrent(RequestContext::eventLoop, null);
        if (eventLoop.inEventLoop()) {
            throw new SomeException("you are blocking an I/O thread!");
        }
        ...
    }
```

**Comment by imasahiro** [comment]
Thanks for comments. Writing JMX monitoring and JVM agent sounds good to me. Let me write JMX monitoring first (because I use many valiation of asyncs include CompletableFuture, ListenerbleFuture, RxJava, etc. in 1 service.. ) to detect blocking.
