### ISSUE TITLE
Generalize LoggingService

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#645]
I think currently, we provide two `LoggingService`, one that logs everything at a specified log level, and one that does samping to log at a specified log level. Personally, I feel like the ideal logger

- Logs all errors at warn or error (user-specified error log level)
- Logs a user-specified sample (or 100%) of non-errors at an info-type level
- Allows specifying a user function to sanitize request/response payloads when available

Parameters to this service can reproduce the current behavior of `LoggingService` and `SampledLoggingService` for other use cases.

Would this be useful?

**Comment by trustin** [comment]
Sounds good to me. @imasahiro @minwoox WDYT?

**Comment by minwoox** [comment]
I would love to see that!
