### ISSUE TITLE
Add specific name field to AnnotatedHttpService related annotations for logger/metrics

### ISSUE THREAD

**Issue by krrrr38** [line/armeria#651]
## problem
currrently when we use `AnnotatedHttpService`, logger/metrics names become followings 

- loggerName
  - `armeria.services.__UNKNOWN__`
- metricName example (get from metrics path)
  - `server.${serviceName}.__UNKNOWN_PATH__.GET.successes`

## proposal
add metricName or something into `@Get`, `@Post`, ... annotations. then fill-in into logger/metrics name.

**Comment by trustin** [comment]
Sounds like a good idea. This could be solved in two steps:

1. Fix AnnotatedHttpService so that it produces better default loggerName and metricName
2. Add some annotations for customizing loggerName and metricName.

**Comment by trustin** [comment]
@krrrr38 Could you let us know what path pattern you used?

**Comment by krrrr38** [comment]
I used prefix path pattern, which is supported in `AnnotatedServiceRegistrationBean`.

**Comment by trustin** [comment]
@krrrr38 Should be fixed by #659. Could you review it?

**Comment by hyangtack** [comment]
@krrrr38 I filed a new issue #661 about No.2 of @trustin 's comment. We will think more about that when we handle metric-related issues. Thanks again to your idea. 😄

**Comment by krrrr38** [comment]
thanks :) actually in my current situation, it's enought. it's ok to keep or do that issue.
