### ISSUE TITLE
Migrate DocService to more scalable frontend framework

### ISSUE THREAD

**Issue by trustin** [line/armeria#654]
.. so we can add more features and organize them easily. Vue.js or Angular?

**Comment by trustin** [comment]
http://vuematerial.io/ and https://material.angular.io/

**Comment by anuraaga** [comment]
Or React? :) www.material-ui.com/

Just to add the option, I guess there's never a right or wrong answer on which framework to pick (which makes it hard to pick...).

**Comment by trustin** [comment]
Haha, yeah. I have some experience with Angular.js, so I was rather inclined to Angular than to React, but you know, Vue.js is also hot these days. :-D I think it's just a matter of who's gonna do the job and he or she prefers which.
