### ISSUE TITLE
Generalize LoggingClient

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#678]
`LoggingClient` should also support the features of the generalized `LoggingClient` in #645

**Comment by imasahiro** [comment]
Hi @anuraaga, any progress about this issue?
If not, is it ok to take over?
I just start to take a look this; https://github.com/imasahiro/armeria/commit/f51d31ef

**Comment by anuraaga** [comment]
Thanks for checking in and sorry for not getting to it - please take it over :)

**Comment by imasahiro** [comment]
Fixed via https://github.com/line/armeria/pull/772
