### ISSUE TITLE
How ZooKeeperEndpointGroup be used by client

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#684]
I can't find sample usage for endpoint group, so here is my usage, I'm not sure whether it is the right way.
```java
String connStr = "localhost:2181";
        String nodePath = "/armeria-eone";
        ServerListener zkListener = new ZooKeeperUpdatingListener(connStr, nodePath, 3000,
                                                                  Endpoint.of("localhost", port));
Server server = builder.build();
server.addListener(zkListener);
```

and then, my question is, how does the client call the server by ZooKeeperEndpointGroup, and with  the load balance mechanism.

**Comment by trustin** [comment]
@eonezhang Did you have a chance to check our documentation out? http://line.github.io/armeria/advanced-zookeeper.html

**Comment by eonezhang** [comment]
gocha, thank you @trustin.
After a period research and a few comparison, we plan to introduce armeria as part of our microservice framework, not decided at the moment yet, but it could be a candidate, maybe more questions will be raised in the near future.
thank you contribute so great stuff for the community, I hope we can also contribute back to community if possible.

**Comment by trustin** [comment]
@eonezhang Awesome! Please feel free to let us know if there are any issues adopting Armeria into your organization regardless if it's small/big or short/long term problem. We'd be very happy to listen to your concerns and feature requests and get them addressed. Cheers!

**Comment by eonezhang** [comment]
sure, I will.
BTW, is there any slides can be shared so that I can share with my team and the boss, so as to help them make decision. 
I searched from slideshare, and find only two of them.
