### ISSUE TITLE
Add a DNS-based EndpointGroup

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#688]
Many service discovery systems support returning a list of endpoints as records in a DNS response, and since DNS resolution is built into netty, it makes sense for armeria to add support out of the box. Some methods use `A` records with IP addresses and others use `SRV` records with CNAMEs - so armeria should ideally support at least both of these.

I dug through netty's DNS resolver package and found a lot of useful logic, but am not sure if there is a good integration point for it.

The biggest problem is I don't see a way to support `SRV` records - the API only exposes knobs for address family, e.g. IPV4 and IPV6, which correspond to `A` and `AAAA` only.

https://github.com/netty/netty/blob/1767814a466f9fc6a51c87a84bd73d93eb0ca1d7/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java

I think we also need a way to always be able to know the most recent result for the DNS query for monitoring - it's very important to be able to present the mapping from service name -> resolved endpoints, and it's not clear this can be accomplished with the default `DnsNameResolver` (maybe by showing the state of the dns cache?).

That said, there's much logic in `DnsNameResolver`, `DnsNameResolverContext`, and `RoundRobinDnsAddressResolverGroup` that I don't think we want to duplicate into an endpoint group implementation.

**Comment by anuraaga** [comment]
@trustin any thoughts on a clean DNS-based EndpointGroup implementation? I think I need some pointers (including whether we should edit APIs in netty) but with some pointers, can do the implementation.

**Comment by trustin** [comment]
Very cool! `DnsNameResolverBuilder` should be a good starting point for you:

- https://netty.io/4.1/api/io/netty/resolver/dns/DnsNameResolverBuilder.html

You'll need to use `DnsNameResolver.resolveAll()` or `query()` depending on how much information you need.

**Comment by trustin** [comment]
With `query()`, you can send an arbitrary DNS question. (I guess this is what you're looking for.)

**Comment by trustin** [comment]
> I think we also need a way to always be able to know the most recent result for the DNS query for monitoring - it's very important to be able to present the mapping from service name -> resolved endpoints, and it's not clear this can be accomplished with the default DnsNameResolver (maybe by showing the state of the dns cache?).

I guess you're gonna need to read the TTL value of the answer record you received and re-query when it's expired. You could implement this by sending an initial query and then scheduling a follow-up one after `<TTL>` seconds.

**Comment by anuraaga** [comment]
Yeah - I found query and am able to get DNS responses - but found there's tons and tons of logic dealing with correctly handling the response. It would be quite sad to have to duplicate it

https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverContext.java#L336

It's why using resolve would be much nicer, but has the limitation of no `SRV` support. Any thoughts on a cleaner way to avoid duplicating what looks like pretty hairy (i.e. easily buggy) code?

**Comment by anuraaga** [comment]
Just to follow up, I've mostly completed an implementation that manually handles the query response. While a good amount of copy-paste, by removing some of the more esoteric features that probably don't apply in service discovery, I could simplify it quite a bit.

https://github.com/anuraaga/armeria/blob/dev_rag/core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
