### ISSUE TITLE
Client Endpoint should support specifying both target and host

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#693]
Currently, an `Endpoint` only has one address, `host`. It can be useful for the `Endpoint` to have two addresses, the `target`, which can be an IP address, and `host` which is used as the HTTP HOST header and SSL common name. This can make it easier to couple service discovery with TLS because services may have endpoints with random IP addresses but serving a fixed SSL name that is used for discovery.

**Comment by trustin** [comment]
If I understood correctly, you basically want to specify an `Endpoint` which is already resolved so it doesn't have to go through `DnsAddressResolver`. Is it correct? If so, I think it makes sense as long ad the ip address part is optional.

**Comment by anuraaga** [comment]
Is it not possible to specify a resolved IP address as `Endpoint.host` already? I renamed `host` to `target` in my proposal which might have been confusing. FWIU, the current semantics of `host` itself doesn't have to be changed (IP address can be used as is, String needs to be resolved), as long as there is a way to also optionally force the HTTP `Host` header / SSL common name during handshake.

**Comment by trustin** [comment]
I think this issue can be closed because you can specify an IP address in a URL and specify a custom authority in the header. What do you think, @anuraaga ?

**Comment by anuraaga** [comment]
Yeah I think we did a lot of changes to load balancing and host resolution and this should be fixed now.

**Comment by trustin** [comment]
Thanks @anuraaga for closing quickly.
