### ISSUE TITLE
Discuss STATIC_INIT checkstyle rule

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#700]
Just happened to run into this checkstyle rule and thought a small discussion would be good. It requires an empty line around a static initialization block. I feel like this can be left up to the programmer, since many static initialization blocks are directly tied to a field - removing the empty line makes this association clearer to me.

Rule: 'STATIC_INIT' should be separated from previous statement. [EmptyLineSeparator]
Example code:
```java
class Foo {
    private static final List<InetAddress> ADDRESSES;

    static {
        try {
            ADDRESSES = ImmutableList.of(
                    InetAddress.getByName("1.2.3.4"),
                    InetAddress.getByName("2.3.4.5"));
        } catch (UnknownHostException e) {
            throw new Error(e);
        }
    }
}
```

**Comment by trustin** [comment]
.. and your suggestion is to allow removing the empty line between `private static final List...` and `static {`, right? That sounds good to me. I sometimes found that annoying as well. @hyangtack @minwoox @imasahiro Thoughts?

**Comment by anuraaga** [comment]
Ah yep - that's my suggestion :)

**Comment by hyangtack** [comment]
👍  It sounds good to me, too. I've also experiences getting the error from the rule.

**Comment by minwoox** [comment]
👍 It sounds good to me, as well.

**Comment by trustin** [comment]
Also need to update the Checkstyle settings for line/centraldogma
