### ISSUE TITLE
Spring Boot armeria server always shutdown in 0.51.0

### ISSUE THREAD

**Issue by Adanz** [line/armeria#702]
hello, I use armeria and spring boot,  below bean before version 0.51.0 (i.e. 0.46.0 - 0.50.0) is normal,
use armeria-spring-boot-starter.  (but not use spring-boot-starter-web)
```java
@Configuration
public class RpcServiceConfiguration {
    @Bean
    public ThriftServiceRegistrationBean rpcService(RpcHandler rpcHandler) {
        return new ThriftServiceRegistrationBean()
                .setServiceName("RpcService")
                .setService(THttpService.of(rpcHandler, ThriftSerializationFormats.COMPACT))
                .setPath("/api/data");
    }
}
```

but in 0.51.0, An unexpected close has occurred, like:

[main]   : Started Application in 8.869 seconds (JVM running for 9.946)
[Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6e0f5f7f: startup date [Wed Jul 26 14:35:19 CST 2017]; root of context hierarchy
[Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
Disconnected from the target VM, address: '127.0.0.1:58717', transport: 'socket'

How can I do? thank!

**Comment by Adanz** [comment]
I found Prevent premature shutdown of JVM when running a Server ([#686](https://github.com/line/armeria/commit/c4875534f533b3aace7ce5f90bad3c17dbf4620e)), may fix.

**Comment by minwoox** [comment]
@Adanz Sorry for the late response. It will solve the problem. If not, please let us know. :)

**Comment by imasahiro** [comment]
Yeah, I wrote a small spring-boot app and confirm that current SNAPSHOT solves this issue.
https://github.com/imasahiro/armeria-issue/tree/issue702

**Comment by trustin** [comment]
0.52.0 has been released! Please feel free to open a new issue you have the same problem. Thanks!
