### ISSUE TITLE
is there any plan to support eureka as EndpointGroup

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#707]
hi @trustin, nowadays, spring cloud is pop, do you have any idea about that.

**Comment by trustin** [comment]
Sounds like a good idea to have `EurekaEndpointGroup`. We don't internally use it but we are interested definitely. Have you thought about sending a PR for it?

**Comment by eonezhang** [comment]
@trustin after few days investigation, we decide to postpone the feature to our backlog list, we'll keep updating here if there's any progress.

**Comment by huydx** [comment]
I will handle that

**Comment by minwoox** [comment]
@eonezhang Hey~ Are you still interested in this? I created #2701 and want to see if it's working well. 😄

**Comment by trustin** [comment]
Fixed via #2701
