### ISSUE TITLE
Gradle build failed at buildNeeded task.

### ISSUE THREAD

**Issue by krisjey** [line/armeria#712]
hi @trustin,

I was test a build for buildNeeded task, but failed it.
Could you check it out?

Additionally, Eclipse builds fail too by the Circular dependency.
Eclipse error keyword is "A cyclic dependency in eclipse".

Workaround of eclipse build fail by cyclic dependency is 
changing build severity.
Preferences > Java > Compiler > building > Build path problems.
Circular dependencies : Change value Error to Warning.

Below is error messages of Gradle.

```
* What went wrong:
Circular dependency between the following tasks:
:core:buildNeeded
\--- :testing-internal:buildNeeded
     +--- :core:buildNeeded (*)
     +--- :testing:buildNeeded
     |    +--- :core:buildNeeded (*)
     |    \--- :testing-internal:buildNeeded (*)
     \--- :testing-internal:buildNeeded (*)

(*) - details omitted (listed previously)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED in 3s

== BUILD FAILED ==
```

**Comment by minwoox** [comment]
Oops~ let me check this.

**Comment by minwoox** [comment]
It seems like we had this issue before #710 was merged. Let me dig into more and remove the circular dependency. Before that, I have a question for you. Does your eclipse fails suddenly? or has the problem before?

**Comment by krisjey** [comment]
@minwoox gradle build is working but, gradle buildNeeded is fail.

I updated gradle 3.1 to 4.0.2.
however Two gradle version and gradlew are same error.

**Comment by trustin** [comment]
Looks like a bug in Gradle: https://github.com/gradle/gradle/issues/1647

**Comment by krisjey** [comment]
@trustin Do you think eclipse build ship has the same bug?
below is Eclipse Marker log.
```
A cycle was detected in the build path of project 'core'. The cycle consists of projects {core, testing-internal,  
more 17 lines ...
```

**Comment by minwoox** [comment]
Well, they said this is the expected behavior. https://github.com/eclipse/buildship/issues/460

**Comment by krisjey** [comment]
@trustin @minwoox Thank you for answers.
