### ISSUE TITLE
HTTP 1.1 path should be allowed *(asterisk) character.

### ISSUE THREAD

**Issue by krisjey** [line/armeria#715]
Hi, guys.

I'm using armeria as a REST API server. Like below.
GET http://foobar.com/cache/keyname::hello

Sometimes armeria server response 404.
GET http://foobar.com/cache/key*::hello

The reason is that HTTP 1.1 path should be allowed *(asterisk) character.
Please check below link.
https://stackoverflow.com/questions/25085992/when-should-an-asterisk-be-encoded-in-an-http-url

Fix code https://github.com/line/armeria/pull/714

**Comment by trustin** [comment]
Closed by #714
