### ISSUE TITLE
Add a session-level option for initial HTTP/2 settings

### ISSUE THREAD

**Issue by trustin** [line/armeria#716]
.. so that a user can specify initial window size, max concurrent streams, and more.

Also, we can test if Armeria server handles non-default HTTP/2 settings properly using this feature.

**Comment by minwoox** [comment]
In #728, settings for Initial connection window size, SETTINGS_INITIAL_WINDOW_SIZE (for stream-level) and SETTINGS_MAX_FRAME_SIZE are implemented.
