### ISSUE TITLE
Add request/response content preview to RequestLog

### ISSUE THREAD

**Issue by trustin** [line/armeria#730]
A user wants to see the first N bytes of HTTP request/response content via `RequestLog`, where N is configurable.

**Comment by lovepoetry** [comment]
Yes, we have strong wish of logging request body for debugging or investigation.

**Comment by tmdgus0118** [comment]
This issue can be closed. Solved at #1574

**Comment by trustin** [comment]
Thanks again, @hyeonjames :+1:
