### ISSUE TITLE
Allow resetting the request timeout with the same value

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#740]
Currently, when using `ServiceRequestContext.setRequestTimeout` multiple times with the same value, the latter calls are ignored. It seems like there are use cases for refreshing the timeout multiple times per request, e.g. the timeout should be applied per message in a gRPC message stream. Currently, it's actually still possible to do this with something silly like `setRequestTimeout(timeout * numMessagesSoFar)` @trustin, does it make sense to remove the `if` statement that guards against the same value in this function?

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java#L196

**Comment by trustin** [comment]
SGTM. Are you going to send a PR?

**Comment by anuraaga** [comment]
I thought about this a bit more and realized that `setRequestTimeout` updates the timeout vs the beginning of the request, not the current time. This was a bit confusing to me as my assumption was it'd be from the time `set` was called, but I want to confirm if this is just me or not. If the correct semantics are for the timeout to be from start of request, even when updated by `setRequestTimeout`, then can close this without any change since the current behavior is correct. Otherwise, will send a PR to change it to refreshing the timeout if it seems more natural :)

**Comment by trustin** [comment]
Ah, I see. Yes, I made `setRequestTimeout` to update the timeout against the beginning of request. Not sure which is the 'right' behavior, though. Current behavior seems OK to me though.

**Comment by ikhoon** [comment]
I'd like to give it a shot.😄
