### ISSUE TITLE
Client side Thrift callback not notified correctly for a void method with RetryingRpcClient

### ISSUE THREAD

**Issue by LiYing2010** [line/armeria#780]
I am using the latest Armeria v0.53.2, but something is going wrong.

When I call a method via Thrift, if this method has not return value, for example:
`public void doSomething(p1, p2)`

The thrift client side will go into deadlock.

I did some research, traced into source code of Armeria, and find these source is not working well:
https://github.com/line/armeria/blob/54e124d73178609b4f0af6d833ea562a1ce15bd9/core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java#L117-L121

If the method has not return value, the "result" will be null, the RPC call is completed normally, but RetryingRpcClient process this case as an error, and it will call the "responseFuture.completeExceptionally(thrown)" branch.

**Comment by trustin** [comment]
Changed the title because it's not a dead lock technically.
