### ISSUE TITLE
Armeria opens lots of files in synthetic benchmark

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#802]
If I create a JMH benchmark which creates a single empty HTTP endpoint and single client that accesses it, and a benchmark which just hits the endpoint without blocking, the server spews exceptions of too many open files (on Linux). Is this expected? My intuition would be that the client and server have a single HTTP/2 connection, so there should only be one socket and therefore open file for this benchmark even though there are many concurrent requests because the benchmark doesn't block for the response between requests.

Exception
```
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
        at io.netty.channel.unix.Errors.newIOException(Errors.java:117)
        at io.netty.channel.unix.Socket.accept(Socket.java:314)
        at io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:112)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
```

The benchmark code

https://github.com/anuraaga/armeria/blob/dev_rag2/core/src/jmh/java/com/linecorp/armeria/benchmarks/HttpServerBenchmark.java#L71

**Comment by trustin** [comment]
It's of course unexpected. Could you merge the benchmark into #798? Let me try to run them by myself.

**Comment by anuraaga** [comment]
Merged in. Hopefully we find it's just something silly I'm doing when writing / running the benchmark :)

**Comment by anuraaga** [comment]
I noticed `DefaultKeyedChannelPool` doesn't synchronize channel creation on a given key (e.g., using `computeIfAbsent`), so when starting many connections concurrently, channels are never reused. While it's easy to trigger with a synthetic benchmark, I guess it's possible in practice too for loads that open highly concurrent connections quickly on a fast network. What do you think?

https://github.com/line/armeria/blob/54e124d73178609b4f0af6d833ea562a1ce15bd9/core/src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java#L121
