### ISSUE TITLE
ClientRequestContext should be customizable when creating requests.

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#805]
Followup to #766, as discussed sometimes it's not enough to be able to load-balance based on request information, for example, requests should be balanced based on user-id but the request should contain an encrypted user token rather than the raw id for security purposes even for internal services.

One idea I had is propagating through a `ThreadLocal` - does this seem like a reasonable API?

```java
try (withContextCustomizer(ctx -> ctx.attrs().set(USER_ID, userId)) {
  client.doRpc(request);
}
```

**Comment by imasahiro** [comment]
Thanks for writing the issue. I realized that we already have a http header customizer using ThreadLocal, [Clients.withHttpHeaders](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/Clients.java#L314) but does not provide AttributeMap yet.

Think it is better to provide full functionality to manipulate whole client's attribute.

**Comment by trustin** [comment]
Sounds good to me.  Care to send a PR?

**Comment by trustin** [comment]
`withAttrs()` as well as `withContextCustomizer()` would be useful.

**Comment by imasahiro** [comment]
@trustin yep. here it is, https://github.com/line/armeria/pull/807
