### ISSUE TITLE
One connection per event loop made even with HTTP/2

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#816]
I noticed that `EventLoopScheduler` is always used, even for HTTP/2 connections. This means that a client will open as many connections as number of event loops, though I would expect one connection per client when using HTTP/2.

https://github.com/line/armeria/blob/54e124d73178609b4f0af6d833ea562a1ce15bd9/core/src/main/java/com/linecorp/armeria/client/EventLoopScheduler.java#L133

I wonder if there should be a client boss thread which can maintain the connection pool and delegate work to workers? It feels like a connection should own its event loop, while currently it seems like an event loop owns a connection (i.e., the channel pool is unique to each event loop).

**Comment by trustin** [comment]
> I noticed that `EventLoopScheduler` is always used, even for HTTP/2 connections. This means that a client will open as many connections as number of event loops, though I would expect one connection per client when using HTTP/2.

That's correct. This way, we spread the requests evenly to all `EventLoop`s. If we chose to reuse the connection with active requests when all `EventLoop`s are not utilized yet, the requests would not utilize all CPU cores. i.e. two requests handled by one event loop vs two requests handled by two event loops. I'm not sure if this can ever make performance worse, though. Any insights?

> I wonder if there should be a client boss thread which can maintain the connection pool and delegate work to workers? It feels like a connection should own its event loop, while currently it seems like an event loop owns a connection (i.e., the channel pool is unique to each event loop).

I initially tried this but it wasn't easy to achieve without removing `RequestContext.eventLoop()`, which is often very useful for scheduling a task that runs in an I/O thread. It's because `ClientRequestContext` is created and it becomes accessible by decorators even before we acquire a connection from the pool. Please let me know if you have a good idea about this. :-)

**Comment by anuraaga** [comment]
I think if possible, we should have one connection per HTTP/2 stream - quantitatively, not sure what the performance impact of multiple connections is but it seems to go against the spirit of HTTP/2.

I think it's ok for one connection to be served by multiple event loops though, hence the idea of a boss, which would make the client and server more consistent semantically.

If `RequestContext.eventLoop` is the main problem, I think we could have it return `CompletableFuture<EventLoop>`?

**Comment by trustin** [comment]
I'm not sure making one client connection handled by multiple event loops is a good idea. Given Netty's thread model, it would be more like passing events to another thread pool while doing I/O in a single thread, which removes the merit of doing jobs in an I/O thread at lower latency.

Instead, how about just reducing the max number of event loops per endpoint (i.e. per `EventLoopScheduler.State`)? That would effectively limit the number of connections to minimum.

> If `RequestContext.eventLoop` is the main problem, I think we could have it return `CompletableFuture<EventLoop>`?

That sounds like a good idea. Let me create a dedicated issue. It will involve non-trivial changes to the pool implementation so it will take some time.

**Comment by trustin** [comment]
See: #818

**Comment by anuraaga** [comment]
I see - to maximize IO performance using multiple connections/event loops sounds ok. But yeah being able to configure this so a user can keep down to one connection per endpoint seems nice - if the setting is 1 (reasonable for a largish `EndpointGroup`) we could bypass the heapsort entirely I think.

**Comment by trustin** [comment]
What would be the sensible default for the maximum number of event loops per endpoint? `1`?

**Comment by trustin** [comment]
I also wonder if there is a better way to address this issue than limiting the number of event loops used per endpoint. Thoughts?

**Comment by anuraaga** [comment]
I like the value of `1` but am not sure what is the best default or not. 

One observation that just came to mind in my use case is that for a low QPS service, the health check request actually becomes more important as it allows the channel to stay warm by guaranteeing requests on a connection. With lots of connections to a single endpoint (our servers have 16 event loops), health check every 3s has a lower probability of keeping a connection warm. This observation came up while thinking about what may be contributing to logs of untraced time in our request traces.

**Comment by trustin** [comment]
BTW we need to make sure Armeria respects the `MAX_CONCURRENT_STREAM` settings because connection coalescing will increase the chance of exceeding `MAX_CONCURRENT_STREAM` dramatically.

**Comment by trustin** [comment]
I think this issue can be closed thanks to the hard work by @minwoox. Please reopen if you think the issue is still there.
