### ISSUE TITLE
cancelTimeout is slow

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#821]
We cancel a timeout future at the end of every successful response. Unfortunately `ScheduledFuture.cancel` is implemented with `PriorityQueue.remove` - `remove` has O(N) performance and is expected to be slow with many concurrent requests.

@trustin Do you think we are abusing `cancel` and shouldn't be calling it every request? Or if it seems like reasonable behavior, should we file an issue in Netty to replace the queue with one with fast removals?

**Comment by minwoox** [comment]
In the case of retrying client, if the timeout futures are not cancelled properly, they would, all executed at the same time when response timeout happens.

**Comment by anuraaga** [comment]
I was thinking if frequent cancels is not really what Netty intends, then we could implement our own scheduler in armeria, otherwise it's better to fix upstream

**Comment by anuraaga** [comment]
I found that netty already has an optimized priority queue implementation available and it was trivial to use it for scheduled futures. So sent this upstream which will solve this issue - https://github.com/netty/netty/pull/7384

**Comment by anuraaga** [comment]
Change is in so will close this issue - next netty version update will have the speed-up

**Comment by trustin** [comment]
Thanks, @anuraaga !

**Comment by trustin** [comment]
@anuraaga We are still much behind gRPC even with this fix applied, right?
