### ISSUE TITLE
Reconsider the endpoint selection API to support more use cases

### ISSUE THREAD

**Issue by trustin** [line/armeria#833]
Related: #832 #819 

When a user implements client-side load-balancing using `EndpointGroup`, he or she may want to choose an endpoint based on:

- the parameter values of `RpcRequest`
- the header values of `HttpRequest`
- the content of `HttpRequest`

The current API support only the second use case (HTTP header values). For the two other use cases, a user has to:

- set some custom attribute in `RequestContext` from a custom `DecoratingClient` and
- use a custom `EndpointSelectionStrategy` which access the context attribute.

However, it scatters the load-balancing logic into two places, which is not very beautiful.

We also need to think about the similarities between a decorator and an `EndpointSelector`. If all three (or more) uses cases are covered by the new endpoint selection API, would it be any different from a decorator? Is it actually better ditching the current API and providing various decorators that serves similar purposes?

**Comment by anuraaga** [comment]
Just wondering, is the use case to prevent duplication? When I imagine sticky load balancing, I think of something like

```java
String id = user.getId();
RpcRequest request = new RpcRequest.setId(id);
try (withClientContextCustomizer(ctx -> ctx.attr(USER_ID).set(id)) {
  // This request was set up by the calling code, so there shouldn't be any need to aggregate it.
  client.send(request);
}
```

which has a bit of duplication, but it seems reasonable to me. Are there use cases where an entire `DecoratingClient` is actually needed instead of just letting the calling code to determine the load balancing id, which seems ok?

**Comment by anuraaga** [comment]
@imasahiro The example in #832, `HttpRequest.toRequestAscii()` seems like a synthetic use case. Would you be able to provide a more real-world use case where it is better to extract from the request in the `EndpointSelector` instead of the callers doing it?

**Comment by trustin** [comment]
IIUC he is writing a reverse HTTP proxy server that forwards an incoming request and he wants to extract some information from the request content. In this case, a user still doesn't have to write a decorator but need to aggregate it, extract the information, set the attribute and execute the aggregated request.

Still, there are two parts that involves load balancing here: the `EndpointSelector` implementation and attribute-injecting code. I guess what he intended is doing the same job in a single `EndpointSelector` implementation, without any attribute injection.

**Comment by anuraaga** [comment]
FWIW, I was actually thinking, even before seeing this issue, that we should add something like this to armeria

```java
public final class StickyEndpointSelectionStrategy implements EndpointSelectionStrategy {

  public static final AttrKey<Long> STICKY_HASH_KEY;

  public SafeCloseable withStickyHash(long hash) {
    return Clients.withContextCustomizer(ctx -> ctx.attr(STICKY_HASH_KEY).set(hash);
  }

  public StickyEndpointSelectionStrategy() {
    this(ctx -> ctx.attr(STICKY_HASH_KEY).get());
  }
}
```
and it becomes really trivial for callers to set the hash key. IMO, this doesn't feel like a scattering of load balancing logic, as the strategy is just ensuring connections are sticky, and the load balancing itself is happening at the caller side, which feels natural and clean enough to me.

**Comment by trustin** [comment]
@anuraaga Sounds like a reasonable opinion. Thoughts, @imasahiro?

**Comment by imasahiro** [comment]
> Would you be able to provide a more real-world use case where it is better to extract from the request in the EndpointSelector instead of the callers doing it?

We wanted to write a proxy server that selects upstreams based on urlencoded contents like:
`curl --data "id=client1&data=&size=11" http://proxy-server/`  -> proxies to a server for client1
`curl --data "id=client2&data=&size=11" http://proxy-server/` -> proxies to a server for client2
...

And yeah, using withContextCustomizer sounds good to me now.

**Comment by trustin** [comment]
#845 reverts #819.
