### ISSUE TITLE
Upgrade to Netty 4.1.19.Final

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#925]
Found a critical DNS bug was fixed in the recent version of Netty

https://github.com/netty/netty/commit/844d804aba4b459215f05c9ade59157f6c2cfb4b#diff-8a94497e9e56fe3bc57fb556b89c2f89

And of course it also contains my cancelTimeout optimization :)

@trustin Do you think we'd be able to do the upgrade and armeria release soon to fix this DNS bug?

**Comment by trustin** [comment]
Yes. Was going to release this week.

**Comment by trustin** [comment]
Done via #926
