### ISSUE TITLE
Virtual host support for access logging

### ISSUE THREAD

**Issue by trustin** [line/armeria#947]
A user may want to keep different access log files for different virtual hosts.

We could use different logger names for different virtual hosts so that a user can configure his or her `logback.xml`.

One simple solution for this feature would be appending the reversed domain name to the logger name, e.g. `com.linecorp.armeria.logging.access.com.example` for `*.example.com`

**Comment by tmdgus0118** [comment]
I'm currently working on this issue. Please let me know if someone is doing.
