### ISSUE TITLE
How can I add JSON-based GRPC services, a.k.a unframed gRPC-JSON?

### ISSUE THREAD

**Issue by demongaorui** [line/armeria#953]
I wonder if it is possible to auto add Json based service whenever a GRPC service is added to server. This will helps organizations who want to migrate from Json base Rest apis server to Armeria-Grpc server.

For example, we have a grpc SomeGrpcService which have a rpc `SayHello`. And the path for SayHello GRPC service could be something like `my.package/SomeGrpcService/SayHello`. 

With the following config, we could auto add a Rest version SayHello service while binding to the path of `my.package/SomeGrpcService/Rest/SayHello`. 

```
 serverBuilder
            .service(
                (ServiceWithPathMappings<HttpRequest, HttpResponse>)
                    new GrpcServiceBuilder()
                        // This is the config of new proposed function
                        .enableRestService(true)
                        .addService(someGrpcService)
                        .supportedSerializationFormats(GrpcSerializationFormats.values())
                        .build()
           )
```

Then, by default, we assume the GRPC request and response of SayHello service is SayHelloRequest and SayHelloResponse. And  to serve all client Json based Rest requests to the path of `my.package/SomeGrpcService/Rest/SayHello` via GRPC SayHello service by adding a layer which using @chokoswitch 's [Buffer <-> JSON marshaller](https://github.com/curioswitch/curiostack/tree/master/common/grpc/protobuf-jackson ) to convert to/from Json and GRPC request and response.

**Comment by demongaorui** [comment]
@trustin @anuraaga  Could you kindly share your opinions? Thank you very much.

**Comment by anuraaga** [comment]
Support for unframed requests and JSON using that serializer is already there to try to make it easier to migrate JSON API services. Is it not what you're looking for?

https://github.com/line/armeria/blob/874301f40859edc2d656de7cc91db42b813d0b1f/grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java#L169

**Comment by demongaorui** [comment]
Oooops!!!

Is that means if we set `.enableUnframedRequests(true)` to the someGrpcService builder in above example, then the server could handle requests to the path of `my.package/SomeGrpcService/SayHello` with JSON format data in the request body, and response with JSON format date to the client?

**Comment by demongaorui** [comment]
Looks like the [UnframedGrpcService decorator] (https://github.com/line/armeria/blob/bc37686c4b5802a579431fc933f0d07e5678095f/grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java) is doing what I want! 

Great!!!  Gonna try it.

Thank you very much!

**Comment by anuraaga** [comment]
Yeah - the format is determined by the content type of the request. In fact, this is currently being the debug form for gRPC.

There is a bit of documentation here, if there's anything not clear let me know so we can fix it :)

http://line.github.io/armeria/server-grpc.html#unframed-requests

**Comment by eonezhang** [comment]
@anuraaga does this feature production ready?

**Comment by anuraaga** [comment]
@eonezhang Yeah it's intended to be production-ready, the usage in debug form is just a coincidence. The marshaller should be about as fast as you can get for JSON

**Comment by demongaorui** [comment]
Found an issue that if set enableUnframedRequests(true), then can't do
```
serverBuilder
      .service(
                (ServiceWithPathMappings<HttpRequest, HttpResponse>)
                    new GrpcServiceBuilder()
                        .addService(someGrpcService)
                        .supportedSerializationFormats(GrpcSerializationFormats.values())
                        .enableUnframedRequests(true)
                        .build(),
                withJwtAuth)
```
which avoid binding "/" to the Grpc service with specific decorator.

The point is in GprcBuilder.build() method:
```
        return enableUnframedRequests ? grpcService.decorate(UnframedGrpcService::new) : grpcService;
```

Seems could change GprcBuilder.build() return type to GrpcService?

Another concern is that for an Armeria-Grpc API server which is used in organizations migrating to Grpc from Rest API, a decorator which could handle OPTIONAL request from browsers along with UnframedGrpcService decorator maybe generally needed?

**Comment by anuraaga** [comment]
Sent #956 so the unframed version also implements path mappings by delegating them.

I don't understand the second concern - the decorator and gRPC service itself are set up to intelligently accept serialization formats that are passed to `supportedSerializationFormats`, if you want to support only gRPC, just need to set to `GrpcSerializationFormats.PROTO`, if you want both proto and json you set both, `GrpcSerializationFormat.values()` is shorthand for proto, json, and gRPC-web. With the unframed decorator, you also get support for `application/protobuf` and `application/json;charset=utf-8`. Is there a case which isn't handled by one of these content types?

Relevant code
https://github.com/line/armeria/blob/bc37686c4b5802a579431fc933f0d07e5678095f/grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java#L100
https://github.com/line/armeria/blob/bc37686c4b5802a579431fc933f0d07e5678095f/grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java#L121

**Comment by demongaorui** [comment]
Thanks for your rapid implementation of #956 !

About the second concern, for organizations migrating to Grpc from Rest API, the web page client which will use `application/json` to access unframed Grpc service is hosted in a legacy web server host, then cross-domain support is needed.  This is a typical status for migrationg Rest API to Armeria-Grpc. 

So maybe could add a config property like `enableCrossDomainAccess(ImmutableList.of("abc.example.com", "bcd.example.com"))` to GrpcServiceBuilder to auto add a decorator to handle OPTIONS requests(OPTIONS request will be send before sending POST request in browsers). Also, make the response of OPTIONS request configurable could be usefull too(like `Access-Control-Max-Age`).

**Comment by anuraaga** [comment]
cross-origin is a concept more general than gRPC so it wouldn't go in the `GrpcServiceBuilder` (I don't think it's a good default either way).

Armeria has `CorsService` which you should be able to specify as a decorator when doing `ServerBuilder.service(gRpcService, Functions.compose(withJwtAuth, corsService)` (something like that, haven't checked if it compiles), would it work for you?

**Comment by trustin** [comment]
Updated the title of this issue to make it an answered question.
