### ISSUE TITLE
Disable path mapping cache for prefix mapping

### ISSUE THREAD

**Issue by trustin** [line/armeria#967]
We currently cache a path mapping result as long as the response status is successful and the mapping does not have any path parameters: https://github.com/line/armeria/blob/8e6cbc36a92de7ae3e03a41531e7ab486cd0121a/core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java#L334-L338

This does not work well with prefix mapping which can map to infinit number of paths, because the mapping result will always have zero path parameters.

To address this issue, we could:

1. Disable caching for prefix mapping by default
2. Provide a way to enable path mapping caching for some special cases, e.g. `HttpFileService` would use prefix mapping but still could use cache because it will return successful response status for a limited number of paths.
   - Annotation? e.g. `@EnablePathMappingCache`
   - Interface?

     ```java
     public interface SomeInterfaceThatServiceWillImplement {
         boolean canCache(PathMapping, PathAndQuery);
     }
     ```

Thoughts?

/cc @hyangtack @huydx @anuraaga

**Comment by anuraaga** [comment]
Thanks for bringing this up - an interface method seems good to me. I guess it could be a defaulted method on Service instead of introducing yet another interface.

Happy to fix this tomorrow if the approach makes sense

**Comment by trustin** [comment]
> I guess it could be a defaulted method on Service instead of introducing yet another interface.

+1. Thanks! Please feel free to assign yourself. Much appreciated.
