### ISSUE TITLE
Consider switching to Project Reactor

### ISSUE THREAD

**Issue by trustin** [line/armeria#970]
At the time when we began Armeria, we ended up with `StreamMessage` which is a specialized variant of Reactive Stream `Publisher` mainly because there was no suitable Reactive Stream implementation that meets our requirements:

- Few third party dependencies
- Stable
- Rich set of `Publisher` implementations that's suitable for publishing network traffic

[Project Reactor](https://projectreactor.io/) was in a very early stage when I reviewed it and now it seems to meet our requirements. It even looks way richer than `StreamMessage`:

- Read from here to learn the basics: http://projectreactor.io/docs/core/release/reference/docs/index.html#intro-reactive
- Read about their `Processor` implementations which could replace `DefaultStreamMessage` and `StreamMessageDuplicator`: http://projectreactor.io/docs/core/release/reference/docs/index.html#processors

This change would guarantee huge undertaking and broken backward compatibility. We will get richer API and potentially better interoperability/migration opportunaty against other libraries that use Project Reactor such as [Spring Webflux](https://docs.spring.io/spring/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/web-reactive.html).

Thoughts? /cc @hyangtack @minwoox @anuraaga @imasahiro @kojilin @taicki @kshgizmo and everyone interested

**Comment by anuraaga** [comment]
I had thought about reactor a little when looking into the streams - it seems like a good idea to me

**Comment by trustin** [comment]
We may also want to do some research on other reactive stream implementations such as RxJava 2.

**Comment by rvit34** [comment]
It would be a greate ability to provide integration with Spring 5 (webflux) and/or Spring Boot 2.0 as it can run Netty/RxNetty under the hood. Referenced to your project [here](https://jira.spring.io/browse/SPR-16466)

**Comment by trustin** [comment]
Thanks @rvit34 for your interest. We only have limited integration with Boot 1 but it would be great to provide better seamless integration with WebFlux and Boot 2.0.

**Comment by trustin** [comment]
@rvit34 You may be interested in this pull request, which allows Armeria integrate with Spring WebFlux - #1326

**Comment by anuraaga** [comment]
@trustin Should we give this another look and close if it seems infeasible? I guess it would affect the API in a major way.

**Comment by trustin** [comment]
I think we went too far already and our implementation has interesting features like `SubscriptionOption` which cannot be replaced easily with Reactor. I also tend to prefer shorter stack trace :wink:
