### ISSUE TITLE
ClientFactory.close doesn't actually close in-progress connections

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#972]
I was trying to simulate a scenario where a client opens a connection to the server (e.g., starts a gRPC stream) but then forcibly closes the socket. I would expect `ClientFactory.close` to close the socket, but it doesn't actually seem to. It calls `DefaultKeyedChannelPool.close`, but that only keeps track of available connections, not offered connections, so the actual stream doesn't seem to be affected. Should the pool also keep track of offered connections to allow closing them when needed?

**Comment by trustin** [comment]
Yes. In-progress connections should be closed as well. Are you going to include the fix for this when you send a PR for #973 ?

**Comment by anuraaga** [comment]
No let's keep it separate, as this one will be a more invasive change :)

**Comment by trustin** [comment]
Never mind. A separate PR would be better.

**Comment by trustin** [comment]
OK. Are you working on the PR?

**Comment by anuraaga** [comment]
Yeah trying it now
