### ISSUE TITLE
GracefulShutdownSupportTest does not pass with Java 9

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#978]
I'm not sure if this is a problem with the test or the actual logic not being Java 9 compatible, but when I run `./gradlew :core:test` with JDK9, I get this failure that doesn't show with JDK8.

This is still the same source/target compatibility, so it's only the difference of what JRE is running the code.

```
GracefulShutdownSupportTest.activeBlockingTaskNotPassedQuietPeriod: FAILURE

com.linecorp.armeria.server.GracefulShutdownSupportTest > activeBlockingTaskNotPassedQuietPeriod FAILED
    org.mockito.exceptions.verification.TooManyActualInvocations: 
    ticker.read();
    Wanted 1 time:
    -> at com.linecorp.armeria.server.GracefulShutdownSupportTest.assertWithPendingTasks(GracefulShutdownSupportTest.java:210)
    But was 2 times. Undesired invocation:
    -> at com.linecorp.armeria.server.GracefulShutdownSupport$DefaultGracefulShutdownSupport.completedQuietPeriod(GracefulShutdownSupport.java:123)
        at com.linecorp.armeria.server.GracefulShutdownSupportTest.assertWithPendingTasks(GracefulShutdownSupportTest.java:210)
        at com.linecorp.armeria.server.GracefulShutdownSupportTest.activeBlockingTaskNotPassedQuietPeriod(GracefulShutdownSupportTest.java:146)
```

**Comment by trustin** [comment]
We never tested Armeria against Java 9 yet but we should. :-)

**Comment by anuraaga** [comment]
FWIW it seems to be working ok :) But I haven't verified graceful shutdown yet in an actual server either hope it works, heh

**Comment by machi1990** [comment]
JUnit 5.1 has annotation support to disable and enable tests depending on the JRE version. 
[JUnit Enable or Disable on JRE annotation](http://junit.org/junit5/docs/snapshot/api/org/junit/jupiter/api/condition/EnabledOnJre.html)

**Comment by trustin** [comment]
Fixed long time ago.
