### ISSUE TITLE
Verify HOST header of upgrade requests

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#98]
While looking through armeria code in an unrelated matter, I found this method

https://github.com/line/armeria/blob/master/src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java#L81

It computes a value for a map using more parameters than are provided to the key of the map. This is usually wrong, so I tried looking through and it seems that the specified host is only used for specifying the HOST header of the HTTP2 upgrader request.

https://github.com/line/armeria/blob/master/src/main/java/com/linecorp/armeria/client/HttpConfigurator.java#L260

I haven't ran anything to verify the behavior, but looking at the code it seems likely that all upgrade requests will have the host of the very first client to send a request for the session protocol on a given remote invoker factory, which there is usually only one of in a binary.

**Comment by trustin** [comment]
#100 should fix this issue.

**Comment by trustin** [comment]
Fixed in 0.9.0.Final
