### ISSUE TITLE
Copying manifest attributes

### ISSUE THREAD

**Issue by borag** [line/armeria#984]
I tried to use gradle/scripts in a sample project. 
But it seems 'java-shade.gradle' doesn't copy/inherit manifest file from the jar even if it
has jar manifest attributes.

**Comment by borag** [comment]
1) Add jar to build.gradle
jar {
    manifest {
        attributes(
                'Main-Class': '...'
        )
    }
}

2) Add manifest.inheritFrom to
    task shadedJar(
            type: ShadowJar,
            group: 'Build',
            description: 'Builds the shaded JAR.',
            dependsOn: tasks.classes) {        
        configureShadowTask(project, delegate, true)
        baseName = "${project.archivesBaseName}-shaded"  
        manifest.inheritFrom tasks.jar.manifest      
    }

**Comment by trustin** [comment]
Was your issue resolved, @borag ? What was the problem?
