### ISSUE TITLE
Throttling decorator for rpc can't works well

### ISSUE THREAD

**Issue by kojilin** [line/armeria#996]
due to https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingService.java#L70

it may create RpcResponse of RpcResponse.

I think 1 way is make `RpcResponse#from` supports `CompletableFuture<? extends RpcResponse>` like
```
static RpcResponse from(CompletionStage<?> stage) {
        requireNonNull(stage, "stage");
        final DefaultRpcResponse res = new DefaultRpcResponse();
        stage.whenComplete((value, cause) -> {
            if (cause != null) {
                res.completeExceptionally(cause);
                return;
            }
            if (value instanceof RpcResponse) {
                ((RpcResponse) value).whenComplete((rpcResponseResult, rpcResponseCause) -> {
                    if (rpcResponseCause != null) {
                        res.completeExceptionally(Exceptions.peel(rpcResponseCause));
                        return;
                    }
                    res.complete(rpcResponseResult);
                });
            } else {
                res.complete(value);
            }
        });
        return res;
    }
```

But this make me think how about `CompletableFuture<CompletableFuture<RpcResponse>>` or nested `RpcResponse`. or we should separate RPC's implementation of `ThrottlingRpcService` from `ThrottlingService`?

**Comment by jmostella** [comment]
How about changing `CompletableFuture<Boolean> ThrottlingStrategy.accept -> boolean ThrottlingStrategy.accept`?

Practically speaking, in `RateLimitingThrottlingStrategy` its calling `RateLimiter.tryAcquire` which internally has a mutex lock here: https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/RateLimiter.java#L348

I can't imagine similar strategies won't have the same type of penalty. So I don't see the value in having this op be asynchronous.

**Comment by kojilin** [comment]
I'm not sure if there is a needs about it. And maybe not all user use RateLimitingThrottlingStrategy?

**Comment by anuraaga** [comment]
I think a method that returns a completed future and a synchronous method are conceptually the same, so switching to synchronous can never be a real solution, it's more for situations where the extra allocations / volatile reads of the future would be prohibitive. Here that doesn't seem to be the case and I think adding a sync version seems weird.

I think @kojilin's proposal seems correct, currently `RpcResponse.from` does not work the same as `HttpResponse.from`, which seems like a bug in general, not just this decorator.

Another more radical proposal is what happens if we get rid of RpcRequest/Response? Having to specify type parameters all over the world is one of the most annoying things when using armeria, and their main use seems to be mainly in logging type stuff - similar functionality should be easy to provide on the context.

**Comment by trustin** [comment]
> I think a method that returns a completed future and a synchronous method are conceptually the same, so switching to synchronous can never be a real solution, it's more for situations where the extra allocations / volatile reads of the future would be prohibitive. Here that doesn't seem to be the case and I think adding a sync version seems weird.

+1

> I think @kojilin's proposal seems correct, currently `RpcResponse.from` does not work the same as `HttpResponse.from`, which seems like a bug in general, not just this decorator.

Yeah, how about cherry-picking @kojilin's fix into your PR, @imasahiro?

> Another more radical proposal is what happens if we get rid of RpcRequest/Response? Having to specify type parameters all over the world is one of the most annoying things when using armeria, and their main use seems to be mainly in logging type stuff - similar functionality should be easy to provide on the context.

Could you show me some examples? I'm curious about this!

**Comment by anuraaga** [comment]
@trustin I think the best example may be gRPC - it's an RPC protocol implemented without RPCResponse, except for setting it in log builder.

**Comment by imasahiro** [comment]
@trustin 
> Yeah, how about cherry-picking @kojilin's fix into your PR, @imasahiro?

Sounds good. Let me update my PR with #997
